### ISSUE TITLE
Dynamic Columns

### ISSUE THREAD

**Issue by Skintillion** [kevinkhill/lavacharts#100]
I couldn't find anything in the documentation on having dynamic column data, for example

For example pulling this from a query

![image](https://cloud.githubusercontent.com/assets/1521506/12774562/f6cc011c-c9fa-11e5-8138-6c4ec9ec81bc.png)

Not every year has qty for every model... 

In Excel I can pivot

![image](https://cloud.githubusercontent.com/assets/1521506/12774593/27a989ee-c9fb-11e5-9e26-adda951df562.png)

Have you encountered this kind of problem before?

```
use Khill\Lavacharts\Lavacharts;

$lava = new Lavacharts; // See note below for Laravel

$finances = $lava->DataTable();

$finances->addDateColumn('Year')
         ->addNumberColumn('Ford')
         ->addNumberColumn('Kia')
         ->addNumberColumn('Toyota')
         ->setDateTimeFormat('Y')
         ->addRow(['2004', 5, 0, 3])
         ->addRow(['2005', 2, 4, 4])
         ->addRow(['2006', 8, 2, 0])
         ->addRow(['2007', 0, 5, 4]);

$lava->ColumnChart('Finances', $finances, [
    'title' => 'Company Performance',
    'titleTextStyle' => [
        'color'    => '#eb6b2c',
        'fontSize' => 14
    ]
]);
```

Sorry if this is the wrong place to ask this kind of question.

**Comment by Skintillion** [comment]
This was my solution but I'm using c3js
```
//Initialize Labels
$labels='';
$legend='';
$data='';
//Cycle through tags and make labels for chart
foreach(Tag::where('forcar',1)->orderBy('tag')->get() as $index => $element)
{
	//Add tag to labels array for chart
	$labels.="'".$element['tag']."' : 'x".$index."',";
	
	$legend.='[\'x'.$index."'";
	$data.="['".$element['tag']."'";
	//Cycle through Years and Qty and add to legend and data array
	foreach(Cars::issuedByTagYearActive()->filterpermissions()->where('tag_id',$element['id'])->get() as $subindex => $subelement)
	{
		$legend.=",'".$subelement['year']."'";
		$data.=",".$subelement['count']."";
		
	}
	$legend.="],";
	$data.="],";
}
$labels=rtrim($labels,",");
$legend=rtrim($legend,",");
$data=rtrim($data,",");

$legend.=",";
$data.=",";

$chartdata['data'] = rtrim($legend.$data,",");
$chartdata['labels'] = $labels;


return $chartdata;

```

**Comment by kevinkhill** [comment]
I'm sorry, but I'm not sure what you functionality you are looking for. Do you want the similar car makes grouped?

**Comment by Skintillion** [comment]
I'm having trouble, when a "Make" does not always have a quantity for a year, the array does not line up the way I am trying to do it... I was curious if you had an example that fitted this scenario. 

I accomplished it manually using c3.js and hand written php, but I like the idea of lavacharts as its more concise for more general graphs. Just had trouble with this. There might be 5 columns (Year, Ford, Toyota, Nissan, Mazda), but in 2008 only Ford and Nissan had numbers.

So the columns are
         ->addNumberColumn('Ford')
         ->addNumberColumn('Toyota')
         ->addNumberColumn('Nissan')
         ->addNumberColumn('Nissan')

but the rows are
         ->addRow(['2006', 5, 0, 3])
         ->addRow(['2007', 2, 4, 4])
         ->addRow(['2008', 8, 2])
         ->addRow(['2009', 5, 4]);
         ->addRow(['2010', 0, 5, 3]);


My guess it's a possible eloquent or sql way of giving data properly to lavacharts, I just couldn't figure it out conceptually. Thank you for taking the time to read however.

**Comment by kevinkhill** [comment]
You can pass nulls, for the columns that have no data.

**Comment by Skintillion** [comment]
Ok, I'll see if I can figure something out.
