### ISSUE TITLE
Laravel : Uncaught ReferenceError: dataTableJson is not defined

### ISSUE THREAD

**Issue by douglaswong111** [kevinkhill/lavacharts#101]
hi kevinkhill, i have some problem for using lavacharts ajax and change the result in every month with dropdown list. But after i return the data to ajax success, that message "dataTableJson is not defined"
Here my Screenshot, hopefully can solve the problem
## **View AJAX**

![view ajax](https://cloud.githubusercontent.com/assets/15793809/12836679/fcca0ac6-cbf5-11e5-9549-c0a264b5ac04.PNG)
## **CONTROLLER AJAX**

![ajax_controller](https://cloud.githubusercontent.com/assets/15793809/12836690/09e1a2e6-cbf6-11e5-8d29-1689be4df686.PNG)
## **CONTROLLER**

![controller](https://cloud.githubusercontent.com/assets/15793809/12836699/1972b89e-cbf6-11e5-9b51-4a675fe8bbb3.PNG)

**Comment by kevinkhill** [comment]
So, in your ajax javascript, you have
```javascript
success: function (html) {
    lava.loadData('category', dataTableJson, function (html) {
        console.log(html.msg);
    });
}
```

The reason why dataTableJson is undefined is because what the Controller is returning, the DataTable->toJson(), you have labeled as ```html``` in your callback. So the AJAX call is returning the datatable json, but you aren't passing it into the ```lava.loadData()``` method

**Comment by douglaswong111** [comment]
Thank kelvinhill, finally can display in console log. But i still have some problem have to asking you, inside the console log, why the tz undefined? and the chart there was prompt table has been no columns? When i changing to (html) console log, it have a data.

**Console log**
![console](https://cloud.githubusercontent.com/assets/15793809/12870388/f2de23de-cd7c-11e5-86cc-bfeca8d97390.PNG)

**Comment by kevinkhill** [comment]
I'm not sure what you are returning from your controller then, but the success function needs to be receiving the ```DataTable->toJson()``` and the callback of ```lava.loadData``` will receive the Google chart object

**Comment by kevinkhill** [comment]
Closing due to staleness. Please re-open or start a new issue if you still are having trouble.
