### ISSUE TITLE
Using with yii2

### ISSUE THREAD

**Issue by lukBarros** [kevinkhill/lavacharts#103]
Hi mans!

Someone with experience with him in yii2 ? How do I register it in yii2 ?

**Comment by kevinkhill** [comment]
I have not used yii before, but I am not opposed to learning and integrating. 3.1 is in the works with drastic under-the-hood changes to make life easier. For now, you can manually use the library in the framework without any problems.

Just create a lavachart instance in your controller ```$lava = new \Khill\Lavacharts\Lavacharts;``` create and configure charts, then pass the ```$lava``` instance to your view and ```$lava->render()```

**Comment by lukBarros** [comment]
Ok  i use yii2. I test it and report about it.

**Comment by kevinkhill** [comment]
Closing due to the fact that I don't know if I will have time to do this. It's already been so long. I do apologize
