### ISSUE TITLE
Setting your own values in vertical axis in Line graph

### ISSUE THREAD

**Issue by rapunk27** [kevinkhill/lavacharts#104]
I wanted to make my own set of values for the vertical axis for my line graph. 
I wanted to have 0,1,2,3,4,5,6. From Bottom to Top.  Can I do it here in lavacharts? :)

As I've noticed the vertical axis automatically outputs values depending on the data that I looped. Like this one here.

![performance](https://cloud.githubusercontent.com/assets/15083212/13031962/cfcb1574-d31b-11e5-84f1-e647caaab751.PNG)

Here's what I have coded for the linegraph. Do I need to add something?

$linechart = Lava::LineChart('Overall')
	->setOptions([
		'datatable'	=> $overall_chart,
		'title'		=>	'Overall Performance Line Chart',
		'pointSize'	=> 10,
		'lineWidth'	=> 6
		]);

**Comment by rapunk27** [comment]
Im using laravel 4 btw.

**Comment by kevinkhill** [comment]
From your example, I take it your are using the 2.5 branch of the library?

**Comment by rapunk27** [comment]
Yes it is. :)

**Comment by kevinkhill** [comment]
First, I'd encourage an upgrade to 3.0 but that's beside the point ;)

Anyways, try adding to your options:
```php
'vAxis'=>new \Lava::VerticalAxis([
'ticks'=>[1,2,3,4]
]) 
```

**Comment by kevinkhill** [comment]
If that doesn't work (I don't remember if I included that option in the VerticalAxis object) then use ```customize('vAxis'=>
'ticks'=>[1,2,3,4])```
And if THAT doesn't work I'll have to dig into it later once I'm working on the project (answering this from my phone)

**Comment by rapunk27** [comment]
The first one shows this error message:
syntax error, unexpected 'VerticalAxis' (T_STRING), expecting variable (T_VARIABLE) or '$'

While the second one you gave me shows this:
Call to a member function customize() on a non-object

I kind of changed the folder structure for my Laravel 4 project because I had issues in my Web Hosting about the system I uploaded. 
Hope there's still a way though for an old version to work. Haha! :)
If not, I guess I really have to upload the 3.0 version.

**Comment by kevinkhill** [comment]
Sorry, I accidentally slipped a ```new``` in the example. It should just be:
```php
'vAxis' => \Lava::VerticalAxis([
    'ticks'=>[1,2,3,4]
])
```

and for the ```customize()``` method, you can just put all the options in there and forget about using the ```setOptions``` method

**Comment by kevinkhill** [comment]
Did this work for you?

**Comment by kevinkhill** [comment]
I am closing this issue for now, as with the 3.0.2 update, you can set any option you need. There are no restrictions, no need for the ```customize``` method. Follow the [upgrade guide](https://github.com/kevinkhill/lavacharts/wiki/Upgrading-from-2.5-to-3.0) for instructions on updating your syntax.

**Comment by geetikaarora** [comment]
How to set  vertical axis to be in 'integer' not float point number.any idea???

**Comment by kevinkhill** [comment]
Can you please open a new issue for this question? This is issue has already been closed.

**Comment by geetikaarora** [comment]
sure

**Comment by geetikaarora** [comment]
sure :)

**Comment by kevinkhill** [comment]
Thank you
