### ISSUE TITLE
how  timestamp format

### ISSUE THREAD

**Issue by montes2012** [kevinkhill/lavacharts#105]
very good package, congratulations

how  timestamp format? 

```
$lava = new Lavacharts;

$population = $lava->DataTable();

$population->addDateColumn('Year')
           ->addNumberColumn('degrees');

foreach ($datos as $key => $value) {
      $valores = str_replace(array("+","-",'C','*'),"",$value->raw_record );
	list($var1,$var2,$var3,$var4,$var5,$var6) = explode(" ", $valores);
      $population->addRow([
      $value->timestamp, $var2/10
    ]);
           }     


$lava->LineChart('Population', $population, [
    'title' => 'Temperatura Estatuas',
    'legend' => [
        'position' => 'in'
    ]
]);    

```
data
2016-02-15 00:00:47 !T01 +000849 +000000 +000000 +1306 +0211 C0770*
2016-02-15 00:11:25 !T01 +000848 +000000 +000000 +1306 +0210 C076E*
2016-02-15 00:22:06 !T01 +000849 +000000 +000000 +1305 +0209 C0776*
2016-02-15 00:32:43 !T01 +000849 +000000 +000000 +1305 +0208 C0775*
2016-02-15 00:43:23 !T01 +000849 +000000 +000000 +1304 +0206 C0772*
2016-02-15 00:54:03 !T01 +000849 +000000 +000000 +1304 +0205 C0771*

**Comment by kevinkhill** [comment]
Thank you for the compliment :) 

So you can use the 
I would encourage you to read the ```setTimezone``` method of the datatable to set where you are, and then you can use the ```setDateTimeFormat``` with a format string, to tell the datatable how to interpret datetime strings.

I don't mind answering questions, but I would encourage a read through the documentation before opening an issue. (I put a lot of time into the docs) 

Check out [lavacharts.com](http://lavacharts.com), specifically the DataTables section.

**Comment by montes2012** [comment]
Part of DataTables do not understand, you could do examples

**Comment by kevinkhill** [comment]
```php
$population->addDateColumn('Year')
->addNumberColumn('degrees')
->setTimezone('America/Los_Angeles')
->setDateTimeFormat('Y-d-m H:i:s');
```

**Comment by kevinkhill** [comment]
Here is how you can construct format strings for the DataTable. 

http://php.net/manual/en/function.date.php
