### ISSUE TITLE
Problem with ajax

### ISSUE THREAD

**Issue by montes2012** [kevinkhill/lavacharts#106]
hi, problem with ajax

TypeError: lava.loadData is not a function
lava.loadData('Chart1', dataTableJson, function (chart) {

```
//routes.php
Route::get('googleAjax', function(){

$lava = new Lavacharts;

$temps = $lava->DataTable('America/Los_Angeles');

$temps->addDateColumn('Date')
      ->addNumberColumn('Max Temp')
      ->addNumberColumn('Mean Temp')
      ->addNumberColumn('Min Temp');

foreach(range(1, 30) as $day) {
    $temps->addRow(array(
        '2014-10-'.$day,
        rand(50,90),
        rand(50,90),
        rand(50,90)
    ));
}

return $temps->toJson();

});
```

```
//test.blade.php
<script src="{{ asset('/js/jquery-2.1.3.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">

$(document).ready(function() {  
  $(document).ready(function() {


    $.getJSON('http://localhost/bitacorasGraficas/public/googleAjax', function (dataTableJson) {
  lava.loadData('Chart1', dataTableJson, function (chart) {
    console.log(chart);
  });
});
});
});
</script>
```

**Comment by kevinkhill** [comment]
I've been having lots of issues as of late with AJAX, with a lengthy discussion in #81.

I am working on it though.

Out of curiosity, why do you have double ```$(document).ready(function() {});```?

**Comment by kevinkhill** [comment]
Question: did you output the chart into the page, with the ```\Lava::render()``` method? or the blade extension ```@linechart()```?

**Comment by montes2012** [comment]
does not work, what problem?

```
//routes.php
Route::get('googleAjax', function(){

$lava = new Lavacharts;

$temps = $lava->DataTable();

$temps->addStringColumn('Type')
      ->addNumberColumn('Value')
      ->addRow(['CPU', rand(0,100)])
      ->addRow(['Case', rand(0,100)])
      ->addRow(['Graphics', rand(0,100)]);

$lava->GaugeChart('Temps', $temps, [
    'width'      => 400,
    'greenFrom'  => 0,
    'greenTo'    => 69,
    'yellowFrom' => 70,
    'yellowTo'   => 89,
    'redFrom'    => 90,
    'redTo'      => 100,
    'majorTicks' => [
        'Safe',
        'Critical'
    ]
]);

return $temps->toJson();
});
```

```
//test.blade.php
<div id="temps_div"></div>
<?= $lava->render('GaugeChart', 'Temps', 'temps_div') ?>

<script src="{{ asset('/js/jquery-2.1.3.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">

$(document).ready(function() {	



    $.getJSON('http://localhost/bitacorasGraficas/public/googleAjax', function (dataTableJson) {
  lava.loadData('Chart1', dataTableJson, function (chart) {
    console.log(chart);
  });
});
});

</script>
```

**Comment by kevinkhill** [comment]
Are you not using the service provider in laravel? if you are, you need to create charts with ```\Lava::GaugeChart()``` or whatever, then in the view, use ```\Lava::render()```

When charts are created, they are stored within the Lava class. You either need to use the service provider with the alias, OR, pass the ```$lava``` object you created with the chart, into the view.

**Comment by montes2012** [comment]
does not work, what problem?

```
Route::get('googleAjax', function(){

$lava = new Lavacharts;

$temps = $lava->DataTable();

$temps->addStringColumn('Type')
      ->addNumberColumn('Value')
      ->addRow(['CPU', rand(0,100)])
      ->addRow(['Case', rand(0,100)])
      ->addRow(['Graphics', rand(0,100)]);

$lava->GaugeChart('Temps', $temps, [
    'width'      => 400,
    'greenFrom'  => 0,
    'greenTo'    => 69,
    'yellowFrom' => 70,
    'yellowTo'   => 89,
    'redFrom'    => 90,
    'redTo'      => 100,
    'majorTicks' => [
        'Safe',
        'Critical'
    ]
]);

return $temps->toJson();
});
```

```
<div id="temps_div"></div>

<?= \Lava::render('GaugeChart', 'Temps', 'temps_div') ?>

<script src="{{ asset('/js/jquery-2.1.3.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">

$(document).ready(function() {	



    $.getJSON('http://localhost/bitacorasGraficas/public/googleAjax', function (dataTableJson) {
  lava.loadData('GaugeChart', dataTableJson, function (GaugeChart) {
    console.log(chart);
  });
});
});

</script>
```

**Comment by kevinkhill** [comment]
You are still manually instantiating the Lava object ```$lava = new Lavacharts;``` This happens in the ServiceProvider so you don't need to do it manually.

Siince you are using Laravel, and the service provider, replace all ```$lava->``` with ```\Lava::```

**Comment by montes2012** [comment]
ErrorException in Volcano.php line 78: GaugeChart('Temps') was not found. (View: /var/www/html/bitacorasGraficas/resources/views/grafica2.blade.php)

//app.php
 'providers' => [
Khill\Lavacharts\Laravel\LavachartsServiceProvider::class,
  ],

'aliases' => [
'Lava'      => Khill\Lavacharts\Laravel\LavachartsServiceProvider::class
   ],


//routes.php
Route::get('googleAjax', function(){

//$lava = new Lavacharts;

$temps = Lava::DataTable();

$temps->addStringColumn('Type')
      ->addNumberColumn('Value')
      ->addRow(['CPU', rand(0,100)])
      ->addRow(['Case', rand(0,100)])
      ->addRow(['Graphics', rand(0,100)]);

$lava->GaugeChart('Temps', $temps, [
    'width'      => 400,
    'greenFrom'  => 0,
    'greenTo'    => 69,
    'yellowFrom' => 70,
    'yellowTo'   => 89,
    'redFrom'    => 90,
    'redTo'      => 100,
    'majorTicks' => [
        'Safe',
        'Critical'
    ]
]);

return $temps->toJson();
});



<div id="temps_div"></div>

<?= \Lava::render('GaugeChart', 'Temps', 'temps_div') ?>

<script src="{{ asset('/js/jquery-2.1.3.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">

$(document).ready(function() {	



    $.getJSON('http://localhost/bitacorasGraficas/public/googleAjax', function (dataTableJson) {
  lava.loadData('GaugeChart', dataTableJson, function (GaugeChart) {
    console.log(chart);
  });
});
});

**Comment by kevinkhill** [comment]
Just wondering, did you know there is full documentation for using Lavacharts in Laravel?[Laravel Install](http://lavacharts.com/#install-laravel)

Anyways, you missed one
```php
$lava->GaugeChart(...
```
needs to be
```php
\Lava::GaugeChart(...
```

**Comment by montes2012** [comment]
ErrorException in Lavacharts.php line 526: string is not a valid DataTable. (View: /var/www/html/bitacorasGraficas/resources/views/grafica2.blade.php)

**Comment by montes2012** [comment]
```
//routes.php
Route::get('googleAjax', function(){

//$lava = new Lavacharts;

$temps = \Lava::DataTable();

$temps->addStringColumn('Type')
      ->addNumberColumn('Value')
      ->addRow(['CPU', rand(0,100)])
      ->addRow(['Case', rand(0,100)])
      ->addRow(['Graphics', rand(0,100)]);

\Lava::GaugeChart('Temps', $temps, [
    'width'      => 400,
    'greenFrom'  => 0,
    'greenTo'    => 69,
    'yellowFrom' => 70,
    'yellowTo'   => 89,
    'redFrom'    => 90,
    'redTo'      => 100,
    'majorTicks' => [
        'Safe',
        'Critical'
    ]
]);
return $temps->toJson();
});
```

```
//test.blade.php
<div id="temps_div"></div>
<?= \Lava::GaugeChart('GaugeChart', 'Temps', 'temps_div') ?>
<script src="{{ asset('/js/jquery-2.1.3.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() {	
    $.getJSON('http://localhost/bitacorasGraficas/public/googleAjax', function (dataTableJson) {
  lava.loadData('GaugeChart', dataTableJson, function (GaugeChart) {
    console.log(chart);
  });
});
});
</script>

```

**Comment by kevinkhill** [comment]
Do you have a two routes setup? The first needs to have the chart initialization; DataTable and Chart creation, then you can render in the blade template.

Second route will just have the DataTable, with data, returning the json.
```php
//routes.php
Route::get('googleAjax', function(){

$temps = \Lava::DataTable();
$temps->addStringColumn('Type')
      ->addNumberColumn('Value');

\Lava::GaugeChart('Temps', $temps, [
    'width'      => 400,
    'greenFrom'  => 0,
    'greenTo'    => 69,
    'yellowFrom' => 70,
    'yellowTo'   => 89,
    'redFrom'    => 90,
    'redTo'      => 100,
    'majorTicks' => [
        'Safe',
        'Critical'
    ]
]);
});

Route::get('googleAjaxData', function(){

$temps = \Lava::DataTable();
$temps->addStringColumn('Type')
      ->addNumberColumn('Value');

return $temps->toJson();
});
```

```html
//test.blade.php
<div id="temps_div"></div>
<?= \Lava::GaugeChart('GaugeChart', 'Temps', 'temps_div') ?>
<script src="{{ asset('/js/jquery-2.1.3.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() {  
    $.getJSON('http://localhost/bitacorasGraficas/public/googleAjaxData', function (dataTableJson) {
  lava.loadData('GaugeChart', dataTableJson, function (GaugeChart) {
    console.log(chart);
  });
});
});
</script>
```

**Comment by montes2012** [comment]
sorry!!!!,  not working 

why?
	

string is not a valid DataTable. (View: /var/www/html/bitacorasGraficas/resources/views/test.blade.php)


Route::get('googleAjax', function(){

$temps = \Lava::DataTable();
$temps->addStringColumn('Type')
      ->addNumberColumn('Value');

\Lava::GaugeChart('Temps', $temps, [
    'width'      => 400,
    'greenFrom'  => 0,
    'greenTo'    => 69,
    'yellowFrom' => 70,
    'yellowTo'   => 89,
    'redFrom'    => 90,
    'redTo'      => 100,
    'majorTicks' => [
        'Safe',
        'Critical'
    ]
]);


return view('test');
});

Route::get('googleAjaxData', function(){

$temps = \Lava::DataTable();
$temps->addStringColumn('Type')
      ->addNumberColumn('Value');

return $temps->toJson();
});

//test.blade.php
<div id="temps_div"></div>
<?= \Lava::GaugeChart('GaugeChart', 'Temps', 'temps_div') ?>
<script src="{{ asset('/js/jquery-2.1.3.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() {  
    $.getJSON('http://localhost/bitacorasGraficas/public/googleAjaxData', function (dataTableJson) {
  lava.loadData('GaugeChart', dataTableJson, function (GaugeChart) {
    console.log(chart);
  });
});
});
</script>

**Comment by kevinkhill** [comment]
Ah! I missed it all these times, you are trying to create another chart in your view:
```php
//test.blade.php
<div id="temps_div"></div>
<?= \Lava::GaugeChart('GaugeChart', 'Temps', 'temps_div') ?>
\\                                                             ^ String is not a valid DataTable
```

you need to call the render method in your view, or use the ```@gaugechart()```
```php
//test.blade.php
<div id="temps_div"></div>
<?= \Lava::render('GaugeChart', 'Temps', 'temps_div') ?>
```
OR
```php
//test.blade.php
<div id="temps_div"></div>
{{{ @gaugechart('Temps', 'temps_div') }}}
```

**Comment by montes2012** [comment]
<div id="temps_div"></div>
{{{ @gaugechart('Temps', 'temps_div') }}}

error

FatalErrorException in 1ab868f0b78f012581e4950f3ea1bb8a line 2: syntax error, unexpected '<'

<div id="temps_div"></div>
{{{ @gaugechart('Temps', 'temps_div') }}}
<script src="{{ asset('/js/jquery-2.1.3.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() {  
    $.getJSON('http://localhost/bitacorasGraficas/public/googleAjaxData', function (dataTableJson) {
  lava.loadData('GaugeChart', dataTableJson, function (GaugeChart) {
    console.log(chart);
  });
});
});
</script>

div id="temps_div"></div>
<?= \Lava::render('GaugeChart', 'Temps', 'temps_div') ?>

error
Error: [Lavacharts] Chart "GaugeChart" was not found.
throw new Error('[Lavacharts] Chart "' + chartLabel + '" was not found.');


div id="temps_div"></div>
<?= \Lava::render('GaugeChart', 'Temps', 'temps_div') ?>
<script src="{{ asset('/js/jquery-2.1.3.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() {  
    $.getJSON('http://localhost/bitacorasGraficas/public/googleAjaxData', function (dataTableJson) {
  lava.loadData('GaugeChart', dataTableJson, function (GaugeChart) {
    console.log(chart);
  });
});
});
</script>

**Comment by TheTechnoMan** [comment]
@montes2012: It's not really something I need to care about, but you're really rude. At least say "please" and "thanks" if you want someone to assist you without paying a penny. You can be glad that @kevinkhill is such a patience person.

**Comment by montes2012** [comment]
@TheTechnoMan  You're right!, the problem is the language English.sorry sorry sorry. Could help me please

{{{ @gaugechart('Temps', 'temps_div') }}}

error

FatalErrorException in 1ab868f0b78f012581e4950f3ea1bb8a line 2: syntax error, unexpected '<'

{{{ @gaugechart('Temps', 'temps_div') }}}

div id="temps_div">
<?= \Lava::render('GaugeChart', 'Temps', 'temps_div') ?>

error
Error: [Lavacharts] Chart "GaugeChart" was not found.
throw new Error('[Lavacharts] Chart "' + chartLabel + '" was not found.');

div id="temps_div">
<?= \Lava::render('GaugeChart', 'Temps', 'temps_div') ?>

**Comment by kevinkhill** [comment]
Haha, thanks @TheTechnoMan, I figured a language barrier was the issue, but yes, I am a patient person.

Anyways, it looks like maybe the blade templates are getting cached, so the changes aren't making it to the page? Try clearing your caches with artisan.

**Comment by montes2012** [comment]
@kevinkhill Thanks for understand, 

I do indication

# php artisan view:clear
Compiled views cleared!

error
Error: [Lavacharts] Chart "GaugeChart" was not found.
throw new Error('[Lavacharts] Chart "' + chartLabel + '" was not found.');

	googleAjax (line 200, col 6)

**Comment by montes2012** [comment]
![grafica](https://cloud.githubusercontent.com/assets/3384541/13089682/d16a602e-d4bf-11e5-83f7-81711e22f860.png)

**Comment by kevinkhill** [comment]
Hopefully, the last piece of this puzzle....
Your chart is titled ```Temps``` so in the loadData function, you need to pass the title, not the chart type to load that chart's data.

```javascript
$(document).ready(function() {  
    $.getJSON('http://localhost/bitacorasGraficas/public/googleAjaxData', function (dataTableJson) {
  lava.loadData('Temps', dataTableJson, function (chart) {
    console.log(chart);
  });
});
```

**Comment by montes2012** [comment]
thanks for support , but I have this error

![error1](https://cloud.githubusercontent.com/assets/3384541/13090730/6968474c-d4c5-11e5-9cb4-71c3f988a35f.png)

![error2](https://cloud.githubusercontent.com/assets/3384541/13090762/a3e1f3f0-d4c5-11e5-8302-c70267b4983a.png)

![error3](https://cloud.githubusercontent.com/assets/3384541/13090776/b8071360-d4c5-11e5-92a2-85fdaa4ece79.png)

**Comment by kevinkhill** [comment]
Well now you have reached the same point as @TheTechnoMan to which this is a legitimate bug. :(

I am working on a fix

**Comment by montes2012** [comment]
thanks for your help and I congratulate

**Comment by kevinkhill** [comment]
I think I have fixed this issue in 3.1, and will backport the fix for the 3.0 branch soon.

**Comment by kevinkhill** [comment]
Currently, in the master branch, I have added a new method, for controlling race conditions. It will be added soon to the 3.0 branch.

But you use it like this:
```javascript
lava.ready(function() {
    $.getJSON('http://localhost:8000/data.php', function (data) {
        lava.loadData('Prices', data);
    });
});
```

The lava.ready method is called as the last step in the process. Once the google chart api loads and the charts are rendered, then it is called. This way, there is no worry that a chart is trying to load or be accessed if it is not ready

**Comment by kevinkhill** [comment]
The master branch, which will soon become 3.1 should have support for events. Please re-open or start a new issue if needed.
