### ISSUE TITLE
Aggregated data with Dashboard

### ISSUE THREAD

**Issue by patroniton** [kevinkhill/lavacharts#107]
I want to dynamically display aggregated column chart data in a dashboard based on the date range the user has selected.

This is an example of the data I am using. This is what is in the DataTable object:

    "2016-01-01" [
    	"Apple" => 5,
    	"Orange" => 2,
    	"Banana" => 10
    ],
    "2016-01-02" [
    	"Apple" => 1,
    	"Orange" => 7,
    	"Banana" => 3
    ],
    "2016-01-03" [
    	"Apple" => 2,
    	"Orange" => 9,
    	"Banana" => 5
    ],
    "2016-01-04" [
    	"Apple" => 8,
    	"Orange" => 9,
    	"Banana" => 0
    ],
    "2016-01-05" [
    	"Apple" => 6,
    	"Orange" => 8,
    	"Banana" => 11
    ]

So for the entire date range the column chart would have the following values:

	"Apple" => 22, // 5 + 1 + 2 + 8 + 6
	"Orange" => 35, // 2 + 7 + 9 + 9 + 8
	"Banana" => 29 // 10 + 3 + 5 + 0 + 11

But if the user slides the date range filter to `2016-01-02 - 2016-01-04` it would have the following values:

	"Apple" => 11, // 1 + 2 + 8
	"Orange" => 25, // 7 + 9 + 9
	"Banana" => 8 // 3 + 5 + 0

Is there any way to accomplish this with this package?

**Comment by kevinkhill** [comment]
I believe it should work... 
My support for dashboards is still in it's infancy, but that sounds like a reasonable expectation. I'll look into it when I get a chance

**Comment by patroniton** [comment]
No problem. I'm already pretty grateful for the package that you have out right now. Saving me a bunch of time and headaches.

Is there a way to do this right now in the current version? If I put in the data as described before, for the column chart it will have 5 data groups each with 3 points (5 dates with 3 fruits for each date). This is expected since I'm dividing the data up by date. But I'm wondering if there's some sort of `group` or aggregate function(s) I missed in the documentation or something where I can group/aggregate the data for all dates and show only a single data point for each fruit.

If that's not possible right now then it's no biggie. This is by far the easiest package I've seen that integrates charting with Laravel.

**Comment by kevinkhill** [comment]
So, upon taking a quick look into this, it might be possible..... That is, if Google's Chart API can aggregate data like you want. As of right now, lavacharts does no processing of the data internally, it just converts it to json and gives it to the API. It might be possible to use some tools that Google offers, and achieve what you want, but it would be a bit before that would get added into Lavacharts.

I found [this article](https://developers.google.com/apps-script/articles/charts_dashboard#what_exactly_are_the_filter_and_dashboard_objects), and it looks like I might (in the future) be able to do some interesting things with dashboards and such
