### ISSUE TITLE
OneToMany Dashboard binding not displaying charts of different chart types

### ISSUE THREAD

**Issue by patroniton** [kevinkhill/lavacharts#108]
I want one filter to control the data of multiple charts. I have my code set up like so:

	// Controller
	$lineChartWrapper = Lava::ChartWrapper($lineChart, 'line-chart');
	$areaChartWrapper = Lava::ChartWrapper($areaChart, 'area-chart');
	
	$combinedControl = Lava::ControlWrapper($filter, 'combined-control');
	$combinedDash = Lava::Dashboard('Combined')->bind($combinedControl, [$lineChartWrapper, $areaChartWrapper]);
	
	return View::make('test-dashboard')->with('Combined', $combinedDashboard);
	
	// View
    <div id="combined-dashboard">
        <div id="line-chart">
        </div>
        <div id="area-chart">
        </div>
        <div id="combined-control">
        </div>
    </div>
	
    {!! Lava::render('Dashboard', 'Combined', 'combined-dashboard') !!}

This displays nothing when the view loads. The divs `line-chart`, `area-chart`, and `combined-control` are all empty. However when I make the charts of the same type like so:

	// Controller
	$lineChartWrapper = Lava::ChartWrapper($lineChart, 'line-chart');
	$lineChartWrapper2 = Lava::ChartWrapper($lineChart2, 'line-chart2');
	
	$combinedControl = Lava::ControlWrapper($filter, 'combined-control');
	$combinedDash = Lava::Dashboard('Combined')->bind($combinedControl, [$lineChartWrapper, $lineChartWrapper2]);
	
	return View::make('test-dash2')->with('Combined', $combinedDashboard);
	
	// View
    <div id="combined-dashboard">
        <div id="line-chart">
        </div>
        <div id="line-chart2">
        </div>
        <div id="combined-control">
        </div>
    </div>
	
    {!! Lava::render('Dashboard', 'Combined', 'combined-dashboard') !!}
	
It works and both charts update based on the single filter on the page. From what I can tell the javascript on the page is all there, I can see the datatable and the `dashboard.bind` in the javascript, but the divs are just empty when the page loads. I'm not sure if it's something I'm missing or if this is a bug. Thanks!

**Comment by kevinkhill** [comment]
Probably a bug, since I am not the best javascript-er and am still learning while making all of this. I will look into this.

**Comment by kevinkhill** [comment]
Turns out that using Line and Area produced this output in my javascript
```
google.load('visualization', '1', {
                packages: ["controls","corechart","corechart"],
                callback: function() {
                    lava.dashboards["Combined"].render();
                }
            });
```
and when you went to two line charts it was just ```packages: ["controls","corechart"]```

Adding ```array_unique()``` seems to have fixed the problem. In my test I could control a Line & Area chart with one slider
