### ISSUE TITLE
[Question] Material Chart Types

### ISSUE THREAD

**Issue by patroniton** [kevinkhill/lavacharts#109]
Hi just a quick question. Are you planning on implementing material charts into this package at any point? It looks like Google implemented this into their core charts fairly recently.

https://developers.google.com/chart/interactive/docs/gallery/barchart#creating-material-bar-charts (they have this section on each of their core charting pages for material chart types)

I think all that's needed to be done (from what I see in the Google Charts documentation anyway) is to change the visualization package and set up the options differently.

Thanks!

**Comment by kevinkhill** [comment]
Definitely, I saw that it was an option as well. I don't think it will be too hard to implement.

I will take a look and see if it can make it into 3.1

**Comment by patroniton** [comment]
Awesome! Thanks so much for being on top of these questions and willing to look into them. Developers like you are what make the world go round. :)

**Comment by kevinkhill** [comment]
Keeping on top of questions is easy, since I use IFTTT to get alerts on my phone when issues are raised on github. 

As for willing to work on things... This library is my baby, I've invested so much time now, and people actually use it and like it.

It started out just for myself, because I found no good php charting libraries, and has just evolved over time.

**Comment by kevinkhill** [comment]
If you want to test it out, the 3.1 branch has support for material charts. Require ```dev-3.1``` in your project to test it out. I haven't written all the docs yet but just add ```'material' => true``` to your option array.

Also, with 3.1, there is no need to add the elementId for rendering in the view, it is assigned to the chart. Either use the 4th parameter of the chart constructor, or add ```'elementId' => 'example-output-id'``` to your option array.

Google currently only supports Line, Bar and Scatter for material design, so, Lavacharts follows suit.

**Comment by kevinkhill** [comment]
The master branch, which will soon become 3.1 should have support for events. Please re-open or start a new issue if needed.
