### ISSUE TITLE
NULL is not a valid DataTable.

### ISSUE THREAD

**Issue by cardi777** [kevinkhill/lavacharts#110]
What version are you having trouble with?
now that im using laravel 5.2, im getting 

> InvalidDataTable in Lavacharts.php line 522:
> NULL is not a valid DataTable.

```
$stat_table = Lava::DataTable();
$stat_table
        ->addDateColumn( 'date' )
        ->addNumberColumn( 'Visits' )
        ->addNumberColumn( 'Page Views' );
$stats = LaravelAnalytics::getVisitorsAndPageViews( 30, "date" );
```

**Comment by kevinkhill** [comment]
You're going to have to show me more code for me to help, but that exception means the datatable wasn't passed to the chart

**Comment by cardi777** [comment]
Kevin - thanks for the reply. Sorry i wuz up very late when i wrote the msg. Should have put in way more

I had a thought that might be responsible. That code is actually in the blade template - not in a controller - probable cause?

**Comment by kevinkhill** [comment]
Well, yes then. All chart creation happens in the controller. The only thing you need in the view is to render the chart. Have you checked out the examples on lavacharts.com?

**Comment by cardi777** [comment]
Everything was working fine in Laravel 5 inside the blade page - it was to save me time. I will put it all in the controller.

Love the package sooo happy thanks mate

**Comment by kevinkhill** [comment]
Sure thing, stop by anytime if you need help. I'll close this issue for now

**Comment by cardi777** [comment]
ok sorry iv moved it into the controller - its still going on.



```
$stat_table = \Lava::DataTable();
			$stat_table
				->addDateColumn( 'date' )
				->addNumberColumn( 'Visits' )
				->addNumberColumn( 'Page Views' );


			$stats = \LaravelAnalytics::getVisitorsAndPageViews( 30, "date" );

			foreach ( $stats as $stat ) {
				$tmp = array( $stat['date'], $stat['visitors'], $stat['pageViews'] );
				$stat_table->addRow( $tmp );
			}
			//dd($stat_table);
			$lineChart = \Lava::LineChart( 'Visitors & Page Views' )
			                 ->setOptions( array(
				                 'datatable'      => $stat_table,
				                 'title'          => 'Visitors & Page Views - 30 days',
				                 'fontSize'       => 12,
				                 'fontName'       => 'Open Sans',
				                 'titleTextStyle' => \Lava::TextStyle( array(
					                 'color'    => '#000',
					                 'fontSize' => 18,
					                 'bold'     => false,
				                 ) ),
				                 'lineWidth'      => 2,
				                 'colors'         => array( '#337ab7', '#33B796' )
			                 ) );

			$chart_1 = \Lava::render( 'LineChart', 'Visitors & Page Views', 'getVisitorsAndPageViews' );
```

Error:

```
InvalidDataTable in Lavacharts.php line 522:
NULL is not a valid DataTable.
in Lavacharts.php line 522
at Lavacharts->chartFactory('LineChart', array('Visitors & Page Views')) in Lavacharts.php line 148
at Lavacharts->__call('LineChart', array('Visitors & Page Views')) in Facade.php line 218
at Facade::__callStatic('LineChart', array('Visitors & Page Views')) in AdminController.php line 48
at AdminController->welcome()
at call_user_func_array(array(object(AdminController), 'welcome'), array()) in Controller.php line 78
at Controller->callAction('welcome', array()) in ControllerDispatcher.php line 146
at ControllerDispatcher->call(object(AdminController), object(Route), 'welcome') in ControllerDispatcher.php line 94
```

not sure if iv done something wrong? I figured out the code executes up until this line

`$lineChart = \Lava::LineChart( 'Visitors & Page Views' )`

**Comment by kevinkhill** [comment]
Are you using Lavacharts 3.0 or 2.5?

**Comment by cardi777** [comment]
`"khill/lavacharts": "2.5.*",`

**Comment by kevinkhill** [comment]
I will look into this and get back to you, it's getting late for me.

**Comment by kevinkhill** [comment]
OK, so check out the wiki page for the new 3.0 syntax, you are using the old 2.5 syntax

**Comment by cardi777** [comment]
you are right, syntax is different. Sorted! thanks

**Comment by kevinkhill** [comment]
No problem, happy to help
