### ISSUE TITLE
cannot change interface

### ISSUE THREAD

**Issue by toanthree** [kevinkhill/lavacharts#111]
- I have used your column chart dependency. And it works very well, but i have something i couldn't do.
- I want to customize some thing in interface of the chart. But i don't know how to do it. Can you give me some instruction ?

- Thanks in advances

**Comment by kevinkhill** [comment]
I'm not really sure what you are looking for, could you elaborate?

**Comment by toanthree** [comment]
I want to customize ( in Column chart) :

-  Color of column
-  Move title of chart to center ( which default is on the left)
-  Make border for the legend, too.

=> How can i customize that?

**Comment by kevinkhill** [comment]
Any option that Google offers, you can use in Lavacharts. Just pass in the options you want as an array to the chart as the third parameter when creating it. 

Check here for all available options. 
https://developers.google.com/chart/interactive/docs/gallery/columnchart

**Comment by kevinkhill** [comment]
I'm closing this as an issue, as with the 3.0.2 update, you can set any option you might need.
