### ISSUE TITLE
Generate chart in view

### ISSUE THREAD

**Issue by farr433** [kevinkhill/lavacharts#113]
Hey Kevin is it still possible to create new charts from the view? I recently upgraded from 2.5 and have been having a little trouble. I'm still on laravel 4.2 but Essentially I have a few simple widgets where I wanted to include the logic and view in one file. Then I just @yield the section into my main page based off user roles. I created a gist where I am creating a pie chart based off the number of employees in each department. This code worked fine with the older version of lavacharts (minus migration changes) but now I get the attached error. I probably should just use ajax requests instead of being lazy but I just want to make sure it is not me missing something.

[Here is the gist:](https://gist.github.com/farr433/c370a5578bca4a0b93eb)
You will see I load two charts, the line chart is loaded in the controller before creating the view and works fine if I take the pie chart call out.

![err](https://cloud.githubusercontent.com/assets/3854190/13621353/04fa0362-e565-11e5-9086-6e8c31233848.PNG)

**Comment by kevinkhill** [comment]
I'll need you to post the contents of the file it's referring to. (it's in your cache folder) Since it's a compiled blade template, I can't really go off of your screen shot alone.

**Comment by kevinkhill** [comment]
Sorry! Missed the attachments, I'll take a look

**Comment by farr433** [comment]
Ahh, I didn't even think of checking the compiled view out because yeah that error is absolutely no help. Now I just loaded a view as the owner (changing session variables) and his shows both graphs beautifully. It must be something on my end with syntax...

![errrrrpng](https://cloud.githubusercontent.com/assets/3854190/13622124/93d95088-e56a-11e5-8c3a-f813ea0dcb45.PNG)

**Comment by kevinkhill** [comment]
Hmm, well, I'm here if any other issues arise

**Comment by farr433** [comment]
But theoretically there shouldn't be any issues with creating the Lava::chart within the view right because in 4.2 its all pretty much global?

**Comment by kevinkhill** [comment]
I don't see why not. As long as you use the one instance of Lavacharts, then you should be able to create and render wherever.

**Comment by farr433** [comment]
This is it right here... Not sure how that is happening yet though.

![er](https://cloud.githubusercontent.com/assets/3854190/13622412/850d7668-e56c-11e5-9492-781bb02860dc.PNG)

**Comment by farr433** [comment]
I'm sure you see it but the first PHP tag doesn't close before opening the new one.

**Comment by kevinkhill** [comment]
It might be an issue with my blade directives. It looks like it's putting one inside the other. I don't think I tested using two like that.

**Comment by farr433** [comment]
Yep so now this works. 
`
{{Lava::render('PieChart', 'departmentProfile', 'departmentProfile')}}

{{Lava::render('LineChart', 'weekSales', 'chart_div')}}

`

**Comment by farr433** [comment]
So it's in the blade template shortcut

**Comment by farr433** [comment]
Thanks for taking the time to put another eye on it though... Leave it up to me to find the weird stuff haha, I love library though!

**Comment by kevinkhill** [comment]
Thanks for giving it a shot. Also, thanks for reporting this bug you've found. I'll add it to my todo list

**Comment by kevinkhill** [comment]
It's strange, I can't seem to reproduce this error. I tried with two directives, back to back. Then in a @section, @extend-ing a layout. Each time it seems fine. I am puzzled.

I did borrow some code from my working branch, so I'll put that in the 3.0 line

**Comment by kevinkhill** [comment]
I'm not going to tag it just yet, but if you feel like testing, then just require ```dev-3.0```
