### ISSUE TITLE
ColumnChart doesn't support some options

### ISSUE THREAD

**Issue by michelerota** [kevinkhill/lavacharts#115]
V3, ColumnChart is missing some options like: annotations, dataOpacity, enableInteractivity, forceIFrame, orientation, reverseCategories, series, theme.
These options are documented at [google doc](https://google-developers.appspot.com/chart/interactive/docs/gallery/columnchart#configuration-options)

**Comment by kevinkhill** [comment]
For now, you can use the ```customize``` method to set any options you want. In v3.1, there will be no limitations on options

**Comment by michelerota** [comment]
"customize" works perfectly, thanks!
Thanks for lavacharts, it's very useful.

**Comment by kevinkhill** [comment]
Happy to help :)

**Comment by motahida-jordan** [comment]
how to use customize method? where?
I tried the series in this example: https://jsfiddle.net/api/post/library/pure/ but it didn't work:
```
Lava::ColumnChart('ConnectedDisconnected', $data, [
           
            'titleTextStyle' => [
                'color'    => 0,
                'fontSize' => 14
            ],
            'legend' => [
                'alignment' => 'end',
                'position' => 'top'
            ],
            'series'=>[
                '0'=>['axis'=>'criterias_count'],
                '1'=>['axis'=>'criterias_count2'],
            ],
            'axes'=>['y'=>[
                'criterias_count'=>['label'=>'Test1'],
                'criterias_count2'=>['label'=>'Test2']
            ]]
        ]);
```

Any help is appreciated, thanks

**Comment by kevinkhill** [comment]
I'm not sure what you are asking because the fiddle isn't loading for me (all the panes are empty) and the php code you posted, isn't using the customize method.
