### ISSUE TITLE
InvalidConfigProperty when setting pieHole in DonutChart

### ISSUE THREAD

**Issue by Bogstag** [kevinkhill/lavacharts#116]
Using this code:
```
$chart = \Lava::DonutChart('stepToday', $steps, [
            'pieHole' => 0.7
        ]);
```
Generates this error:
InvalidConfigProperty in JsonConfig.php line 117:
"pieHole" is not a valid property for DonutChart->setOptions, must be one of [ animation | backgroundColor | chartArea | colors | datatable | events | fontName | fontSize | height | is3D | legend | pieResidueSliceColor | pieResidueSliceLabel | pieSliceBorderColor | pieSliceText | pieSliceTextStyle | pieStartAngle | reverseCategories | slices | sliceVisibilityThreshold | title | titlePosition | titleTextStyle | tooltip | width ]

But if i use this instead:
```
$chart = \Lava::DonutChart('stepToday', $steps, [

        ]);
        $chart->pieHole(0.7);
```
it works.

If i look in the [lavacharts.com](http://lavacharts.com/#chart-donut) documentation, it looks like the first option is was is described here.

I dont know if it is a bug or if i'm reading the docs wrong. But i just wanted to say something if others has the same problem.

Thanks for lavacharts, keep up the good work!

What version are you having trouble with?
LavaCharts 3.0.1 and Laravel 5.2.23

**Comment by kevinkhill** [comment]
Sounds like a bug to me, I'll look into it for you

**Comment by kevinkhill** [comment]
I believe I have found and squashed the bug, could you test in your project for me with the ```dev-3.0``` branch so we can verify? I will tag as ```3.0.2``` once you do :smile: Thanks!

**Comment by Bogstag** [comment]
I installed "3.0.x-dev" and it works for me.

Thanks!

**Comment by kevinkhill** [comment]
Excellent :)
