### ISSUE TITLE
Combo chart docs

### ISSUE THREAD

**Issue by emmanuelLS** [kevinkhill/lavacharts#117]
Hi 

How do you implement the combo chart? I checked your documentation still can't find it. Guessing it is not yet updated. 

Attached here the image I'm trying to achieve.
![graph](https://cloud.githubusercontent.com/assets/5345023/13937742/5f288fbe-f002-11e5-8e84-aad177337ad8.png)

Thanks,
Emman

**Comment by kevinkhill** [comment]
ComboCharts are supported, I didn't realize that I missed that in my docs!

**Comment by kevinkhill** [comment]
[Here is an example of how to create one](https://github.com/kevinkhill/lavacharts/blob/3.0/tests/Examples/Charts/ComboChart.php)

**Comment by emmanuelLS** [comment]
Yes, Im sorry I really cant find the docs, 
Maybe I missed it out. I hope you can help

**Comment by kevinkhill** [comment]
[Here is an example of how to create one](https://github.com/kevinkhill/lavacharts/blob/3.0/tests/Examples/Charts/ComboChart.php)

**Comment by emmanuelLS** [comment]
Thanks
