### ISSUE TITLE
CalendarChart does not load and causes chrome tab to lock up?

### ISSUE THREAD

**Issue by colford** [kevinkhill/lavacharts#119]
Hello, 
I must be doing something wrong but I can't seem to get the calendar chart to work from a blade. I create the date and count columns and rows and can use a bar chart to plot these with and that all works great. If I then change to using a calendarchart chrome will not load the page. I'm using the charts in a tab, all of my other charts load OK, except when I use the calendarchart?

...any ideas?

```
   $dataTable = \Lava::DataTable();
   $dataTable->addDateColumn( 'Date' )->addNumberColumn( 'Count' );
   $dataTable->addRow([ $row->date, $row->count ]);
   $graphic = \Lava::CalendarChart('EventsByHeatmap', $dataTable);
```

```
    <div id="tab7" class="tab-pane fad">
       <h3>Events Heatmap (raw count)</h3>
       <div id="EventsHeatmap">
       </div>
       @calendarchart('EventsByHeatmap','EventsHeatmap')
    </div>
```

**Comment by kevinkhill** [comment]
That is very strange. I will try and recreate your issue and see if I can find out what's going on.

**Comment by kevinkhill** [comment]
hmmmm, so I made a quick test and I can get a calendar chart to display, no issue. It is a very bare test though.

A couple questions, are the dates coming in as properly formatted dates for [Carbon](https://github.com/briannesbitt/Carbon) to create an instance from? If not, and they are a different than usual format, try using the ```setDateTimeFormat()``` of the DataTable to define how dates with be parsed.

Is there any javascript errors thrown in the console, or does it just freeze up?

**Comment by colford** [comment]
Hi, thanks for trying. If I var_dump a couple of the added rows it shows:

```
object(stdClass)[777]
  public 'count' => int 1
  public 'date' => string '2015-11-26' (length=10)
object(stdClass)[776]
  public 'count' => int 8
  public 'date' => string '2016-02-18' (length=10)
```

The main page locks up on chrome but if I inspect then I see this error:

`Uncaught TypeError: $(...).datetimepicker is not a function`

![capture](https://cloud.githubusercontent.com/assets/13421296/14076914/ffd31440-f4dd-11e5-97fb-3cb141f14d5b.JPG)

**Comment by kevinkhill** [comment]
Maybe the error is halting all JS execution? Try removing that plug in or fixing that it's not found?

**Comment by colford** [comment]
Looks like its getting stuck in a loop, width is 0 for some reason?
![image](https://cloud.githubusercontent.com/assets/13421296/14086935/7f7957ae-f51f-11e5-93f2-777d25f3dc1d.png)

**Comment by kevinkhill** [comment]
Maybe because, since it's in a tab, when it tries to render, it picks up zero width from the hidden div? Try defining the chart with a  set width. ```'width'=>600```

It's possible that it's a limitation / bug of Google's and not mine.

**Comment by colford** [comment]
I tried changing the width parameter but that made no difference. However if I take it out of the tab then it renders? Looks like it's a bug with the Google code or a tab bug...

![image](https://cloud.githubusercontent.com/assets/13421296/14104120/4f0082d8-f59b-11e5-8fb9-46d882cd9b68.png)

**Comment by colford** [comment]
Seems OK in a tab on it's own but unhappy if I have one tab with @calendarchart and one tab with a @dashboard. As soon as I do that I get the infinite loop in the chrome tab.

**Comment by kevinkhill** [comment]
I don't know exactly how the rendering process works with Google, but I do know others have had issues in the past with charts hidden in tabs. Like Issue #97

**Comment by kevinkhill** [comment]
I developed a way for outputting charts as PNG in the 3.1 branch, which I think will be easy to port back into 3.0.... might work for tabs? I have yet to test

**Comment by colford** [comment]
OK, so I've been digging a little further and it appears if I have a calendar then the other charts do not appear but if I have the other charts then the calendar does not appear. The render function will not be called for some reason?

**Comment by colford** [comment]
Ah a bit further. It looks as if I try and render more than one "plain" (i.e. non dashboard) chart then I can only get the one to show up. If they are dashboards then I can render more than one. Need to see if I can use a calendar in a dashboard. 

Potentially it could be this google bug? 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/google-visualization-api/KulpuT418cg/yZieM8buCQAJ

**Comment by kevinkhill** [comment]
Very interesting... It's really hard to debug timing issues like that. I like the idea of chaining the rendering of the charts upon each other's ready events. I do get that will make it so a user can't use the chart's ready event, but since I'm adding a ```lava.ready``` method to pass a callback into.

**Comment by colford** [comment]
Do you have any plans to use the gstatic loader that is shown in the new documentation?
https://developers.google.com/chart/interactive/docs/basic_load_libs

**Comment by kevinkhill** [comment]
I did recently notice that they introduced the new gstatic loader. I do plan on incorporating it, since I want to keep Lavacharts up to date with Google's API

**Comment by kevinkhill** [comment]
This will be a little more in-depth than just replacing the URL, damn...

The first caveat from the docs:
> You can only call google.charts.load() once. But you can list all the packages that you'll need in one
> call, so there's no need to make separate calls.

I have each chart loading itself as needed, so multiple calls to the load method. I will have to refactor chart output to be done all at once, or at least collect what charts will be output and have them preloaded when the lava.js module is output

**Comment by colford** [comment]
Yes, I was just looking at that as well. Also since you only can call load once you have to load up everything that you might want to possibly use.

**Comment by colford** [comment]
Could you put the load in lave.js::this.run::onreadystatechange and then in the factory where the loads are use: 

google.charts.setOnLoadCallback(lava.charts.<chartType>["<chartLabel>"].render());

**Comment by kevinkhill** [comment]
Could you move this discussion into issue #127 for me so we can track this issue independently from the calendar bugs?

**Comment by kevinkhill** [comment]
Closing this issue (about the calendar) due to staleness. Please re-open if you are still having issues.
