### ISSUE TITLE
Don't load the alias in the ServiceProvider

### ISSUE THREAD

**Issue by Gummibeer** [kevinkhill/lavacharts#120]
Hey,

it would be nice if the ServiceProvider won't load the alias. The reason is simple: you define the alias but the dev/user of the package can have it's own Class with this name or just don't like it.
So the dev should have the option to define the alias by it's own.

**Comment by kevinkhill** [comment]
I though for sure I was safe with Lava, I didn't think I would run into issues. Are you running into an issue with the alias? Or do you just want to give it a different one?

**Comment by Gummibeer** [comment]
There are different points. For me it's mostly the fact that I don't like packages that do something that I don't want (adding an alias) and in my App I want to have, if I use the alias, an alias named `Chart`.
And to the fact why I don't like it: everything that a package does is something like in a blackbox - the User can't change the behaviour or add it's own or decide to don't use an alias.
So it's no real issue that it doesn't work but it's not good/best practice. Would be cool if you can change this.

**Comment by kevinkhill** [comment]
I see what you are saying. Honestly, I don't remember when I found the blog post about autoloading the alias, but I thought it was cool. I get that the user would want to be able to change it. 

I suppose I could remove the auto alias and just add a note in the docs about manually adding the alias (Like every other Laravel package)

**Comment by kevinkhill** [comment]
I have decided that I am not going to alter the package, and affect hundreds of other users, just to solve the very rare occurrence that there is another package needing the "Lava" alias.

Sorry! I hope you understand
