### ISSUE TITLE
Fatal error: Class 'Lava' not found

### ISSUE THREAD

**Issue by r4lly99** [kevinkhill/lavacharts#122]
I'm using version 3 lavachart with laravel 5.1 , xammp php7 , with demo example

`use Khill\Lavacharts\Lavacharts;`

`$stocksTable = \Lava::DataTable() ;`

`$stocksTable->addDateColumn('Day of Month')
                    ->addNumberColumn('Projected')
                    ->addNumberColumn('Official');`

`for ($a = 1; $a < 30; $a++)`

```
 {
            $rowData = [
              "2014-8-$a", rand(800,1000), rand(800,1000)
            ];

            $stocksTable->addRow($rowData);
        }
```

```
and View 

` <div id="stocks"></div>
                        @linechart('Stocks', 'stocks-div', true)`

then i get error CLass 'Lava' not found
```

**Comment by stefanmahr** [comment]
Hi r4lly99!

I have the same error. Try these

Change
`use Khill\Lavacharts\Lavacharts;`

to

`use Khill\Lavacharts\Laravel\LavachartsFacade as Lava;`

Hope this will help you.

**Comment by kevinkhill** [comment]
So some people get this error and others don't, but I still don't know why? In my test Laravel apps, I've never had to add a use statement for the Facade

**Comment by r4lly99** [comment]
Sorry for late response , i'm using version 3 mr.kevin, still got same error mr.stefanmahr. I dont know why , i try downgrade xampp version and using php 5 . But thank for your suggestion anyway

**Comment by kevinkhill** [comment]
My only guess is... 
It might be that since you are manually including lavacharts with the ```use``` statement, it is overriding Laravel's autoloading of the Lava alias?

Since composer is loading Lavacharts and Laravel is loading composer, you don't need the ```use``` line. Try removing it and see if that helps.

**Comment by r4lly99** [comment]
still got same error mr.kevin, when i used it with laravel 5.0 and lavachart 2.5 it's fine, is there conflict in another requirement on my composer
 `"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "efficiently/authority-controller": "dev-master",
		"cossou/jasperphp": "dev-master",
		"laravelcollective/html": "5.1.*",
		"guzzlehttp/guzzle": "~5.3|~6.0",
		"khill/lavacharts" : "3.0.*"
    },` 
sorry for newbie question btw , i'm newbie after all

**Comment by kevinkhill** [comment]
No problem at all, I am happy to fix bugs. I will try and recreate this with your same composer requirements

**Comment by kevinkhill** [comment]
Closing this due to staleness. Please open another issue if you still need help :smile:

**Comment by cardi777** [comment]
im having this heartache. can't figure it out

**Comment by kevinkhill** [comment]
Can you please post you composer file, and the relevant chart creation code, so I can try to recreate your issue?

**Comment by PascalZajac** [comment]
I encountered this issue while upgrading from Laravel 5.2 to 5.3. I resolved it by adding the following line to the `aliases` entry within `config/app.php`:

```php
        'Lava' => Khill\Lavacharts\Laravel\LavachartsFacade::class,
```

I copied the line from the `LavachartsServiceProvider` class. My Composer file is:

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.3.*",
        "doctrine/dbal": "~2.5",
        "khill/lavacharts" : "3.0.*"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "2.2.3",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/AuthenticatedTestCase.php",
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

**Comment by cardi777** [comment]
i have rectified the issue. sorry! I tried for a very long time to fix it before posting here - was my own error :)

**Comment by kevinkhill** [comment]
Well I'm glad you got it working ☺️

**Comment by bhirons** [comment]
Hi Kevin,  I got the same problem with the facade not being recognized. (I'm using Lavacharts with Laravel 5.4 and PhpStorm on Mac, although I'm not sure how much that makes a difference or not.) I fixed it for my environment by changing your code (on this line of the LavachartsServiceProvider)[https://github.com/kevinkhill/lavacharts/blob/b243de1cd38a9a5078d215e1f7d2c0b8416936cd/src/Laravel/LavachartsServiceProvider.php#L70]:

`$loader->alias('Lava', 'Khill\Lavacharts\Laravel\LavachartsFacade');`

to this

`$loader->alias('Lava', \Khill\Lavacharts\Laravel\LavachartsFacade::class);`

I can send this a a PR if you like, anyway it is a simple and harmless change I think for current versions of Laravel.

Budd.

**Comment by kevinkhill** [comment]
What is interesting to me, is that `\Khill\Lavacharts\Laravel\LavachartsFacade::class` should resolve to the same string as what was replaced. Maybe the leading `\` is needed?

I don't want to use the `::class` operator (even though I like it) because it was introduced in PHP 5.5 and v3.1 of the library is still PHP 5.3 compatible.

If you can verify that a leading slash on the string works, as `$loader->alias('Lava', '\Khill\Lavacharts\Laravel\LavachartsFacade');` I would happily accept a PR for that.

**Comment by kevinkhill** [comment]
Closing due staleness and lack of communication. Please open a new issue of you still need assistance, as I am happy to help. ☺️
