### ISSUE TITLE
lavacharts.com is unreachable in some regions

### ISSUE THREAD

**Issue by orottier** [kevinkhill/lavacharts#124]
I think you have a DNS problem

Amsterdam server:
<pre>
dig lavacharts.com +noall +answer

; <<>> DiG 9.8.3-P1 <<>> lavacharts.com +noall +answer
;; global options: +cmd
</pre>

Chicago server:
<pre>
dig lavacharts.com +noall +answer

; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> lavacharts.com +noall +answer
;; global options: +cmd
lavacharts.com.		1800	IN	A	192.30.252.153
</pre>

**Comment by kevinkhill** [comment]
I'm not sure what Namecheap did, because I remember setting this up before. Anyways, I think it's good now. It might take some time for the DNS to propagate but, I am already getting this with dig
```
$ dig lavacharts.com +nostats +nocomments +nocmd

; <<>> DiG 9.10.3-P3 <<>> lavacharts.com +nostats +nocomments +nocmd
;; global options: +cmd
;lavacharts.com.                        IN      A
lavacharts.com.         1799    IN      A       192.30.252.154
lavacharts.com.         1799    IN      A       192.30.252.153
```

**Comment by orottier** [comment]
:+1: works from here again

**Comment by kevinkhill** [comment]
Glad to hear, thanks for bringing it to my attention
