### ISSUE TITLE
New div on the fly?

### ISSUE THREAD

**Issue by hopewise** [kevinkhill/lavacharts#126]
I am expecting to render custom number of charts vertically under each other, I've noticed that I have to define the target div, but in my case, I need the divs to be created on the fly.

At least, to render all charts into one div, is this possible? what's your thoughts about it?

**Comment by kevinkhill** [comment]
Do you mean, [like this?](https://github.com/kevinkhill/lavacharts/blob/3.0/src/Lavacharts.php#L249) :smiley:

**Comment by hopewise** [comment]
Yes :+1:  so, I just pass true, and it will create the target div ? where would it add the new div then?

**Comment by kevinkhill** [comment]
It will be placed [right before the javascript block](https://github.com/kevinkhill/lavacharts/blob/3.0/src/Lavacharts.php#L292) so wherever your ```render()``` call or blade directive is, that's where the div will go.

**Comment by hopewise** [comment]
Thanks, but I am still not able to make it work with `@columnchart` can you please put an example with blade that does not require to specify div?

**Comment by kevinkhill** [comment]
Were you able to get this working? (Sorry for my lack of reply)

**Comment by kevinkhill** [comment]
The way that the library is evolving now, this feature for creating the div on the fly is becoming obsolete. I can still help you resolve this if you are having trouble, but in v3.2 it will no linger work.

Are you using Laravel 5+

I will still help, but I want to close the issue
