### ISSUE TITLE
Gstatic Loader

### ISSUE THREAD

**Issue by kevinkhill** [kevinkhill/lavacharts#127]
Switching from the old style to the [new gstatic loader](https://developers.google.com/chart/interactive/docs/basic_load_libs#basic-library-loading) as disscussed in #119

**Comment by colford** [comment]
I can load the google maps in lava.js this.run and I have set up the render callback in the template for the chart. The render function gets called but the google.visulization is null because it's not been loaded. Not sure where to load that?

I can't see how this demo works since visulization is not explicitly loaded. Unless of course the gstatic charts loader loads it up?

https://jsfiddle.net/3qdxd2m9/2/

I'm loading it here, maybe its the wrong place?

![image](https://cloud.githubusercontent.com/assets/13421296/14434035/c3a515a0-0008-11e6-943b-62645bd76e3f.png)

**Comment by colford** [comment]
Well I have it working :)

![image](https://cloud.githubusercontent.com/assets/13421296/14438068/18db4a2c-001c-11e6-9293-dfa3b1aa4f09.png)

**Comment by colford** [comment]
I changed lavacharts/javascript/lava.js:

```
  this.run = function (window) {
    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.src = '//www.gstatic.com/charts/loader.js';
    s.onload = s.onreadystatechange = function (event) {
      event = event || window.event;
      if (event.type === "load" || (/loaded|complete/.test(this.readyState))) {
        google.charts.load('current', {packages: ['corechart','calendar','controls']});
        this.onload = this.onreadystatechange = null;
        lava.events.emit('jsapi:ready', window.google);
      }
    };
    document.getElementsByTagName('head')[0].appendChild(s);
  };
```

I changed lavacharts/src/Javascript/DashboardFactory.php by deleting the load and replacing it with:

`google.charts.setOnLoadCallback(lava.dashboards["<label>"].render);`

Basically the same for the ChartFactory.php

`google.charts.setOnLoadCallback(lava.charts.<chartType>["<chartLabel>"].render);`

...and that was it..

**Comment by colford** [comment]
Should have said...the google docs where a bit miss-leading until you read...

https://developers.google.com/chart/interactive/docs/basic_multiple_charts

...then that tells you that you can call setOnLoadCallback for each chart.

**Comment by kevinkhill** [comment]
That makes more sense. So I will just have to read each property of the chart, to get it's package and build a list to give to ```google.charts.load()```

You might want to check the overhaul branch if you are going to do any hacking against the codebase. I have many, drastic changes under the hood in 3.1, which I decided to back port to 3.0

**Comment by kevinkhill** [comment]
I've been making progress with gstatic loader :) charts work, but the dashboards are being stubborn

**Comment by colford** [comment]
That's good to know, well done! I'm currently using my quick patch but will switch over when you get the dashboards going. Thanks for the update :)

**Comment by kevinkhill** [comment]
gstatic loader works and it living in the master branch. I will get it into the next 3.0 release

**Comment by kevinkhill** [comment]
The master branch, which will soon become 3.1 should have support for events. Please re-open or start a new issue if needed.
