### ISSUE TITLE
Missing chart types

### ISSUE THREAD

**Issue by umbertix** [kevinkhill/lavacharts#128]
Is there any projection in the plugin to include the missing charts? a.k.a histograms, trend line, etc.

**Comment by umbertix** [comment]
Never mind, checking the version 3.1 on the comments are there. Sweeeeet

**Comment by kevinkhill** [comment]
I am also backporting them into 3.0, because 3.1 has some other changes and I don't want to split the user base into 3.0 and 3.1 too much.
