### ISSUE TITLE
Column Charts Not All Rendered in Chrome

### ISSUE THREAD

**Issue by zahidaziz16** [kevinkhill/lavacharts#129]
Hi Kevin,

Im using Lavacharts version 3.0. I have to render 10 column charts in a single view, but I notice not all charts rendered in Google Chrome, sometimes 3 out of 10, sometimes 5 out of 10.  Yet all the charts well rendered in Firefox. May you help me with this issue? Thanks

**Comment by zahidaziz16** [comment]
So far I figured out, It is a cache problem. The chart having trouble to render after the first time.

**Comment by kevinkhill** [comment]
I haven't seen this in my tests so far, but I will try and recreate your bug

**Comment by emmanuelLS** [comment]
Hi,

I believe I'm having the same problem. How did you solve this issue? 

Thanks

**Comment by kevinkhill** [comment]
So far I haven't encountered this bug. I even once used a ```for``` loop and ```rand()``` to make a page with 100 line charts of random data other all rendered :/

**Comment by kevinkhill** [comment]
Closing this issue due to staleness. Please re-open if you are still having issues.
