### ISSUE TITLE
export to excel

### ISSUE THREAD

**Issue by RokSiEu** [kevinkhill/lavacharts#13]
Is there any chance that you will make it possible to export charts to excel/csv ?

**Comment by kevinkhill** [comment]
It's been a while, but v3 is in the works. No ETA because I am often busy, but right now importing csv files works and I will look into exporting as well.

**Comment by kevinkhill** [comment]
I pulled the extra functionality of csv and collection parsing into another package, [DataTablePlus](https://github.com/kevinkhill/datatableplus). I am still working on everything when I have free time, but right now importing & exporting csv files works. Also, parsing Eloquent collections to datatables. If you want to dig into it, please feel free, but documentation won't happen until later.

**Comment by kevinkhill** [comment]
Since I have moved this functionality into the other package, I'm going to mark this as closed. I might pull the DataTablePlus package into Lavacharts at some point, but I have left this open for too long.
