### ISSUE TITLE
Changing all Text Color

### ISSUE THREAD

**Issue by mucskaati** [kevinkhill/lavacharts#130]
What version are you having trouble with?
Hi,

Can someone of you help me to change colors of texts?

Thanks.

**Comment by patroniton** [comment]
Look at the documentation: http://lavacharts.com/

Search for 'color' and you'll see a bunch of colour options. If you need more help as to what those options refer to, read up on the Google Charts documentation. https://developers.google.com/chart/

**Comment by kevinkhill** [comment]
Thank you @patroniton :)

**Comment by kevinkhill** [comment]
Closing due to staleness of the issue.
