### ISSUE TITLE
Unknown number of columns

### ISSUE THREAD

**Issue by nilsth** [kevinkhill/lavacharts#131]
I might be doing this all wrong (php amateur), but I want to make a line chart with sales numbers per salesperson per date. The number of salespeople might be different each time the code run (based on some other factors). This is what I tried:

Made an array with the active salespeople, then ran a foreach that generated a _$salesTable->addNumberColumn($name)_ for each. That worked fine, but now I'm stuck trying to figure out how to make the rows. Is there any way to fill a single row with values from an array?

Some other way I should be approaching this?

I'm on version 3.0.

Thanks for all your work!

**Comment by kevinkhill** [comment]
From your example, I would use ```addStringColumn``` over number column for sales people's names. 

So, I would do: date, string, number columns and then you would use ```addRow(['2016-1-1','SalesGuy',50000])``` or whatever to add the data

**Comment by nilsth** [comment]
Hmm, that gives me "All series on a given axis must be of the same data type". Tried with just some test data (below), with the same result.

$salesTable->addDateColumn('Date');
$salesTable->addStringColumn('Name');
$salesTable->addNumberColumn('Points');

$salesTable->addRow(['2016-04-20', 'John', 10 ]);
$salesTable->addRow(['2016-04-21', 'John', 15 ]);
$salesTable->addRow(['2016-04-22', 'John', 25 ]);

**Comment by kevinkhill** [comment]
Ah, yes, of course. (I shouldn't answer issues when tired apparently)

Since each row represents a date, then the first is the date column and rest of the row must be sales numbers. Therefore, all columns must be number, not string. Each sales person will be added as a column, after date, so that each row can have corresponding sales figures.

Try something more like this:
```php
    $salesTable->addDateColumn('Date');
    $salesTable->addNumberColumn('Employee1');
    $salesTable->addNumberColumn('Employee2');
    $salesTable->addNumberColumn('Employee3');

    $salesTable->addRow(['2016-04-20', 10, 10, 10 ]);
    $salesTable->addRow(['2016-04-21', 15, 20, 25 ]);
    $salesTable->addRow(['2016-04-22', 20, 20, 30 ]);
```

**Comment by nilsth** [comment]
No problem, I'm just happy that you respond :)

That what was I was trying to to originally. The problem was finding a way to fill the row with data, when the number of employees varies. I can generate a column per employee with a foreach-statement, but what do I do with the rows?

**Comment by kevinkhill** [comment]
I don't know how you are getting the data to provide to the chart, but you could either use some sort of for/foreach statement to build the row data then insert it:
```php
$rowData = ['2016-1-1'];
foreach($employees as $employee) {
    $rowData[] = $employee['sales'];
}
$salesTable->addRow($rowdata);
```
OR

if you can build the whole array beforehand, then you can use the ```addRows()``` method to drop them all in at once. It takes an array of row arrays, so you don't have to make multiple ```addRow``` calls

**Comment by nilsth** [comment]
Thanks! That did the trick
