### ISSUE TITLE
Bar Graph with Line Graph

### ISSUE THREAD

**Issue by emmanuelLS** [kevinkhill/lavacharts#132]
Hi,

How do you create a graph same as this, 
![consultgrap](https://cloud.githubusercontent.com/assets/5345023/14771376/b7faba1c-0abb-11e6-9e9b-cb0dc0f5d338.png)

I tried using ComboChart, but the line graph depends on the value of the bar graph, I want to have a independent value for the line graph. I tried reading some of the docs of yours, but can't find them useful. I hope you can help. 

Thanks,

**Comment by kevinkhill** [comment]
I was under the assumption that the combo chart can graph with multiple axes (check the series config option and axes) so you can have a chart like you show. What about the combochart example I have? (check out  in the repo tests/examples/Charts)

**Comment by emmanuelLS** [comment]
I cant figure out on how to place the 2nd vertical values on the right side, and the line chart follows the maximum values of the bar chart. How do you create a line chart with separate values with the bar chart? As you can see, the line chart is a percentage values while the bar chart is a decimal values.

**Comment by kevinkhill** [comment]
Check out the options for vAxis and vAxes
https://developers.google.com/chart/interactive/docs/gallery/combochart#configuration-options

**Comment by kevinkhill** [comment]
As for the difference on formats, you will need to format the column with the data how you wish.

**Comment by emmanuelLS** [comment]
It is really hard to comprehend all on the documents, :(
If you could only provide a sample graph the same as my sample, it will be a lot of help. 

I did formatted the values as percentage but the real problem is how to have 2 vertical axis same as the sample image, Do you have a sample graph for the graph I have posted?

**Comment by kevinkhill** [comment]
I will take a look a get back to you on that

**Comment by kevinkhill** [comment]
```php
$lava->ComboChart('Sales', $data, [
        'seriesType' => 'bars',
        'series' => [
            1 => [
                'targetAxisIndex' => 1,
                'type' => 'line'
            ]
        ],
        'vAxes' => [
            [
                'format' => 'decimal',
                'title' => 'Rooms',
                'textStyle' => [
                    'color' => 'blue'
                ]
            ],
            [
                'format' => 'percent',
                'title' => 'Capacity',
                'textStyle' => [
                    'color' => 'red'
                ]
            ]
        ]
    ]);
```

**Comment by emmanuelLS** [comment]
awesome! Thanks! gonna try this one.

**Comment by kevinkhill** [comment]
I'm going to assume this worked for you? If not, please feel free to re-open this issue.
