### ISSUE TITLE
Graph Rendering

### ISSUE THREAD

**Issue by emmanuelLS** [kevinkhill/lavacharts#133]
Hi, 

I have a minor issue on rendering a graph. When using POST to retrieve values from database, it also generates the graphs, however I noticed that the graphs on the bottom part is not rendering the way it should be. When I hit refresh the page, that's the time the graph is showing. Here are the screenshots of the graph, 

The first one is the page when I request a POST on the form, and you can see the graph is not showing at the bottom, 
![grapp2](https://cloud.githubusercontent.com/assets/5345023/14800828/2d999840-0b77-11e6-9d5f-dc0dcd71f721.png)

The second image shows the graph after refreshing the page.
![grapp1](https://cloud.githubusercontent.com/assets/5345023/14800840/4dba3cc4-0b77-11e6-94c8-e81640622115.png)

I did check the elements of the page, and saw that the div for the graph, has no script that used for drawing the graph. It is empty unlike the other div

![inspect](https://cloud.githubusercontent.com/assets/5345023/14800858/6e52d3c4-0b77-11e6-8698-5762c3b4b552.png)

I tried using firefox and I did not encounter this issue. Is this a browser issue or something? It's funny to think that this is called google chart and having issues on chrome itself.

**Comment by kevinkhill** [comment]
Very true, this is a weird bug. I think that it is a race condition, that your data is making it in before the rest of the chart api and my module are loading or something like that. I have introduced a new method to to the lava.js module, ```lava.ready()``` You can use it as a callback to wrap any interaction with the charts, like loading with ajax, using the ```lava.loadData()``` method

**Comment by emmanuelLS** [comment]
Can you please provide a sample using that callback?

**Comment by kevinkhill** [comment]
It's only in the master branch right now, soon to be included in 3.0.*

But you use it like this:
```javascript
lava.ready(function() {
    $.getJSON('http://localhost:8000/data.php', function (data) {
        lava.loadData('Prices', data);
    });
});
```

The lava.ready method is called as the last step in the process. Once the google chart api loads and the charts are rendered, then it is called

**Comment by kevinkhill** [comment]
This way, there is no worry that a chart is trying to load or be accessed if it is not ready

**Comment by kevinkhill** [comment]
Closing this issue due to staleness. Please re-open if you are still having issues.
