### ISSUE TITLE
PieCharts and DonutCharts - percentages only?

### ISSUE THREAD

**Issue by giorgiopagnoni** [kevinkhill/lavacharts#134]
What version are you having trouble with? 3.0.2
Do PieCharts and DonutCharts accept only percentages? That is, values that add up to 100, as in all the examples here http://lavacharts.com/#example-pie? If my values don't add up to 100, I get funny charts like this one:
<img width="400" alt="screen shot 2016-04-26 at 15 12 50" src="https://cloud.githubusercontent.com/assets/7541741/14819299/ba0b0418-0bc1-11e6-8c8b-4f14a62d695b.png">
What am I doing wrong?

**Comment by kevinkhill** [comment]
It is my understanding that pie charts are supposed to show the parts of a whole, so yes, I believe that your values should add up to 100

**Comment by giorgiopagnoni** [comment]
It doesn't look like they should in any of the examples here. Am I misunderstanding anything? https://developers.google.com/chart/interactive/docs/gallery/piechart#example

**Comment by kevinkhill** [comment]
Hmmm, very true. Would you mind sharing the code you are using to generate the chart? I might be able to spot the issue

**Comment by giorgiopagnoni** [comment]
OK that was completely my fault. Some charts like PieCharts and DonutCharts don't like their values to be strings, while others like BarCharts work with both. I just had to manually cast the values to integers.
Thank you for your time.

**Comment by kevinkhill** [comment]
Happy to help
