### ISSUE TITLE
TreeMaps

### ISSUE THREAD

**Issue by giorgiopagnoni** [kevinkhill/lavacharts#136]
What version are you having trouble with? 3.0.1

I can't get TreeMaps to work. 
Whenever I do this:
```
$lava->TreeMap('hello', $data, [
   'title' => 'hello'
]);
$result .= $lava->render('TreeMap', 'hello', 'hello', true);
```
I get this:
`Uncaught exception: TreeMap('hello') was not found`
The other types of charts I have been using in the same fashion work though. Anyone else?

**Comment by kevinkhill** [comment]
Try updating to the newest version, 3.0.3, and report back

**Comment by giorgiopagnoni** [comment]
Updated; I'm still getting the same error. 
Is 'TreeMap' the right name? If I change it to 'PieChart' or 'BarChart' in both places, I don't get any php error - just some javascript error (rightly so) because the format of the data of the charts is different.

`Khill\Lavacharts\Volcano->getChart('TreeMap', Object(Khill\Lavacharts\Values\Label))`

**Comment by giorgiopagnoni** [comment]
That's probably easier than expected - there's no 'TreeMap' in chartClasses.

**Comment by kevinkhill** [comment]
I don't know why I missed that before, but you're right. I forgot to add it to the list of accepted charts. Easy fix at least! I'll make a new tag for this

**Comment by kevinkhill** [comment]
[TreeMaps](https://github.com/kevinkhill/lavacharts/releases/tag/3.0.4)

**Comment by giorgiopagnoni** [comment]
Thank you!
