### ISSUE TITLE
Column Chart Labelling

### ISSUE THREAD

**Issue by zahidaziz16** [kevinkhill/lavacharts#138]
![untitledss](https://cloud.githubusercontent.com/assets/17349528/14982622/4400aeea-116a-11e6-9977-d3c04821b6ab.png)

Hi, I am using lavacharts 3.0. How I can put a value label on the top of every bar in the chart? Like Ceiling(Blue) - 31.3%, Component(Orange) - 35.7%

**Comment by kevinkhill** [comment]
Look into annotations in Google's documentation. You should be able to add them in the chart options. 

Also, reference issue #135 where I helped another user with annotations. 

Report back with your findings and I'm happy to help more if you can't figure it out

**Comment by zahidaziz16** [comment]
Im not really good in organizing data into chart. Where I have to amend my codes below to display the label of value on the top of each column? Hopefully you can help.

This is my code for your review,

![fireshot capture 10 - e-iqa - electronic internal qu_ - http___localhost_eiqa_public_report_generate](https://cloud.githubusercontent.com/assets/17349528/15140461/c45be0ba-16cd-11e6-9ed5-8b2a3a70b771.png)


`$ewa = Lava::DataTable();`

`$ewa->addStringColumn('EXTERNAL WALL')
					->addNumberColumn('Finishing')
					->addNumberColumn('Evenness / Roughness')
					->addNumberColumn('Cracking / Damages')
					->addNumberColumn('Jointing / Alignment');`

`$ewa_data = [ "EXTERNAL WALL", $percentage_non_comp_ewa_ae1,$percentage_non_comp_ewa_ae2,$percentage_non_comp_ewa_st,$percentage_non_comp_ewa_cd
				];`

`$ewa->addRow($ewa_data);`

`Lava::ColumnChart('EWA', $ewa, ['vAxis'=> ['title'=>'% Non-Compliances']]);`

**Comment by kevinkhill** [comment]
You will need to restructure your datatable a little bit to achieve what you want. I made a quite little mockup to get you started
```php
$ewa = \Lava::DataTable();
$ewa->addStringColumn('Infraction')
         ->addNumberColumn('Percent')
         ->addRoleColumn('string', 'style')
         ->addRoleColumn('string', 'annotation');

$ewa->addRows([
    ['Finishing',            20, 'green', '20%'],
    ['Evenness / Roughness', 13, 'orange',  '13%'],
    ['Cracking / Damages',   34, 'red', '34%'],
    ['Jointing / Alignment', 22, 'blue', '22%']
]);

\Lava::ColumnChart('EWA', $ewa, [
    'title' => "EXTERNAL WALL",
    'legend' => 'none',
    'vAxis' => [
        'title'=>'% Non-Compliances'
    ],
    'height' => 400,
    'width' => 600
]);
```
![annotations](https://cloud.githubusercontent.com/assets/266076/15455718/ad368fbe-2011-11e6-96bf-a4858ad19f05.png)

**Comment by kevinkhill** [comment]
Closing because solved? Please start a new issue if you are still having problems.

**Comment by marzoukiniz** [comment]
hi , i m using lavachart with laravel 5.5 and i fetech data from my database , but i can not apply styling on line charts , is it the same way with addRoleColumn or should i insert styles on db table ?

**Comment by kevinkhill** [comment]
You dont' have to add styles to your DB, unless you want to have a different style per data point.

What is it you are trying to achieve? Maybe I can point you in the right direction

**Comment by marzoukiniz** [comment]
Thanks for your reply , i had fixed the problem , actually it was about chart options (legend , colors , ... ) . lavachart is amazing 👍 @kevinkhill

**Comment by kevinkhill** [comment]
I'm glad you sorted out the issue!
