### ISSUE TITLE
Responsive charts in v3.1

### ISSUE THREAD

**Issue by giorgiopagnoni** [kevinkhill/lavacharts#139]
What version are you having trouble with? 3.1

In v.3.0.* I used the method "render" to render each of my charts individually. By setting $divDimensions = true, my charts would be completely responsive: I could shrink my browser page after rendering and they would adapt to it.

I can't find a way to do that anymore with v3.1 and the method renderAll. All my charts have a fixed width (and a fixed height) and they won't adapt to my page if I enlarge it or shrink it after rendering it.

Is there a workaround to this?

**Comment by kevinkhill** [comment]
I had started in a direction with 3.1 but didn't really like some of my decisions and did like some. So, I have stopped working on 3.1 for now, and have been porting features from 3.1 into the 3.0 branch.

I would recommend staying on the 3.0 branch for now

**Comment by giorgiopagnoni** [comment]
Thank you! What prompted me to switch was the fact that there was no TimelineChart in 3.0.

**Comment by kevinkhill** [comment]
If you look at the master branch commit history, I've added almost all of the missing charts :) 

Coming soon!

**Comment by giorgiopagnoni** [comment]
I'll be waiting then. Thank you.
