### ISSUE TITLE
How to use Lavacharts in CodeIgniter ?

### ISSUE THREAD

**Issue by matthieubrunet** [kevinkhill/lavacharts#14]
Hi,

I would like to use Lavacharts as a CodeIgniter helper. I put the src/Khill/Lavachart drectory in my helpers directory and created a lavacharts_helper.php file :

    require_once APPPATH."/helpers/Lavacharts/Lavacharts.php";

Then, I try to call it with :

    $lava = new Lavacharts();

But it did'nt worked. So I tried :

    $lava = new Khill\Lavacharts\Lavacharts();

But I got a fatal error : "Fatal error: Class 'Khill\Lavacharts\Volcano' not found in application/helpers/Lavacharts/Lavacharts.php on line 118"

I don't use Composer or Laravel. Is it mandatory ?

Thanks

**Comment by kevinkhill** [comment]
Please see Issue #24

**Comment by kevinkhill** [comment]
If you want to pull and test against the 2.4 branch, I have included a Psr4 Autoloader so you do not have to use composer (even though it is a great tool)
The only thing you need to do is also include the [Carbon](https://github.com/briannesbitt/Carbon) before Lavacharts.

Here is an example:
```
<?php
  require_once('Carbon-1.18.0/src/Carbon/Carbon.php');
  require_once('lavacharts-2.4/src/Lavacharts.php');

  use \Carbon\Carbon;
  use \Khill\Lavacharts\Lavacharts;

  $lava = new Lavacharts;

  $dt = $lava->DataTable();

  $dt->addDateColumn('dates');
  $dt->addNumberColumn('numbers');

  for ($a=1; $a <= 30; $a++) {
    $dt->addRow([Carbon::parse($a.'-1-2015'), rand(100,200)]);
  }

  $lava->LineChart('Stuff')
       ->dataTable($dt);
?>
 
<doctype html>
<html>
  <head>
    <title>No Composer</title>
  </head>
  <body>
    <div id="chart"></div>
 
    <?php echo $lava->render('LineChart', 'Stuff', 'chart'); ?>
  </body>
</html>
```

**Comment by matthieubrunet** [comment]
Thank you very much. In the meantime, I started my project directly with the google API. But for my next project, I will test Lavachart again :+)
