### ISSUE TITLE
Undefined index: AreaChart

### ISSUE THREAD

**Issue by TheTechnoMan** [kevinkhill/lavacharts#140]
Hey,

I'm on the dev-master branch and suddendly can't load the graphs page anymore as I get:

ErrorException in Volcano.php line 113: Undefined index: AreaChart

Did you do some breaking changes?

Thanks!

**Comment by kevinkhill** [comment]
The master branch is always volatile ;) I didn't think anyone was dependent upon it, since that's where I've been working.

I'd recommend keeping on a tagged version or the 3.0 branch of you don't want errors

**Comment by TheTechnoMan** [comment]
What wold be the most stable one with the fix for the racecondition?

**Comment by kevinkhill** [comment]
Oh, yes, I almost forgot about that. Tomorrow I will push the working code into the 3.0 branch so you can depend on dev-3.0 for the fixes while I still work in dev-master

**Comment by TheTechnoMan** [comment]
Oh okay. So:
"khill/lavacharts": "~3.0"

right?

Currently that gives me:
'All' is not a valid Lavachart object when I do:
<?= \Lava::renderAll(); ?>

Worked fine before though :D

**Comment by TheTechnoMan** [comment]
I'll list wait for tommorrow then, need to go to be anyways. Thanks!

**Comment by kevinkhill** [comment]
A couple things, using ```~3.0``` is the same as ```>=3.0.0, <3.1.0``` and the same as ```3.0.*``` but for tagged versions.

To depend on a branch, you prefix the branch name with ```dev-```

**Comment by kevinkhill** [comment]
Also, what I said in issue #139

**Comment by TheTechnoMan** [comment]
Oh okay, thanks. Did you already merge it into 3.0?

**Comment by kevinkhill** [comment]
I forgot to do the merge, but I did fix the issue on the master branch

**Comment by TheTechnoMan** [comment]
Yep, that works. Thanks!

**Comment by kevinkhill** [comment]
Just wondering, what do you think about adding the ability to assign options with dot notation in arrays, to reduce array nesting?

Such as 
```
LineChart('label',  $data, [
    'legend.position' => 'in'
]);
```

Instead of
```
LineChart('label',  $data, [
    'legend' => [
        'position' => 'in'
    ] 
]);
```
