### ISSUE TITLE
Tooltip html

### ISSUE THREAD

**Issue by umbertix** [kevinkhill/lavacharts#142]
Is more a question than a bug. How do you customize the tooltip to display html? 

So far I've got to display the html but it's not being rendered. I've tryied using the isHtml option on the array but it does not seem to affect it.
Code:

```
$price_array = [];
    foreach ($all_price_distribution as $row) {
        $price_array[] = [$row->val, $row->total, "<div id=\"tooltip\"><div id=\"val\" class=\"tooltip_val\">Price: $row->val</div><div id=\"val\" class=\"tooltip_val\">N. searches: $row->total</div></div>"];
    }

$price_datatable = \Lava::Datatable();
$price_datatable->addNumberColumn('Weight')
                    ->addNumberColumn('Number of searches')
                    ->addRoleColumn('string', 'tooltip')
                    ->addRows($price_array);

$options = [
        'title'  => trans('statistics.title.price_distribution'),
        'height' => 400,
        'legend' => [
            'position' => 'none',
        ],
        'hAxis'  => [
            'title' => 'Price',
            'format' =>  'currency'
        ],
        'vAxis'  => [
            'title' => 'N. of searches',
        ],
        'tooltip' => [
            'isHtml' => true
        ]
    ];
\Lava::ScatterChart('priceDistributionScatterChart', $price_datatable, $options);
```

![screen shot 2016-05-16 at 12 35 26](https://cloud.githubusercontent.com/assets/708948/15288436/ffcf6f6a-1b62-11e6-8bf6-456ef49a5263.png)

**Comment by kevinkhill** [comment]
I'm not quite sure, but I will try and take a look when I can. My real job and life are pretty demanding right now, so I'm not going to make any promises (I'm just here checking issues as to not seem absent)

**Comment by poerkiemen** [comment]
I'm trying to get this working and I havent found an answer yet either! you're not the only one atleast.
by the looks it doesn't render it at all and writes it like plain text

**Comment by Vojkan1** [comment]
According to [google](https://groups.google.com/forum/?fromgroups=#!topic/google-visualization-api/Cl7krTzXY0s), you also need to specify the 'p': {'html':true} attribute when adding the tooltip column. I didn't have the time to go in depth with the package's code, but i was able to fix this adding another property to the Column class (boolean $html). Then in the jsonSerialize method, i'm adding this option the same way you would add a role. If there is a more elegant solution to this, i would like to know. Right now, i'm extending the DataTable, Column and ColumnFactory classes in order to get this to work.

**Comment by kevinkhill** [comment]
I believe I have fixed your issues! (super late, I know) but I found some downtime this holiday weekend. I was able to get the tooltip to process the HTML instead of displaying it directly. Pull the master branch if you are so inclined.

![screenshot_2016-11-26_17-14-42](https://cloud.githubusercontent.com/assets/266076/20644861/3848feb0-b3fc-11e6-9f51-85307f521c1c.jpg)

**Comment by poerkiemen** [comment]
They always say better late then never!
I'll check it out whenever I have a bit of spare time.
Thanks in advance

**Comment by manojsharma20** [comment]
I have tried the same in my geochart, but thats not working.

`$data = []; 
foreach ($chtData as $obj){
	$dt = json_decode(json_encode($obj), true);
	$data[] = [$dt['latitude'], $dt['longitude'], $dt['type'], '<div style="color: red;">Manoj</div>'];
}

$geoChart = Lava::DataTable();
$geoChart->addNumberColumn('Lat')
->addNumberColumn('Long')
->addStringColumn('Type')
->addRoleColumn('string', 'tooltip', ['html' => true])
->addRows($data);

Lava::GeoChart('ThreatMap', $geoChart, [
		'title' 			  		=> '',
		'displayMode'		  		=>'markers',
		'colorAxis'           		=> ['minValue' => 0, 'maxValue' => 0],
		'height'			  		=> 750,
		'markerOpacity'  			=> 0.7,
		'legend'			  		=> 'none',
		'backgroundColor'	  		=> ['fill'=> 'transparent', 'stroke' => '#FFF', 'strokeWidth' => 0],
		'datalessRegionColor' 		=> '#fff',
		'enableRegionInteractivity'	=> true,
		'resolution'				=> 'countries',
		'region'					=> 'world',
		'keepAspectRatio'			=> true,
		'width'						=> '90%',
		'tooltipColor'				=> ['textStyle' => ['color' => '#444444']],
		'tooltip'					=> ['isHtml' => true, 'trigger' => 'selection'],
]);`

**Comment by kevinkhill** [comment]
Your using the most recent version a presume? I will see if I can figure out whats up and get your code to render right.

**Comment by kevinkhill** [comment]
I edited your comment in #172 so that it would link to this. We'll continue in the other issue and I'll close this one.

**Comment by flashery** [comment]
Is this still not possible in 3.0? Since the line on Line Chart cannot be Gradient. This is the best work around.

**Comment by kevinkhill** [comment]
It should be possible in the 3.1 branch. I haven't tagged a release yet, but it should be stable enough to use

**Comment by flashery** [comment]
Thanks man. I can't wait for your awesome update 👍
