### ISSUE TITLE
multiple domains

### ISSUE THREAD

**Issue by AlexECP** [kevinkhill/lavacharts#143]
in version 2.5 I had the columns of a multi domain chart setup like this:

```
$table->addColumn('string', 'Date1', null, null, 'domain')
->addNumberColumn('Visitors')
->addColumn('string', 'Date2', null, null, 'domain')
->addNumberColumn('Visitors');
```

im having trouble how to set this up in version 3, keep getting the `domain is not a valid column role...` error.  An example of a multi-domain chart is given here: https://developers.google.com/chart/interactive/docs/roles

**Comment by kevinkhill** [comment]
According to Google's documentation, ```domain``` is not a valid [column role](https://developers.google.com/chart/interactive/docs/roles#what-are-roles). So, I'm not quite sure how/why it worked before? I honestly haven't tested every single aspect of how Google charts work. I have more implemented the wrapper how it **should** work, and test along the way that pieces are working as expected.

**Comment by AlexECP** [comment]
any update on this, or advice on how to workaround it?

**Comment by kevinkhill** [comment]
Not currently, sorry. I have a site with a client I am finishing up, but once I'm done, then I can resume work on Lavacharts.

**Comment by adaojunior** [comment]
@kevinkhill any update on this, or advice on how to workaround it?

**Comment by kevinkhill** [comment]
Wow, it's been a while! I will look into this

**Comment by adaojunior** [comment]
Thank you!

**Comment by kevinkhill** [comment]
I forgot to reference this issue in the commit message, but [data and domain](https://github.com/kevinkhill/lavacharts/releases/tag/3.0.8) are back in the list of valid roles as of commit ab4aa8d

**Comment by adaojunior** [comment]
@kevinkhill thank you!
