### ISSUE TITLE
multiple lines on a linechart

### ISSUE THREAD

**Issue by slaapzakineentent** [kevinkhill/lavacharts#144]
Using version 3.0 in Laravel. This is a suggestion/enhancement.

I want to make linechart with 2 (or more) lines that have their own different x axis.
I found an example how to do that in Javascript
[example](http://jsfiddle.net/asgallant/XF7JE/) 
[original question](http://stackoverflow.com/questions/18037925/google-chart-two-date-series-on-the-same-chart)

To do this they combine data sets/tables, can you make something like that for Laravel?

**Comment by umbertix** [comment]
I haven't tried it, but wouldn't something along this line work?


        foreach ($all_cut_distribution as $row) {
            $cut_array[] = [$row->val, $row->total];
        }

        $cut_datatable = \Lava::DataTable();
        $cut_datatable->addStringColumn('cut name')
                      ->addNumberColumn('cut#');

        if (!empty($cut_array)) $cut_datatable->addRows($cut_array);

**Comment by slaapzakineentent** [comment]
I might wrong, but i get all values on the same line...

**Comment by umbertix** [comment]
Can you post the code?

**Comment by slaapzakineentent** [comment]
I have 2 sets of data that each represents its own line
```php
$table1 = Lave::DataTable();
$table1 ->addDateTimeColumn('Date');
$table1 ->addNumberColumn($name);

$table1->addRow(array('2016-2-1 12:02:45', 45));
$table1->addRow(array('2016-2-2 12:03:10', 60));
//There are more row but i left them out, you get the idea.

$table2 = Lave::DataTable();
$table2 ->addDateTimeColumn('Date');
$table2 ->addNumberColumn($otherName);

$table2->addRow(array('2016-2-1 11:02:45', 10));
$table2->addRow(array('2016-2-2 11:01:55', 40));

Lava::LineChart('progressChart', $table1, [
            'title' => 'progress'),
            'pointSize' => 10,
        ]);
```
Now I am only passing one datatable to the view (It won't accept an array of datatables).
Is there a way to merge/join these tables? In the original Javascript you can do this by calling a special function:
```Javascript 
var joinedData = google.visualization.data.join(table1, table2, 'full', [[0, 0]], [1], [1]);
```
If I merge the data as an array beforehand i get only one line.
If I create 2 numberColumns and semi merge them like this:
```php
//date , line 1, line 2
$table->addRow(array('2016-2-1 11:02:45', 10, null));
$table->addRow(array('2016-2-1 12:02:45', null, 45));
$table->addRow(array('2016-2-1 11:01:55', 40, null));
$table->addRow(array('2016-2-1 12:03:10', null, 60));
```
The result is that everywhere a row has `null` the line will go to 0 same for empty string.
Is there maybe a wildcard that will ignore it?

**Comment by kevinkhill** [comment]
First, this is a very valid point and a good idea for a feature request. Adding the ability to use an array of DataTables and have the JS output use the ```google.visualization.data.join``` method. Secondly, did you try adding ```interpolateNulls: true``` to your chart options, like in your JS example?

**Comment by slaapzakineentent** [comment]
I havn't tried `interpolateNulls: true` yet.
Now I googled these words and it makes sense... :)
I will try tomorrow.

**Comment by kevinkhill** [comment]
Cool, let me know if that works for you. Also, if it does, can you close this issue and open a new one with the links and info about joining DataTables? I'll mark it as an enhancement and put it on my todo list :)

**Comment by slaapzakineentent** [comment]
Thanks guys, it works!
I will close it and make a new issue.

Thanks again!
