### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by shealan** [kevinkhill/lavacharts#145]
Does anyone know how I would go about formatting the text in the tooltip? I need it to show the figure with % after the number. You do this using a formatter in js. Is it possible to do in Lavacharts?

http://stackoverflow.com/questions/6724451/how-to-set-tooltips-to-display-percentages-to-match-axis-in-google-visualization

**Comment by kevinkhill** [comment]
Absolutely! Create a number formatter as such:
```php
$formatter = $lava->NumberFormat([ //Or \Lava::NumberFormat if you're using Laravel
    'fractionDigit' => 2,
    'suffix' => '%'
]);
```
and then apply the format to a column in your DataTable:
```php
$data = $lava->DataTable()
    ->addStringColumn('Month')
    ->addNumberColumn('Things', $formatter);
```
![formatter](https://cloud.githubusercontent.com/assets/266076/15455579/482af244-200d-11e6-820e-c34ca57cc39a.png)

**Comment by shealan** [comment]
Amazing! I can't thank you enough for this incredible library.

**Comment by kevinkhill** [comment]
Happy to help :smile:
