### ISSUE TITLE
[enhancement] Multiple lines on a linechart

### ISSUE THREAD

**Issue by slaapzakineentent** [kevinkhill/lavacharts#146]
Started with this issue: #144 

In order to have 2 or more lines on a chart that don't have the same x axis values.
When you have more sources for your data is easier to make a dataTable for each dataset and merge/join them. Pass these as an array of dataTables to the `Lava::LineChart('name', $tables[], $options[])` method. Right now this method only takes one table This would be for me cleaner code.
[JavaScript example](http://jsfiddle.net/asgallant/XF7JE/) 
[original question](http://stackoverflow.com/questions/18037925/google-chart-two-date-series-on-the-same-chart)

Now this wonderful plugin Lavacharts does not support this.

``` javascript
var joinedData = google.visualization.data.join(data1, data2, 'full', [[0, 0]], [1], [1]);

var chart = new google.visualization.LineChart(document.querySelector('#chart_div'));
    chart.draw(joinedData, {
        interpolateNulls: true
    });
```

This does the magic. 
When we pass a array of tables we should automatically add the  `interpolateNulls: true` to the options (correct me if I'm wrong).
We also need to add somewhere the other parameters, 'full' could be in the options array, but I have no idea yet how to pass the other arrays.
More info on these parameters: [Google documentation](https://developers.google.com/chart/interactive/docs/reference#join)

I don't know how you are going to implement this, you might use the Javascript method or make the merge yourself in php. When you make it in php it is not necessary to have any trailing `null`.
`php $table->addRow(array('2016-2-1 11:02:45', 10, null));`
equals
`php $table->addRow(array('2016-2-1 11:02:45', 10));`

**Comment by kevinkhill** [comment]
I haven't had much time to work on Lavacharts as of late, so I'm sorry for the delay in my reply. I am just stopping by to see how my package is doing, and that I'm not gone. This is still on my list of TODOs, but I have no timeline for anything.

**Comment by kevinkhill** [comment]
It's not working yet, but I am doing a lot of refactoring for 3.2 and [this will be included](https://github.com/kevinkhill/lavacharts/blob/master/src/DataTables/JoinedDataTable.php) :smile:

**Comment by RikuTheFuffs** [comment]
[Laravel, using Lavacharts 3.2]
Hello,
I'm trying to implement a JoinedDataTable, but having no success in doing it with this code:

In my controller: ("data" and "myaData" are the 2 DataTables that I want to join)
`$tables = new \Khill\Lavacharts\DataTables\JoinedDataTable($data,$myaData);`
`\Lava::LineChart('Test', $tables, ['title' => 'Test table'] ,'test-div');`

In My View:
`<div id="test-div"></div>`
`<?= \Lava::renderAll(); ?>`

The result is just an empty page, no errors thrown. (it should display the Chart with 2 lines, each one representing a different DataTable)

However, if I do a: `dd($tables);` I can see that the JoinedDataTable is not empty.
Maybe something prevents it from rendering?

Moreover, I can't use: `$tables = \Lava::JoinedDataTable($data,$myaData);` . It throws a `Unknown method "JoinedDataTable" in "Khill\Lavacharts\Lavacharts".`

**Comment by kevinkhill** [comment]
Honestly, I don't remember where I left off working on the 3.2 branch. I don't have much free time lately, so I haven't worked on it in a while. I didn't think anyone would use it yet! Haha, anyways, I will take a look when I can and see what's going on.

**Comment by poornadhivya** [comment]
how to use addTimeOfDayColumn(). Need sample code. I'm new to Lavacharts

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
