### ISSUE TITLE
Javascript date function parsing as a string literal in $this.data

### ISSUE THREAD

**Issue by chrisbeaver** [kevinkhill/lavacharts#147]
In 3.0, I'm loading a single value with a date from the database, and I can var_dump my DataTable to see that the Carbon objects are correct for all the dates. However, if I show a 2+ month span of date-value pairs, they tend to always double up every other month. So I get empty plots in February, 2 in March, none in April, 2 plots in May. The dates are rendering as a string in $this.data, here's an example:

  $this.data = new google.visualization.DataTable({"cols":[{"type":"date","label":"Date"},{"type":"number","label":"count"}],"rows":[{"c":[{"v":"Date(2015,4,31,0,0,0)"},{"v":"260"}]},{"c":[{"v":"Date(2015,5,1,0,0,0)"},{"v":"202"}]},{"c":[{"v":"Date(2015,5,2,0,0,0)"},{"v":"199"}]},{"c":[{"v":"Date(2015,5,3,0,0,0)"},{"v":"201"}]},{"c":[{"v":"Date(2015,5,4,0,0,0)"},{"v":"227"}]},{"c":[{"v":"Date(2015,5,5,0,0,0)"},{"v":"164"}]},{"c":[{"v":"Date(2015,5,6,0,0,0)"},{"v":"192"}]},{"c":[{"v":"Date(2015,5,7,0,0,0)"},

SO ON AND SO FORTH ...

{"c":[{"v":"Date(2016,4,23,0,0,0)"},{"v":"36"}]},{"c":[{"v":"Date(2016,4,24,0,0,0)"},{"v":"0"}]},{"c":[{"v":"Date(2016,4,25,0,0,0)"},{"v":"0"}]},{"c":[{"v":"Date(2016,4,26,0,0,0)"},{"v":"0"}]}]}, 0.6);

I shortened it, but I actually have a years worth of data being passed with a -1 monthly offest from the DateCell object.

And for some weird reason, it plots [this graph here](http://imgur.com/aax9rz2).

So my dates are rendering properly, aside from the fact that they are in double quotes. Is google running an eval on this, or is something else wrong? It tends to grab the correct month every other month, and it plots the off months on the month following it.

**Comment by chrisbeaver** [comment]
This appears to have gone away, the only explanation I have is that something changed on the Google end of it.

**Comment by kevinkhill** [comment]
Happy to help! :laughing: :+1:
