### ISSUE TITLE
Chart TYPE = Table

### ISSUE THREAD

**Issue by quoka** [kevinkhill/lavacharts#148]
https://github.com/kevinkhill/lavacharts/blob/3.0/src/Charts/TableChart.php#L34 is declaring the TYPE as "TableChart", which causes a JS error when binding (Invalid visualization type: TableChart)

I believe `const TYPE = 'Table';` would be the correct type to use (https://developers.google.com/chart/interactive/docs/gallery/table#example).

**Comment by kevinkhill** [comment]
I haven't had much time to work on Lavacharts as of late, so I'm sorry for this delay in my reply. If you could submit a PR, I would happily merge it.

**Comment by kevinkhill** [comment]
Table charts render just fine for me, so I am not sure what issue you are having. If you post your code, I will take a look and try and help. For now, I am closing this as an issue. Please re-open if needed

**Comment by nedjamez** [comment]
> Table charts render just fine for me, so I am not sure what issue you are having. If you post your code, I will take a look and try and help. For now, I am closing this as an issue. Please re-open if needed

@quoka is right.
When https://github.com/kevinkhill/lavacharts/blob/3.0/src/Charts/TableChart.php#L34 is changed from 'TableChart' to 'Table', the filter works fine and the table renders. However other normal tables without filters do not load anymore. My code below works with the change, else this error is shown "Invalid visualization type: TableChart"

`		$lava = new \Khill\Lavacharts\Lavacharts;
		$ups = $wpdb->get_results(
			"select concat ('https://#/admin/upcs/?cat=',upcs.Catalog) AS Link, upcs.UPC AS UPC, upcs.ReleaseDate, upcs.Title, upcs.Artist, upcs.MainGenre, upcs.SubGenre
from dxtrt_view_cat_UPC_info upcs", ARRAY_A);
		$releases = $lava->DataTable();
		$releases->addStringColumn('Release')
		              ->addStringColumn('UPC')
		              ->addStringColumn('Release Date')
		              ->addStringColumn('Title')
		              ->addStringColumn('Artist')
		              ->addStringColumn('MainGenre')
		              ->addStringColumn('SubGenre');
		
		$releases->addRows($ups);
		$releasesChart = $lava->TableChart('Releases', $releases, [
			'allowHtml' => true,
			'negativeColor' => 'red',
			'negativeParens' => true,
			'page' => count($ups)>10 ? 'enable':'disable',
			'showRowNumber' => true,
			'alternatingRowStyle' => false,
			'width' => '100%'
		]);
		
		$filter = $lava->StringFilter(3, [
			'matchType'         => 'string',
		]);
		$control = $lava->ControlWrapper($filter, 'control');
		$chart   = $lava->ChartWrapper($releasesChart, 'releases-div');
		$lava->Dashboard('Releases', $releases)->bind($control, $chart);
		
		echo '<div id="my-dash"><div id="control"></div><div id="releases-div"></div></div>';
		echo $lava->render('Dashboard', 'Releases', 'my-dash');
		
		return ob_get_clean();
`

**Comment by kevinkhill** [comment]
Could you please update to the latest version and let me know if the problem persists?
