### ISSUE TITLE
Dashboard ajax

### ISSUE THREAD

**Issue by umbertix** [kevinkhill/lavacharts#149]
How can you update a chart inside a dashboard? I get the error "[Lavacharts] Chart "chart_test" was not found.

**Comment by kevinkhill** [comment]
I haven't had much time to work on Lavacharts as of late, so I'm sorry for this big delay in my reply. I am not certain from the last time I was in the code, if that is possible or not. I will leave this open and when I have free time, I will take a look.

**Comment by kevinkhill** [comment]
Closing due to staleness. Please start a new issue if you are still having problems.

**Comment by pureforce** [comment]
If it's still relevant to anyone, you can do it through getDashboard and googleChart.

```
lava.getDashboard('Dashboard', function (googleChart, lavaChart) {
    // console.log(googleChart);

   googleChart.draw(result.data)
});
```
