### ISSUE TITLE
Gantt chart support?

### ISSUE THREAD

**Issue by emmanuelLS** [kevinkhill/lavacharts#150]
Currently using version 3. 

Does this version support the Gantt Chart? 

Thanks,
Emman

**Comment by kevinkhill** [comment]
Soon it will. I haven't been working on this for a bit since I have a freelance site I'm working on. No time for hobbies right now. I believe I left the master branch in a usable state if you want to try it out. It has many additional charts added.

**Comment by emmanuelLS** [comment]
Does it includes Timeline Chart?

**Comment by kevinkhill** [comment]
It includes all of these charts
https://github.com/kevinkhill/lavacharts/tree/master/src/Charts

**Comment by kevinkhill** [comment]
It includes all of these [charts] (https://github.com/kevinkhill/lavacharts/tree/master/src/Charts)

**Comment by kevinkhill** [comment]
This is available in the master branch (should work) which will eventually become v3.1

**Comment by kevinkhill** [comment]
Closing this as an issue, since it will be available soon in 3.1 :+1:
