### ISSUE TITLE
problem in daterange filter 

### ISSUE THREAD

**Issue by arikazukito** [kevinkhill/lavacharts#151]
What version are you having trouble with?
version 3.0
problem:
One or more participants failed to draw()×
Column 1 is not a date×

code:

```
        $datatable = Lava::DataTable();
        $datatable->addDateColumn('Date');
        $datatable->addNumberColumn('Inventory');
        $d=$datatable->addRows([
            ['2016' , 5] ,
            ['2016' , 7]


        ]);
```

//            dd($d);
            $pieChart = Lava::PieChart('Donuts' , $datatable , [
                'width'        => 400 ,
                'pieSliceText' => 'value'
            ]);

```
        $filter = Lava::DateRangeFilter(1 , [
            'minValue' => 2012,
            'maxValue' => 2016

        ]);

        $control = Lava::ControlWrapper($filter , 'control');
        $chart = Lava::ChartWrapper($pieChart , 'chart');
        $a = Lava::Dashboard('Donuts')->bind($control , $chart);
```

**Comment by kevinkhill** [comment]
Sorry that I haven't replied in a while, but maybe try ```setDateTimeFormat()``` on the datatable?
[Datatable Utility Methods](http://lavacharts.com/#datatable-utility)

**Comment by kevinkhill** [comment]
Closing due to staleness. Please start a new issue if you are still having problems.
