### ISSUE TITLE
Question more than an issue -- In Laravel 5.x view, how to I check chart exists to avoid error

### ISSUE THREAD

**Issue by freedomfflow** [kevinkhill/lavacharts#153]
Lavacharts working fine, but  I get error:
ErrorException in Volcano.php line 78:
PieChart('REG-CHART') was not found.

This occurs in a method where my chart doesn't exist that uses the same view as another method.

How do I say:   @if ( chart 'REG-CHART' exists)  to conditionally display this in blade?

**Comment by kevinkhill** [comment]
You can use the [```exists()```](https://github.com/kevinkhill/lavacharts/blob/3.0/src/Lavacharts.php#L354) method

**Comment by kevinkhill** [comment]
Closing this for now as I believe I have solved your issue / question. If need more help, please feel free to open a new issue
