### ISSUE TITLE
Remove or customize legend

### ISSUE THREAD

**Issue by pezzetti** [kevinkhill/lavacharts#154]
Hi, i am creating a Area Chart about the month sales, but there is no space for the legend on the bottom. I've tried change de data format but it doens't make any difference.

The code is : 
  $current_month_chart = \Lava::DataTable();               
        $current_month_chart->addDateColumn('Day')
                       ->addNumberColumn('Sales $')
                       ->setDateTimeFormat('d');
        
        foreach($month_sales as $day_sale){
                                                                    // number of the day and total
            $current_month_chart->addRow([$day_sale->date_created,$day_sale->total]);
        }   
<img width="911" alt="captura de tela 2016-08-24 as 12 19 43 1" src="https://cloud.githubusercontent.com/assets/6005103/17916213/951f76e8-69f4-11e6-8d7c-3f00d48ecc75.png">

**Comment by kevinkhill** [comment]
Check out Google's documentation for customizing the Horizontal Axis. You can pass any of the configuration options into the chart, as an associative array, as the third parameter.

There are a few examples on [lavacharts.com](http://lavacharts.com) with configuration options being used.

**Comment by pezzetti** [comment]
I see, i am trying to use hh:mm as hAxis but i am not sure about what type of column should i use. I always get this error: at DateCell::parseString('12:41', 'HH:mm') in RowFactory.php line 84.

I have tried addDateColumn('date') with "datetime", "time", but no one seems to work. which is the correct one ? Thanks

**Comment by kevinkhill** [comment]
Are you trying to add times or dates?

**Comment by pezzetti** [comment]
Times. Create one chart using hours and minutes.

**Comment by kevinkhill** [comment]
Try ```addTimeColumn()``` or ```addDateTimeColumn()``` or putting your time format string into ```setDateTimeFormat()``` instead of 'd'

**Comment by pezzetti** [comment]
Oh God, i feel sad about myself. Thanks Kevin

**Comment by kevinkhill** [comment]
No worries, you all sorted out?

**Comment by pezzetti** [comment]
Yes, definitely.

**Comment by kevinkhill** [comment]
Great! Happy to help :)
