### ISSUE TITLE
Laravel 5.3 bug

### ISSUE THREAD

**Issue by iryont** [kevinkhill/lavacharts#155]
`In prior versions of Laravel, when registering custom Blade directives using the directive method, the $expression passed to your directive callback contained the outer-most parenthesis. In Laravel 5.3, these outer-most parenthesis are not included in the expression passed to your directive callback. Be sure to review the Blade extension documentation and verify your custom Blade directives are still working properly.`

From:

https://www.laravel.com/docs/5.3/upgrade

**Comment by kevinkhill** [comment]
Hmmm, I didn't know that. I'm still playing / learning 5.2  
I will have to modify the Laravel extension and check for this. Thank you for bringing this to my attention. I will add it to my list of todos

**Comment by iryont** [comment]
No problem at all. I did recently update to Laravel 5.3 from 5.2 and LavaCharts stopped working due to lack of ) within compiled view.

The work-around is rather trivial. Instead of using custom extension such as @piechart you do call the render method directly:

{!! Lava::render('PieChart', 'POLL', 'chart_div') !!}

Later on when you fix it I will switch to @piechart back again :)
