### ISSUE TITLE
Hide Column Values

### ISSUE THREAD

**Issue by osamaalvi** [kevinkhill/lavacharts#156]
2.5

![image](https://cloud.githubusercontent.com/assets/7011249/18120115/76d9c822-6f77-11e6-9d9e-ca203e24bdeb.png)

I want to hide the numberColumn values (values in red circle) how can I hide columnvalues?

**Comment by kevinkhill** [comment]
Please excuse my brevity, but try looking Google's docs about customizing the tooltips, then add whatever options you would like to the chart.

**Comment by kevinkhill** [comment]
Closing due to staleness, please open a new issue if needed.
