### ISSUE TITLE
Version 3, Lavachart

### ISSUE THREAD

**Issue by encry2024** [kevinkhill/lavacharts#158]
Hi Sir Kevin, I have read about the issue on multiple lavachart on issue #141 . May i ask if you were able to resolve this issue or if you have a workaround? I downgraded my version to 2.5 and encountered an error **Cannot set property 'data' of undefined** and was able to fix by using this code #15 
( But still encountered an error about this class **use Khill\Lavacharts\Helpers\Helpers as h;**. I managed to resolve that issue by deleting that helper and changed this

`public function getChartJs(Chart $chart, $elementId = null)
{
    if (isset($chart->datatable) && h::isDataTable($chart->datatable)) {
        $this->chart = $chart;
    } else {
        throw new DataTableNotFound($chart);
    }

```
if (h::nonEmptyString($elementId)) {
    $this->elementId = $elementId;
} else {
    throw new InvalidElementId($elementId);
}

return $this->buildChartJs();
```

}
`

and to this:
( this code is from version 3 )
`public function getChartJs(Chart $chart, $elementId = null)
    {
        if (isset($chart->datatable) === false) {
            throw new DataTableNotFound($chart);
        }

```
    if (Utils::nonEmptyString($elementId) === false) {
        throw new InvalidElementId($elementId);
    }

    $this->chart     = $chart;
    $this->elementId = $elementId;

    return $this->buildChartJs();
}`
```

)

**Comment by kevinkhill** [comment]
I believe that the master branch has working code built into the lava.js module. I know it is possible since I have a test / demo page on my laptop that I use to see if I broke anything, which renders every chart type on one page. Try it out and see if it works for you?

**Comment by encry2024** [comment]
Sure! I'll try it today as soon as i'm done with my work. Thank you sir for responding.

**Comment by kevinkhill** [comment]
Closing due to staleness, please open a new issue if needed.
