### ISSUE TITLE
javaScript lava is not defined

### ISSUE THREAD

**Issue by nimeshc64** [kevinkhill/lavacharts#159]
![image](https://cloud.githubusercontent.com/assets/8343294/18425404/dab8a15c-78d6-11e6-9bf7-1e3a0cd984ba.png)

![image](https://cloud.githubusercontent.com/assets/8343294/18425412/eb5cf5c6-78d6-11e6-86b3-e8781390893d.png)

![image](https://cloud.githubusercontent.com/assets/8343294/18425417/f59d224a-78d6-11e6-9f14-172dc4eb909a.png)

**Comment by kevinkhill** [comment]
What version are you using?

**Comment by kevinkhill** [comment]
I will be closing this for now (spring cleaning of my issue backlog) but please, feel free to open a new issue if you still need assistance. I am always happy to help.

**Comment by nbravos** [comment]
Hi, sorry for reopenig this, but I'm having the same problem as stated above and using the 3.0 version.
I can see the json response from the chrome dev tools and everything is there, but the lava.loadData is giving me an error "Uncaught ReferenceError: lava is not defined".
Any help would be appreciated :)

**Comment by kevinkhill** [comment]
Can you please update to the latest version and see if that helps? (3.0 is pretty old now)

**Comment by nbravos** [comment]
I did update, but I still have the same error D:

**Comment by kevinkhill** [comment]
Closing due staleness and lack of communication. Please open a new issue of you still need assistance, as I am happy to help. ☺️
