### ISSUE TITLE
Calendar chart

### ISSUE THREAD

**Issue by cheskq** [kevinkhill/lavacharts#16]
Hello,

Any plan on integrating the Google Calendar chart into lavacharts?

It is shown here: https://developers.google.com/chart/interactive/docs/gallery/calendar

**Comment by kevinkhill** [comment]
I just merged in my 2.1 branch into master, with support for CalendarCharts! I won't tag it until later, after more testing, but it should be ready to go. You can try it out with dev-master in composer if you would like :)

**Comment by cheskq** [comment]
You're the best :+1:  Thanks a lot !
