### ISSUE TITLE
  How to set vertical axis to be in 'integer' not floating point number ?

### ISSUE THREAD

**Issue by geetikaarora** [kevinkhill/lavacharts#161]
What version are you having trouble with?
Lavacharts v3.0

**Comment by kevinkhill** [comment]
It has been a while since I've used my own library :smile: so I will research and get back to you

**Comment by geetikaarora** [comment]
ok :D

**Comment by geetikaarora** [comment]
alright :)

**Comment by kevinkhill** [comment]
Do any of these work? [NumberFormats](https://developers.google.com/chart/interactive/docs/customizing_axes#number-formats)

**Comment by kevinkhill** [comment]
Closing due to staleness. Please create a new issue if you are still having trouble.
