### ISSUE TITLE
Line chart sometimes doesn't render

### ISSUE THREAD

**Issue by troypesola** [kevinkhill/lavacharts#162]
What version are you having trouble with? 3.0 with Laravel 5.1

I have a double line chart and another line chart on the same page.  MOST of the time the render, but occasionally nothing gets updated and there is nothing in the console or error divs.

Here's a snipped from my controller.
```
    $lava = new Lavacharts;
    $temptable = $lava->DataTable();
    $temptable->addDateTimeColumn('Date')->setTimezone('America/Denver')
      ->setDateTimeFormat('Y-m-d H:i:s')
      ->addRoleColumn('string','annotation')
      ->addNumberColumn('Temperature')
      ->addNumberColumn('Humidity');

    $heaptable = $lava->DataTable();
    $heaptable->addDateTimeColumn('Date')->setTimezone('America/Denver')
      ->setDateTimeFormat('Y-m-d H:i:s')
      ->addNumberColumn('Heap');

    $tempOptions = [
      'titleTextStyle' => ['fontName' => 'Arial','fontColor' => 'blue'],
      'legend' => ['position' => 'top'],
      'annotations' => ['style'=>'line'],
      'height' => 600,
      'series' => [['targetAxisIndex' => 0],['targetAxisIndex'=>1]],
      'vAxes' => [['title'=>'Temps(F)'],['title'=>'Humidy(%)']]
    ];
    $humiOptions = [
      'titleTextStyle' => ['fontName' => 'Arial','fontColor' => 'blue'],
      'legend' => ['position' => 'top'],
    ];

// skipped lines ....

    $lava->LineChart('TempData', $temptable, $tempOptions);
    $lava->LineChart('HeapData', $heaptable, $humiOptions);
```

Then in my blade it is rendered by 

```
<div id="tempdata-div"></div>
<div id="heapdata-div"></div>

{!! $lava->render('LineChart', 'TempData', 'tempdata-div') !!}
{!! $lava->render('LineChart', 'HeapData', 'heapdata-div') !!}
```

I can't determine if there is a data problem or something else.

Any thoughts or suggestions?

**Comment by kevinkhill** [comment]
Many users have reported a race condition like this, where the error is intermittent. I had started working on a fix many months ago, but then I lost all my free time to develop. I'm pretty sure I left the repo in a working state on the master branch. I rewrote the lava.js module to use promises to avoid this race condition. I'm sorry I can't be more helpful, but my day job and life have left me no free time for this hobby. I hope I can get back into it, but I won't make any promises.

**Comment by troypesola** [comment]
Kevin,  No worries.  Thank you for putting all the work you have into this project.

I don't get much time to play with this either, but I'll pull the repo down and take a look.   I'll let you know if I get any flashes of insight.

   -Troy

**Comment by twify93** [comment]
I also encounter sometimes this problem with not rendered charts. But it occurs when I only render 1 chart. Any idea? Is it possible to be, because of the use of the old api loader (`https://www.google.com/jsapi`) from google and not the static loader(`https://www.gstatic.com/charts/loader.js`) one?

**Comment by kevinkhill** [comment]
Possibly. I have decided to revert the breaking changes I made in 3.1, so I
can release it to everyone, before excluding anyone that doesn't want to
have the changes. (the breaking changes are small, but I don't like drawing
lines in the sand)

Anyways, the 3.1 branch uses the new loader. It also has a re-written
lava.js module and supports most of the charts.

**Comment by twify93** [comment]
Where can we have or grab the changes for the drawing, because non working rendering is causing real problems right now?

**Comment by kevinkhill** [comment]
Try changing the require statement in your composer file to ```3.1.x-dev```. This will get you the most recent, stable version I have in development.

**Comment by twify93** [comment]
Yeah, I found out that I have issue even with the `3.1.x-dev` as I already load the `loader.js` it starts complaining `Uncaught Error: Google Charts loader.js can only be loaded once.`. I am not that good with JS, but I can try pushing a change to check if `loader.js` is already inserted.
I also have this issue, that even if I remove the loading in my code I still get 2 places where the `loader.js` is loaded(but no error):
`https://www.gstatic.com/charts/loader.js`
`https://www.gstatic.com/charts/45.1/loader.js`

**Comment by danielverissimo** [comment]
Hello, this happens to me too ...
As for me it was urgent, I made a small change that resolved, it is temporary, then I will improve, if someone knows how to do better would be great.

In the javascript lava.js, it looks like the `LavaChart.setData (json)` call function is not taking effect. When you call redraw on the graph, nothing changes.

I made a change in ChartFactory, in the render function to ckeck if has params data:

> if (data){
   $this.data = new google.visualization.DataTable(data);
}else{
   $this.data = new \<dataClass\>(\<chartData\>, \<dataVer\>);
}

And then in my callback, I call render again:

> lava.loadData('chart4', charts.chart4, function (chart) {
                                lava.charts.LineChart["chart4"].render(charts.chart4);
                            });

**Comment by kevinkhill** [comment]
I would recommend trying the 3.1 branch before hacking on the library because I rewrote most of the lava.js module. There are many bug fixes and improvements that might resolve your issues.

**Comment by danielverissimo** [comment]
Thanks @kevinkhill, I will try.

**Comment by kevinkhill** [comment]
It's been a while on this, are there still issues?

**Comment by danielverissimo** [comment]
Sorry for late feedback. I'm using version 3.1 and there is no longer any problem.

Thanks a lot.

**Comment by kevinkhill** [comment]
Excellent news, thanks for letting me know :smile:
