### ISSUE TITLE
LavaChart not updating on ajax call.

### ISSUE THREAD

**Issue by manojsharma20** [kevinkhill/lavacharts#163]
I am using lavachart 3.0 version this is working and drawing chart, but it is not properly showing the chart.

I have done below code in Controller.

I have done this in blade file and js
```
$chtDonutData =Data::select(\DB::raw('count(*) as total'), \DB::raw('substr(type,1,4) as type'), \DB::raw("IFNULL(type, 'Testing') as t_type"))->groupBy('type')->get();
        $donutChart = Lava::DataTable();
        $donutChart->addStringColumn('Total')
        ->addNumberColumn('Total Count');
        foreach ($chtDonutData as $obj){
            $donutChart->addRow([$obj->t_type, $obj->total]);
        }
        Lava::DonutChart('totals', $donutChart);
```
blade:
`{!! Lava::render('PieChart', 'totals', 'pie_div') !!}`

js:
```
var pieUrl = "{{ route('getPieChart') }}";
	$.getJSON(pieUrl, function (dataTableJson) {
	  lava.loadData('total', dataTableJson, function(data){
	  	// console.log(data);
	  });
	});
```
Data is proper, but pei chart showing 100% with other, no other legend showing. Please help me where i am wrong

**Comment by kevinkhill** [comment]
Upon first glance, it looks like you called the chart "total**s**" but in the ajax call, you just reference "total"

**Comment by kevinkhill** [comment]
I will be closing this for now for a lack of response and I'm doing spring cleaning of my issue backlog. Please feel free to open a new issue if you still need assistance. I am always happy to help.
