### ISSUE TITLE
Example of formatting with addStringColumn

### ISSUE THREAD

**Issue by mark-rs** [kevinkhill/lavacharts#164]
I've looked all through the documentation for an example of the use of Format for `addStringColumn`, but I haven't been able to find one. Could you point me to one, please?

**Comment by kevinkhill** [comment]
You are trying to format a string column?

**Comment by mark-rs** [comment]
Yes, exactly.

*MARK ABRAMSON*
SVP ENGINEERING OPERATIONS
T: +1 650 797 2221
1810 Gateway Dr., Suite 200, San Mateo, California 94404

**Comment by kevinkhill** [comment]
Honestly, I don't remember! :laugh:
It's been so long since I've looked at Lavacharts code. I will try and
carve a little time out and see if I can help you out. I'm pretty sure that
it's possible, but I just don't remember.

**Comment by kevinkhill** [comment]
Can you be more specific in what you are trying to accomplish?

**Comment by mark-rs** [comment]
Sorry for the very delayed response. I'm trying to set the font and font size.

**Comment by kevinkhill** [comment]
For the legend? the axes? everything?

**Comment by kevinkhill** [comment]
Were you able to figure this out or do you still need help?

**Comment by kevinkhill** [comment]
Closing due staleness and lack of communication. Please open a new issue of you still need assistance, as I am happy to help. ☺️
