### ISSUE TITLE
How do I set locale?

### ISSUE THREAD

**Issue by FPGL** [kevinkhill/lavacharts#165]
Hi!
I'm trying to figure out how to use local strings, any idea?  
https://developers.google.com/chart/interactive/docs/basic_load_libs#loadwithlocale

**Comment by kevinkhill** [comment]
Well, since I had no need, it appears I forgot to make a method for setting this. Whoops! I don't think it would  be too hard to add to the datatable creation, similiar to the ```setDateTimeFormat()``` or as a constructor param. I will add this to my list of TODOs (which is quite long sadly, since I don't have any time to work on this)

**Comment by FPGL** [comment]
Thank you for your answer. Happy to hear that it is on the todo list, and thank you for all the work already done!

**Comment by kevinkhill** [comment]
psssssst If you update from the master branch, you should be able to set the locale ;)

It works with my local tests, using the singleton instance of Lavacharts, like so
```
    $lava = new Khill\Lavacharts\Lavacharts();
    $lava->setLocale('ja');
```

So try that if you are doing a composer/manual install project, but it should also work with Laravel.

Try ```\Lava::setLocale()```

**Comment by kevinkhill** [comment]
![screenshot_2016-11-26_14-06-09](https://cloud.githubusercontent.com/assets/266076/20644261/7f0d031e-b3e3-11e6-833f-be59d779aa62.jpg)

**Comment by FPGL** [comment]
Hi!

Great news, Thank You! 
I have some weird composer issue. So, I have updated my composer.json with 
"khill/lavacharts" : "master-dev",
or "khill/lavacharts" : "master",
but it fetch me the 3.0.5 (seen in Lavacharts::VERSION)
and not the 3.1.0 (as expected here https://github.com/kevinkhill/lavacharts/blob/master/src/Lavacharts.php)

But there is no 3.1.0 version. 
The requested package khill/lavacharts 3.1.0 exists as khill/lavacharts[1.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.10, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.5.x-dev, 3.0.0, 3.0.0-beta1, 3.0.0-beta2, 3.0.0-rc1, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.x-dev, 3.1.0-alpha1, 3.1.0-alpha2, 3.1.0-alpha3, 3.1.x-dev, dev-gstatic, dev-master, dev-overhaul] but these are rejected by your constraint.

**Comment by kevinkhill** [comment]
It's not you, I probably broke it trying to alias master to the 3.1.0 version, but I also have a 3.1 branch? I am not the best with composer and git. I'm sure there's an easier way!

**Comment by kevinkhill** [comment]
I removed the alias of dev-master to 3.1 branch. I think it should be ok now to just depend on ```dev-master```

**Comment by FPGL** [comment]
Yeah! It works, but only with the rev number: 
"khill/lavacharts" : "dev-master#be8ae3f"
otherwise it fetch the d46142a :(

**Comment by kevinkhill** [comment]
Weird... maybe Packagist is slow in updating from Github?

**Comment by kevinkhill** [comment]
It was, I forced an update on packagist and now it registers dev-master @ be8ae3fe

**Comment by FPGL** [comment]
It works like a charm, thanks Kevin!

**Comment by kevinkhill** [comment]
Happy to help :+1:
