### ISSUE TITLE
LineChart('data') was not found in view

### ISSUE THREAD

**Issue by Nagesh-WRG** [kevinkhill/lavacharts#166]
What version are you having trouble with?
I am using Lavachart 3.0 And i am getting this error when i try to load my view in laravel 5. 
LineChart('data') was not found in view. This is my controller

```
use Khill\Lavacharts\Lavacharts;
public function chart()
{
$value= \Lava::DataTable();

		$data= servers::select("data_value as 0","data_label as 1")->get()->toArray();

		$value->addNumberColumn('data_value')
				->addDateColumn('data_label')
				->addRows($data);

		\Lava::LineChart('server_data',$value,['title'=>'Data From Server']);

		return view('chart');
}
```

This is my view
```

<!DOCTYPE html>
<html>
<head>
	<title>Line Chart</title>
</head>
<body>
<div id="temps_div"></div>

{!! \Lava::render('LineChart', 'data', 'temps_div') !!}

</body>
</html>
```

and i have provided it in app.php as well
Khill\Lavacharts\Laravel\LavachartsServiceProvider::class,

i dont what is the problem. Please help

**Comment by kevinkhill** [comment]
You have defined the chart label as **server_data** here ```\Lava::LineChart('server_data',$value,['title'=>'Data From Server']);```

and then you are trying to render a non-existent called **data**

Try changing ```data``` to ```server_data``` or vice-versa

**Comment by kevinkhill** [comment]
Did this work for you? I am closing this issue for now, but please re-open it if you are still having trouble.
