### ISSUE TITLE
How to format data for async updates

### ISSUE THREAD

**Issue by manojsharma20** [kevinkhill/lavacharts#167]
First of all that for making this such a good module. I am using lavacharts 3.0 with laravel 5.2. I am able to draw barchart, piechart and dounutchart and also able to update based on ajax.

I am having two problem with the lavachart, 1) i want to update lavacharts fromm nodejs and 2) i want to do 3D formatting, color schemes legend position and styling, and last but not the least animations.

Please suggest me some example or give me demo.

**Comment by kevinkhill** [comment]
Updating the charts from node? You would probably have to setup websockets and tie the ajax style of refreshing into the logic from your node app.

As for formatting, you should be able to apply customizations with the chart constructor. Have you visited http://lavacharts.com to check out the examples?

**Comment by manojsharma20** [comment]
I have setup everything and able to emit and receive the data. Now the question is how to format data, I can execute mysql queries from Node itself and able to retrieve the required data. Question is formation of data which i am earlier return from laravel i want to return same data formation?

**Comment by kevinkhill** [comment]
Yeaaah, I haven't documented the json output format that the lava.js module is expecting. It's customized a little. I would recommend making a little test datatable in php and use the toJson() method and see what it returns. That will show you how you need to format your node app's json output.

**Comment by kevinkhill** [comment]
I don't know if this is still an issue for you or not, but I have written a draft of the [JSON schema](https://github.com/kevinkhill/lavacharts/blob/master/tests/JsonSchema/datatable.json) which Google (and Lavacharts) uses for creating DataTables

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
