### ISSUE TITLE
Undefined variable: lavaClass

### ISSUE THREAD

**Issue by maplater** [kevinkhill/lavacharts#168]
Hi, I am having trouble with rendering a chart and I'm not sure where I've messed up.  I'm doing the below:

` \Lava::Geochart('chart_index',$table,[
            'title' => 'US City Chart',
            'legend' => [
                'position' => 'none'
            ],
            'height' => 600,
            'options' => array(
                'sizeAxis' => array(
                    'minValue' => -50,
                    'maxValue' => 50
                ),
                'displayMode' => 'markers',
                'colorAxis' => array(
                    'colors' => array(
                        'blue',
                        'red'
                    )
                ),
            ),
        ]);
`

`$render = \Lava::render('GeoChart',$this->chartGraph[$chartName]['index_id'],$this->chartGraph[$chartName]['index_id']);
`

And receiving the error:

> ErrorException in Lavacharts.php line 161:
Undefined variable: lavaClass

Do you have any suggestions?  Thank you.

**Comment by kevinkhill** [comment]
I probably missed something during refactoring, what version are you using?

**Comment by maplater** [comment]
Thanks for the response! Version 3.0.

**Comment by kevinkhill** [comment]
Sorry it took me so long get back to you, but I believe it is as simple as changing ```Geochart``` to ```GeoChart```

I suppose the error could be a bit more descriptive 😄

**Comment by kevinkhill** [comment]
I will be closing this for now (spring cleaning of my issue backlog) but please, feel free to open a new issue if you still need assistance. I am always happy to help.
