### ISSUE TITLE
Laravel Facade in 3.1-beta1

### ISSUE THREAD

**Issue by Yannici** [kevinkhill/lavacharts#169]
Hello,

Why was the Laravel Facade removed in the 3.1 branch? Is there a reason?
I want to use the Facade in Laravel with the beta (because I need the HTML in tooltips).

Edit: I forked it and tried it with Facade. It didn't work. I think there is still more to do ;)

Greetings,
Yannici

**Comment by kevinkhill** [comment]
I believe (don't quote me) that I was going to move the Laravel integration and Symphony integration into their own packages, to keep it lighter? But then probably got side tracked and did something else, then haven't put it back yet? 

I think I decided that moving it out would only be a benefit to new users and an inconvenience to existing users. 

I will put it back :smile:

**Comment by Yannici** [comment]
Alright, thank you :)
