### ISSUE TITLE
Util::arrayIsMulti for Traversable/ArrayAccess

### ISSUE THREAD

**Issue by twify93** [kevinkhill/lavacharts#170]
So I thought today it is going to be a good idea to check also for `Traversable` for the main array ( basically because `DataTable::addRows` ) and also for each row to check if it is `ArrayAccess` this way any object implementing these interfaces will be able to be passed. For example - Larave's Collection for the main array and a Eloquent model as a row(it implements `ArrayAccess`).

Or/and also to check the commonly used `toArray()` if object.
I wrote a little bit of code for it, but I haven't even ran it, maybe today after work, but I was wondering what do you think?

**Comment by kevinkhill** [comment]
At first when I read this, I didn't understand, but then I re-read it tell me if I am understanding you.

You want the ```addRow``` method to accept objects, implementing ```ArrayAccess``` so you could just pass in Eloquent objects and not have to manually dump the object to an array and then format the array again for the DataTable?

**Comment by twify93** [comment]
Yes, but not only. Currently I am not using Laravel in my project, but I can implement these interfaces in my classes and achieve the same thing as Laravel.
I was thinking for something like this(not tested at all, I just wrote it):
```php
class Utils
{
    // ....
    /**
     * Simple test to see if array is multi-dimensional.
     *
     * @param array|\Traversable Array of values.
     * @return bool Returns true is first element in the array is an array,
     *              otherwise false.
     */
    public static function arrayIsMulti($array)
    {
        if (self::checkTraversable($array)) {
            if (count(array_filter($array, 'self::checkArrayAccess')) > 0) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    /**
     * @param array|\Traversable $array
     */
    public static function checkTraversable($array) {
        if(is_array($array) || $array instanceof \Traversable){
            return true;
        }

        return false;
    }

    /**
     * @param array|\ArrayAccess $array
     *
     * @return bool
     */
    public static function checkArrayAccess($array)
    {
        if(is_array($array) || $array instanceof \ArrayAccess) {
            return true;
        }

        return false;
    }
    // ...
```

**Comment by twify93** [comment]
Also the `RowFactory::create` should be also changed. As it checks for `is_array()`.
I will test it and if no additional changes except the changes for the checking need to be changed will be great.
Also if PHP 7.1 is going to be supported, we might use the new [`iterable`](http://php.net/manual/en/migration71.new-features.php#migration71.new-features.iterable-pseudo-type) type hint

**Comment by kevinkhill** [comment]
I know I've been slacking on my tests, so I won't ask you to add any. But these seem like minor changes, so if you verify that this works, I'd be happy to merge a pull request if you make one. As for supporting PHP7+, I need to finish all my work on v3.1 before I even think about that 😄

**Comment by twify93** [comment]
I didn't mean to say that there were not tests and etc. I just said that I wrote the code, but I didn't even try to run it :D

**Comment by kevinkhill** [comment]
No worries. I'm just happy you have found my package useful and are contributing 👍

**Comment by twify93** [comment]
Should I use `illuminate/support` and get the Collection class from there for require-dev or you prefer own implementations of ArrayAccess and Traversable?

**Comment by kevinkhill** [comment]
Wow this has been a while. I'm going to close this since I pulled your work in already.

**Comment by twify93** [comment]
Can you reference the PR/changes?

**Comment by kevinkhill** [comment]
My git-foo is poor, so I don't know how to quickly find that out... but [here are the validators you wrote](https://github.com/kevinkhill/lavacharts/blob/3.1/src/Support/Traits/ParameterValidatorsTrait.php) as a trait and that `Row` [now implements](https://github.com/kevinkhill/lavacharts/blob/3.1/src/DataTables/Rows/Row.php) `ArrayAccess`
