### ISSUE TITLE
How to add html tooltip into GeoChart

### ISSUE THREAD

**Issue by manojsharma20** [kevinkhill/lavacharts#172]
Hi, I am creating a Geochart where i have put lot of markers. When user hover or click then a pop should shown and that pop must be like tooltip. 

I want that tooltip must be customizable. When i have research on same i came to know that i can add role column and type tooltip, then i can enter custom html in the row, but that is not working for me.

Efforts.

$geo->addRoleColumn('string', 'tooltip', true);
 and option while creating Geachart contains.

'tooltip'	=> ['isHtml' => true], 

this line to, but that popup not showing as popup instead in popup complete html showing.

Please tell me the write syntax for the same.

**Comment by manojsharma20** [comment]
I have tried also tried your mentioned solution on issue [https://github.com/kevinkhill/lavacharts/issues/142](url), but is also not helping me. it display as <div>Manoj<div> rather then just Manoj.

**Comment by kevinkhill** [comment]
Sorry! I went back through my commits in https://github.com/kevinkhill/lavacharts/issues/142 and just realized that the fix I made was applied to the master (3.1)

I will see if it would be easy to port this fix into the 3.0 branch.

**Comment by manojsharma20** [comment]
Ok, could you please let know the changes as i am working on a project which need to be finalize by today itself.

**Comment by kevinkhill** [comment]
I'm sorry, but I have no idea when I would be able to get this working in the 3.0 branch. I poked around a bit and I might have to do a lot of refactoring to get it working. I re-wrote almost the whole JavascriptFactory base class and the lava.js module in the 3.1 branch, which I believe the interpretation of html tooltips depends on.

If you want to, the 3.1 branch should be stable enough to use and you would have access to html tooltips, plus more charts and an improved lava.js module.

**Comment by kevinkhill** [comment]
There is a slight syntax change from 3.0 -> 3.1 but it is [explained here](https://github.com/kevinkhill/lavacharts/wiki/Upgrading-from-3.0-to-3.1)

**Comment by kevinkhill** [comment]
Now that version 3.1 has been release, I recommend updating as it should resolve your issues. If it doesn't please open another issue and I will be happy to help.
