### ISSUE TITLE
How to set vertical axis to be in time format

### ISSUE THREAD

**Issue by sugengsuprayogi** [kevinkhill/lavacharts#173]
I want to make a graph with a vertical axis to be in time format.
How to set vertical axis to be in time format?

This example my code 
```
         $presensi[$lists->id_karyawan]->addDateColumn('Date' . $lists->nama)
                ->addNumberColumn('In')
                ->addNumberColumn('Out')
                ->addRow(['2014-10-16', $dt->toTimeString(), $dt->toTimeString()])
                ->addRow(['2014-10-16', $dt->toTimeString(), $dt->toTimeString()])
                ->addRow(['2014-10-16', $dt->toTimeString(), $dt->toTimeString()])
            ;
```

Please help, thx

**Comment by kevinkhill** [comment]
I'm sorry, but I'm not quite sure what you are trying to accomplish. I see you have a DateColumn and dates for the first column, which will be the vertical axis, so I don't know how you want that displayed as time. 

Can you elaborate or tell me more about what you are trying to accomplish?

**Comment by sugengsuprayogi** [comment]
I want to create a chart with the X axis as the date of attendance and the Y axis is hours of attendance

**Comment by kevinkhill** [comment]
What about using a ```Timeline chart``` to show dates along the Y axis and then the hours of attendance in the X axis?

[Something similar to this example](https://developers.google.com/chart/interactive/docs/gallery/timeline#controlling-the-colors), but swapping the "room" for dates and keeping the hours along X?

**Comment by kevinkhill** [comment]
I will be closing this issue for now (spring cleaning) but please re-open or create a new one if you still need help.
