### ISSUE TITLE
Draw charts on demand, not on render?

### ISSUE THREAD

**Issue by twify93** [kevinkhill/lavacharts#174]
Is it possible to render the JS and the div for example. but the chart not to be drawn on load?

My problems is that I have a `display: none` field which contains the chart, on load is drawn there and when it's shown(removing the `display: none`) the chart is not rendering correctly, because there is a problem doing it like this.

**Comment by kevinkhill** [comment]
This would take some refactoring of the lava.js module, to enable the user to initiate the rendering. It is tied to the loading of the page. I'm not saying I won't look into it, but I have no promises on a time line 😄

**Comment by twify93** [comment]
Perhaps now that you refactored the new API url/style for loading google charts, it will be easier? I haven't taken a look at it, but I can check what can be done.

I think that in the new Loader you had to have only 1 callback for rendering the chart, not quite sure.

**Comment by kevinkhill** [comment]
Yes, it might be easier. I just need to dig into it when I get a chance and see what it would take to get it working.

**Comment by kevinkhill** [comment]
What do you think about setting an option when cre

**Comment by kevinkhill** [comment]
I often forget to check my issues before committing to tag them here for tracking.

This feature was added in 3.1.6 (even though it is not documented)

[The run call is now wrapped](https://github.com/kevinkhill/lavacharts/blob/3.1/javascript/src/lava.entry.js#L40-L42) with the conditional `auto_run` option.

This can be set with `$lava = new Lavacharts(['auto_run' => false]);` or here `$lava->renderAll(['auto_run' => false])` or in the [published config file if you are using Laravel](https://github.com/kevinkhill/lavacharts/blob/3.1/src/Laravel/config/lavacharts.php)

**Comment by kevinkhill** [comment]
I probably shouldn't have added features in a patch but I have been working on 3.2 and I wanted to try and help the 3.1-ers

**Comment by kevinkhill** [comment]
Should we mark this as closed now?

**Comment by twify93** [comment]
I haven't tested it, but yes, close it I guess, and for bugs - new issues

**Comment by kevinkhill** [comment]
Ok, sounds good.
