### ISSUE TITLE
Call to undefined method 

### ISSUE THREAD

**Issue by JasonForrest1972** [kevinkhill/lavacharts#175]
I've updated to laravel 5.4 and hit the following error...
[Symfony\Component\Debug\Exception\FatalThrowableError] 
Call to undefined method Illuminate\Foundation\Application::share() 

I get it as soon as I add Khill\Lavacharts\Laravel\LavachartsServiceProvider::class, to the providers then run php artisan vendor:publish

It happens on both my existing project and on a fresh install of laravel 5.4. 

Didn't occur on the same project in laravel 5.3.*

**Comment by kevinkhill** [comment]
Whelp, you are correct! I checked the [laravel upgrade guide](https://www.laravel.com/docs/5.4/upgrade#upgrade-5.4.0) and the ```share()``` has been removed. It looks like it should be a simple enough fix.

**Comment by kevinkhill** [comment]
try using ```dev-3.0``` and see if it fixes your issue. I will tag and release a bugfix if this works for you.

**Comment by JasonForrest1972** [comment]
Thanks for working on that so quickly. Would that be "khill/lavacharts" : "dev-3.0"?
if so I'm getting an error when trying to install it...

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package khill/lavacharts dev-3.0 exists as khill/lavacharts[1.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.10, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.5.x-dev, 3.0.0, 3.0.0-beta1, 3.0.0-beta2, 3.0.0-rc1, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.x-dev, 3.1.0-alpha1, 3.1.0-alpha2, 3.1.0-alpha3, 3.1.0-beta1, 3.1.x-dev, dev-master] but these are rejected by your constraint.

**Comment by kevinkhill** [comment]
Sorry, I forgot for a minute how composer calls branches.

```3.0.x-dev``` is what I meant

**Comment by filipegar** [comment]
@kevinkhill looks like it has been fixed. looking forward to a new release soon. :)

**Comment by kevinkhill** [comment]
3.1 is on its way! I put it in feature freeze and am working on tests and docs

**Comment by JasonForrest1972** [comment]
Not sure if this is a separate issue or not. I'm no longer getting the error installing the lavacharts package. However now I'm getting Class 'Lava' not found in the view when trying to render a chart using the laravel blade templating engine using 
<?= Lava::render('ColumnChart', 'Income', 'income-chart')  ?> 
I've tried with or without the leading \

When I use @ColumnChart('Income', 'income-chart') I get no error but nothing is rendered in the div.

In the controller I'm using lavacharts facade like so ... use Khill\Lavacharts\Laravel\LavachartsFacade as Lava;

I only started having this issue after updating to laravel 5.4. Not sure if I'm missing something. Here is my code from the controller by the way. There query is returning the data as it should.

$startMonth = START_FINANCIAL_YEAR;
        $today = TODAY;     

        $taskData = taskQuery::getMonthlyJobTotals($startMonth, $today);


        if($taskData){
            $incomeChart = new Lava; 
        
            $income = $incomeChart::DataTable();
            $income->addStringColumn('Amount')
                    ->addNumberColumn('Month')
                    ->addRows($taskData);

            $incomeChart::ColumnChart(
                    'Income', $income, [
                    'title' => 'Monthly sales data',
                    'titleTextStyle' => [
                        'color'    => '#eb6b2c',
                        'fontSize' => 14
                        ],
                    'colors' => [
                                '#e5f5f1'
                            ],
                    'animate' => true
                    ]
                );
        }

**Comment by kevinkhill** [comment]
Whats interesting to me, is that some people (you included) have stated that they have to put ```use Khill\Lavacharts\Laravel\LavachartsFacade as Lava;``` in their controllers for the alias to work. I don't know entirely how the guts of Laravel work, but I've never had to add that line in my tests. I just use ```\Lava::``` and get no complaints from Laravel.

I am wondering if the [automatic alias assignment](https://github.com/kevinkhill/lavacharts/blob/3.0/src/Laravel/LavachartsServiceProvider.php#L46-L49) is buggy?

## Scratch that!

I just scrolled back up and looked a little more carefully through your code and I found the culprit!

This line is what is causing you issues
```$incomeChart = new Lava; ```

The [service provider](https://github.com/kevinkhill/lavacharts/blob/3.0/src/Laravel/LavachartsServiceProvider.php#L42-L44) creates the instance of Lavacharts, so you do not need to manually create one. Using the Facade gets the instance from the container, and the way Lavacharts works, all chart data is stored internally, so by creating a new instance, you are losing the stored data, and pulling nothing into the view.

**Comment by kevinkhill** [comment]
1. Remove ```$incomeChart = new Lava;```
2. Change ```$income = $incomeChart::DataTable();``` to ```$income = \Lava::DataTable();```
3. Change ```$incomeChart::ColumnChart``` to ```\Lava::ColumnChart```

and you should be good 😄

**Comment by JasonForrest1972** [comment]
Oh I see. Makes sense. I'll give that a try

**Comment by kevinkhill** [comment]
I added more detailed documentation for installing into Laravel to the readme and I will add a note about not creating an instance.
