### ISSUE TITLE
How to disable decimal value and force to use Integer in NumberColumn ?

### ISSUE THREAD

**Issue by jithesh-portrave** [kevinkhill/lavacharts#176]
Even if my data is like 4, 6 , 7 , 9 the AreaChart will mark values 4, 4.5, 5, 5.5, 6, 6.5...etc. How to disable this ? I have gone through the documentation and couldn't find an option to do this. Please advice. I am using Laravel 5.2.

**Comment by kevinkhill** [comment]
Lavacharts does explicitly support options for charts. Whatever Google supports for configuration options, that is what can be used. Take a look through Google's documentation for area charts, specifically for the axis options. There might be something for that.  If not, we could try a number format column.

**Comment by kevinkhill** [comment]
I believe your best bet is using a combination of vAxis options, like ```vAxis.format``` or ```vAxis.ticks``` units as shown in [Google's documentation for area charts](https://developers.google.com/chart/interactive/docs/gallery/areachart#configuration-options).

**Comment by kevinkhill** [comment]
Did you resolve this issue?

**Comment by kevinkhill** [comment]
closing due to lack of communication.
