### ISSUE TITLE
show percentage data in legends of google pie chart

### ISSUE THREAD

**Issue by eafshary** [kevinkhill/lavacharts#177]
hi, I want to show percentage which is displayed inside chart to the legends also 
how can i do that?
http://stackoverflow.com/questions/19178029/want-to-show-percentage-data-in-legends-of-google-pie-chart

**Comment by kevinkhill** [comment]
From the accepted answer on SO, you could create the pie chart with the option [asgallant](http://stackoverflow.com/a/19181740) recommends:
```
$lava->PieChart('Label', $datatable, [
    legend => [
        position => 'labeled'
    ]
]);
```

**Comment by kevinkhill** [comment]
I will be closing this issue for now (spring cleaning) but please re-open or create a new one if you still need help.
