### ISSUE TITLE
How to use Lavacharts with Symfony 3 in the twig html files

### ISSUE THREAD

**Issue by rgroothuis** [kevinkhill/lavacharts#178]
I want to use Lavacharts in combination with Symfony 3. The example code on the Lavacharts web-site to build the diagram is straight forward. The problem I'm having is how to pass that object/variable into the Symfony twig.html template. 

Adding the "<div id="chart-div"></div>" part in the twig.html code is easy of course. 

But how to add the "<?= $lava->render('PieChart', 'IMDB', 'chart-div') ?>" code in the twig.html file. Symfony doesn't allow php code in the twig.html file. 

Any suggestion and/or an example how to do this?

**Comment by rgroothuis** [comment]
Found the solution to the problem. Found it on the following web-site: 
https://github.com/kevinkhill/lavacharts-symfony 

The trick is to use: 

{{ linechart('Stocks', 'stocks-div')|raw }}

in the twig.html file. 

This topic can be closed.

**Comment by kevinkhill** [comment]
I'm glad you were able to figure this out :smile: I will be expanding the documentation soon, so this will be easier to figure out for future users
