### ISSUE TITLE
Google jsAPI doesn't work over https

### ISSUE THREAD

**Issue by PouleR** [kevinkhill/lavacharts#18]
The JavascriptFactory.php contains an URL to "//google.com/jsapi", however this url doesn't work when using an https connection.

This URL works when using "www" as prefix, so:

Doesn't work:
https://google.com/jsapi 

Does work:
https://www.google.com/jsapi 
http://www.google.com/jsapi
https://google.com/jsapi 

Can you change the URL in the JavascriptFactory ?

**Comment by kevinkhill** [comment]
If you could make the change and submit a pull request, I will merge it in. My laptop's charger died so I'm stuck to my phone.

**Comment by PouleR** [comment]
I've created a pull request, it's just a small change ;)

**Comment by kevinkhill** [comment]
Thank you!
