### ISSUE TITLE
Load loader.js only when not loaded yet

### ISSUE THREAD

**Issue by twify93** [kevinkhill/lavacharts#181]
I tried the `3.1.x-dev` version, but I see problem when I already have loaded the `loader.js`, I'm not that good with JS, so I wanted to ask if it is possible to load the script in [javascript - lava/Lava.js line 403](https://github.com/kevinkhill/lavacharts/blob/3.1/javascript/src/lava/Lava.js#L403) only when it hasn't been loaded yet? A little bit of digging also was rewarding as I found [this quote in the documentation](https://developers.google.com/chart/interactive/docs/basic_load_libs#loading-details)
> As of version 45, you can call google.charts.load more than one time in order to load additional packages, but if you do so, you must provide the same version number and language setting each time.

Which means that we can keep the current code for the loading of the charts components and it should be ok.

I've checked in Google documentation, it has the option to not specify the components if you use the wrapper [Google charts documentation Load settings](https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings) using [ChartWrapper class](https://developers.google.com/chart/interactive/docs/reference#chartwrapper-class) where you can also use DataTable, json of DataTable, provide html with the data or use Ajax. But this probably will take time to be implemented and tested.

**Comment by kevinkhill** [comment]
Is the library outputting the lava.js module more than once? It is supposed to be tracking internally if it has been output to the page, and not put it in page more than once. I remember reading about that it can't be loaded more than once, [which is why I added in the tracking of it](https://github.com/kevinkhill/lavacharts/blob/3.1/src/Javascript/ScriptManager.php#L51-L56).

I suppose it is a useful safeguard though, what you added for checking if it is already loaded in your pull-request.

**Comment by twify93** [comment]
Yes, we actually have it loaded on our page already (custom scripts) we wanted to use lavacharts without hacking our page to remove the loader.js. So basically lava.js is checking if LAVACHARTS isn't loading it twice, but if it loaded outside there was no protection.

**Comment by kevinkhill** [comment]
That makes sense. Therefore, I like the idea you've come up with to protect against this.

I noticed something though, does you solution work? I see that you created ```Lava.prototype._setLoadCallback``` with the logic for loading ```google.charts.load```.

What I was wondering is... Are you are getting errors referencing ```deferred.resolve``` in ```google.charts.setOnLoadCallback``` since ```deffered``` is assigned in ```Lava.prototype._loadGoogle``` which should make it out of scope.

**Comment by kevinkhill** [comment]
Would it be to much to get you to base your work off the master branch instead of 3.1? I want to be able to work with it / test / etc before adding it to the "stable" 3.1 branch

**Comment by twify93** [comment]
Yes, tomorrow I probably can do it. About the error: No, we haven't seen any errors in our charts. Not quite sure how the whole promises work, but I am passing it into the method and I guess when will execute when it's resolved? No idea there... My solution is not the best probably, but I've tested it and it currently works.

**Comment by kevinkhill** [comment]
I will take a look when I get a chance. Thank you for all your contributions, I appreciate it.

**Comment by twify93** [comment]
Can you also reference the PR. I probably will do a sample of at least how to build the package, but I am not quite sure how do you test, it will be nice to explain or you just use the repo and put it in another project with composer?

**Comment by kevinkhill** [comment]
The lava.js module? I was thinking about wrapping it up in its own repo and having ```khill/lavacharts``` depend on it. It started out small and I didn't mind, but now it is a lot Javascript in with all the PHP.

I [started a few tests](https://github.com/kevinkhill/lavacharts/blob/master/javascript/tests/lava.spec.js) in Javascript. I have never done it before, so I am sort of learning as I go.

The command to run the Javascript test suite is ```npm test``` or ```./node_modules/.bin/karma start --singleRun```

**Comment by twify93** [comment]
Ok, so you actually can't check if the package is working inside the package itself(except the tests of course). For JS tests - sorry I haven't done that too, maybe I will try and add some tests, who knows.
I was actually asking for the whole package not only the lava.js, but you already gave the answer.

OK, so tomorrow I will put it to master, perhaps I can only change the destination to 'master'.

**Comment by kevinkhill** [comment]
Merged and refactored your work a little. Thank you for you additions! I want to add you to my list of  contributors, do you want credit under @twify93 or @elpiel-efuture?

**Comment by twify93** [comment]
twify93
