### ISSUE TITLE
Backend Image URL Generation

### ISSUE THREAD

**Issue by necrogami** [kevinkhill/lavacharts#184]
Is there a way to get the image URL before rendering the frontend? I'm in a situation where this passes into a PDF generator and the chart isn't being generated because javascript isn't processed in the pdf generator.

So can i from the backend code get the image url or base64 encoded image of the chart?

**Comment by kevinkhill** [comment]
I have looked into this, but the only way I can get it to work, is with phantomjs. I have been playing with phantom and am able to get static images of charts, but it isn't elegant.

**Comment by kevinkhill** [comment]
It is kind of out of the scope of the project, since it was intended as a php wrapper for the javascript but it isn't impossible.
