### ISSUE TITLE
Can you show me an example how to use your Gradient Object? 

### ISSUE THREAD

**Issue by flashery** [kevinkhill/lavacharts#185]
I am trying to create a Line Chart where the color will change when the line goes up the specific y-axis. The line color will back to normal color when the line goes down. Is this possible?

**Comment by kevinkhill** [comment]
If you look in [Google's documentation for configuring line charts](https://developers.google.com/chart/interactive/docs/gallery/linechart#configuration-options), there doesn't seem to be options for coloring the lines how you want. You can set the line to one color, but I didn't see any options for coloring the line in relation to the y-values.

You can try any the options Google offers, just [configure your chart](http://lavacharts.com/#upgrade-configs).

**Comment by flashery** [comment]
Thank you so much for your plugin. It helps me a lot.

**Comment by kevinkhill** [comment]
You're welcome 😄
