### ISSUE TITLE
Is there any way to update the chart on Ajax request?

### ISSUE THREAD

**Issue by flashery** [kevinkhill/lavacharts#186]
I wanted to update the chart on Jquery Ajax. I saw on your docs using vanilla 
`<div id="pop_div"></div>`
`<?= $lava->render('AreaChart', 'Population', 'pop_div') ?>`
How can we implement this inside Ajax

$.ajax({
            url: "/get_pp_data?start_date=" + start_date + "&end_date=" + end_date,
            success: function (data) {
                // UPDATE CHART HERE
            },
            error: function (result, status, error) {
                console.log(result + " Error: " + status + " Error: " + error);
            }
        });

**Comment by kevinkhill** [comment]
Did you look at the [example on the docs site](http://lavacharts.com/#javascript-ajax)?

**Comment by flashery** [comment]
WOW very awesome. Thanks again God Bless You.

**Comment by kevinkhill** [comment]
Happy to help. You can re-open this if you run into problems.

**Comment by kevinkhill** [comment]
oops
