### ISSUE TITLE
Charts not displaying

### ISSUE THREAD

**Issue by HenryKenya** [kevinkhill/lavacharts#188]
Hey Kevin,
Lavacharts is great. I tried in my laravel 5 app and it worked fine. However, when I am trying it on a new app am working on; instead of displaying the chart I get this: **{!! Lava::render('TableChart', 'Population', 'chart-div') !!}**
```php
<?php
use Khill\Lavacharts\Lavacharts;
class HenryController extends \BaseController
{
	

// Controller
Route::get('reports', function() {
    $population = Lava::DataTable();

    $population->addDateColumn('Year')
               ->addNumberColumn('Number of People')
               ->addRow(['2006', 623452])
               ->addRow(['2007', 685034])
               ->addRow(['2008', 716845])
               ->addRow(['2009', 757254])
               ->addRow(['2010', 778034])
               ->addRow(['2011', 792353])
               ->addRow(['2012', 839657])
               ->addRow(['2013', 842367])
               ->addRow(['2014', 873490]);

    $chart = Lava::TableChart('Population', $population);

    return View::make('report')->with('Population', $chart);
});
    }
```
and my view:
@extends('layout.master')

@section('contents')
<h4>Report Analytics</h4>

<div id="chart-div"></div>
{!! Lava::render('TableChart', 'Population', 'chart-div') !!}
@stop
It doesn't throw any errors but the chart is not displayed.
I am using chart 3.0 and laravel 4.2

**Comment by kevinkhill** [comment]
I notice that your Date column is just years, so it's possible Carbon might be having trouble parsing the year? try adding ```setDateTimeFormat('Y')``` in your datatable chain to instruct Carbon to parse only dates.

**Comment by kevinkhill** [comment]
I am going to take your :+1: as confirmation that your issue has been resolved. If not, please feel free to open another issue as I am happy to help.
