### ISSUE TITLE
lavachart not showing graph perfectly on live server as it working perfectly on localhost

### ISSUE THREAD

**Issue by vishal-bluesys** [kevinkhill/lavacharts#189]
What version are you having trouble with?
![image](https://cloud.githubusercontent.com/assets/24889275/24280974/0e81f43e-107b-11e7-911c-f21b382c67d7.png)
this is screen of live server 

![image](https://cloud.githubusercontent.com/assets/24889275/24280994/2fc03142-107b-11e7-942f-33116fc4ad10.png)
this is of localhost

please help

**Comment by kevinkhill** [comment]
Very interesting.... There is nothing different between the two environments?

**Comment by kevinkhill** [comment]
I really don't know how to help debug or resolve this issue...

**Comment by kevinkhill** [comment]
Closing due to lack of communication. Please open a new issue if you are still having trouble.

**Comment by kjdion84** [comment]
How did you resolve this issue? I'm having the exact same issue @vishal-bluesys

**Comment by vishal-bluesys** [comment]
Problem Not resolve , use HighChart or Google Chart instead this may fix your problem

**Comment by kjdion84** [comment]
I fixed this problem in 5 seconds. You just have to cast the variables as integer by putting `(int)` in front of them lol.

**Comment by kevinkhill** [comment]
@kjdion84, I'm glad you were able to get it working.

@vishal-bluesys, this library *is* Google Charts. Unless you meant using it directly.
