### ISSUE TITLE
Could somebody help me on generating this chart, please?

### ISSUE THREAD

**Issue by karidoe** [kevinkhill/lavacharts#191]
Hello guys,
I'd like to generate a chart that looks exactly the same as the image below, can someone help me please. - I could have the barchart and get the line serie up but I couldn't make the total value to beshown.

![chart1](https://cloud.githubusercontent.com/assets/1001003/24492056/335218ec-1554-11e7-946d-a7b849d9644a.png)

Thanks in advance!

**Comment by kevinkhill** [comment]
Would you like to post what you have tried so far? It's easier for me to help debug if I can toss your code in my testing environment

**Comment by karidoe** [comment]
Hello @kevinkhill, I've tried by cutomizing the example to make the chart like above one. Here below is my code. 
`$finances->addDateColumn('Year')
         ->addNumberColumn('Sales')
         ->addNumberColumn('Expenses')
         ->addNumberColumn('Total')
         ->addRow(['2009-1-1', 1100, 490, 1590])
         ->addRow(['2010-1-1', 1000, 400, 1400])
         ->addRow(['2011-1-1', 1400, 450, 1850])
         ->addRow(['2012-1-1', 1250, 600, 1850])
         ->addRow(['2013-1-1', 1100, 550, 1650]);

$lava->ComboChart('Finances', $finances, [
    'width' => 800,
    'height' => 600,
    'isStacked' => true,
    'title' => 'Company Performance',
    'titleTextStyle' => [
        'color'    => 'rgb(123, 65, 89)',
        'fontSize' => 16
    ],
    'seriesType' => 'bars',
    'vAxes' => [
        [
            'format' => 'decimal',
            'title' => 'Rooms',
            'textStyle' => [
                'color' => 'blue'
            ]
        ],
        [
            'format' => 'decimal',
            'title' => 'Capacity',
            'textStyle' => [
                'color' => 'blue',
            ]
        ]
    ],
    'series' => [
        2 => [
            'targetAxisIndex' => 1,
            'type' => 'line',
            'color' => 'green',
            'fontSize' => 13,

        ]
    ]
]);`

and the its result looks like below
![chart1-0](https://cloud.githubusercontent.com/assets/1001003/24639092/84afc7d6-1917-11e7-9d93-fdd26ed3c068.PNG)

Thanks in advance

**Comment by kevinkhill** [comment]
So is it just the labels above each column what you are trying to get?

**Comment by karidoe** [comment]
Yes and is it possible to set the green line as transparent?

**Comment by kevinkhill** [comment]
It looks like from this [SO discussion](https://stackoverflow.com/questions/30636514/google-chart-how-to-move-annotation-on-top-of-columns) That you could create another column for the annotations.

**Comment by kevinkhill** [comment]
Were you able to get what you wanted?

**Comment by karidoe** [comment]
Not yet, I've just changed the way to show the total number of the bar. I really can't find the way to make the green line disappear.

**Comment by kevinkhill** [comment]
So just to get us on the same page... My last graph I posted it what you want, just without the green line?

**Comment by kevinkhill** [comment]
I'm going to go ahead and close this issue since it's more on Google than me now.
