### ISSUE TITLE
How do I leave the larger graph?

### ISSUE THREAD

**Issue by vanessasoutoc** [kevinkhill/lavacharts#192]
How do I leave the larger graph in view?

**Comment by kevinkhill** [comment]
You're going to have to give me more details or code, because I don't know what you are talking about

**Comment by vanessasoutoc** [comment]
Add properties options.
$graphUsersMonth->AreaChart('dadosUsersGraph', $dadosUsersGraph, ['title'=>'Usuários Cadastrados / Mês','chartArea'=>['left'=>'30','height':'400']);

Thanks.

**Comment by kevinkhill** [comment]
I still am not sure what you are asking for help with... Can you make another gist like with your other issue?
