### ISSUE TITLE
Gantt Chart implementation

### ISSUE THREAD

**Issue by verhelsttroy** [kevinkhill/lavacharts#193]
Hello

I am currently looking for a way to integrate a gantt chart into my laravel website, but can't seem to find one with LavaCharts.

I can see that it is supported on the git over here and can see the class as well, but on the site (http://lavacharts.com) I can't seem to find any example code on which parameters to give along with the object when creating it. 
With the basic charts, for example a PieChart I can find this on the site and I have no problems creating a piechart or linechart since I know which parameters to give when doing:
$pieChart = $lava->PieChart('Donuts', $datatable, [
           // parameters 
 ]);

Could be that I am missing something obvious and the parameters are declared somewhere in the code...

**Comment by kevinkhill** [comment]
You're not missing anything, I just haven't finished the docs yet. I have been working on a [showcase service provider] (https://github.com/lavacharts/laravel-showcase) that can be added to Laravel to demo everything it can do. 

You don't have to install it (but you can if you want.)

**Comment by kevinkhill** [comment]
Oh, it looks like the Gantt demo also uses the new DataFactory! I really should document all the new features :smile:

**Comment by verhelsttroy** [comment]
I think the src/charts/ dir is exactly what I need and specifically the GanttChart.php file there of course.
I'll try to make it work now, but I think it should be possible without to many trial and error.

Thank you so much for your quick reply, really appreciated!

**Comment by kevinkhill** [comment]
Good luck!

**Comment by verhelsttroy** [comment]
The new charts like the gantt aren't loaded into the vendor/khill dir for some reason. I don't know if this is the same for everyone or if it's just for me though. It seems like composer only pulls an older version of some sorts. I don't know if this is the case, but for example the DataFactory class wasn't pulled in either.

This isn't a problem for the standard charts of course since they don't use the DataFactory.
I've tried to make it all work by manually putting the classes in, but I am basically debugging and copying your project over when I can just ask you whether this really is a problem and if it is fixable for composer to pull in everything.

I ran composer update btw, I have the latest version.

**Comment by kevinkhill** [comment]
I keep running into issues with composer and packagist, and I don't know
why...

The DataFactory isn't mandatory, it just is supposed to make datatables
easier / faster.

**Comment by kevinkhill** [comment]
I just force updated packagist, and it is correctly showing 3.1

**Comment by verhelsttroy** [comment]
Hmm, that's really weird. For me it is still not pulling in the newest charts nor the DataFactory. I tried deleting Lavacharts, clearing the composer cache and doing a composer update again, but the package stays the same. 

I think this may have to do with the fact that I'm behind a company proxy. I've seen some problems with github and proxies already. I'll try to pull in Lavacharts at home this evening and I'll update you on this!

Excuse me for answering this late by the way.

**Comment by kevinkhill** [comment]
Don't worry about being "late", I don't check here everyday for issues. 

Maybe you and your company would benefit from setting up a Toran Proxy? 

https://toranproxy.com/

**Comment by verhelsttroy** [comment]
I just pulled Lavacharts into one of my projects at home and as you can see by the image the newest charts aren't included for some reason. (such as the gantt)

![image](https://cloud.githubusercontent.com/assets/25820314/24871046/a39ea83c-1e18-11e7-98a5-cfe9b7f7ad65.png)

Oh and I am currently doing an internship so I won't be changing any proxy settings anytime soon sadly! Toran looks nice though.

**Comment by kevinkhill** [comment]
What's weird, is that you are missing more than just the chart files... (I'm on mobile, so no screenshot) but if you look at the the repo on Github, you should see that you don't have Builders, and configs should be gone... 

This is quite puzzling to me. Can you look in the ```composer.lock``` file and see what commit composer has pulled? Maybe I pointed my 3.1 tag to the wrong branch / commit

**Comment by kevinkhill** [comment]
It looks like somehow you are still getting  3.0.x

Maybe try and change your require line to exactly 3.1.0 instead of ~3.1

?

**Comment by verhelsttroy** [comment]
Oh god I feel so stupid now... 
I had 3.0.* in my composer.json file...

I didn't bother to look at it since I just copy pasted it from the Lavacharts website.
Thanks a lot for the help. I hope I didn't cause you too much headache.

**Comment by verhelsttroy** [comment]
This is so typical, but it seems that the GanttChart example in laravel-showcase doesn't work. I tried the GeoChart example, which is also a new one, and it worked perfectly with "@geochart('Geo', 'chart-div')" in my blade view. I also tried some other new ones and they worked as well.

The gantt example however gave me an error at first because some dates weren't filled in with the example. There were some null values which specifically had to be set I guess, because I got an error saying that some values needed to be able to be parsed by Carbon.

I set those dates in the format already used in the example and now my view just returns the @ganttchart(...) as a string into the view without any errors.

I was thinking that maybe you hadn't stumbled upon this error since in the lavacharts/laravel-showcase app you seem to always be using the render method like this "{!! \Lava::render($type, $title, 'my-chart') !!}".

**Comment by verhelsttroy** [comment]
For the record, I also tried the {!! \Lava::render($type, $title, 'my-chart') !!} way and this time the view returned a error, not specifying where it went wrong though. I'll post two screenshots here. One of the view and one of my console, where you can see that the gantt package is indeed loaded.

![image](https://cloud.githubusercontent.com/assets/25820314/24904616/4edd78a2-1eb1-11e7-8cfa-d5e94e8ee7d4.png)

![image](https://cloud.githubusercontent.com/assets/25820314/24904642/65d9d154-1eb1-11e7-960d-9daf54f60a0e.png)

**Comment by kevinkhill** [comment]
Don't worry! I have banged my head against the keyboard many-a-times in a similar manner. You're not causing me any headaches, but more, creating puzzles for me to solve :smile:

Ok, since we are on the same page now, I probably should be testing the blade directives as well as the actual functionality of the library.

I will take a look when I get a little free time and see if we can't figure out what's going on

**Comment by verhelsttroy** [comment]
Thanks, let me know if you need the code I used to test the gantt.

**Comment by kevinkhill** [comment]
I think I figured it out! There was no logic to handle the null values in the date columns, so it couldn't link the rows together like it was supposed to.

**Comment by kevinkhill** [comment]
Also, if you want to use it, I added a new class `JavascriptDate` because I wanted to copy and paste Google's examples into my datatable. :smile:

just add `use Khill\Lavacharts\Support\JavascriptDate as Date;` and then you can initialize date cells the same way as Javascript `new Date(2015, 0, 9)`

**Comment by kevinkhill** [comment]
Also, if you want to use it, I added a new class `JavascriptDate` because I wanted to copy and paste Google's examples into my datatable. :smile:

just add `use Khill\Lavacharts\Support\JavascriptDate as Date;` and then you can initialize date cells the same way as Javascript `new Date(2015, 0, 9)`

**Comment by verhelsttroy** [comment]
Okay thanks a lot for the update!

**Comment by kevinkhill** [comment]
I'm just realizing I didn't tag a new release. Can you pull the 3.1 branch
and test?

**Comment by kevinkhill** [comment]
I'll go ahead and tag a new versions anyways. I think that I am slowly learning it's easier to release often and fix bugs than to hold back until it's perfect :smile:
