### ISSUE TITLE
 2 graphs do not open on the same page

### ISSUE THREAD

**Issue by vanessasoutoc** [kevinkhill/lavacharts#194]
What version are you having trouble with?
version ~3.1.*

**Comment by kevinkhill** [comment]
do you have some sample code I can help you debug? I know that multiple charts can render on one page (I have made a test page specifically for testing this feature in the past)

![multichart](https://cloud.githubusercontent.com/assets/266076/24892780/f2fd7762-1e33-11e7-8763-2f2486acb993.png)

**Comment by vanessasoutoc** [comment]
Use laravel
my code in https://gist.github.com/vanessasoutoc/b10f263990305f011621d499b5e9c865
![bug_2_graphs](https://cloud.githubusercontent.com/assets/7906420/24907067/f1b06f1a-1e90-11e7-89a6-8ce28dc2afb4.png)

**Comment by kevinkhill** [comment]
It seems that you are overwriting the first chart with the second.

The way the library works is like this:
 - There should only be **one** instance of the Lavacharts library. (If you use the Laravel ServiceProvider, the single instance is made for you and stored in the IoC container.) This way, when you call the alias ```\Lava::``` it will pull the single instance from the container.
 - Each chart created doesn't need to be assigned to a variable, and passed to the view.
 - Each chart is stored internally in the Lavacharts library (If you look in the code, it's called the Volcano)
 - If you don't want to use the ServiceProvider and Alias, that's fine too. Refactor your code to have a  single instance of the library and use it to build everything.

**Comment by vanessasoutoc** [comment]
It's work.
Thank for help me.
:+1:
