### ISSUE TITLE
3.1 doesn't work in Symfony anymore

### ISSUE THREAD

**Issue by Naoclis** [kevinkhill/lavacharts#195]
Works in 3.0 and not in 3.1 : the main class is not found

**Comment by kevinkhill** [comment]
Oh no! (I don't often work with symfony, so I have been working on Lavacharts with the, it isn't broken so don't touch it mentality) 

If you know symfony well, I would happily accept a pull request to fix a simple bug. Otherwise, I will see what's going on and fix this bug.

**Comment by Naoclis** [comment]
I don't really know Symfony well enough to do pull request.
But I know what is the problem : in 3.0.4, you got a repository "Symfony", which has disappear in 3.1.0
I had read the class in the rep and it seems to simply reference to the others
May be if you just put back this repository in 3.1 it will work again : a simple copy/paste could do the job

**Comment by kevinkhill** [comment]
Well, that's an easy fix then! I don't know how I accidentally deleted the Symfony folder, but I just put it back and pushed version 3.1.1

**Comment by Naoclis** [comment]
It's better but not enough because you moved all $chartClasses in Volcano :
You need to replace :
```
$chartClassesProp = new \ReflectionProperty(Lavacharts::class, 'chartClasses') by 
$chartClassesProp = new \ReflectionProperty(Lavacharts::class, 'volcano')
in LavachartsExtension.php, in the Symfony/Bundle/Twig folder
```

And then I got a new error in Twig when I call the chart:
Unknown "piechart" function
 which I understand since the chartclasses has changed, but I can't find how to properly call now you used Volcano

May be you could try something ?

**Comment by Naoclis** [comment]
I found a quick and dirty way to resolve it 

`/*
        $chartClassesProp = new \ReflectionProperty(Lavacharts::class, 'chartClasses');
        $chartClassesProp->setAccessible(true);
        $chartClasses = $chartClassesProp->getValue(new Lavacharts);
        */
        $chartClasses = [
            'AreaChart',
            'BarChart',
            'CalendarChart',
            'ColumnChart',
            'ComboChart',
            'PieChart',
            'DonutChart',
            'GaugeChart',
            'GeoChart',
            'LineChart',
            'ScatterChart',
            'TableChart',
            'TreeMap'
        ];`

But I suppose it's not really what you want to do by adding the chartfactory and the dashboard factory
I let you correct when you can, just tell me

**Comment by kevinkhill** [comment]
I will dig into this when I get home

**Comment by kevinkhill** [comment]
I believe I have solved all your woes!

I installed a fresh copy of Symfony 3.2 and just went back through all of the Bundle code for Lavacharts. You should be able to render charts with the lowercase version of their name `{{ linechart('ChartLabel', 'chart-elem-id')|raw }}`

I also added logic to utilizing the feature of assigning the element id in the controller and omitting it from 
the view render call.

In the controller, when defining the options for the chart, include `'elementId' => 'chart-elem-id'`
So that you can just call `{{ linechart('ChartLabel')|raw }}`

**Comment by Naoclis** [comment]
Hello,

it works perfectly, fine !
When you had some time, could you update Packagist so composer will get the last version ? 
Thanks you !

Continue the good work, your bundle is awesome !

Have a nice day !

Nicolas

**Comment by kevinkhill** [comment]
I really wish I could figure out why packagist isn't automatically updating like it used to... But I will update it

**Comment by kevinkhill** [comment]
Done.

**Comment by Naoclis** [comment]
Thanks, it's perfect
