### ISSUE TITLE
can we switch chart type from 'BarChart' to 'LineChart' using Lava javascript object ?

### ISSUE THREAD

**Issue by rahulsharma841990** [kevinkhill/lavacharts#196]
i have to switch chart using jquery of same data.can we do this with lavachart ?

**Comment by kevinkhill** [comment]
This is actually a very interesting question that I've never thought of before. I don't know of Google charts allows this, but I will definitely look into it.

**Comment by rahulsharma841990** [comment]
Yes, i worked a lot on google charts..it allows us to change chart type if we are creating charts with chartWrapper. See this link: https://groups.google.com/forum/#!topic/google-visualization-api/kSb9gQm8FU8

After change the chart type we just have to re draw chart again.

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
