### ISSUE TITLE
Multiple Vertical Axes on Line Charts

### ISSUE THREAD

**Issue by greasypablo** [kevinkhill/lavacharts#198]
Hi, I'm having trouble working out how to add multiple Y axes to a line chart.

I'm looking to have Date on the X axis. Value and Qty need to be on Y1 and Y2 but I can't see quite how. The chart renders up nicely at the moment with everything on a single Y axis.

It's a very simple setup and I've stripped out the non-lavachart stuff.

I'm using version 3.0.8 with vanilla PHP.

```
$lava = new Lavacharts; 

$sales = $lava->DataTable();
$sales->addDateColumn('Date')
            ->addNumberColumn('Value')
            ->addNumberColumn('Qty');

$sales->addRow([2017-01,500,10]);
$sales->addRow([2017-02,200,5]);
$sales->addRow([2017-03,400,15]);

$lava->LineChart('Sales', $sales, [
    'title' => 'Sales'
]);

echo '<div id="sales_chart"></div>';

echo $lava->render('LineChart', 'Sales', 'sales_chart');
```
I just can't work out from the documentation how to do it and Google is not helping either.

_Edited to correct code_

**Comment by kevinkhill** [comment]
Since I you have three columns, then try changing your addRow calls to:
```
sales->addRow([2017-01,500,10]);
$sales->addRow([2017-02,200,5]);
$sales->addRow([2017-03,400,15]);
```

**Comment by greasypablo** [comment]
Sorry, in my haste to simplify my code, I left the brackets out.

I am getting line charts out, I just can't work out how to add a second vertical axis.

**Comment by greasypablo** [comment]
So, having looked around the various closed tickets and the code, the following gives 2 axes which are labelled:

```
$lava = new Lavacharts; 

$sales = $lava->DataTable();
$sales->addDateColumn('Date')
            ->addNumberColumn('Value')
            ->addNumberColumn('Qty');

$sales->addRow([2017-01,500,10]);
$sales->addRow([2017-02,200,5]);
$sales->addRow([2017-03,400,15]);

$lava->LineChart('Sales', $sales, [
    'title' => 'Sales'
    'series' => array (
        0 => array (
            "targetAxisIndex" => 0
        ),
        1 => array (
            "targetAxisIndex" => 1
        )
    ),
    'vAxes' => array (
        0 => array (
            "title" => "Value"
        ),
        1 => array (
            "title" => "Qty"
        )
    )
]);

echo '<div id="sales_chart"></div>';

echo $lava->render('LineChart', 'Sales', 'sales_chart');
```

**Comment by kevinkhill** [comment]
I'm glad you were able to figure it out :smile:
