### ISSUE TITLE
Charts not re-rendering on window resize

### ISSUE THREAD

**Issue by kyranb** [kevinkhill/lavacharts#199]
What version are you having trouble with?
Tested using the latest: 3.1 branch

If a viewport is small, then resized/expanded the chart remains the original size.

![screenshot 2017-04-19 15 12 14](https://cloud.githubusercontent.com/assets/5426926/25181740/ca56fe10-2512-11e7-9338-837e2f5f1571.png)

However previously on`3.0.8` this was not the case and the chart would re-render to fill the newly increased or decreased space in its parent div.

I'll take a look into the new changes and see if I can discover where this change originated from.

Edit:

Calling the following manually fixes things:

```js
window.lava._forEachRenderable(function (renderable) {
            console.log('redrawing '+renderable.uuid());

            renderable.redraw();
        });
```
however it seems the event listener isn't working:
``` addEvent(window, 'resize', window.lava.redrawHandler);```

**Comment by kevinkhill** [comment]
I will take a look... and see what I probably accidentally deleted!

**Comment by kyranb** [comment]
Thanks! That did it 😄

**Comment by kevinkhill** [comment]
Glad to hear! I will tag a new version soon.
