### ISSUE TITLE
unable to use library with Laravel5

### ISSUE THREAD

**Issue by tamirh67** [kevinkhill/lavacharts#20]
i have added the requirement to the composer.json and did composer update

used one of the examples (pie chart)

and added the provider...which then failes with:
BadMethodCallException in ServiceProvider.php line 111:
Call to undefined method [package]

**Comment by tamirh67** [comment]
Was it ever tested with L5?

**Comment by rmclain** [comment]
The library still works with Laravel 5, you just need to bypass loading the service provider in the config/app.php.

Then your controller would look something like:
```php
    use Khill\Lavacharts\Lavacharts;
    
    class WelcomeController extends Controller
    {
    ...
    public function index()
    {
        $lava = new Lavacharts; // See note below for Laravel
        $finances = $lava->DataTable();
        $finances->addDateColumn('Year')
                 ->addNumberColumn('Sales')
                 ->addNumberColumn('Expenses')
                 ->setDateTimeFormat('Y')
                 ->addRow(array('2004', 1000, 400))
                 ->addRow(array('2005', 1170, 460))
                 ->addRow(array('2006', 660, 1120))
                 ->addRow(array('2007', 1030, 54));

        $columnchart = $lava->ColumnChart('Finances')
                            ->setOptions(array(
                                'datatable' => $finances,
                                'title' => 'Company Performance',
                                'titleTextStyle' => $lava->TextStyle(array(
                                    'color' => '#eb6b2c',
                                    'fontSize' => 14
                                ))
                            ));
         return view( 'welcome', array('lava'=>$lava));
     }
```
Then in your blade view you can do this:
```
    <div id="perf_div"></div>
	{!! $lava->render('ColumnChart', 'Finances', 'perf_div') !!}
```

**Comment by kevinkhill** [comment]
rmclain is correct, you can just create the Lavacharts object yourself. I have not tested the Laravel specific parts with version 5, since I am still using 4.2.

**Comment by stevebauman** [comment]
Laravel 5 removes the `package` method. Since this package doesn't have a configuration/migration/views it's a simple update to get running. Just check if the method exists before using it and you'll have laravel 5 compatibility. I haven't tested this package with Laravel 5 yet, but with my packages this is what I use.

    if (method_exists($this, 'package')) {

            $this->package('khill/lavacharts');

    }

**Comment by kevinkhill** [comment]
If you could write me a quick PR, I'll merge it in.

**Comment by roshimon** [comment]
Lavacharts works fine with Laravel 5.
