### ISSUE TITLE
Problem while printing chart on PDF

### ISSUE THREAD

**Issue by salidine** [kevinkhill/lavacharts#200]
Version 3.1.4
Hi,
I have an issue recently while printing graphics on pdf.
I use wkhtmltopdf with snappy wrapper on Laravel 4.2
Everything used to work fine until recently. I don't know if it has something to do with some updates. The graphics are correctly displayed on the html pages but when it comes to printing them on pdf, I have blank parts instead of the graphics.
Neither snappy nor wkhtmltopdf have been updated since september.
I don't know if someone else is facing this issue.
Cheers,

**Comment by kevinkhill** [comment]
So you're saying that they used to print? I have never used snappy or wk so I don't know what they might be doing.

**Comment by salidine** [comment]
Thanks for your answer.
Yes they used to print until recently.

**Comment by kevinkhill** [comment]
Have you looked at what I was discussing [in this issue](https://github.com/kevinkhill/lavacharts/issues/112) about generating static images of the charts? 

[Google's documents on printing](https://developers.google.com/chart/interactive/docs/printing), if you haven't looked already

**Comment by salidine** [comment]
Thanks for the link. I was thinking about doing it but in a much harder way.
Your solution is much easier.
Cheers,

**Comment by aparedesBB** [comment]
@salidine Did you reach a solution to print the charts with snappy?
