### ISSUE TITLE
Don't really understand how to render a chart in Javascript

### ISSUE THREAD

**Issue by kevinkhill** [kevinkhill/lavacharts#202]
Posted by [2ndGAB](https://github.com/2ndGAB) and copied from [here](https://github.com/kevinkhill/lavacharts-laravel/issues/1) to here so I can track the issue with the main repo.

 > Hello,
> Sorry if it's not really the place to ask this question but I didn't get any answer from Stackoverflow and maybe you don't really pay attention to it as you don't have any defined tag.
> 
> I'm trying to render a chart on CakePHP framework but the problem is not related to the framework but to how to find the chart id from Javascript.
> 
> I explained my problem here I think it's maybe not necessary to redo everything here.
So I would appreciate that get a look at it to help me.
> 
> Thanks a lot,
> Alain

[Link to the SO post](http://stackoverflow.com/questions/43951860/how-to-render-a-lavachart-from-javascript)

**Comment by kevinkhill** [comment]
I'm sorry that your SO post went unseen! I have tried before to answer people on SO but I don't have enough rep or whatever, so I can only comment. I don't really check it regularly (I guess I should.) Also, what tag are you talking about?

Anyways,
It looks correct upon first glance, I will try and re-create to make sure I haven't introduced any bugs.

**Comment by kevinkhill** [comment]
I am not the best with Javascript, I will admit, but...

is this endpoint
```cheminUrl + "Owners/getConsultDesc/<?=$owner_id?>"```

returning a php
```$dataTable->toJson();```

to this portion
```var dataTableJson = this.responseText.split('/');``` ?

I'm curious to the split on ```/``` when it should just be a JSON object already?

**Comment by kevinkhill** [comment]
We went through a lot of the javascript [in this issue](https://github.com/kevinkhill/lavacharts/issues/75) which was related and I have a working example [here in the issues repo](https://github.com/lavacharts/issues) **This is currently getting a 500 error, idk what's wrong with the repo**

**Comment by 2ndGAB** [comment]
Hi Kevin,
ok, so yes the `split()` hasn't any reason to be here.

but as I said, my problem is more to find the id concerned by the displayed chart. I display (if I really to do) an empty chart like that:

	<div class="col-md-10" id="stats">
	    <?php if (isset($lava)): ?>
	        <h3><?= __("Statistiques") ?></h3>
	            <div id='graphe_consult_desc'></div>
	            <?= $lava->render('ColumnChart','consult_desc' ,'graphe_consult_desc')?>
	        <?php endif;?>
	    </div>
	</div>

Then I try to populate it. So I use an asynchronous request which gives me a json data supposed to be directly use by your object be cause it works if I display the chart WITH the data.

    xhr_object.onreadystatechange = function() {  
        if(this.readyState == 4) {
            var dataTableJson = this.responseText.split('/');

            lava.loadData('consult_desc', dataTableJson, function (chart) {
                console.log(chart);
            });
        }
    }

So my problem here is about this error message:

    uncaught exception: ChartNotFound: [Lavacharts] Chart with label "consult_desc" was not found.

So if we refer to the html code above, which id I supposed to give to ``lava.loadData()``? I also tried ``graphe_consult_desc``

I didn't find such kind of example in your repo.

**Comment by kevinkhill** [comment]
Do you have the most recent version? Can you see in the browser, if you type in the console. `lava._charts['ColumnChart']` and is if your chart is in the array?

**Comment by 2ndGAB** [comment]
I use version 3.1.4
And ``lava._charts`` is empty. there is certainly something wrong in my chart initialisation but I don't see what.
Here are the data I pass to `<?= $lava->render('ColumnChart','consult_desc_semaine' ,'graphe_consult_desc_semaine')?>`:

	object(Khill\Lavacharts\Lavacharts) {
		chartFactory => object(Khill\Lavacharts\Charts\ChartFactory) {
			[private] chartBuilder => object(Khill\Lavacharts\Builders\ChartBuilder) {
				[protected] type => 'ColumnChart'
				[protected] datatable => object(Khill\Lavacharts\DataTables\DataTable) {
					timezone => object(DateTimeZone) {
						timezone_type => (int) 3
						timezone => 'UTC'
					}
					[protected] columnFactory => object(Khill\Lavacharts\DataTables\Columns\ColumnFactory) {
						
					}
					[protected] rowFactory => null
					[protected] cols => [
						(int) 0 => object(Khill\Lavacharts\DataTables\Columns\Column) {
							[protected] type => 'date'
							[protected] label => 'Période'
							[protected] format => null
							[protected] role => null
							[protected] options => []
						},
						(int) 1 => object(Khill\Lavacharts\DataTables\Columns\Column) {
							[protected] type => 'number'
							[protected] label => 'Nombre de consultations'
							[protected] format => null
							[protected] role => null
							[protected] options => []
						},
						(int) 2 => object(Khill\Lavacharts\DataTables\Columns\Column) {
							[protected] type => 'number'
							[protected] label => 'Nombre de consultation unique'
							[protected] format => null
							[protected] role => null
							[protected] options => []
						}
					]
					[protected] rows => [
						(int) 0 => object(Khill\Lavacharts\DataTables\Rows\Row) {
							[protected] values => [
								(int) 0 => object(Khill\Lavacharts\DataTables\Cells\DateCell) {
									[protected] v => object(Carbon\Carbon) {
										date => '2017-05-18 00:00:00.000000'
										timezone_type => (int) 3
										timezone => 'UTC'
										[protected] days => [
											(int) 0 => 'Sunday',
											(int) 1 => 'Monday',
											(int) 2 => 'Tuesday',
											(int) 3 => 'Wednesday',
											(int) 4 => 'Thursday',
											(int) 5 => 'Friday',
											(int) 6 => 'Saturday'
										]
										[protected] relativeKeywords => [
											(int) 0 => '+',
											(int) 1 => '-',
											(int) 2 => 'ago',
											(int) 3 => 'first',
											(int) 4 => 'last',
											(int) 5 => 'next',
											(int) 6 => 'this',
											(int) 7 => 'today',
											(int) 8 => 'tomorrow',
											(int) 9 => 'yesterday'
										]
										[protected] toStringFormat => 'Y-m-d H:i:s'
										[protected] weekStartsAt => (int) 1
										[protected] weekEndsAt => (int) 0
										[protected] weekendDays => [
											(int) 0 => (int) 6,
											(int) 1 => (int) 0
										]
										[protected] testNow => null
										[protected] translator => null
										[protected] lastErrors => null
										[protected] utf8 => false
										[protected] monthsOverflow => true
									}
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								},
								(int) 1 => object(Khill\Lavacharts\DataTables\Cells\Cell) {
									[protected] v => (int) 0
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								},
								(int) 2 => object(Khill\Lavacharts\DataTables\Cells\Cell) {
									[protected] v => (int) 0
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								}
							]
						},
						(int) 1 => object(Khill\Lavacharts\DataTables\Rows\Row) {
							[protected] values => [
								(int) 0 => object(Khill\Lavacharts\DataTables\Cells\DateCell) {
									[protected] v => object(Carbon\Carbon) {
										date => '2017-05-11 00:00:00.000000'
										timezone_type => (int) 3
										timezone => 'UTC'
										[protected] days => [
											(int) 0 => 'Sunday',
											(int) 1 => 'Monday',
											(int) 2 => 'Tuesday',
											(int) 3 => 'Wednesday',
											(int) 4 => 'Thursday',
											(int) 5 => 'Friday',
											(int) 6 => 'Saturday'
										]
										[protected] relativeKeywords => [
											(int) 0 => '+',
											(int) 1 => '-',
											(int) 2 => 'ago',
											(int) 3 => 'first',
											(int) 4 => 'last',
											(int) 5 => 'next',
											(int) 6 => 'this',
											(int) 7 => 'today',
											(int) 8 => 'tomorrow',
											(int) 9 => 'yesterday'
										]
										[protected] toStringFormat => 'Y-m-d H:i:s'
										[protected] weekStartsAt => (int) 1
										[protected] weekEndsAt => (int) 0
										[protected] weekendDays => [
											(int) 0 => (int) 6,
											(int) 1 => (int) 0
										]
										[protected] testNow => null
										[protected] translator => null
										[protected] lastErrors => null
										[protected] utf8 => false
										[protected] monthsOverflow => true
									}
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								},
								(int) 1 => object(Khill\Lavacharts\DataTables\Cells\Cell) {
									[protected] v => (int) 0
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								},
								(int) 2 => object(Khill\Lavacharts\DataTables\Cells\Cell) {
									[protected] v => (int) 0
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								}
							]
						},
						(int) 2 => object(Khill\Lavacharts\DataTables\Rows\Row) {
							[protected] values => [
								(int) 0 => object(Khill\Lavacharts\DataTables\Cells\DateCell) {
									[protected] v => object(Carbon\Carbon) {
										date => '2017-05-04 00:00:00.000000'
										timezone_type => (int) 3
										timezone => 'UTC'
										[protected] days => [
											(int) 0 => 'Sunday',
											(int) 1 => 'Monday',
											(int) 2 => 'Tuesday',
											(int) 3 => 'Wednesday',
											(int) 4 => 'Thursday',
											(int) 5 => 'Friday',
											(int) 6 => 'Saturday'
										]
										[protected] relativeKeywords => [
											(int) 0 => '+',
											(int) 1 => '-',
											(int) 2 => 'ago',
											(int) 3 => 'first',
											(int) 4 => 'last',
											(int) 5 => 'next',
											(int) 6 => 'this',
											(int) 7 => 'today',
											(int) 8 => 'tomorrow',
											(int) 9 => 'yesterday'
										]
										[protected] toStringFormat => 'Y-m-d H:i:s'
										[protected] weekStartsAt => (int) 1
										[protected] weekEndsAt => (int) 0
										[protected] weekendDays => [
											(int) 0 => (int) 6,
											(int) 1 => (int) 0
										]
										[protected] testNow => null
										[protected] translator => null
										[protected] lastErrors => null
										[protected] utf8 => false
										[protected] monthsOverflow => true
									}
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								},
								(int) 1 => object(Khill\Lavacharts\DataTables\Cells\Cell) {
									[protected] v => (int) 0
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								},
								(int) 2 => object(Khill\Lavacharts\DataTables\Cells\Cell) {
									[protected] v => (int) 0
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								}
							]
						},
						(int) 3 => object(Khill\Lavacharts\DataTables\Rows\Row) {
							[protected] values => [
								(int) 0 => object(Khill\Lavacharts\DataTables\Cells\DateCell) {
									[protected] v => object(Carbon\Carbon) {
										date => '2017-04-27 00:00:00.000000'
										timezone_type => (int) 3
										timezone => 'UTC'
										[protected] days => [
											(int) 0 => 'Sunday',
											(int) 1 => 'Monday',
											(int) 2 => 'Tuesday',
											(int) 3 => 'Wednesday',
											(int) 4 => 'Thursday',
											(int) 5 => 'Friday',
											(int) 6 => 'Saturday'
										]
										[protected] relativeKeywords => [
											(int) 0 => '+',
											(int) 1 => '-',
											(int) 2 => 'ago',
											(int) 3 => 'first',
											(int) 4 => 'last',
											(int) 5 => 'next',
											(int) 6 => 'this',
											(int) 7 => 'today',
											(int) 8 => 'tomorrow',
											(int) 9 => 'yesterday'
										]
										[protected] toStringFormat => 'Y-m-d H:i:s'
										[protected] weekStartsAt => (int) 1
										[protected] weekEndsAt => (int) 0
										[protected] weekendDays => [
											(int) 0 => (int) 6,
											(int) 1 => (int) 0
										]
										[protected] testNow => null
										[protected] translator => null
										[protected] lastErrors => null
										[protected] utf8 => false
										[protected] monthsOverflow => true
									}
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								},
								(int) 1 => object(Khill\Lavacharts\DataTables\Cells\Cell) {
									[protected] v => (int) 0
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								},
								(int) 2 => object(Khill\Lavacharts\DataTables\Cells\Cell) {
									[protected] v => (int) 0
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								}
							]
						},
						(int) 4 => object(Khill\Lavacharts\DataTables\Rows\Row) {
							[protected] values => [
								(int) 0 => object(Khill\Lavacharts\DataTables\Cells\DateCell) {
									[protected] v => object(Carbon\Carbon) {
										date => '2017-04-20 00:00:00.000000'
										timezone_type => (int) 3
										timezone => 'UTC'
										[protected] days => [
											(int) 0 => 'Sunday',
											(int) 1 => 'Monday',
											(int) 2 => 'Tuesday',
											(int) 3 => 'Wednesday',
											(int) 4 => 'Thursday',
											(int) 5 => 'Friday',
											(int) 6 => 'Saturday'
										]
										[protected] relativeKeywords => [
											(int) 0 => '+',
											(int) 1 => '-',
											(int) 2 => 'ago',
											(int) 3 => 'first',
											(int) 4 => 'last',
											(int) 5 => 'next',
											(int) 6 => 'this',
											(int) 7 => 'today',
											(int) 8 => 'tomorrow',
											(int) 9 => 'yesterday'
										]
										[protected] toStringFormat => 'Y-m-d H:i:s'
										[protected] weekStartsAt => (int) 1
										[protected] weekEndsAt => (int) 0
										[protected] weekendDays => [
											(int) 0 => (int) 6,
											(int) 1 => (int) 0
										]
										[protected] testNow => null
										[protected] translator => null
										[protected] lastErrors => null
										[protected] utf8 => false
										[protected] monthsOverflow => true
									}
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								},
								(int) 1 => object(Khill\Lavacharts\DataTables\Cells\Cell) {
									[protected] v => (int) 0
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								},
								(int) 2 => object(Khill\Lavacharts\DataTables\Cells\Cell) {
									[protected] v => (int) 0
									[protected] f => ''
									[protected] p => null
									[protected] options => []
								}
							]
						}
					]
					[protected] dateTimeFormat => null
				}
				[protected] options => [
					'title' => 'Consultation des fiches par semaine'
				]
				[protected] pngOutput => false
				[protected] materialOutput => false
				[protected] label => object(Khill\Lavacharts\Values\Label) {
					[protected] value => 'consult_desc_semaine'
				}
				[protected] elementId => null
			}
		}
		dashFactory => object(Khill\Lavacharts\Dashboards\DashboardFactory) {
			[private] dashBuilder => object(Khill\Lavacharts\Builders\DashboardBuilder) {
				[protected] datatable => null
				[protected] bindings => []
				[protected] label => null
				[protected] elementId => null
			}
		}
		[private] locale => 'en'
		[private] volcano => object(Khill\Lavacharts\Volcano) {
			[private] charts => [
				'ColumnChart' => [
					'consult_desc_semaine' => object(Khill\Lavacharts\Charts\ColumnChart) {
						[protected] options => [
							'title' => 'Consultation des fiches par semaine'
						]
						[protected] label => object(Khill\Lavacharts\Values\Label) {
							[protected] value => 'consult_desc_semaine'
						}
						[protected] elementId => null
						[protected] renderableStatus => true
						[private] png => false
					}
				]
			]
			[private] dashboards => []
		}
		[private] scriptManager => object(Khill\Lavacharts\Javascript\ScriptManager) {
			[private] lavaJsRendered => false
		}
	}

**Comment by kevinkhill** [comment]
Can you try wrapping all of the Javascript code dealing with the chart, into the `lava.ready()` method? It is the last step of the render chain, that once all the charts are in the page (rendered or not) to be able to interact with them. I had run into race conditions in the past, and this was added to help mitigate. 

```
lava.ready(function() {
    // Place async code here
});
```

**Comment by kevinkhill** [comment]
Any luck?

**Comment by kevinkhill** [comment]
Closing due to lack of communication. Please open a new issue if you have any questions.
