### ISSUE TITLE
Pull Chart-Options over Ajax

### ISSUE THREAD

**Issue by BNEP** [kevinkhill/lavacharts#205]
Hello, 
first many thanks for this awesome work!
I am using Lavacharts 3.1.4
I made a symfony/sonata admin dashboard block which displays many statistical data as charts. 

**Everything works, but one problem i have and i can't find a solution on this, therefore i try to ask here:**
I can't update the options of my gauge-charts, so that the 'max', 'greenTo', 'greenFrom', 'yellowTo', 'yellowFrom', 'redTo', 'redFrom' options, which depend on chartvalues and therefore must be updated when calling the datatable via ajax.

I made following controller which returns, beside other vaues, the dataTables as json, when calling it via XHR:
```php
// Controller returns Json object
...
foreach($gDatas as $k => $gData) {
    //DataTable
    ${$gData[1]} = $this->lava->DataTable();
    ${$gData[1]}
        ->addStringColumn('Type')
        ->addNumberColumn('Percent')
    ;

    // Chart with options
    ${'chart_'.$gData[1]} = $this->lava->GaugeChart('chart_'.$gData[1], ${$gData[1]}, [
        'title'         => $gData[1] . $this->formatAmount($gData[4]),
        'max'           => $gData[2] * 2,

        'greenTo'       => $gData[2] * 2,
        'greenFrom'     => $gData[2],

        'yellowTo'      => $gData[2],
        'yellowFrom'    => $gData[2] / 2,

        'redTo'         => $gData[2] / 2,
        'redFrom'       => 0,

    ]);


    ${$gData[1]}->addRow([ $gData[1],$gData[4] ]);
    $aReturn[$gData[1]] = ${$gData[1]}->toJson();
    $aReturn['chart_'.$gData[1]] = ${'chart_'.$gData[1]}->toJson();

}


return new jsonResponse(
    $aReturn
);
```

The typical return looks like the following:
```json
cash		"{\"cols\":[{\"type\":\"string\",\"label\":\"Type\"},{\"type\":\"number\",\"label\":\"Percent\"}],\"rows\":[{\"c\":[{\"v\":\"cash\"},{\"v\":495}]}]}"
chart_cash	"{\"title\":\"cash\\u20ac 495,00\",\"max\":1204,\"greenTo\":1204,\"greenFrom\":602,\"yellowTo\":602,\"yellowFrom\":301,\"redTo\":301,\"redFrom\":0}"
```

In my page, there are the twig calls
```twig
    <div id="gauge-div" style="float: left;"></div>
    {{ gaugechart('chart_cash', 'gauge-div')|raw }}
```

...and the javascripts, which i mean, should update the chartOptions, too
```javascript
// ...
        $(function() {
            $('.Gauges').click(function() {
                getGaugeCharts($(this).val());
            });
        });

        function getGaugeCharts(range){
            $.getJSON('/xhr/statistics/gauges/' + range, function (dataTableJson) {
                    lava.loadData('chart_cash', dataTableJson.cash, function (chart) {
                    });
                    lava.loadOptions('chart_cash', dataTableJson.chart_cash, function (chart) {
                    });
            });
        }



        lava.ready(function() {
            getGaugeCharts('day');
        });
// ...
```
But unfortunately, they don't update, the initial min and maxes go away, instead of this, the (default) values min: 0 max: 100 appear, and no color (green, yellow, red) is shown.

**For sure i make something wrong, could you tell me what?
Thank you**

**Comment by BNEP** [comment]
Hello,
searched long and finally opened this issue. After opening i found the solution.
The Problem was that the options must be a js object, no json string. 
If others have the same problem: 

```javascript
// wrong
lava.loadOptions('chart_cash', dataTableJson.chart_cash, function (chart) {});

// right
lava.loadOptions('chart_cash', $.parseJSON(dataTableJson.options_cash), function (chart) {});
```

That found out myself, closing this issue :)

**Comment by kevinkhill** [comment]
Sorry I never answered this, but I'm glad you found the solution :)
