### ISSUE TITLE
Google Maps Api Key

### ISSUE THREAD

**Issue by orkokane** [kevinkhill/lavacharts#206]
Hi, I've a problem with geo charts. When I put the geo chart on my view in Laravel, the browser give me the classic error that is missing api key "Google Maps API error: MissingKeyMapError".
How can I fix that? Where do I have to put the google api key?
Thanks!

**Comment by kevinkhill** [comment]
Really? I didn't think the chart API was using the Maps API. I thought it was just doing it all Google side. I haven't seen this error before, so it's quite possible they (Google) changed something and now lavacharts needs to be updated too. 

I will put this on the top of my TODO list for the project.

**Comment by orkokane** [comment]
Hi, thanks for the answer. I've checked disabling all scripts and the google's errors continue. I've disabled the geo chart also and the error disappear. I think it's something new from Google side. On new api must put a google key.

**Comment by tszaniszlo** [comment]
Hi, I have the same issue when using Lavacharts. It seems that it was introduced recently.
Thanks,
Tamas

**Comment by kevinkhill** [comment]
I forgot to tag this issue in the commit, but [I believe this should solve your issue](https://github.com/kevinkhill/lavacharts/commit/41308c28ebf29062d54f32a86af495e9ae3dcd26)!

If you could test the fix for me by updating your composer req to `"khill/lavacharts" : "3.1-dev", then I will tag a new release for the patch.

**Comment by tszaniszlo** [comment]
Trying to pass the key through the option, no success. Could you help me how to pass it ? Thanks

**Comment by kevinkhill** [comment]
First off, are you using Laravel?

**Comment by kevinkhill** [comment]
I just added notes for publishing the config file in Laravel, [found here](https://github.com/kevinkhill/lavacharts/blob/3.1/README.md#configuration)

**Comment by kevinkhill** [comment]
If you are not using Laravel, you can initialize the Lavacharts class with options, like so:
```
$lava = new Lavacharts([
    'maps_api_key' => '23ay5t987354inr28m9crg893crgt9arc98tr2a896tarc2896ta28'
]);
```

**Comment by MarcoCazzaro** [comment]
Hi Kevin, I am struggling with the same issue with Laravel 5.4.
I updated Lavacharts to version 3.1.6, tried to export config with the [command](https://github.com/kevinkhill/lavacharts/blob/3.1/README.md#configuration) you mentioned but no config file is generated. Then I created it manually, inserted my Google API Key but nothing changed, I still get the error. I also ran `composer dump-autoload`, just in case.
I am running it in localhost.
Is there something I am missing? Thanks!

**Comment by kevinkhill** [comment]
I tried a fresh install and what's weird is that Packagist shows `3.1.6`, but composer pulled in `3.1.5`, and my local 3.1 branch has `3.1.7`! 😆 

Anyways, I made a [new tag](https://github.com/kevinkhill/lavacharts/releases/tag/3.1.7) for `3.1.7`, pushed it to Github, and updated Packagist.

Give `composer update` a run and then verify that you got `3.1.7` with `composer show khill/lavacharts`

Lastly, clear your config cache with `php artisan config:clear` and publish the config with `php artisan vendor:publish --tag=lavacharts`

**Comment by MarcoCazzaro** [comment]
Thank you very much, it worked!

**Comment by tszaniszlo** [comment]
Now it works, thanks.

**Comment by kevinkhill** [comment]
Excellent. Thank you everyone for bringing this to my attention. I am glad we got it fixed :smile:

**Comment by Walt2018** [comment]
@kevinkhill, work for me. thanks

**Comment by kevinkhill** [comment]
TBH, I'm glad Lavacharts still works _at all_

I haven't touched the code in years.

Glad you got what you need 😊
