### ISSUE TITLE
center labell in DonutChart

### ISSUE THREAD

**Issue by ghost** [kevinkhill/lavacharts#209]
Hi,
   I am in very trouble.I want to create a  DonutChart with a centered label, I want to show tooltip on hover and also change the legend color.Please give an immediate solution.

**Comment by kevinkhill** [comment]
I'm sorry, but I'm not your on-demand chart generating service.

I'm happy to help you troubleshoot or fix bugs, but you should try it yourself first.

**Comment by kevinkhill** [comment]
I am going to close this, since it is not really an issue. If you try to solve this, and are still having trouble...

Please open a new issue with the code you are trying to get working, and I would be happy to assist.
