### ISSUE TITLE
Can't render 2 charts with the same type in the same view

### ISSUE THREAD

**Issue by lolytallica** [kevinkhill/lavacharts#21]
Using Laravel, I am trying to render multiple column (or pie) charts in the same view, but I just get the last one rendered. For example, if I render 2 pie charts and 1 column chart, I get the column chart, and the last piechart rendered, not both pies.

I wonder If this can be done, or am I missing something..

Thank you!!! :)

**Comment by kevinkhill** [comment]
Do the charts have different titles?  
Eg: Lava::PieChart('pie1') and Lava::PieChart('pie2')

If that isn't the case, could you make a gist of what you are doing so I can try and see where the issue is?

**Comment by lolytallica** [comment]
Exactly, it's differents charts with different titles, same code was working with the previous version of lavacharts, but not with the last one, can this be done with the new version or I might be missing something on my side?
Thank you for replying and for your great work!!

**Comment by kevinkhill** [comment]
If it's not a title issue, could you make a gist with the creation of the
chart code and the view code? I'll test and try and recreate your error

**Comment by lolytallica** [comment]
https://gist.github.com/lolytallica/0c56c2d2d26655dd350d
$chart is the chart type that I gent dynamically, in all cases I juste get only one chart of type rendered, never 2 column charts or 2 pie charts ..

**Comment by deringer** [comment]
I'm seeing the same issue;

```php
// Controller
$start = (new \DateTime())->sub(new \DateInterval('P7D'));
$end   = new \DateTime();

$dailyLinksTable = $this->getDailyLinksTable($start, $end);
$dailyHitsTable = $this->getDailyHitsTable($start, $end);

\Lava::ColumnChart('DailyLinksChart')->setOptions([
    'datatable' => $dailyLinksTable,
]);

\Lava::ColumnChart('DailyHitsChart')->setOptions([
    'datatable' => $dailyHitsTable,
]);
```

```php
// getDailyLinksTable, getDailyHitsTable
$dailyLinkBreakdown = $this->linkRepository->getDailyBreakdown($start, $end);

$dailyLinksTable = \Lava::DataTable();
$dailyLinksTable->addDateColumn('Date')->addNumberColumn('New Links')->setTimezone('Australia/Adelaide');

foreach ($dailyLinkBreakdown as $day)
{
    $dailyLinksTable->addRow([ $day->date, $day->links, ]);
}

return $dailyLinksTable;
```

I receive two javascript errors on the console: `Uncaught TypeError: Cannot set property 'data' of undefined` and `Uncaught TypeError: Cannot read property 'draw' of undefined`.

```javascript
window.onload = function() {
    onResize(function() {
        for(var c = 0; c < lava.registeredCharts.length; c++) {
            var parts = lava.registeredCharts[c].split(':');
            lava.charts[parts[0]][parts[1]].draw(); // First error occurs here
        }
    });
};

// ...

$this.data = new google.visualization.DataTable({"cols":[{"type":"date","label":"Date"},{"type":"number","label":"New Links"}],"rows":[{"c":[{"v":new Date(2015,0,12,0,0,0)},{"v":"3"}]},{"c":[{"v":new Date(2015,0,13,0,0,0)},{"v":"2"}]}]}, 0.6); // Second error occurs here
```

Looks like the second chart somehow overrides the first one, but I've not yet been able to determine where.

**Comment by kevinkhill** [comment]
I haven't had any time yet to look over this, but thank you for the gist and errors. I will go over it when life lets up and gives me a chance to code. (Hopefully soon! I would like to fix this for you two)

If either of you find the problem, I would happily merge a pull request for this issue :)

**Comment by thomthom** [comment]
Is this currently only available on dev-master?
I realized I had "dev-master" configured in composer.json and `composer validate` warned me about unconstrained versions. When I changed to `"khill/lavacharts": "2.0.*"` like the readme says and updated my pie charts broke with `Cannot set property 'data' of undefined`. I guess it's related to this issue.

**Comment by kevinkhill** [comment]
It is quite possible that I missed tagging that commit as a version, I will take a look when I get home from work today. Sorry for the inconvenience.

**Comment by thomthom** [comment]
Ah, so that how Laravel picks versions. I initially thought it was branches with a version naming convention. But I see it's tags now.
I also see in the commit history that this fix exist only in dev-master - that confirms what I saw. I've switched back to dev-master and I'll wait until a new version tag is release for this repo.

Btw, thanks for making this library - saved me from doing it. I'll get you that cup of coffee.

**Comment by kevinkhill** [comment]
Thank you so much, I really appreciate your donation :)
Just wondering, did you noticed my issue I created in Github, about using
the library outside of composer environments? Would you possibly have any
insight into a solution?

**Comment by thomthom** [comment]
Afraid no - I've not been on the webdev scene for a few years and started using composer/laravel only a couple of weeks ago...

**Comment by kevinkhill** [comment]
Ahhh, I see, well, I've been using Laravel for a while now, so if you ever
hit a roadblock, I probably hit the same one and could lend a hand if needed

**Comment by kevinkhill** [comment]
Ok, tagged a stable version for the multiple chart bug, you should be able to depend on the stable version 2.0.4 now and get that fix.

**Comment by thomthom** [comment]
Well, you helped me past one already, adding multiple Google Charts to blade templates linked to Laravel models. :)

**Comment by thomthom** [comment]
I just set the version in my `composer.json` to `"2.0.*" and ran `composer update` - and the charts now work. Everything is working great, I no longer need to get from `dev-master`. 
Thank you very much for your quick response.

**Comment by d32ick** [comment]
Hi. I'm trying to create two dashboards on same page, but only one dashboard shows up. Is there any solution for this? Thank you.

**Comment by kevinkhill** [comment]
Could you open this as a new issue please? I'm pretty sure you have found a bug, and I'd like to track the progress of fixing it in a new issue thread.
