### ISSUE TITLE
ChartNotFound in Volcano.php line 78

### ISSUE THREAD

**Issue by harshdoshi999** [kevinkhill/lavacharts#211]
I have just integrated larachart in my laravel application but getting following issue.

Issue#1 
ChartNotFound in Volcano.php line 78:
ColumnChart('Finances') was not found.

Issue#2
ErrorException in Volcano.php line 78:
ColumnChart('Finances') was not found. (View: D:\xampp\htdocs\project\resources\views\report\property.blade.php)

Here's my laravel code:

use Khill\Lavacharts\Lavacharts;
$lava = new Lavacharts; // See note below for Laravel

        $finances = $lava->DataTable();

        $finances->addDateColumn('Year')
                 ->addNumberColumn('Sales')
                 ->addNumberColumn('Expenses')
                 ->setDateTimeFormat('Y')
                 ->addRow(['2004', 1000, 400])
                 ->addRow(['2005', 1170, 460])
                 ->addRow(['2006', 660, 1120])
                 ->addRow(['2007', 1030, 54]);

        $lava->ColumnChart('Finances', $finances, [
            'title' => 'Company Performance',
            'titleTextStyle' => [
                'color'    => '#eb6b2c',
                'fontSize' => 14
            ]
        ]);

Here's my blade template code:
<div id="perf_div"></div>
<?php Lava::render('ColumnChart', 'Finances', 'perf_div') ?>

I have been using http://lavacharts.com/#example-bar example.

Thanks!

**Comment by kevinkhill** [comment]
Are you using the latest release? 3.1.x?

**Comment by harshdoshi999** [comment]
This is what I have added in my composer.json file

"khill/lavacharts" : "3.0.*"

**Comment by kevinkhill** [comment]
Could you please update to 3.1.* and see if the issue persists

**Comment by harshdoshi999** [comment]
Sure... let me try. Thanks!

**Comment by harshdoshi999** [comment]
Error still there... here's screencap of the error.
http://uploadfile.in/uploads/8525341901134ba3c2486a159d9ca78f85c195f9.png -- Error#1
http://uploadfile.in/uploads/72219663d03f08fd5500fd7aa1d1e4a73019b66a.png -- Error#2

**Comment by kevinkhill** [comment]
##Problem
I see that you have:
```
use Khill\Lavacharts\Lavacharts;
$lava = new Lavacharts; // See note below for Laravel
```
so by doing that, the chart you defined is stored in the `Volcano` of that `$lava` instance.

Now, in your blade templates, I see that item #7 of you screenshot of Error#1 you make use of the LavachartsFacade. The Facade is accessing the `$lava` instance that is contained in the ServiceProvider. That is why it is not found, because you created a second `$lava` instance in your controller.

 - - - 

##Solution
Don't make your own instance of `Lavacharts` (delete this `$lava = new Lavacharts;`) and replace your calls of `$lava->` to `\Lava::`

This way when you create your chart, it is stored in the ServiceProviders instance of Volcano and the LavachartFacade (also accessing that instance) should be able to locate the chart.

**Comment by harshdoshi999** [comment]
Hi Kevin, 
I changed my code according to your soln but still getting error.

Now, here's how my controller code looks like,
`$finances = \Lava::DataTable();

        $finances->addDateColumn('Year')
                 ->addNumberColumn('Sales')
                 ->addNumberColumn('Expenses')
                 ->setDateTimeFormat('Y')
                 ->addRow(['2004', 1000, 400])
                 ->addRow(['2005', 1170, 460])
                 ->addRow(['2006', 660, 1120])
                 ->addRow(['2007', 1030, 54]);

        \Lava::ColumnChart('Finances', $finances, [
            'title' => 'Company Performance',
            'titleTextStyle' => [
                'color'    => '#eb6b2c',
                'fontSize' => 14
            ]
        ]);`


Code in blade template:

`Lava::render('ColumnChart', 'Finances', 'perf_div')`

**Comment by harshdoshi999** [comment]
Hi, previously I was initiating Lava class after rendering the view and that's the reason I was getting the error. So  now I have changed the code and rendering the view after all processes, and, getting no errors but no outputs as well. Now I don't get a single error but I can't even see the graph as well. Nothing prints on  the page.

**Comment by harshdoshi999** [comment]
I am using dompdf.wrapper to create a PDF from the blade template. And in that Blade template I've been using your library. And this is the issue why I cant see the graph in PDF. If I remove PDF code then I can see graph working. So there's no issue with your library. **Any idea about this issue?** For now, I'm closing this issue. Thanks for your time.

**Comment by kevinkhill** [comment]
I don't know anything about `dompdf.wrapper` but I'm 99% certain you aren't seeing the graphs is that they are rendered in the page with javascript, after Lavacharts puts the script blocks into the page.

**Comment by harshdoshi999** [comment]
Looks like I have to find another way to generate PDF as I cant stop using your library because its awesome. :)

**Comment by kevinkhill** [comment]
Haha, thanks!
