### ISSUE TITLE
Rendering multiple charts in a for loop.

### ISSUE THREAD

**Issue by dawnpdb** [kevinkhill/lavacharts#212]
I am trying to render multiple charts from within a for loop. But only the last chart is being displayed. Here is my code:

Controller:

    foreach ($user_farms as $user_farm){
 
    $user_farm_id = $user_farm->id;
    $user_flocks = \App\Flock::where('farm_id', '=', $user_farm_id)->get();
    $no_flocks = \App\Flock::where('farm_id', '=', $user_farm_id)->get()->count();

    $j=0;

    foreach ($user_flocks as $user_flock){

        $user_flock_id = $user_flock->id;
        $weights = \App\Weight::where('flock_id', '=', $user_flock_id)->orderBy('week_id', 'asc')->get();

        $weights_first = $weights ->first();
        $start_week = $weights_first->week_id;

        foreach($weights as $weight ){

            $age = $weight->week_id - $start_week ;
            $actual[$age] = $weight->female;

        }   

        $graph[$i][$j] = Lava::DataTable();
        $graph[$i][$j]->addStringColumn('Weeks')
             ->addNumberColumn('Standard')
             ->addNumberColumn('Actual')
             ->addRow(['1',  $standard[1], ($actual[1]>0? $actual[1] : null) ])
             ->addRow(['2',  $standard[2], $actual[2]])
             ->addRow(['3',  $standard[3], $actual[3]])
             ->addRow(['4',  $standard[4], $actual[4]])
             ->addRow(['5',  $standard[5], $actual[5]])
             ->addRow(['6',  $standard[6], $actual[6]])
             ->addRow(['7',  $standard[7], $actual[7]])
             ->addRow(['8',  $standard[8], $actual[8]])
             ->addRow(['9',  $standard[9], $actual[9]])
             ->addRow(['10',  $standard[10], $actual[10]])
             ->addRow(['11',  $standard[11], $actual[11]])
             ->addRow(['12',  $standard[12], $actual[12]])
             ->addRow(['13',  $standard[13], $actual[13]])
             ->addRow(['14',  $standard[14], $actual[14]])
             ->addRow(['15',  $standard[15], $actual[15]])
             ->addRow(['16',  $standard[16], $actual[16]])
             ->addRow(['17',  $standard[17], $actual[17]])
             ->addRow(['18',  $standard[18], $actual[18]])
             ->addRow(['19',  $standard[19], $actual[19]])
             ->addRow(['20',  $standard[20], $actual[20]])
             ->addRow(['21',  $standard[21], $actual[21]])
             ->addRow(['22',  $standard[22], $actual[22]])
             ->addRow(['23',  $standard[23], $actual[23]])
             ->addRow(['24',  $standard[24], $actual[24]])
             ->addRow(['25',  $standard[25], $actual[25]])
             ->addRow(['26',  $standard[26], $actual[26]])
             ->addRow(['27',  $standard[27], $actual[27]])
             ->addRow(['28',  $standard[28], $actual[28]])
             ->addRow(['29',  $standard[29], $actual[29]])
             ->addRow(['30',  $standard[30], $actual[30]])
             ->addRow(['31',  $standard[31], $actual[31]])
             ->addRow(['32',  $standard[32], $actual[32]])
             ->addRow(['33',  $standard[33], $actual[33]])
             ->addRow(['34',  $standard[34], $actual[34]])
             ->addRow(['35',  $standard[35], $actual[35]])
             ->addRow(['36',  $standard[36], $actual[36]])
             ->addRow(['37',  $standard[37], $actual[37]])
             ->addRow(['38',  $standard[38], $actual[38]])
             ->addRow(['39',  $standard[39], $actual[39]])
             ->addRow(['40',  $standard[40], $actual[40]])
             ->addRow(['41',  $standard[41], $actual[41]])
             ->addRow(['42',  $standard[42], $actual[42]])
             ->addRow(['43',  $standard[43], $actual[43]])
             ->addRow(['44',  $standard[44], $actual[44]])
             ->addRow(['45',  $standard[45], $actual[45]])
             ->addRow(['46',  $standard[46], $actual[46]])
             ->addRow(['47',  $standard[47], $actual[47]])
             ->addRow(['48',  $standard[48], $actual[48]])
             ->addRow(['49',  $standard[49], $actual[49]])
             ->addRow(['50',  $standard[50], $actual[50]])
             ->addRow(['51',  $standard[51], $actual[51]])
             ->addRow(['52',  $standard[52], $actual[52]])
             ->addRow(['53',  $standard[53], $actual[53]])
             ->addRow(['54',  $standard[54], $actual[54]])
             ->addRow(['55',  $standard[55], $actual[55]])
             ->addRow(['56',  $standard[56], $actual[56]])
             ->addRow(['57',  $standard[57], $actual[57]])
             ->addRow(['58',  $standard[58], $actual[58]])
             ->addRow(['59',  $standard[59], $actual[59]])
             ->addRow(['60',  $standard[60], $actual[60]])
             ->addRow(['61',  $standard[61], $actual[61]])
             ->addRow(['62',  $standard[62], $actual[62]])
             ->addRow(['63',  $standard[63], $actual[63]])
             ->addRow(['64',  $standard[64], $actual[64]])
             ->addRow(['65',  $standard[65], $actual[65]]);

            Lava::LineChart($i.'graph'.$j, $graph[$i][$j], [
                'title' => 'Weights of '. $user_flock->name
            ]);
        $j++;
    }

    $i++;
}

And the view:

    @for ($i = 0; $i < $no_farms; $i++)
         @for ($j = 0; $j < $no_flocks; $j++)
  
                                <div id="graph_div"></div>
                                @linechart($i.'graph'.$j, 'graph_div')
                          
        @endfor    
    @endfor

**Comment by kevinkhill** [comment]
Inside of your view loop, you are creating many `div`s with the same id of `graph_div`, so every chart is overwriting itself into that `div`.

Try appending your `$i` and `$j` indices from the loops to the `div` id like so
```
@for ($i = 0; $i < $no_farms; $i++)
    @for ($j = 0; $j < $no_flocks; $j++)
        <div id="graph_div_{{ $i }}_{{ $j }}"></div>
        @linechart($i . 'graph' . $j, 'graph_div_'.$i.'_'.$j)
    @endfor    
@endfor
```

**Comment by kevinkhill** [comment]
Closing due staleness and lack of communication. Please open a new issue of you still need assistance, as I am happy to help. ☺️
