### ISSUE TITLE
How to specify colors for a PieChart

### ISSUE THREAD

**Issue by PingPongLee** [kevinkhill/lavacharts#213]
Im unsure how I'am supposed to set certain colors on certain slices of a PieChart

All the documentation says is "The colors to use for the chart elements. An array of strings, where each element is an HTML color string, for example: colors:['red','#004411']." , but how does that work? If i do the following

```
$chart = \Lava::PieChart('colorChart', $reasons, [
            'title' => 'Farvefordeling',  
            'colors' => array('green', '#00FF00'),
            'is3D'   => true,
]);  
```

It seems to just turn a random slice in that color. How do i specify what slices have what colors?

EDIT: Should point out that im using Laravel 5.4 for this

**Comment by kevinkhill** [comment]
That is a great question, but unfortunately, I don't know.

It doesn't seem that Google shows a direct way to specifically color the slices. Lavacharts is just passing the options in to the chart API, so they aren't getting processed in any way. 

I will look into this and see of it's possible, maybe with a column role...

**Comment by kevinkhill** [comment]
I'm going to go ahead and close this for now. I'll take your :+1: as a sign that you have resolved this.
