### ISSUE TITLE
How to disable console logging

### ISSUE THREAD

**Issue by jozeflambrecht** [kevinkhill/lavacharts#214]
Hi, I am using the latest version of lavacharts and I am loving it. 
Everything works fine, except that I see the log info in the console. Example: 

```
[lava.js] Initializing
Lava.js:501 [lava.js] ColumnChart::Turnover -> initializing
Lava.js:464 [lava.js] ColumnChart::Turnover -> ready
```
Any idea how I can turn this off?

**Comment by kevinkhill** [comment]
Absolutely! You can bug me until I remember to stop pushing my dev build of the lava.js module. XD

**Comment by jozeflambrecht** [comment]
maybe a suggestion for the config ;)

**Comment by kevinkhill** [comment]
[lava.js for prod, 3.1.8](https://github.com/kevinkhill/lavacharts/releases/tag/3.1.8)

**Comment by kevinkhill** [comment]
That would be a good idea, I'll add it to my todo list.
