### ISSUE TITLE
Refer to JavaScript files

### ISSUE THREAD

**Issue by jozeflambrecht** [kevinkhill/lavacharts#215]
When I look to the source code, I see that all the javascript code is embedded. Is there a way to use a <script> tag? (to reduce the lines (> 20 000!) on the source of the page where the carts is rendered)

**Comment by kevinkhill** [comment]
Yeaaa.... I'm still pretty novice at javascript, but I'm getting better! So you want to be able to do something like `<script src="./my/assets/or/whatever/lava.js">` and then just get the chart javascript output?

Side note: v3.1 of lava.js weighs 100+KB but the new and improved lavacharts v4.0 with a refactored lava.js (coming soon) weighs only  23.2 KB :smile:

**Comment by kevinkhill** [comment]
OK, so the lava.js source is available at (using composer I presume?) `vendor/khill/lavacharts/javascript/dist/lava.js` you can copy it out or do with it what you wish.

I don't remember if I included an option to suppress the `<script>` tag output of the lava.js module.

I will double check.....
`

**Comment by kevinkhill** [comment]
Ok, so I did a quick and dirty test and it seems to work, but [I added two methods which should solve your problems](https://github.com/kevinkhill/lavacharts/commit/bc7a4db784d456ed4c961a284d4c37bba5adf66c).

Somewhere before your rendering call, preferably in the controller constructor where you are using this, add:
`\Lava::getScriptManager()->bypassLavaJsOutput();` (I'm assuming Laravel?)

Now when you render your charts, you should only get their script blocks.

I don't know how you want to call it, but in my test I used `<body onLoad="window.lava.run();">` and it worked. You can call `window.lava.run();` however you like thought.

If you could give this a test by updating your composer dependency to `dev-3.1` and report back, I would appreciate it.

**Comment by kevinkhill** [comment]
Should `bypassLavaJsOutput()` be `suppressLavaJsOutput()` instead?

**Comment by kevinkhill** [comment]
Closing since this is a feature of `3.1`

**Comment by muazzamazaz** [comment]
same error

>  lava undefined
