### ISSUE TITLE
can't display data from database into charts

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [kevinkhill/lavacharts#216]
What version are you having trouble with?
3.0
Getting below error
Invalid row property, array with keys type (string) with values [ v | f | p ]

Controller Code
```
<?php 
namespace Redooor\Redminportal\App\Http\Controllers;
use Khill\Lavacharts\Lavacharts;
use Redooor\Redminportal\App\Models\User;
class HomeController extends Controller
{
    /**
     * Show the application welcome screen to the user.
     *
     * @return Response
     */
    public function home()
    {


$lava = new Lavacharts; // See note below for Laravel

$popularity = $lava->DataTable();

$user = User::select('email')->get()->toArray();
	$popularity->addStringColumn('User')
	           ->addNumberColumn('Popularity')
               ->addRow($user);
           

$lava->GeoChart('Popularity', $popularity);



        return view('redminportal::pages.home',compact('lava'));
    }
}
```
View code 👍 
```
<div id="pop-div"></div>

<?= $lava->render('GeoChart', 'Popularity', 'pop-div') ?>
```

**Comment by kevinkhill** [comment]
Is your DB query returning an array of arrays? As in multiple records? If so, try addRows() instead of addRow()

**Comment by kevinkhill** [comment]
Also, you should update to the most recent version, 3.0 is pretty old now

**Comment by kevinkhill** [comment]
Closing due staleness and lack of communication. Please open a new issue of you still need assistance, as I am happy to help. ☺️

**Comment by Francis-Njoku** [comment]
Hey @kevinkhill  I'm facing similar issue and I get the error below

`> The value for addRows must be of type (array of arrays).`

What could be the solution?

**Comment by kevinkhill** [comment]
`addRow` takes one array with a `count()` equal to the number of columns

`addRows` takes and array of arrays where each outer array item is an array, representing a row, which is an array where `count()` is equal to the number of columns

**Comment by Francis-Njoku** [comment]
@kevinkhill I figured it out yesterday, I used
`DB::table()->select()`
instead of
`User::select('email')`

Thanks

**Comment by kevinkhill** [comment]
You're welcome
