### ISSUE TITLE
Charts size issue

### ISSUE THREAD

**Issue by yasserito** [kevinkhill/lavacharts#217]
> I'm using lavachart 3.0

#### Issue
> I have an issue with the size of the charts. when they are first displayed (they have the wrong size (don't take the whole div space) but when i resize the window it takes the good width ( the whole div space).
It may be useful to know that without the jQuery collapse, i don't have this issue.
 Here's the code:

```
        <div class="panel-heading">Temperature statistics</div>
        <div class="panel-body">
          <div class="panel-group" id="accordion">
            <div class="panel panel-info">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Acounts,Bcounts</a>
                </h4>
              </div>
              <div id="collapse1" class="panel-collapse collapse">
                <div class="panel-body"><div id="XiPC1_div"><?= Lava::render('AreaChart', 'XIPC1', 'XiPC1_div') ?></div></div>
              </div>
            </div>
            <div class="panel panel-info">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">ADCsum</a>
                </h4>
              </div>
              <div id="collapse2" class="panel-collapse collapse">
                <div class="panel-body"><div id="XiPC2_div"><?= Lava::render('AreaChart', 'XIPC2', 'XiPC2_div') ?></div></div>
              </div>
            </div>
            <div class="panel panel-info">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">PWM</a>
                </h4>
              </div>
              <div id="collapse3" class="panel-collapse collapse">
                <div class="panel-body"><div id="XiPC3_div"><?= Lava::render('AreaChart', 'XIPC3', 'XiPC3_div') ?></div></div>
              </div>
            </div>
            <div class="panel panel-info">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">ADC clot baseline</a>
                </h4>
              </div>
              <div id="collapse4" class="panel-collapse collapse">
                <div class="panel-body"><div id="XiPC4_div"><?= Lava::render('AreaChart', 'XIPC4', 'XiPC4_div') ?></div></div>
              </div>
            </div>
            <div class="panel panel-warning">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapse6">Warnings</a>
                </h4>
              </div>
              <div id="collapse6" class="panel-collapse collapse">
                <div class="panel-body">
                  <div id="warning" style="height: 300px; overflow: auto;">
                    <table class="table">
                      <thead class="thead-default">
                        <tr>
                          <th>#</th>
                          <th>Date</th>
                          <th>Heure</th>
                          <th>Details</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php for($i = 0; $i<sizeof($warning)/3; $i++){ ?>
                        <tr>
                          <th scope="row"><?php echo $i+1 ;?></th>
                          <td><?php echo $warning[3*$i]?></td>
                          <td><?php echo $warning[3*$i+1]?></td>
                          <td><?php echo $warning[3*$i+2]?></td>
                        </tr>
                        <?php }?>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

```

**Comment by kevinkhill** [comment]
First off, I would recommend updating to 3.1
Second, I have realized during development that the `render` method is a little misleading. It actually outputs the `<script>` tags, not the chart display or anything. I would move the whole line `<?= Lava::render('AreaChart', 'XIPC1', 'XiPC1_div') ?>` to the end of your view and leave the `<div>` empty 
Lastly, try passing `['width'=>'100%']` as part of the options when creating the chart.

**Comment by yasserito** [comment]
I updated lavachart to 3.1 and left the `<div>` empty, i also tried to pass` 'width'=>'100%` in options, the only thing that have worked for me so far, is passing a fixed width which is not what i want.
When i minimize the size of the window then put it pack to full size , the redraw of the chart works with the right width :/ .
Here's an[ image](http://www.hostingpics.net/viewer.php?id=887041lol.png) of the issue:

**Comment by kevinkhill** [comment]
does the container div start with a maximum width before render?

**Comment by yasserito** [comment]
Yes the container where the Chart is rendered starts with maximum width.

**Comment by poepoedarli** [comment]
I show my data by ajax call. Data show correctly, my problem is I don't know how to set my chart formats dynamically. From controller, how can i return formats to view? Please.

**Comment by poepoedarli** [comment]
1. Firstly I showed all data on chart, so my chart size is big and with scroll bar. 
2. When user click filter conditions, i do ajax call and show filtered data on chart.
3. At this time, my data is less and chart size is big. 
How can i resize chart according to data?

**Comment by kevinkhill** [comment]
After you load the data, call `redraw()` on the chart. 

[chart.js src](https://github.com/kevinkhill/lavacharts/blob/3.1/javascript/src/lava/Chart.js#L125)

**Comment by poepoedarli** [comment]
I did as shown in attached picture.
![capture](https://user-images.githubusercontent.com/8011788/30091978-dd9b2272-92ee-11e7-9912-e3bc2463df04.PNG)

**Comment by kevinkhill** [comment]
Is this working for you?

**Comment by poepoedarli** [comment]
Not work, bro. :-)

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
