### ISSUE TITLE
Increase bar width and Height

### ISSUE THREAD

**Issue by dhinesh-K** [kevinkhill/lavacharts#221]
#### What Version?
My laravel version 5.3

#### Issue
we installed lava charts in my project. Charts is working fine.
But i need increase bar density.
i tried many times.
i can't find exact solution. plz help me how to fix this one.

#### Controller Code (chart creation code)
 Lava::BarChart('Votes',$votes);

#### View Code

	{!! Lava::render('BarChart', 'Votes', 'poll_div') !!} 
	<div id="perf_div" class="bar-chart" style="display:none"></div>

**Comment by kevinkhill** [comment]
Have you tried looking through [some of the options] (https://developers.google.com/chart/interactive/docs/gallery/barchart#bar-styles) Google offers for customizing?

**Comment by kevinkhill** [comment]
I am closing this issue due to lack of communication. (+90 days) Please feel free to open another issue if you are having trouble or need assistance. I am happy to help :smile:
