### ISSUE TITLE
Local copy of Charting Lib

### ISSUE THREAD

**Issue by V1TA5** [kevinkhill/lavacharts#222]
Is there a way to have all files localy (e.g. for Intranets)?
(I dont know if google even offers their charting lib for download).

**Comment by kevinkhill** [comment]
Sadly, they do not. I don't remember exactly where in Google's docs I remember seeing it, but they state that you can't download the library for offline use.

Sorry!

**Comment by kevinkhill** [comment]
![image](https://user-images.githubusercontent.com/266076/30241763-bce01ed2-953e-11e7-8b04-c8a2990a300a.png)

[Located here](https://developers.google.com/chart/interactive/faq)
