### ISSUE TITLE
Google chart date axis when only 1 day messed up

### ISSUE THREAD

**Issue by kjdion84** [kevinkhill/lavacharts#224]
I'm using lavacharts in order to display some stats broken down by day. My problem is that if there is only 1 day worth of data, the date axis gets completely messed up and shows a bunch of years.

Example when there is only 1 day worth of data:

$chart.setData({"cols":[{"type":"date","label":"Date"},{"type":"number","label":"Leads"},{"type":"number","label":"Assignments"},{"type":"number","label":"Returns"}],"rows":[{"c":[{"v":new Date(2017,9,6,0,0,0)},{"v":18},{"v":18},{"v":1}]}]});

![Imgur](https://i.imgur.com/SB2Cfc2.png)

As you can see, the date axis is screwed up.

Example when there is more than 1 day worth of data:

$chart.setData({"cols":[{"type":"date","label":"Date"},{"type":"number","label":"Leads"},{"type":"number","label":"Assignments"},{"type":"number","label":"Returns"}],"rows":[{"c":[{"v":new Date(2017,9,4,0,0,0)},{"v":1},{"v":0},{"v":0}]},{"c":[{"v":new Date(2017,9,6,0,0,0)},{"v":18},{"v":18},{"v":1}]}]});

![Imgur](https://i.imgur.com/Oz8HktE.png)

See the date axis is fine here.

Why is this happening and how do I fix it?

**Comment by kevinkhill** [comment]
This appears to be more of an issue with how Google handles the chart's X axis when only one date is present. I would look into [Some of the options for hAxis](https://developers.google.com/chart/interactive/docs/gallery/columnchart#configuration-options) that Google offers and see if you can force the horizontal axis to render how you want, instead of automatically.

**Comment by kjdion84** [comment]
I see that I can use a filter, but I have no idea how to implement it:

```
$dateRange = $lava->DateRangeFilter(int|'string', [
    'minValue' => int|float,
    'maxValue' => int|float,
    'format'   => 'string'
]);
```

How would I set this filter for the `Date` column:

```
        $counts = LeadHistory::select(
            DB::raw('date_format(created_at, "%Y-%m-%d") as date'),
            DB::raw('count(distinct(lead_id)) as leads'),
            DB::raw('(select count(*) from assignments where date_format(created_at, "%Y-%m-%d") = date and returned_at is null) as assignments'),
            DB::raw('(select count(*) from assignments where date_format(returned_at, "%Y-%m-%d") = date and returned_at is not null) as returns'))
            ->whereRaw(date_range('dashboard_', 'created_at'))
            ->groupBy('date');
        $counts_table = $lava->DataTable();
        $counts_table->addDateColumn('Date')->addNumberColumn('Leads')->addNumberColumn('Assignments')->addNumberColumn('Returns');
        foreach ($counts->get() as $count) $counts_table->addRow([$count->date, $count->leads, $count->assignments, $count->returns]);
        $lava->ColumnChart('CountsChart', $counts_table, ['title' => 'Leads, Assignments, & Returns', 'colors' => $colors]);
```

**Comment by kevinkhill** [comment]
The `DateRangeFilter` is actually to be used with Dashboards. (Dashboards are charts with filterable values and features)

**Comment by kjdion84** [comment]
So how do I add minValue to my existing datatable code so I can fix the issue in OP?

**Comment by kevinkhill** [comment]
I am putting together a test to see if I can get the desired output for you. If you are looking for applying `hAxis.minValue` from Google's config options, just add it to your options array as:
```
[
    'title' => 'Leads, Assignments, & Returns',
    'colors' => $colors,
    'hAxis' => [
        'minValue' => 'min-value-goes-here'
    ]
]
```

**Comment by kevinkhill** [comment]
So it's a little convoluted, because I didn't think to cover this edge case (I will have to make this easier on the user)

Since the X (hAxis) is made up of date (internally the php class `DateCell`) to use the option values, Google is expecting date objects.

You will have to do something along these lines: `(string) DateCell::parseString('2017', 'Y')` for the values of those options.

**Comment by kjdion84** [comment]
Now I get `Must be a Carbon instance or a datetime string able to be parsed by Carbon.`.

Code:

        foreach ($counts->get() as $count) {
            \Log::info($count->date);
            \Log::info(DateCell::parseString($count->date));
            $counts_table->addRow([
                DateCell::parseString($count->date), $count->leads, $count->assignments, $count->returns
            ]);
        }

Log:

[2017-10-07 22:48:17] local.INFO: 2017-10-07  
[2017-10-07 22:48:17] local.INFO: Date(2017,9,7,0,0,0)

**Comment by kjdion84** [comment]
I just said fuck it and changed it to `addStringColumn('Date')`. It doesn't include empty dates in the range but whatever....

**Comment by kevinkhill** [comment]
I'm sorry, I had to leave earlier. You don't have to wrap the dates while adding them to the rows. What I meant was if you want to use the options like:
```
[
    'hAxis' => [
        'minValue' => (string) DateCell::parseString('2017', 'Y')
    ]
]
```
You would have to do that. The string dates, when added through `addRow` they are automatically parsed into `DateCell`s

I am glad you were able to get it to work as needed?

**Comment by kjdion84** [comment]
Yeah it works when using it as a string rather than a date column. Thanks for the help.

The only issue is that if a certain date has no results it doesn't show the date on the hAxis. Though that isn't a huge issue.

**Comment by kevinkhill** [comment]
Yeah, I noticed in my tests that sometimes the date would vanish from under the chart.

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
