### ISSUE TITLE
Fatal error: Trait 'Khill\Lavacharts\Support\Traits\HasOptionsTrait' not found

### ISSUE THREAD

**Issue by robweighill** [kevinkhill/lavacharts#227]
#### What Version?
Tried both 3.1.9 and 4.0 - same issue

#### Issue
Installed library using the 'Manual' method from your website, but get and error when requiring Lavacharts.php:

>Fatal error: Trait 'Khill\Lavacharts\Support\Traits\HasOptionsTrait' not found

This is running on php7.0.
I would rather not run Composer and from your website it seemed that it would be possible to use your library without it.

Any help appreciated!

**Comment by kevinkhill** [comment]
It is supposed to be able to work without composer. I will have to take a look

**Comment by robweighill** [comment]
That's great, thank you. 
If you need any more info, please let me know.

**Comment by kevinkhill** [comment]
That should do the trick. Thank you for the issue report

**Comment by robweighill** [comment]
Perfect, thank you for the quick fix!
