### ISSUE TITLE
Lavacharts offline?

### ISSUE THREAD

**Issue by scorlink** [kevinkhill/lavacharts#228]
Hello, 
Thanks for this great package.
I have just one question without any code: can I use Lavacharts without internet connection? 
I use it in an internal laravel application where users are in an intranet network and they don't have internet.
Thanks in advance.

**Comment by kevinkhill** [comment]
I'm sorry, but no, and I can't fix it either. The way it works is that my library outputs all the necessary info for Google to load. Google's script sees what charts need to be loaded and makes its own extra calls, loading more scripts before the final output is rendered.

Unless you were to able to download all the scripts you knew you would need, and modify Google's scripts to use the local copies and not fetch them....

¯\_(ツ)_/¯

**Comment by scorlink** [comment]
Hi Kevin,

Thanks for your quick replay. I already tried to download all scripts and modify the package's scripts to point to it. Unfortunately, it does not work.

any way, I would be sure I don't miss something. so I will find another track.

thank you again ;-)
