### ISSUE TITLE
can i install lavacharts without composer installed??

### ISSUE THREAD

**Issue by pakistanihaider** [kevinkhill/lavacharts#23]
Is It possible i install lavachart without installing composer???

**Comment by kevinkhill** [comment]
First, I would highly recommend composer. It's one little file and it really simplifies php dependencies.. 

Second, no, not yet. I unintentionally made Lavacharts composer dependant. I'm working on using the Symfony autoloader to enable a composer-less install.

**Comment by kevinkhill** [comment]
If you could be so kind to test out the most recent version, I added an autoloader to the project, and it should now work without composer.

**Comment by kevinkhill** [comment]
Please see Issue #24

**Comment by kevinkhill** [comment]
If you want to pull and test against the 2.4 branch, I have included a Psr4 Autoloader so you do not have to use composer (even though it is a great tool)
The only thing you need to do is also include the [Carbon](https://github.com/briannesbitt/Carbon) before Lavacharts.

Here is an example:
```
<?php
  require_once('Carbon-1.18.0/src/Carbon/Carbon.php');
  require_once('lavacharts-2.4/src/Lavacharts.php');

  use \Carbon\Carbon;
  use \Khill\Lavacharts\Lavacharts;

  $lava = new Lavacharts;

  $dt = $lava->DataTable();

  $dt->addDateColumn('dates');
  $dt->addNumberColumn('numbers');

  for ($a=1; $a <= 30; $a++) {
    $dt->addRow([Carbon::parse($a.'-1-2015'), rand(100,200)]);
  }

  $lava->LineChart('Stuff')
       ->dataTable($dt);
?>
 
<doctype html>
<html>
  <head>
    <title>No Composer</title>
  </head>
  <body>
    <div id="chart"></div>
 
    <?php echo $lava->render('LineChart', 'Stuff', 'chart'); ?>
  </body>
</html>
```
