### ISSUE TITLE
How do I disable mousewheel contextual zooming?

### ISSUE THREAD

**Issue by CaseyDStein** [kevinkhill/lavacharts#232]
#### What Version?
> 3.1.9

#### Issue
> If I use my mousewheel while the mouse cursor is over the rendered chart, the chart contextually zooms in or out and will show a larger or smaller date range.  I would like to disable this functionality.  Your web page doesn't show any options for controlling this.

I would appreciate any help you could provide on this.

Thanks,
Casey

**Comment by kevinkhill** [comment]
What kind of chart? Do you know if Google offers this feature to be disabled?

If Google allows it to be disabled, I can probably help you with the Lavacharts code.

**Comment by kevinkhill** [comment]
Closing due to lack of communication. Please open a new issue if you are still having trouble.
