### ISSUE TITLE
Pie chart google options not yet implemented

### ISSUE THREAD

**Issue by DaveMG3** [kevinkhill/lavacharts#236]
#### What Version?
> `composer show khill/lavacharts` 
Version 3.0.8

#### Issue
Hi Kevin thanks for this amazing implementation of google chart API 👍 
I am looking to customize our lavacharts and i have seen Google charts have within its option :

> legend.position | Position of the legend. Can be one of the following:    ...     'labeled' - Draws lines connecting slices to their data values.

 Something as the picture below :
It is not implemented on lavacharts so
could you let us know if you plan to add it in the future or provide us some guidelines to fork your code adding such options for charts?
It would really help
thks
#question #enhancement

![piechart](https://user-images.githubusercontent.com/32598581/36092920-5a5cd824-0fe9-11e8-938f-1d96eabc401b.png)

**Comment by kevinkhill** [comment]
Thank you for the compliement :smile: 

First off, I would recomend you to update to the most recent version, just to make sure you aren't encountering bugs I've already squashed.

Second, Lavacharts should support any option that Google offers since internally, the options array is just `json_encode`d into the javascript definition.

So for your example, you would change the dot notation into this:

```
Lava::PieChart('Test Results', [ 'legend' => [ 'position' => 'labeled' ]])
```

**Comment by kevinkhill** [comment]
Did this work for you? Can we close the issue?

**Comment by DaveMG3** [comment]
Hola Kevin,
Funny ,just read your messages this morning back to work after 3w. I have seen indeed your library has more than what is described on the Lavachart website (for example, we can find Candle chart which is nice). So people should be careful of digging in the library to find all the functionalities described in Google chart.
Currently the option 'legend' is not working out on my PieChart but i am trying to figure out my setting and will post the feedback soon...thanks for the follow up...

**Comment by kevinkhill** [comment]
I haven't updated the docs in a while. I've just been too busy
