### ISSUE TITLE
Error with TimeZone

### ISSUE THREAD

**Issue by assismoraes** [kevinkhill/lavacharts#238]
#### What Version?
> 3.1.9

#### Issue
> Hi! Timezone 'America/Fortaleza' works for other Carbon utilities on my application. But it does not work when i try to generate my LineChart. Obs.: I defined my TimeZone in my .env file and use it in my config/app.php file. Need help here. =D

#### Controller Code (chart creation code)
```
public function home()
    {
        $visitas = \Lava::DataTable();
        $visitas->addDateColumn('Data')->addNumberColumn('Visitas');
        $titulo = 'De ' . Carbon::today()->startOfMonth()->format('d-m-Y') . ' à ' . Carbon::today()->format('d-m-Y');
        \Lava::LineChart('Visitas', $visitas, ['title' => $titulo]);
        for ($i = 0; $i < Carbon::today()->day; $i++)        {
            $dia = Carbon::today()->startOfMonth()->addDay($i);
            $visitas->addRow([$dia->toIso8601String(),  Visita::quantidadePorDia($dia)]);
        }

        return view('admin.index');
    }
```

#### View Code
```
<div class="card">
    <div class="card-header" >
        Visitas deste mês
    </div>
    <div class="card-body">
        <div id="visitas" ></div>
        @linechart('Visitas', 'visitas')
    </div>
</div>
```
![400x300_eo9y65ph2lxhupmp1jzi](https://user-images.githubusercontent.com/13661678/37864431-69dfebaa-2f4d-11e8-88ab-5ea67b2f95f5.png)

**Comment by kevinkhill** [comment]
Hmmm, so as you can [see here](https://github.com/kevinkhill/lavacharts/blob/f76ec3882a425e3b260d5071eea25ee3b299466b/src/DataTables/DataTable.php#L760) I use `timezone_abbreviations_list()` to create a list to check against. I'm not sure what that timezone is, but if it is indeed valid, then I'm not sure why it's not included in the output of the php std function...

**Comment by assismoraes** [comment]
I got it! I realized it happens only when i deploy locally. Thank you! o/

**Comment by kevinkhill** [comment]
No worries, happy you help. I guess a try / catch block will be your new friend, haha
