### ISSUE TITLE
Unnecessary warnings in src\Configs\DataTable.php on lines 245, 260 and 275

### ISSUE THREAD

**Issue by hugovoerman** [kevinkhill/lavacharts#239]
#### What Version?
> Run `composer show khill/lavacharts` if you don't know
composer show khill/lavacharts
name     : khill/lavacharts
descrip. : PHP wrapper library for the Google Chart API
keywords : charts, google, graphs
versions : * 2.5.x-dev
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/kevinkhill/lavacharts.git 9acd4b792606f5c16aa698808ea1e3312ad7abc2
dist     : [zip] https://api.github.com/repos/kevinkhill/lavacharts/zipball/9acd4b792606f5c16aa698808ea1e3312ad7abc2 9acd4b792606f5c16aa698808ea1e3312ad7abc2
names    : khill/lavacharts

autoload
psr-4
Khill\Lavacharts\ => src/

requires
nesbot/carbon ~1.14
php >=5.3.0

requires (dev)
mockery/mockery ~0.9
mybuilder/phpunit-accelerator ~1.1
phpunit/phpunit ~4.5
sami/sami ~2.0
satooshi/php-coveralls ~0.6
squizlabs/php_codesniffer ~2.0

#### Issue
Unnecessary warning

> Please describe the issue. 
Using php 7.1

I had to add a typecast to string like:
        return $this->addColumn('string', $optLabel, 'col_' . (string)(count($this->cols) + 1), $formatter);
in file DataTable.php on row 245, and similar on rows 260 and 275 to get rid of a nasty warning

Warning: A non-numeric value encountered in D:\home\site\vendor\khill\lavacharts\src\Configs\DataTable.php on line 275

In my opinion the code should be warning free at all times.

Perhaps you can do something with this finding..

Kind regards,
Hugo

#### Controller Code (chart creation code)
```
see above
```

#### View Code
```
see above
```

**Comment by kevinkhill** [comment]
Do I see there you are using version 2.5? That's so old! You should update to the latest version 👍🏻

**Comment by hugovoerman** [comment]
Hi Kevin,

Yes, it’s an ‘old’ system (site) and I upgraded PHP to 7.1 and ran into this ‘warning’. I will upgrade to the latest version using the upgrade notes on your site within the next months when time allows.

Thanks for the reply,

Hugo

**Comment by kevinkhill** [comment]
If you would like to submit a pull request to fix the warnings, I will happily accept it. But I no longer support that branch so I won't make any proactive updates.
