### ISSUE TITLE
Composer Update / Install error

### ISSUE THREAD

**Issue by JFOC** [kevinkhill/lavacharts#240]
#### What Version?
> 3.1.9

#### Issue
> During the update for first-time installation got an error:
In MySqlConnector.php line 119:

  Object of class O2System\Kernel\Containers\Environment could not be convert
  ed to string

#### Controller Code (chart creation code)
```
// paste over this
```

#### View Code
```
// paste over this
```

**Comment by kevinkhill** [comment]
I'm sorry, but are you sure this error is not from something else? Lavacharts does not have a `MySqlConnector.php`
