### ISSUE TITLE
a.getTime is not a function (when try to set hAxis min and max)

### ISSUE THREAD

**Issue by despotbg** [kevinkhill/lavacharts#243]
#### What Version?
3.1.9

#### Issue
I get error "a.getTime is not a function", when I try to set chart hAxis _min_ and _max_. I tried a lot of different datetime format (unix timestamp, full datetime in different shapes, created datetime with Carbon::create() , 'new Date('2018-05-23')')  but no luck...
Also I want to thank you and to say that you done **fantastic work here**.
#### Controller Code (chart creation code)
```
        Lava::ColumnChart('houses', $blocksChart, [
            'vAxes' => [
                [
                    'title' => 'First',
                    'titleTextStyle' => ['color' => '#3366CC'],
                    'textStyle' => ['color' => '#3366CC']
                ],
                [
                    'title' => 'Second',
                    'titleTextStyle' => ['color' => '#DC3912'],
                    'textStyle' => ['color' => '#DC3912']
                ]
            ],
            'series' => [['targetAxisIndex' => 0], ['targetAxisIndex' => 1]],
            'focusTarget' => 'category',
            'tooltip' => ['isHtml' => true],

            'hAxis' => [
//                'viewWindowMode' => 'pretty',
                'viewWindowMode' => 'explicit',
                'viewWindow' => [
                    'min' => '2018-05-23',
                    'max' => '2018-05-24'
                ]
            ],
        ]);
```

**Comment by kevinkhill** [comment]
I think a similar issue was raised about this or this exactly... I found out that Google expects the dates to be Javascript dates but my internal code treated the hAxis dates as strings.

**Comment by catnumberOne** [comment]
Hello, Kevin! Here https://github.com/kevinkhill/lavacharts/issues/230 I thought you solved this issue, but after I update extension version to 3.1 and 3.2 I found not Date class in Support folder. I found this class in dates branch of this repository only. Can you check it please? Thanks for great work!

**Comment by kevinkhill** [comment]
I would love to help debug this, but I haven't even opened my laptop in months. Life has been crazy

**Comment by kevinkhill** [comment]
I have been just trying to triage issues from my phone when I can

**Comment by catnumberOne** [comment]
Ok, Kevin, Thanks! If you could, help me please. I think, that to create new version of extension with Date class on Gitub is enough.

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
