### ISSUE TITLE
There no usual event when hover/click on last legend item

### ISSUE THREAD

**Issue by despotbg** [kevinkhill/lavacharts#244]
#### What Version?
3.1.9

#### Issue
When I try to hover/click last legend item nothing happen. Usually lines become bold/double-lines, but when done that on last legend item nothing happen. And always last don't work.

So if I hover/click on **sunny** (like this click event on picture) I get expected event. But if I done same for **teus** nothing happen

![screenshot from 2018-05-25 21-27-42](https://user-images.githubusercontent.com/3776319/40562802-c07a13f0-6062-11e8-9fc6-f6263f58f698.png)

Same thing with pie chart. Here click on **180 days** done nothing, while click on **90 days** give this:

![screenshot from 2018-05-25 21-47-20](https://user-images.githubusercontent.com/3776319/40563536-65b3286e-6065-11e8-9eee-83f25385e817.png)

This is maybe google chart issue ?

**Comment by despotbg** [comment]
Problem update:
There is one exception for this. If I have too many labels so I get "pagination" arrows, last item click will work as it should 
 
![1](https://user-images.githubusercontent.com/3776319/41620162-296e1212-7409-11e8-8e61-23c80275e602.png)

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
