### ISSUE TITLE
Chart color and label color

### ISSUE THREAD

**Issue by davemg3** [kevinkhill/lavacharts#248]
Hello Kevin,

For pie chart, how to change the color of slices and also color of text in the labels or annotation? Also on mobil, charts are resized but not enough so labels are replaced by '...'. Any method to circumvent this?

I have seen the following issue but it doesnt solve mine:
https://github.com/kevinkhill/lavacharts/issues/138
Using '->addRoleColumn('string', 'style')' just stop my graph from loading with a 
```

$data = \Lava::DataTable();
        $data->addStringColumn('X')
            ->addNumberColumn('Y')
            ->addRoleColumn('string', 'style');

        foreach ($itemsas $item) {
       $data->addRow([$item->label, (double)$item->data],'color:red');
}
...

```

![image](https://user-images.githubusercontent.com/32598581/41238776-0ea91544-6d97-11e8-908b-0bfd8f5625ce.png)

**Comment by DaveMG3** [comment]
Ok  for Pie Chat I understood we need to insert color there : 
```
     r \Lava::PieChart('PCC', $data, [
            'title' => 'Title',
            'colors'=> ['#e0440e', '#e6693e', '#ec8f6e', '#f3b49f', '#f6c7b6'],
            'is3D' => true,
            'height' => 300,
            'legend' => ['position' => 'labeled']
         ]);
```

**Comment by h4rris** [comment]
how do you set those labels around the chart please?

**Comment by kevinkhill** [comment]
[They are generated by the DataTable](http://lavacharts.com/#example-pie)

**Comment by h4rris** [comment]
I did it by using :
`'legend' => [ 'position' => 'labeled']` 
thanks for the anwering ;)

**Comment by IssacHD** [comment]
I'm using this options, too
['legend' => ['position' => 'labeled']]

And using @davemg3 graphic example, how can I change the grey color of percentage values?

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
