### ISSUE TITLE
Js issue

### ISSUE THREAD

**Issue by mPaleo** [kevinkhill/lavacharts#25]
Hi, i'm getting "ReferenceError: google is not defined" in chrome dev tools, my code is the one of the donut example (exactly the same), extra: the blade view code is inside a ng-view that loads dynamic
http://lavacharts.com/#example-donut

**Comment by kevinkhill** [comment]
I've never worked with angular before, so I'm not sure what the issue would be.

My assumption:
The render method or the blade @ syntax inserts all the Javascript, including the Google Chart API, so it's possible that angular is running it's view Javascript first, before the html and Lava Javascript is ran?

**Comment by mPaleo** [comment]
@kevinkhill google chart script must be outside the ng-view, i think it would be useful to have a blade extension like @lavaRenderGoogleScript to print google chart script, or leave the script import responsibility to developers

**Comment by kevinkhill** [comment]
So what you're saying is that having the library generate the Google JSAPI script tag along with the rendering Javascript is the issue? And to fix it, that script tag needs to be outside of the "ng-view"?

**Comment by mPaleo** [comment]
@kevinkhill  In my case that I am using angular, yes. For some reason, if the script is within the ng-view,  is not parsed. I have another project with the same error, it uses Highcharts, and the solution was to remove the Highchart script from the ng-view

**Comment by kevinkhill** [comment]
I will add this to my list of todos, and address it as soon as I can. Thank
you for your help in figuring out the problem.

**Comment by mPaleo** [comment]
Thanks :)

**Comment by kevinkhill** [comment]
This issue should be resolved in version 2.3

You can use the new method jsapi() to drop the google jsapi script tag (along with some core lavachart js) in the head or outside of your ng-view.

The lava object, will track that the jsapi was output manually and the render methods will not add it again. Hopefully this helps :+1:

**Comment by mPaleo** [comment]
@kevinkhill Thanks a lot !
