### ISSUE TITLE
Chart is invisible in view (but upon inspecting the elements, it's there)

### ISSUE THREAD

**Issue by ruby-ann-y-matias** [kevinkhill/lavacharts#250]
#### What Version?
> Run `composer show khill/lavacharts` if you don't know
3.0.8

#### Issue
> Please describe the issue. 
I can see the table for my chart already upon inspecting the elements on my page but either the chart is transparent or I'm missing something. Please help, thanks!

#### Controller Code (chart creation code)

        $wagePerJob = Lava::DataTable();
        $wagePerJob->addStringColumn('Job')
                ->addNumberColumn('Wage');

        $payouts = Payout::all();
        // dd($payout);
        foreach ($payouts as $payout) {
            $wagePerJob->addRow([
                $payout->job->job,
                $payout->wage
            ]);
        }
        // dd($wagePerJob);

        Lava::DonutChart('JobDonut', $wagePerJob, [
            'title' => 'Wage Distribution per Job'
        ]);

        return view('home');

#### View Code

![screen shot 2018-06-17 at 11 32 27 pm](https://user-images.githubusercontent.com/38877089/41509475-e15e592e-7286-11e8-8ba1-d756da2d080a.png)

![screen shot 2018-06-17 at 11 26 14 pm](https://user-images.githubusercontent.com/38877089/41509426-fee5b7ae-7285-11e8-901c-52c10a95ed6d.png)

**Comment by ruby-ann-y-matias** [comment]
View Code is this: 

<div id="jobDonutDiv"></div>
<?= Lava::render('DonutChart', 'JobDonut', 'jobDonutDiv') ?>

**Comment by kevinkhill** [comment]
Can you please first try updating to the latest version? Use `^3.1` in your composer file and update.

**Comment by ruby-ann-y-matias** [comment]
Hello, I did that just now. Still the same, unfortunately.
Keeps saying "Can't find variable: lava" in the script. 
The only thing I can think of is I didn't require Carbon. Is that something I have to do first?

![screen shot 2018-06-18 at 12 13 59 am](https://user-images.githubusercontent.com/38877089/41509845-c4fa5016-728c-11e8-87d0-fa9a0b5bf7cc.png)

**Comment by kevinkhill** [comment]
can you verify that the `render` call is outputting 2 `script` tags to the page?

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
