### ISSUE TITLE
Refresh Lavachart in Javascript to resize the chart

### ISSUE THREAD

**Issue by DaveMG3** [kevinkhill/lavacharts#251]
Hello Kevin,

#### Issue
I  encounted the SO , discussed issue(on which you intervened in 2014),  on having Lavachart in a 2nd tab which doesnt render at the proper size.
 https://stackoverflow.com/questions/34972183/lavacharts-doesnt-display-chart-size-properly-using-tab-first-tab-is-ok-seco
What i am doing so is
```
 $(document).ready(function(){                    
          $('#markets-tab').click(function(e){
              e.preventDefault();
              drawChart(data);//TODO use a method to refresh chart without preferably reloading data
          });
```

But i cannot find any method in library which could help to start a redraw of chart.
Is there something about that?

**Comment by kevinkhill** [comment]
[What about `lava.redrawCharts()`?](https://github.com/kevinkhill/lavacharts/blob/3.1/javascript/src/lava/Lava.js#L276-L290)

**Comment by DaveMG3** [comment]
Thanks for feedback.
 Lava.redrawCharts() doesnt work  as i can see it redraws the chart but dont do a resizing.
However based on following issue https://github.com/kevinkhill/lavacharts/issues/106, i implemented below which is working.

  ```
 $('#charts-tab').click(clickCoin(coin_id));

          function clickCoin(coin_id) {
              return function(e) {
                  e.preventDefault();
                  $.getJSON('/coin/charts/'+coin_id, function (dataTableJson) {
                      lava.loadData('ComboCh', dataTableJson, function (data) {
                      });
                  })
              };
          }
```

**Comment by DaveMG3** [comment]
@kevinkhill ,
My only deception is that the graph doesnt adapt itself to the range of its data

![image](https://user-images.githubusercontent.com/32598581/41612820-4874f276-73f4-11e8-8af0-c98a5354843f.png)

**Comment by kevinkhill** [comment]
I do believe you need to load some initial data, so that the chart gets drawn to the correct range, and then load the data to get it to update.

**Comment by DaveMG3** [comment]
Yep. The same data I provide at initialisation in my page controller are the one i provide again through Json by Javascript for refresh. But i will investigate in details...
