### ISSUE TITLE
Is it possible to implement NumberFormat PositiveColor property in Lavachart?

### ISSUE THREAD

**Issue by davemg3** [kevinkhill/lavacharts#253]
Google chart have following properties defined but not Lavachart
NumberFormat  colorPositive
ArrowFormat
They are quite useful, is it possible to implement them?
https://github.com/kevinkhill/lavacharts/issues/145
https://developers.google.com/chart/interactive/docs/reference#dateformatter

**Comment by despotbg** [comment]
Try something like this 
```
use Khill\Lavacharts\DataTables\Formats\DateFormat;
class SomeClass{
.
.
$dateFormat = new DateFormat();
$dateFormat->pattern('MMM d, h a');
$chart->addDateColumn('Date', $dateFormat);
```

**Comment by DaveMG3** [comment]
Thanks @despotbg...but i am not looking for formating the dateFormat..i want to color positive number in green and negative in red as in google docs...

**Comment by despotbg** [comment]
@DaveMG3 sorry for misreading

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
