### ISSUE TITLE
Line chart points

### ISSUE THREAD

**Issue by Programmingisfun93** [kevinkhill/lavacharts#254]
#### What Version?
> Run `composer show khill/lavacharts` if you don't know

3.0.8
#### Issue
> Please describe the issue. 

Hi is it possible to display the points being used for the line chart?

#### Controller Code (chart creation code)
```
// paste over this
```

#### View Code
```
// paste over this
```

**Comment by kevinkhill** [comment]
If [Google's chart customization options](https://developers.google.com/chart/interactive/docs/gallery/linechart#configuration-options) allow it, then yes.

**Comment by Programmingisfun93** [comment]
Yes thanks for the link
The solution is   'pointSize' => 5

**Comment by kevinkhill** [comment]
Happy to help 👍🏻
