### ISSUE TITLE
Rendering with blade helper just shows the code

### ISSUE THREAD

**Issue by reviart** [kevinkhill/lavacharts#255]
#### What Version?
> 3.0.*

#### Issue
> How to render? i always get the real code with blade view

#### Controller Code (chart creation code)
```
public function lava(){
        $lava = new Lavacharts;
        $population = $lava->DataTable();
        $population->addDateColumn('Year')
                   ->addNumberColumn('Number of People')
                   ->addRow(['2006', 623452])
                   ->addRow(['2007', 685034])
                   ->addRow(['2008', 716845])
                   ->addRow(['2009', 757254])
                   ->addRow(['2010', 778034])
                   ->addRow(['2011', 792353])
                   ->addRow(['2012', 839657])
                   ->addRow(['2013', 842367])
                   ->addRow(['2014', 873490]);

        $lava->AreaChart('Population', $population, [
            'title' => 'Population Growth',
            'legend' => [
                'position' => 'in'
            ]
        ]);        
        return view('chart', ['varb' => $lava]);
    }
```

#### View Code
```
<div id="pop_div"></div>
@areachart('lava', 'pop_div')
```

**Comment by kevinkhill** [comment]
First things first, you should update to the latest version of the library (`~3.1`) to get the latest features and bugfixes.

Second, it appears you are using Laravel, so you do not need to create your own instance of the library. **[1]** (No need to `$lava = new Lavacharts`) You should use the instance of the library stored within the ServiceProvider and make calls to it with the registered `Lava` alias. **[2,3]**

Using the `@areachart()` blade helper relies on the library instance stored within the container. By creating your own instance, and using `$lava->AreaChart` the helper has no knowledge of your chart. Your chart is stored in your `$lava` instance. Also, on top of that, I see you titled your chart `Population` but then tried to render a chart titled `lava` in your `@areachart` helper.

Lastly, you do not need to pass anything to the view **[4]**, everything is stored within the service provider's instance of the library, so just use the blade helpers, `Lava::render(<chart_type>, <chart_title>, <div_id>)` or `Lava::renderAll()` (added in 3.1)

So, to put it all together, try this instead:

#### Controller Code
```php
public function lava(){
//1       $lava = new Lavacharts;
//2       $population = $lava->DataTable();
        $population = \Lava::DataTable();
        $population->addDateColumn('Year')
                   ->addNumberColumn('Number of People')
                   ->addRow(['2006', 623452])
                   ->addRow(['2007', 685034])
                   ->addRow(['2008', 716845])
                   ->addRow(['2009', 757254])
                   ->addRow(['2010', 778034])
                   ->addRow(['2011', 792353])
                   ->addRow(['2012', 839657])
                   ->addRow(['2013', 842367])
                   ->addRow(['2014', 873490]);

//3       $lava->AreaChart('Population', $population, [
        \Lava::AreaChart('Population', $population, [
            'title' => 'Population Growth',
            'legend' => [
                'position' => 'in'
            ]
        ]);        
//4        return view('chart', ['varb' => $lava]);
        return view('chart');
    }
```
#### View Code
```html
<div id="pop_div"></div>
@areachart('Population', 'pop_div')
```

**Comment by reviart** [comment]
Thank you sir!, i always using 3.1 version, and that's awesome!.

And i want to **ask**, how to styling at individual point (scatter chart)?
on js : 
`
var data = google.visualization.arrayToDataTable
            ([['X', 'Y', {'type': 'string', 'role': 'style'}],
              [5, 4, null],
              [6, 3, 'point { size: 18; shape-type: star; fill-color: #a52714; }'],
              [7, 2.5, null]
        ]);
`     

on lava datatable : 
`
$datatable = \Lava::DataTable();
        $datatable
                ->addNumberColumn('Y')
                ->addNumberColumn('AMPASSS')
                ->addStringColumn(['type'=> 'string', 'role'=> 'style'])
                ;
         $datatable->addRow([rand(10,25), rand(10,25), ??]);
`

**Comment by kevinkhill** [comment]
You might find [this method](https://github.com/kevinkhill/lavacharts/blob/1e4d056519a933e2406699d956b2bd8a27150955/src/DataTables/DataTable.php#L368) useful and [some information on what roles can be](https://developers.google.com/chart/interactive/docs/roles)  

(I think you might want a style column)

**Comment by reviart** [comment]
Not just a column, row style to. I want to styling the row like this [Customizing individual points](https://developers.google.com/chart/interactive/docs/points#customizing-individual-points)

Is this true?
`
$datatable->addRoleColumn('string', 'style');
`
`
$datatable->addRow([rand(10,25), rand(10,25), null]);
$datatable->addRow([rand(10,25), rand(10,25), [
            'size' => 18, 'pointShape' => 'star', 'fill-color'=> '#a52714'
        ]]);
`

Sorry i'm basic, i don't understand for single column and row style.

**Comment by kevinkhill** [comment]
You're adding a third column, so you can describe _per row_ what style you want. Just like your example you gave me.

`['X', 'Y', {'type': 'string', 'role': 'style'}]`

Just like how the Javascript defines a third column

**Comment by kevinkhill** [comment]
That looks OK to me. Does that work?

**Comment by reviart** [comment]
Not work sir.
Error: 
> Argument 3 passed to Khill\Lavacharts\DataTables\Cells\Cell::__construct() must be of the type array, string given

Code:
`
$datatable
                ->addNumberColumn('Y')
                ->addNumberColumn('X')
                ->addRoleColumn('string', 'style');
                ; 
$datatable->addRow([rand(10,25), rand(10,25), null]); 
        $datatable->addRow([rand(10,25), rand(10,25), [ 'size' => 18, 'pointShape' => 'star', 'fill-color'=> '#a52714' ]]);
`

**Comment by kevinkhill** [comment]
Glad you figured it out
