### ISSUE TITLE
Lavachart america/sao_paulo is not a valid timezone

### ISSUE THREAD

**Issue by NelsonBaez** [kevinkhill/lavacharts#256]
#### What Version?
3.1.10

#### Issue
lavachart is not working with timezone 'America/Sao_Paulo', but the problem only occurs in a centOS with nginx, in my local enviroment with apache it works, any idea?
![screenshot_1](https://user-images.githubusercontent.com/41634849/43143913-50fa5504-8f32-11e8-9a44-81567b13b569.png)

**Comment by kevinkhill** [comment]
[If you scroll to the end of the file] (https://github.com/kevinkhill/lavacharts/blob/3.1/src/DataTables/DataTable.php), you can see how the library validates timezones. I thought it would be safe to use builtin php functions to create a validation list.

I don't know why it would be different per environment. Are you using different versions of php?

**Comment by NelsonBaez** [comment]
yeah, they are different, i checked and in local we use php 7.1.9 and it works, in production we use 7.1.17 and fails, after that, i tried to use php 7.1.17, 7.1.19 and 7.1.20 locally but it seems that just the 7.1.9 works, i will try this version in the production enviroment later to confirm that.

**Comment by NelsonBaez** [comment]
i did a var_dump in the timezone_abbreviations_list(), and there are no 'America/Sao_Paulo' abbreviation,
after more research i found this issue that seems related.
[https://github.com/sensiolabs/SensioDistributionBundle/commit/bcc5391672fa8eb8f9535f42ce20cd48f2b9fc72](url)
They fixed by using `timezone_identifiers_list()` instead of `timezone_abbreviations_list()`, maybe you can do the same.
Another thing is that in php 7.1.9 there are 'America/Sao_Paulo' in the abbreviation list, i don't know why after that version it got removed.

**Comment by kevinkhill** [comment]
Very strange indeed.... Thank you for looking into this for me. I don't have time to work on it, but if you are willing to make a patch, I'd happily accept a pull request

**Comment by kevinkhill** [comment]
Tagged version `3.1.11` with the fix :+1:

**Comment by NelsonBaez** [comment]
Sorry, i may did something wrong(it was my first pull request), but 3.1.11 isn't with the fix.

**Comment by kevinkhill** [comment]
Honestly, I don't know where your commit went? I am not a git master, but I thought you did it right, and it looks like you pulled against my 3.1 branch, but I don't see it when I pull from github......

**Comment by kevinkhill** [comment]
OK! I think I got it sorted out. Now give it a try :+1:

**Comment by NelsonBaez** [comment]
Working 👍

**Comment by asllanmaciel** [comment]
> i did a var_dump in the timezone_abbreviations_list(), and there are no 'America/Sao_Paulo' abbreviation,
> after more research i found this issue that seems related.
> [bug #338 Fix: Timezone Requirement (felipyamorim)](https://github.com/sensiolabs/SensioDistributionBundle/commit/bcc5391672fa8eb8f9535f42ce20cd48f2b9fc72)
> They fixed by using `timezone_identifiers_list()` instead of `timezone_abbreviations_list()`, maybe you can do the same.
> Another thing is that in php 7.1.9 there are 'America/Sao_Paulo' in the abbreviation list, i don't know why after that version it got removed.

Fixed with `timezone_identifiers_list()` (or `DateTimeZone::listIdentifiers()` ) also!
