### ISSUE TITLE
 Class 'Khill\Lavacharts\Laravel\LavachartsServiceProvider' not found  

### ISSUE THREAD

**Issue by isaacpitwa** [kevinkhill/lavacharts#258]
#### What Version?
> Run `composer show khill/lavacharts` if you don't know

#### Issue
> Please describe the issue. 
After adding "khill/lavacharts" : "3.0.*" in the composer.json  , running composer update and adding Khill\Lavacharts\Laravel\LavachartsServiceProvider::class, in the app.php aswell as defining the alias 'Lava'=>Khill\Lavacharts\Laravel\LavachartsServiceProvider::class. on Running php artisan serve i get 
In ProviderRepository.php line 208:
                                                                        
  Class 'Khill\Lavacharts\Laravel\LavachartsServiceProvider' not found  

#### Controller Code (chart creation code)
```
// paste over this
```

#### View Code
```
// paste over this
```

**Comment by kevinkhill** [comment]
1) I recommend you use `~3.1` since it is the current version.

2) You need to add the dependency and run `composer update` _before_ adding the service provider to `app.php`

3) The alias is registered automatically, so you don't need to worry about it 😊

**Comment by isaacpitwa** [comment]
thanks

**Comment by kevinkhill** [comment]
Did this resolve your issue?

**Comment by isaacpitwa** [comment]
Yes
