### ISSUE TITLE
Donut chart not showing

### ISSUE THREAD

**Issue by EdozdeDandez** [kevinkhill/lavacharts#261]
Version 3.1.11

I am trying to display a donut chart but it's displaying a pie chart instead

Controller code
        $stats = \Lava::DataTable();

        $stats->addStringColumn('Reasons')
            ->addNumberColumn('Percent')
            ->addRow(['Check Reviews', 5])
            ->addRow(['Watch Trailers', 2])
            ->addRow(['See Actors Other Work', 4])
            ->addRow(['Settle Argument', 89]);

        \Lava::DonutChart('Population', $stats, [
            'title' => 'Reasons'
        ]);

View Code
    <div id="pop_div"></div>
    @donutchart('Population', 'pop_div')

**Comment by kevinkhill** [comment]
It looks like I accidentally removed the setting of the `pieHole` option in the `DonutChart` class.

The `DonutChart` class was supposed to extend `PieChart` just as a shortcut to add the extra configuration option `['pieHole' => 0.5]`

So if you add `pieHole` to your `PieChart` you will get a `DonutChart`

**Comment by EdozdeDandez** [comment]
Thanks a lot. That worked.
