### ISSUE TITLE
Uncaught ReferenceError: $st, when hosting

### ISSUE THREAD

**Issue by reviart** [kevinkhill/lavacharts#263]
#### What Version?
> 3.1

#### Issue
> When i hosting the project, the chart just display _@scatterchart('CHART', 'chart-div')_ , and when i check the console, `Uncaught ReferenceError: $st is not defined
    at common.js:263`.
Before that, the project run well on localhost

**Comment by reviart** [comment]
The problem was fixed, sorry to dissapointed you

**Comment by kevinkhill** [comment]
No worries. Glad you sorted it out
