### ISSUE TITLE
Show value into column chart stacked

### ISSUE THREAD

**Issue by marcoraymundo** [kevinkhill/lavacharts#264]
#### What Version?
> 3.0.8

#### Issue
> I need show the values into colunm chart stacked. 

I see the issue #138, but i cant adapte the example code.
My test:
![image](https://user-images.githubusercontent.com/23462147/44009344-8db74566-9e81-11e8-8487-40dcba9bd7cc.png)

Can help me?

**Comment by kevinkhill** [comment]
Did you try adding an annotations role column?

Could you post the chart creation for you are trying?

(side note, you should update to `~3.1`}

**Comment by marcoraymundo** [comment]
Hi!

1)I did not understand how to use the annotations to show the value within the column segment.

I update LavaCharts to 3.1.11

My controller:
<?php

namespace App\Http\Controllers;

use View;
use Illuminate\Http\Request;
use Khill\Lavacharts\Lavacharts;
use Illuminate\Support\Facades\DB;

class pricingController extends Controller
{
	private $visao     = NULL;
	private $grafico   = NULL;
	private $campo     = NULL;


    public function show() {
        return view('pricing_a1');
    }

    public function index(Request $request) {
        $this->visao    = (is_null($request->query('visao')) ? 1 : $request->query('visao'));
        $this->grafico  = (is_null($request->query('grafico')) ? 'posicionamento' : $request->query('grafico'));

        if($this->visao == 1) {
            $this->campo  = 'psq_ret_local_nome';
        } elseif($this->visao == 2) {
            $this->campo  = 'psq_ret_local_cidade';
        } elseif($this->visao == 3) {
            $this->campo  = 'psq_ret_local_uf';
        } elseif($this->visao == 4) {
            $this->campo  = 'psq_ret_item_depto';
        } elseif($this->visao == 5) {
            $this->campo  = 'psq_ret_item_secao';
        } elseif($this->visao == 6) {
            $this->campo  = 'UPPER(LEFT(MONTHNAME(psq_ret_data), 3))';
        } /*else {
            return view('pricing_a1_index')->with('return', 'erro-100')->render();
        }*/


        if($this->grafico === 'posicionamento') {
            $return = $this->posicionamento();
        } elseif($this->grafico === 'precos') {
            $return = $this->precos();
        } else {
            $return = View::make('teste');
        }

        return  $return;
    }

    public function posicionamento() {
        $lava = new Lavacharts; 

        $posicionamento = $lava->DataTable();

        $stringQuery = "
            SELECT
                cc.agrupado                                         as agrupado,
                SUM(cc.mb)                                          as maisBarato,
                SUM(cc.mp)                                          as mesmoPreco,
                SUM(cc.mc)                                          as maisCaro
            FROM (
                SELECT
                    $this->campo                                     as agrupado,
                    IF(psq_ret_meu_preco < psq_ret_preco, 1, 0)     as mb,
                    IF(psq_ret_meu_preco = psq_ret_preco, 1, 0)     as mp,
                    IF(psq_ret_meu_preco > psq_ret_preco, 1, 0)     as mc
                FROM pesquisa_retornos
            ) cc
            GROUP BY cc.agrupado
        ";
        $query = DB::select($stringQuery);
        
        $tableQuery = array();
        $maisBarato = 0;
        $mesmoPreco = 0;
        $maisCaro   = 0;

        $posicionamento
            ->addStringColumn('LOJAS')
            ->addNumberColumn('+ Barato')
            ->addNumberColumn('Mesmo Preço')
            ->addNumberColumn('+ Caro');

        foreach ($query as $key => $value) {
            $posicionamento->addRows([
                "$value->agrupado", 
                [(int)$value->maisBarato,
                (int)$value->mesmoPreco,
                (int)$value->maisCaro],
                ['green']
            ]);
            $maisBarato += (int)$value->maisBarato; $mesmoPreco += (int)$value->mesmoPreco; $maisCaro += (int)$value->maisCaro;
        }

        $posicionamento->addRow(["GERAL", $maisBarato, $mesmoPreco, $maisCaro]);

        $lava->ColumnChart('Posicionamento', $posicionamento, [
            'isStacked' => 'percent',
            'title' => 'POSICIONAMENTO',
            'legend' => [
                'position' => 'bottom'
            ],
            'vAxis' => [
                'textPosition' => 'none',
                'gridlines' => [
                    'color' => 'transparent',
                ],
            ],
        ]);

        $myView = View::make('charts.column', ['lava'=>$lava, 'destino'=>$this->grafico]);

        return $myView;
    }
}

In the bellow image i use the google api, and i use setColumns to show value into colunm segment.
![image](https://user-images.githubusercontent.com/23462147/44031974-1447867c-9edc-11e8-96b7-07029dc234c6.png)

**Comment by marcoraymundo** [comment]
In issue #135, I found an example that helped me solve this issue.

**Comment by kevinkhill** [comment]
Awesome! Glad to hear that you figured it out
