### ISSUE TITLE
Cannot access data via event chart parameter

### ISSUE THREAD

**Issue by andrewskm** [kevinkhill/lavacharts#265]
#### What Version?
3.1.10

#### Issue
Chart parameter (shown here) does not have the same structure
`function selectCallback (event, chart) {
  // Useful for using chart methods such as chart.getSelection();
  console.log(chart.getSelection());
} `
as shown here in the googleChart parameter
`lava.getChart('myFancyChart', function (googleChart, lavaChart) {
    console.log(googleChart);
    console.log(lavaChart);
});`

#### View Code (javascript call from event => select)
```
graphRedirect: function(event, chart)
	{
		var selection = chart.getSelection();
		console.log(chart.data.getValue(0,0));

		lava.getChart('Diversion Rate Comparison', function (googleChart, lavaChart) {
			console.log(googleChart.data.getValue(0,0));
		});
	}
```

I can get the selected node from the lava.getChart method based on the name, but is there a way to get this from the chart parameter that is passed through the event so that this function doesn't have to be hard coded?

**Comment by kevinkhill** [comment]
Try adding a third parameter here `function(event, chart, third)` and see if it the `lavaChart` object. It's been so long since I've looked at the code, I vaguely remember adding it, but never documented it....

**Comment by andrewskm** [comment]
That was it, needed the 3rd param set.
