### ISSUE TITLE
Implementation of PatternFormat

### ISSUE THREAD

**Issue by davemg3** [kevinkhill/lavacharts#268]
With already everything easy this lib can do, It would be nice to be able to color cells or text cells of specific columns according to their value as per google doc. 
https://developers.google.com/chart/interactive/docs/reference#dateformatter
Do you have plan to add it? or can you provide some directions for us to add it to your library?
Thanks

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
