### ISSUE TITLE
Add link on chart

### ISSUE THREAD

**Issue by kk-dot** [kevinkhill/lavacharts#271]
Hi,
How can i add link on chart ? so if i click the chart it redirect to link added
I'm use piechart

Thank you

**Comment by kevinkhill** [comment]
Try defining an [event](http://lavacharts.com/#events) to capture the selection, then add some logic to redirect, maybe with `window.location` or something

**Comment by Fox16** [comment]
how i can get the label name from chart

**Comment by kevinkhill** [comment]
Can you elaborate? From the selection?

**Comment by h4rris** [comment]
is there a way to get the label we have set while adding rows : 
`->addRow(['Check Reviews', 5])`. In this case can I get 'Check Reviews'

**Comment by kevinkhill** [comment]
Closing due to staleness, please open a fresh issue if you are still having issues
