### ISSUE TITLE
Pie chart events

### ISSUE THREAD

**Issue by JonaLieb** [kevinkhill/lavacharts#274]
#### What Version?
> Run `composer show khill/lavacharts` if you don't know
3.1

#### Issue
> Please describe the issue. 
I went through the documentation and I didn't find anything specific enough to assist me in my situation. Basically I need to put an onclick event on the slices of the pie chart. I will insert my code below and will appreciate it if you could help me as soon as possible. Thank you for your time.

#### Controller Code (chart creation code)
```
$chart= Lava::DataTable();
  $chart->addStringColumn('Status format')
            ->addNumberColumn('Percent');

//in the next foreach is where I create my pie slices, I would like to have an onclick function on the slice //to return the $key variable

        foreach ($statusCount as $key => $total) { 
                $chart->addRow([$statusDescr[$key], $total]);
         }

        Lava::PieChart('division', $chart, [
            'is3D' => true,
            'title' => 'Status format',
            'backgroundColor' => 'transparent',
            'titleTextStyle' => [
                'fontSize' => 16,
                'bold' => true
            ]
        ]);
```

#### View Code
```
<div id="division_chart">
      @piechart('division', 'division_chart')
 </div>
```

**Comment by kevinkhill** [comment]
I'm going to close this, just because it is so stale. This project is not abandoned, just in a stable state for now. I am always happy to help and please open a new issue if needed.

Thank you for using Lavacharts!
