### ISSUE TITLE
Composer fails on install

### ISSUE THREAD

**Issue by raleydotcom** [kevinkhill/lavacharts#28]
having trouble installing via composer:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - khill/lavacharts 2.0.1 requires nesbot/carbon 1.13.* -> satisfiable by nesbot/carbon[1.13.0].
    - khill/lavacharts 2.0.2 requires nesbot/carbon 1.13.* -> satisfiable by nesbot/carbon[1.13.0].
    - khill/lavacharts 2.0.3 requires nesbot/carbon 1.13.* -> satisfiable by nesbot/carbon[1.13.0].
    - khill/lavacharts 2.0.4 requires nesbot/carbon 1.13.* -> satisfiable by nesbot/carbon[1.13.0].
    - Conclusion: don't install nesbot/carbon 1.13.0
    - Installation request for khill/lavacharts 2.0.* -> satisfiable by khill/lavacharts[2.0.1, 2.0.2, 2.0.3, 2.0.4].

I am running 1.4 of carbon - how can I get around this?

**Comment by kevinkhill** [comment]
Is it not possible to update Carbon? You're quite a few releases behind...

**Comment by raleydotcom** [comment]
not sure what you mean.  I am running version 1.14 of carbon - it seems like lavacharts wants only somehting in the 1.13 which is older?

**Comment by kevinkhill** [comment]
In your original post it says 1.4, and I was about to go digging into carbon to see what version features I used. 

If you have the most recent version, then I'm behind! I'll bump that, not a problem at all.

**Comment by raleydotcom** [comment]
thanks man!

**Comment by kevinkhill** [comment]
Should be fine now, thanks for pointing that out to me :+1:

**Comment by raleydotcom** [comment]
how long would it take for composer to see this.  still getting that error as of now.  Sorry to bug you about it - I'm a composer newb so if there is something I am doing wrong just holler at me.

**Comment by kevinkhill** [comment]
haha, nope, it's all me, I'm sorry. I just updated the master branch, and not a specific version. You pretty much just repeated your command and my commit did nothing. I'll tag a new version for ya

**Comment by kevinkhill** [comment]
ok, NOW it should be good, I tagged v2.0.5 with the updated carbon dep

**Comment by raleydotcom** [comment]
excellent!  thanks a lot for doing that.

**Comment by kevinkhill** [comment]
Not problem at all :)
