### ISSUE TITLE
Sometimes it works fine, sometimes it doesn't and showing some variative errors

### ISSUE THREAD

**Issue by Ghiffari** [kevinkhill/lavacharts#280]
Hi @kevinkhill hope you're doing great
thanks for your awesome package, it really helps me a lot
but when i use it i encounter issue like this

#### What Version?
> Run `composer show khill/lavacharts` if you don't know
3.1.11
Laravel 5.6

#### Issue
> Please describe the issue. 

as title said,  sometimes it works fine but sometimes when i reload/open for 1st time
showing some variative errors like these : 
1 Uncaught SyntaxError: Unexpected string    at monthly:143
Uncaught ReferenceError: lava is not defined      at monthly:155

or 
2 Uncaught SyntaxError: Unexpected identifier     at monthly:143
 Uncaught ReferenceError: lava is not defined
    at monthly:155
    at monthly:191
or
3  Uncaught SyntaxError: missing ) after argument list   at monthly:143
monthly:154 Uncaught ReferenceError: lava is not defined
    at monthly:154
    at monthly:190
or
4 Uncaught SyntaxError: Unexpected token var at monthly:143
lastmonth:155 Uncaught ReferenceError: lava is not defined
    at lastmonth:155
    at lastmonth:191

and many more
#### Controller Code (chart creation code)
```
use Lava;
		public function viewOrderMonthly()
	{
		$month = date('m');
		$month_name = date("M", strtotime("first day of this month"));
		$start_date = date("d", strtotime("first day of this month"));
		$end_date = date("d");
		$getOrder = Orders::whereMonth('created_at',$month)->get();
		$order = $getOrder->count();
		$orderdata = $getOrder->groupBy(function ($item, $key) {
			return $item->created_at->format('d M');
		});
		$orders = Lava::DataTable();

		$orders->addColumn('string')
		->addNumberColumn('New Register Count')	;
		for ($i=$start_date; $i <= $end_date ; $i++) {
			$status =0; 
			foreach($orderdata as $c){
				if($c[0]->created_at->format('dm') == $i.$month){
					$orders->addRow([$i." ".$month_name,$c->count()]);
					$status = 1;
				}
			}
			if($status==0){
				$orders->addRow([$i." ".$month_name,0]);
			}
		}
		if($end_date <12){
			Lava::LineChart('Temps', $orders, [
				'curveType' => 'function',
				'vAxis'=> [
				'maxValue' => '25',
				],
				'pointSize' => '5',
				'legend'=> 'none',
				]);
		}
		else{
			Lava::LineChart('Temps', $orders, [
				'curveType' => 'function',
				'vAxis'=> [
				'maxValue' => '25',
				],
				'hAxis'=>[
				'showTextEvery' => '3',

				],
				'pointSize' => '5',
				'legend'=> 'none',
				]);
		}

		return view('dashboard.admin.report.order',compact('order'));
	}`
// paste over this
```

#### View Code
```

i've tried both
           <div id="temps_div">
              
            </div>
              @linechart('Temps', 'temps_div')`
and
         <div id="temps_div">
              
            </div>
              <?= Lava::render('LineChart', 'Temps', 'temps_div') ?>


// paste over this
```

*note i already read issue #80 , i already tried to change to dateColumn, unfortunately issue above still occurred

**Comment by kevinkhill** [comment]
I can't be certain... but those errors don't look like they are from my library? Can you post more? I don't see what the issue is...

**Comment by Ghiffari** [comment]
yeah thats why i wondering how can that happen

but right now i havent encounter this issue without any code changed (its weird tho)

i guess we can close this one since i didnt encounter this issue again
