### ISSUE TITLE
how to change horizontal values ?

### ISSUE THREAD

**Issue by h4rris** [kevinkhill/lavacharts#282]
Hello,

I want to know how we can change horizontal axis values. In my case (as in the image) my axis values are like 0,2,4,6,8 and I want to change it into 0,1,2,3,4,5,6,7,8
<img width="937" alt="capture d ecran 2018-11-08 a 15 39 34" src="https://user-images.githubusercontent.com/44297297/48205495-a17b8500-e36c-11e8-80dc-ba1d0414df00.png">

**Comment by Ghiffari** [comment]
as mention on readme.md

you can explore it in here 
https://developers.google.com/chart/interactive/docs/gallery/linechart#Configuration_Options
also giving an example
http://lavacharts.com/#config-horizontalaxis

i don't think it's an issue

**Comment by kevinkhill** [comment]
Thanks for answering for me :+1:

**Comment by h4rris** [comment]
Yeah it's not an issue.

Anyway I used this code to change the number of lines :
`'hAxis' => ['gridlines' => ['count' => 8]]`
