### ISSUE TITLE
BarChart colors

### ISSUE THREAD

**Issue by alexeydg** [kevinkhill/lavacharts#284]
Last version
I set colors :
\Lava::BarChart('Votes', $votes, [
            'colors'=> ['red', 'blue', '#ec8f6e', '#f3b49f', '#f6c7b6'],
        ]);

All lines have red color. How set various colors?

**Comment by kevinkhill** [comment]
Weird, that looks right :thinking:

You could also try [adding a role column](https://developers.google.com/chart/interactive/docs/gallery/barchart#coloring-bars)

**Comment by alexeydg** [comment]
Yes, I saw it, does not work in your plugin

**Comment by masnuril** [comment]
With the last version (3.1.11)
you can set just like this :
$votes->addStringColumn('Food Poll')
      ->addNumberColumn('Votes')
      ->addRoleColumn('string','style')
      ->addColumn(['Tacos',  rand(1000,5000), 'color:red');

**Comment by kevinkhill** [comment]
Closing due to staleness, please open a fresh issue if you are still having issues
