### ISSUE TITLE
"Class 'Khill\Lavacharts\Laravel\LavachartsServiceProvider' not found"

### ISSUE THREAD

**Issue by MartyHemart** [kevinkhill/lavacharts#288]
###### What Version?
> khill/lavacharts" : "3.0.*

###### Issue
> After "composing update" and then adding "Khill\Lavacharts\Laravel\LavachartsServiceProvider::class" & "Lava' => "Khill\Lavacharts\Laravel\LavachartsFacade', as the documentation indicates, when creating my controller, I have the following message in my terminal: 
"Class "Khill\Lavacharts\Laravel\LavachartsServiceProvider' not found"

I can't solve the problem, can you please help me. 

Sincerely.

**Comment by kevinkhill** [comment]
if you are using Laravel `5.5+` and the latest Lavacharts `3.1.*` then it should work with no intervention. Laravel's package discovery should load it all automatically.
