### ISSUE TITLE
PNG output

### ISSUE THREAD

**Issue by approached** [kevinkhill/lavacharts#29]
Hi@all,

Is the PNG output available?

Example:
https://chart.googleapis.com/chart?cht=lc&chxt=x,y&chs=700x400&chco=76A4FB,FF9900&chg=0,8.3333333&chdl=Visits|Unique%20visits&chls=3|3&chma=40,20,20,30&chxr=1,0,33411&chds=0,33411&chd=t%3A33411,33411,33411,33411,33411,33411,33411,33411,33411,33411,33411,33411|33411,33411,33411,33411,33411,33411,33411,33411,33411,33411,33411,33411&chxl=0%3A|Jan-10|Feb-10|Mar-10|Apr-10|May-10|Jun-10|Jul-10|Aug-10|Sep-10|Oct-10|Nov-10|Dec-10

**Comment by kevinkhill** [comment]
This looks like an interesting task to tackle. I'll have a look and see how, if possible, it could be integrated.

**Comment by approached** [comment]
This feature is deprecated and will goes offline in April 2015.

https://developers.google.com/chart/image/

A workaround will be cool, but i have no idea how.

**Comment by kevinkhill** [comment]
If it's going to be turned off that soon, then I'm not going to put any
time into supporting it.
