### ISSUE TITLE
Select a barchart's bar programatically

### ISSUE THREAD

**Issue by shahidsattar** [kevinkhill/lavacharts#290]
Hey,

I have created a Lavacharts barchart and I need to select the first bar by default. Any ideas on how this can be done?

**Comment by kevinkhill** [comment]
With Javascript, you should be able to `lava.get()` the chart object and set as selected?

**Comment by kevinkhill** [comment]
Closing this due to staleness, but I'm happy to help debug if you post your attempts to make it work. :relaxed:
