### ISSUE TITLE
Add vertical line on Gantt Chart on present day

### ISSUE THREAD

**Issue by brunods87** [kevinkhill/lavacharts#291]
#### What Version?
3.1.11

Hi, I've been looking everywhere for a way to add a vertical line on a Gantt chart indicating the present day, but I can't find a working solution. Any idea on how to achieve this?

Thanks in advance
Best Regards
![2018-12-17](https://user-images.githubusercontent.com/34553360/50106348-85022080-0227-11e9-983a-ffded24d5a3a.png)

**Comment by kevinkhill** [comment]
I'm not certain. If you look through the Google docs on those types of charts, and it's possible, I can direct you how to add it.

**Comment by kevinkhill** [comment]
Closing this due to staleness, if you have found a solution, or would like more help, please reopen or create a new issue. Thanks! 😊
