### ISSUE TITLE
Draw multiple lines in same chart

### ISSUE THREAD

**Issue by haydi80** [kevinkhill/lavacharts#295]
#### What Version?

3.1.11
#### Issue
Hello, I am new to Lavacharts. I have 2 arrays of data: costs and gains. I want to display both of them in the same chart for a period of 6 months. So the costs will appear for instance in red and the paid bills in green. The code like I have it now displays 2 charts, and they don't follow the style options, both lines are blue. 
Thanks in advance

#### Controller Code (chart creation code)
```
        $chart = new Lavacharts;
        $costsTable = $chart->DataTable();
        $costsTable->addStringColumn('Months')
           ->addNumberColumn('Costs');
        $gainsTable = $chart->DataTable();
        $gainsTable ->addStringColumn('Months')
            ->addNumberColumn('Gains');
        $costsOptions = [
            'titleTextStyle' => ['fontName' => 'Arial','fontColor' => 'red'],
            ];
        $gainsOptions = [
            'titleTextStyle' => ['fontName' => 'Arial','fontColor' => 'green'],
            'legend' => ['position' => 'top'],
            ];
        $ind = 0;
        foreach($allcosts as $cost){
            $costsTable->addRow([
                $xaxis[$ind], $cost,
            ]);
            $ind++;
        }
        $inde = 0;
        foreach($billspaid as $paid){
            $gainsTable->addRow([
                $xaxis[$inde], $paid,
            ]);
            $inde++;
        }
        $chart->LineChart('Costs', $costsTable, $costsOptions);
        $chart->LineChart('Gains', $gainsTable, $gainsOptions);



#### View Code
```
<div id="costsdiv"></div>
          <div id="paiddiv"></div>

          {!! $chart->render('LineChart', 'Costs', 'costsdiv') !!}
          {!! $chart->render('LineChart', 'Gains', 'paiddiv') !!}

**Comment by kevinkhill** [comment]
Easy! Just merge everything you have together. One DataTable with date, number, number for columns. Put that in one Linechart and you'll get one chart with 2 lines.

**Comment by haydi80** [comment]
Thank you very much.. It works like a charm!

**Comment by kevinkhill** [comment]
Happy to help
