### ISSUE TITLE
Deprecated parameter

### ISSUE THREAD

**Issue by miqwit** [kevinkhill/lavacharts#296]
#### What Version?
3.0.8

#### Issue
The current configuration file raises a deprecated warning on symfony 3.4:
Not quoting the scalar "%khill.lavacharts.class%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 in "vendor/khill/lavacharts/src/Symfony/Bundle/Resources/config/services.yml"

Just quoting the parameters will do fine. I can PR if you don't see any consequential issue.

**Comment by kevinkhill** [comment]
merged #305, will release soon
