### ISSUE TITLE
Laravel5 support

### ISSUE THREAD

**Issue by robert83ft** [kevinkhill/lavacharts#30]
Hi

I might be wrong but I think it's not compatible with Laravel5.

I get

```
  [BadMethodCallException]
  Call to undefined method [package]

Script php artisan clear-compiled handling the post-update-cmd event returned with an error

  [RuntimeException]
  Error Output:
```

right after I add `'Khill\Lavacharts\Laravel\LavachartsServiceProvider',` in app.php as instructed for Laravel.

Seems OK in Laravel4.
Would you like to make it compatible with Laravel5?

**Comment by kevinkhill** [comment]
If you update to the most recent version, 2.0.5, you should have no problem. This was already addressed in issue #20

**Comment by robert83ft** [comment]
Well I used `"khill\lavacharts" : "2.0.*"` .. that means I was using latest ...
Thanks for the reference to #20 ... it means it's simply something else .. specific to my project.
I will digg deeper.

Thanks!!

**Comment by kevinkhill** [comment]
If it does still happen to be on my end, please let me know

**Comment by robert83ft** [comment]
I appreciate your help. If I don't figure it out .. I'll ask for more help
later.
I stopped looking deeper .. as it looked very much like it was not updated
for L5 (got that in other packages as well) but it seems that's not the
problem ;).

Robert

On 26 February 2015 at 17:49, Kevin Hill <notifications@github.com> wrote:

> If it does still happen to be on my end, please let me know
> On Feb 26, 2015 7:48 AM, "Robert Rotter" <notifications@github.com> wrote:
>
> > Well I used "khill\lavacharts" : "2.0.*" .. that means I was using latest
> > ...
> > Thanks for the reference to #20
> > <https://github.com/kevinkhill/lavacharts/issues/20> ... it means it's
> > simply something else .. specific to my project.
> > I will digg deeper.
> >
> > Thanks!!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/kevinkhill/lavacharts/issues/30#issuecomment-76201402>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinkhill/lavacharts/issues/30#issuecomment-76201693>
> .
>



-- 

Robert Rotter


*Manager*

*smart**spot*

m: +40 744 269743

d: +40 364 887698

e: *robert@smartspot.ro <robert@smartspot.ro>*

w: *www.smartspot.ro <http://www.smartspot.ro>*

**Comment by robert83ft** [comment]
When I re-tested today it suddenly worked fine. It must have been something specific to my project which was fixed in the meantime. I'm sorry I have wasted your time. 

Thanks!!

**Comment by kevinkhill** [comment]
Don't worry, not a waste, I'm happy to help. Glad you fixed your problem

**Comment by thomthom** [comment]
I ran into this myself today - upgrading and old L4 project via Laravel Shift.

When I remove lavachart from `composer.php` and `app.php` the error goes away. The moment I add them back I get errors:

```
C:\Users\Thomas\SourceTree\ErrorReporter (laravel-5.0-shift)
λ composer update
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "C:\ProgramData\ComposerSetup\bin\composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing khill/lavacharts (2.0.5)
    Downloading: 100%

Writing lock file
Generating autoload files
> php artisan clear-compiled



  [BadMethodCallException]
  Call to undefined method [package]



Script php artisan clear-compiled handling the post-update-cmd event returned with an error


  [RuntimeException]
  Error Output:
```

**Comment by thomthom** [comment]
Updating the old `2.0.*` to `2.5.*` avoided the error.

**Comment by kevinkhill** [comment]
That is a very old version of Lavacharts, I would recommend trying the most
recent version.

Require 3.0.* in your composer.json

**Comment by kevinkhill** [comment]
You answered your own question before my answer, but I would recommend getting into the 3.0 branch, as it is under active development.

**Comment by thomthom** [comment]
Yes, I will most likely do that - but wanted to get a quick-fix to complete the Laravel migration before refactoring the lavachart code. Version 3 looks nice though. :)

**Comment by kevinkhill** [comment]
Good plan :smile: :+1:
