### ISSUE TITLE
Moving Lavacharts to Laravel 5.8 not possible

### ISSUE THREAD

**Issue by Crazykriz** [kevinkhill/lavacharts#302]
#### What Version?
3.1.11

#### Issue
Hi all,

Laravel 5.8 requires Carbon 2.x but Composer's dependency for Lavacharts still stucks in old Carbon 1.x: 

`khill/lavacharts 3.1.11 requires nesbot/carbon ~1.14`

So updating my sources with Composer breaks down at this point and as long as Lavacharts doesn't support or permit Carbon 2.x the current library seems not to be usable with Laravel 5.8. 
I think we need a new major update for Lavacharts supporting Carbon 2.x

Thanks for your feedback
Crazykriz

**Comment by timp999** [comment]
Same here. I created a pull request to bump it to <3.0

**Comment by Crazykriz** [comment]
Hopefully it will ;-)

**Comment by robinklaassen** [comment]
Any update on this issue? Since Carbon 1.x is now officially deprecated and everyone is urged to upgrade to 2.0, this PR of yours @timp999 would be a very welcome addition.

**Comment by JackWH** [comment]
@kevinkhill Can we get this merged? Impossible to use Lavacharts with Laravel 5.8 at the moment!

**Comment by kevinkhill** [comment]
I appreciate you all as a community keeping this project a love as I focus on other priorities in my life. I would happily merge a PR

**Comment by kevinkhill** [comment]
I think I only have it as a dependancy to integrate with the earlier versions of Laravel. I don't think DataTables use many carbon methods... 🤔

**Comment by kevinkhill** [comment]
So upgrading or allowing any version (or the same as Laravel? Align version compatibility?)

**Comment by JackWH** [comment]
@kevinkhill I've needed to use Lavacharts for an urgent project over the last week, and as a temporary workaround used Composer to load the package direct from this PR: #304 

I haven't come across any issues, despite using Lavacharts in-depth. That PR uses `"nesbot/carbon": ">=1.14 <3.0"` as the version constraints, which seems to work well.

**Comment by kevinkhill** [comment]
I'm terribly sorry for letting this sit. I am very busy and forgetful, a dangerous combo for doing tasks 😜

**Comment by kevinkhill** [comment]
PR merged! I will try and push a release

**Comment by JackWH** [comment]
@kevinkhill Thanks! A new tagged release would be very much appreciated so we can start using this without having to go via a separate repository in Composer.

**Comment by robinklaassen** [comment]
@kevinkhill any update on the new release including the carbon version bump?

**Comment by kevinkhill** [comment]
now?

**Comment by kevinkhill** [comment]
🤣

**Comment by robinklaassen** [comment]
I still can't see a stable release, according to Packagist: https://packagist.org/packages/khill/lavacharts#3.1.11

I would expect a 3.1.12 stable release. I can see that the 3.1.x-dev build has the updated Carbon dependency but I would prefer to keep my dependencies in the stable channel.

**Comment by kevinkhill** [comment]
How strage... 🤔 Github must have changed something about their API, because I had to re-authorize packagist. Anyways, I did a manual update and can see 3.1.12

Can you please verify?

**Comment by robinklaassen** [comment]
Yes, I got it now. Thank you very much! 😄

**Comment by kevinkhill** [comment]
Absolutely! Good luck and please stay in touch with anything else, happy to help.
