### ISSUE TITLE
Vertical Barchart

### ISSUE THREAD

**Issue by ultrasamad** [kevinkhill/lavacharts#303]
#### What Version?
^3.1

#### Issue
How do I set vertical bars for barcharts instead of the default horizontal bars?
I couldn't find the `bars` option, but I passed it anyway hoping it will work.
But it didn't

#### Controller Code (chart creation code)
```
Lava::BarChart('Votes', $votes, [
        'bars'  => 'horizontal'
    ]);
```

#### View Code
```
@barchart('Votes', 'poll_div')
```

**Comment by kevinkhill** [comment]
ColumnChart

**Comment by ultrasamad** [comment]
@kevinkhill Ah Didn't notice that. Thanks very much

**Comment by kevinkhill** [comment]
You're welcome 😊
