### ISSUE TITLE
Geo Chart for states

### ISSUE THREAD

**Issue by Francis-Njoku** [kevinkhill/lavacharts#306]
#### What Version?
>3.0

#### Issue
> How do I implement for states

#### Controller Code (chart creation code)
```
// paste over this
```

#### View Code
```
// paste over this
```

**Comment by kevinkhill** [comment]
I do not write chart code on request, please try to do it yourself, then come back if you are stuck. I am happy to help debug 😄

**Comment by kevinkhill** [comment]
Closing due to staleness, please open a fresh issue if you are still having issues
