### ISSUE TITLE
"NULL is not a valid DataTable." 

### ISSUE THREAD

**Issue by LewisHolt** [kevinkhill/lavacharts#307]
#### What Version?
> versions : * 3.1.11 (was 3.0.8 upon submitting this before updating)

#### Issue
> I've got the array working and it is outputting values, however the chart doesn't seem to want to accept the data, as per the error "NULLis not a valid DataTable.". This was previously "array is not a valid datatable" but the error has changed since the update. I've googled but unfortunately I'm kind of stuck here!

#### Controller Code (chart creation code)
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
//use Khill\Lavacharts\Lavacharts;
use App\Chart;
use App\Replay;
use App\Hero;
use App\Map;
use DB;

class ChartsController extends Controller
{
 function index() {

$heroes = \Lava::DataTable();

$heroes = DB::table('replays')
        ->leftJoin('heroes', 'heroes.id', '=', 'replays.hero_id')
        ->select(DB::raw('replays.hero_id as hero_id, heroes.hero_name as hero_name'))
        ->get()
        ->toArray();


foreach($heroes as &$hero) 
{ 
    $hero = [
        'hero' => $hero->hero_name, $hero->hero_id, 
    ]; 
}

$counted_heroes = array_count_values(array_column($heroes, 'hero'));

//dd($counted_heroes);
 
\Lava::DonutChart('Heroes', $counted_heroes, [
    'title' => 'Heroes Played'
]);
return view('public.stats',compact('lava'));

    }
}
```

#### View Code
```
<div id="chart-div"></div>
<?= Lava::render('DonutChart', 'Heroes', 'chart-div') ?>

@donutchart('Heroes', 'chart-div')
```

Any help you can offer would be most appreciated! Very new to charts!

(As for the view, I most likely don't need the blade there however I'm currently unable to do any testing due to the php error overriding the view.)

**Comment by LewisHolt** [comment]
Just updated from 3.0.8 to 3.1.1 and the error has changed from "array is not a valid DataTable" to NULL is not a valid datatable.

**Comment by kevinkhill** [comment]
First thing I notice, you need to pick either the blade directive or the `Lava::render` call. They do the same thing, so it's possible that is where the `null` is coming from (the second call?)

**Comment by kevinkhill** [comment]
Closing due to staleness, please re-open or start a new issue if you still need help.

**Comment by kevinkhill** [comment]
Closing due to staleness, please re-open or start a new issue if you still need help.
