### ISSUE TITLE
Help with Line Charts

### ISSUE THREAD

**Issue by Emily-J-Hall** [kevinkhill/lavacharts#309]
#### What Version?
> 3.0.8

#### Issue
> Please describe the issue. 
Is there somewhere with a good example on how I can use a line chart associated with a database, I've looked around online and on the docs and it's just confusing me.

I just need a line graph which displays a blood sugar level according to date if that makes sense a bit like this diagram here.
![2](https://user-images.githubusercontent.com/43569024/56667570-fc4c3300-66a5-11e9-9364-e8b782de87a1.PNG)

There would be multiple inputs a day as well.

Any advice would be great. Thanks

#### Controller Code (chart creation code)
```
Don't have any just yet


```

#### View Code
```
Don'y have one just yet...
```

**Comment by kevinkhill** [comment]
Please excuse my brevity, [but there are examples on the website...](http://lavacharts.com/#example-line)

**Comment by kevinkhill** [comment]
[you can start by copying the example from the docs](http://lavacharts.com/#example-line) and get a sample graph, then use the datatable methods to build your own datatable. If you post some attempts, I will happily help.

**Comment by kevinkhill** [comment]
Closing due to staleness, please open a fresh issue if you are still having issues
