### ISSUE TITLE
Does not comply with psr-4 autoloading standard.

### ISSUE THREAD

**Issue by avesgit** [kevinkhill/lavacharts#321]
#### What Version?
> Run `composer show khill/lavacharts` if you don't know
versions : * 3.1.12

#### Issue
> Please describe the issue. 
Deprecation Notice: Class Khill\Lavacharts\Support\RenderableTrait located in ./vendor/khill/lavacharts/src/Support/Renderable.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

#### Controller Code (chart creation code)
```
// paste over this
```

#### View Code
```
// paste over this
```

**Comment by arungpisyadi** [comment]
Hello @kevinkhill 

I'm having this issue too.

**Comment by kevinkhill** [comment]
Follow #323 for progress on this issues
