### ISSUE TITLE
Add Laravel 7 support

### ISSUE THREAD

**Issue by schonhose** [kevinkhill/lavacharts#323]
Hi Kevin,
Could you update composer.json to support Laravel 7 as well?
Thanks

**Comment by kevinkhill** [comment]
What needs to be changed? Lavacharts is framework agnostic, so technically it already can be used? Have the Laravel specific features not working?

(I haven't been in PHP land a while, the last Laravel release I was excited about included auto-discovery for packages)

**Comment by arungpisyadi** [comment]
Hello @kevinkhill 

It creates this error:
`"Deprecation Notice: Class Khill\Lavacharts\Support\RenderableTrait located in [Root Folder]/vendor/khill/lavacharts/src\Support\Renderable.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201"`

Do you have any suggestions to workaround it?

**Comment by kevinkhill** [comment]
I fiiiiiiiiiinally downloaded L7 and linked my local copy of Lavacharts...

now we blowing off the cobwebs.... do some dusting....

No issue so far with L7 and Lavacharts 3.1, just made a quick PieChart

We'll track the progress of Composer 2.0 testing with this issue

**Comment by jackwh** [comment]
Hi! Any updates on this issue please? 

Laravel is now up to version 8, and Composer 2.0 has been out for some time.

**Comment by kevinkhill** [comment]
I have been out of the PHP land for a bit, so L5.x was my last working
site. Do you know what it would take? Easy upgrade? I don't have time to
learn L7 and upgrade Lavacharts. My life is just too busy at the moment. I
would gladly accept pull requests if you can make the upgrade work.

**Comment by schonhose** [comment]
@kevinkhill you might want to check out https://github.com/kevinkhill/lavacharts/pull/322

**Comment by kevinkhill** [comment]
Could you try the latest tag? I have other users reporting no more issues.

**Comment by kevinkhill** [comment]
https://github.com/kevinkhill/lavacharts/releases/tag/3.1.14

**Comment by jackwh** [comment]
@kevinkhill 3.1.14 seems to have fixed this. Thanks for putting together this package, it's very much appreciated!
