### ISSUE TITLE
lavacharts.com is down

### ISSUE THREAD

**Issue by fbollon** [kevinkhill/lavacharts#327]
Hello 
I can't access the documentation.

I have got the error:
Unable to find the IP address of the lavacharts.com server.
DNS_PROBE_FINISHED_NXDOMAIN

I checked, and it's not just for me. 

Lavacharts.com Status
Is lavacharts.com down right now?
It's not just you! lavacharts.com is down.

I hope it's just a temporary problem.

**Comment by sicaboy** [comment]
+1

**Comment by kevinkhill** [comment]
Not sure whats going on here...
![image](https://user-images.githubusercontent.com/266076/88279756-71d3f400-cc99-11ea-82a4-e71d44165c6b.png)
So I'll try again later

**Comment by kevinkhill** [comment]
It appears to be up now, so closing....

**Comment by deesouza-invillia** [comment]
Same problem here:

DNS_PROBE_FINISHED_BAD_CONFIG

**Comment by kevinkhill** [comment]
Arg! What's up with namecheap??

**Comment by kevinkhill** [comment]
I'm having issue getting into my account 🤬 I don't know why it's not accepting my OTP code

**Comment by DeeSouza** [comment]
I'm with the same problem:

![image](https://user-images.githubusercontent.com/12430887/101903264-c74e6600-3b92-11eb-93a4-58ba85bbe94c.png)

**Comment by kevinkhill** [comment]
Here's a workaround...
Its still hosted on Github, just I used some absolute refs it looks like and the css isn't properly loading...

https://kevinkhill.github.io/lavacharts/

**Comment by kevinkhill** [comment]
I finally got access back to my namecheap account and it seems that github changed their name server ip addresses...

**Comment by kevinkhill** [comment]
I just [updated the dns records to the ip addresses found on this page](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site)

Let's see if this fixes our problem

**Comment by DeeSouza** [comment]
@kevinkhill here yet is down. But, I'm accessing by VPN with chrome extension to see documentation. 

But, when changing the DNS settings, we need to wait up to 72 hours to work.

**Comment by kevinkhill** [comment]
I'm tearing my hair out! I swear it's all set right....

**Comment by kevinkhill** [comment]
FANFARE! IT'S BACK UP! AHHHH FINALLY

**Comment by kevinkhill** [comment]
WTF?!?! what is the issue?

**Comment by kevinkhill** [comment]
![image](https://user-images.githubusercontent.com/266076/107032456-aeb09580-6768-11eb-9744-c57d275ef94a.png)

**Comment by kevinkhill** [comment]
![image](https://user-images.githubusercontent.com/266076/107032891-604fc680-6769-11eb-904c-48ce391206fd.png)

**Comment by kevinkhill** [comment]
🖕 DNS

**Comment by deesouza-ps** [comment]
Now is working, congratz!

By the way, how change a message "no data" in the PieChart? :smile:
