### ISSUE TITLE
Piecharts have stopped working

### ISSUE THREAD

**Issue by IvorNetJam** [kevinkhill/lavacharts#329]
#### What Version?
3.1

#### Issue
Since Google has updated their charts library (see https://developers.google.com/chart/interactive/docs/basic_load_libs#updateloader) piecharts no longer seem to work.

An error saying "Cannot read property 'isHtml' of null" is displayed when trying to render a piechart

**Comment by andrewskm** [comment]
Check this issue for the workaround https://github.com/kevinkhill/lavacharts/issues/326
