### ISSUE TITLE
Google Charts version "current" is breaking things

### ISSUE THREAD

**Issue by kevinkhill** [kevinkhill/lavacharts#330]
The problem is related to an attribute called "isHtml". Since there is no occurrence of this attribute in any file in this repository, I assume that the error was generated by the Google Charts library itself.

That way, as suggested by @daveblake, replacing the "current" version with a specific [frozen version](https://developers.google.com/chart/interactive/docs/release_notes#official-releases), we were able to solve the problem.

Given that the latest frozen version of Google Charts was released in May 2020 ([48](https://developers.google.com/chart/interactive/docs/release_notes#version-history-current:-may-2020)) and it is generating the error, it would be appropriate to specify the latest compatible version, which [47](https://developers.google.com/chart/interactive/docs/release_notes#february-2020)

So, I believe that replacing the line that defines the version to be loaded, is enough to solve the problem. 

In /javascript/dist/lava.js:
```
google.charts.load ('current', config);
```

switch to:
```
google.charts.load ('47 ', config);
```

_Originally posted by @jordankobellarz in https://github.com/kevinkhill/lavacharts/issues/326#issuecomment-633091453_

**Comment by kevinkhill** [comment]
Well its up now :man_shrugging:

**Comment by kevinkhill** [comment]
@daveblake @jordankobellarz

**Comment by kevinkhill** [comment]
#329 #328

**Comment by fotonmoton** [comment]
@kevinkhill, can you release new version so your changes can be fetched via simple package update? Otherwise we should patch this bug ourselves by hand. Thanks for discovering real cause of the bug 👍

**Comment by kevinkhill** [comment]
https://github.com/kevinkhill/lavacharts/releases/tag/3.1.13
