### ISSUE TITLE
Refused to load the script 'https://www.gstatic.com/charts/loader.js' because it violates the following Content Security Policy

### ISSUE THREAD

**Issue by nabeeleteam** [kevinkhill/lavacharts#337]
#### What Version?
    "khill/lavacharts":  "^3.1",

#### Issue
Refused to load the script 'https://www.gstatic.com/charts/loader.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

#### Controller Code (chart creation code)
```
Controller code works fine.
```

#### View Code
```
View code works fine
```

**Comment by davidvandertuijn** [comment]
Work-arround:
script-src:  **gstatic.com** 'self' 'unsafe-inline' 'unsafe-eval'
