### ISSUE TITLE
Laravel says "Class 'App\Http\Controllers\Lava' not found"

### ISSUE THREAD

**Issue by KevinMarques** [kevinkhill/lavacharts#34]
After adding "khill\lavacharts" : "2.2.*" to composer.json, executing "composer update" and adding "Khill\Lavacharts\Laravel\LavachartsServiceProvider" in app.php, when I use "Khill\Lavacharts\Lavacharts" from custom Controller, Laravel returns an error saying that class 'App\Http\Controllers\Lava' is not found.

I'm using Laravel 5.

**Comment by kevinkhill** [comment]
I have not tested in Laravel 5 yet, so I'm not sure why the Facade isn't working. The service provider should be registering the class alias. Try putting \Lava::methodName  to see of that works?

**Comment by KevinMarques** [comment]
Putting the backslash before Lava::methodName worked.

Thanks!!

**Comment by kevinkhill** [comment]
No problem. I personally like knowing why things do or don't work, not just
how to fix them, so this is why that worked.

http://php.net/manual/en/language.namespaces.basics.php

Happy coding!

**Comment by r4lly99** [comment]
I have same problem using laravel 5.1 , using sample of demo

`$votes  = \Lava::DataTable();`
`$votes->addStringColumn('Food Poll')
              ->addNumberColumn('Votes')
              ->addRow(['Tacos',  rand(1000,5000)])
              ->addRow(['Salad',  rand(1000,5000)])
              ->addRow(['Pizza',  rand(1000,5000)])
              ->addRow(['Apples', rand(1000,5000)])
              ->addRow(['Fish',   rand(1000,5000)]);`

and in view 

` <div id="poll_div"></div>
                           @barchart('Food Poll', 'poll_div')`

the output is 

`FatalThrowableError in DashboardController.php line 30: Fatal error: Class 'Lava' not found`

Any help will be appreciate

**Comment by kevinkhill** [comment]
What version of the package are you using?

**Comment by mrvic** [comment]
The same problem here:

`$popularity = \Lava::DataTable();`
results:
`Call to undefined method Khill\Lavacharts\Laravel\LavachartsServiceProvider::DataTable()`



config\app.php:
```
'providers' => [
        Khill\Lavacharts\Laravel\LavachartsServiceProvider::class,

'aliases' => [
        'Lava' => Khill\Lavacharts\Laravel\LavachartsServiceProvider::class,

```

>composer show
```
khill/lavacharts           3.0.6   PHP wrapper library for the Google Chart API
laravel/framework      v5.3.30 The Laravel Framework.
```

**Comment by kevinkhill** [comment]
[You do not need to manually assign the alias](http://lavacharts.com/#install-laravel)

But if you did want to override it, you would need to point it to the ```Facade```, not the ```ServiceProvider```

```
'aliases' => [
        'Lava' => Khill\Lavacharts\Laravel\LavachartsFacade::class,
```

**Comment by carlituxman** [comment]
if I add the aliases 'Lava' => Khill\Lavacharts\Laravel\LavachartsFacade::class, it works 
I'm using in laravel 5.1

**Comment by mrvic** [comment]
Thank you Kevin it works now. But assigning the alias is not optional in Laravel 5.1 I had to enter it because it is not auto assigned. Tried multiple times with or without, also tried:

```
composer dump-autoload
artisan config:clear
artisan clear-compiled
```
**VERSION:**
```
$ php artisan --version
Laravel Framework version 5.3.30
```

**Comment by kevinkhill** [comment]
I am feeling like I should just remove the automatic alias bit, and add to the install docs about adding the alias. Most, if not all composer packages I have seen include in their docs about adding the alias. I don't even remember when I found the automatic alias loading bit of code.

Thoughts?

**Comment by Bogstag** [comment]
Some more information if needed. Error was generated web upgrading from Laravel 5.3.29 to 5.4.11 and Lavacharts from 3.0.4 to 3.0.6.

This gets me an error:
app.php:
`'providers' => [
        "Khill\Lavacharts\Laravel\LavachartsServiceProvider",`

Row 59 in Charts.php file:
`$chart = \Lava::DataTable();`

Error in laravel:
`FatalThrowableError in Charts.php line 59:
Class 'Lava' not found`

But adding:
`'aliases' => [
        'Lava' => Khill\Lavacharts\Laravel\LavachartsFacade::class,`
to app.php resolves the problem.

Currently running:
`khill/lavacharts                   3.0.6

laravel/framework                  v5.4.11

PHP 7.0.13`

**Comment by kevinkhill** [comment]
I will try and recreate this environment and see whats up

**Comment by sahibkhan** [comment]
'aliases' => [
        'Lava' => Khill\Lavacharts\Laravel\LavachartsFacade::class,


its working fine

**Comment by kevinkhill** [comment]
I will be including this in the documentation, and depreciate the "auto" loading of the Facade
