### ISSUE TITLE
How to properly add a callback?

### ISSUE THREAD

**Issue by TheTechnoMan** [kevinkhill/lavacharts#36]
Hey,

sorry for this kind of question, sadly I am not that good with JS and can't figure out how to do that.

What I want is to call a JS function after the chart has been rendered and is ready to be displayed. How can I achieve that?

I tried adding this into PHP:

```
LavachartsFacade::Ready('test');
```

and this into the blade template:

```
    <script>

        function test (event, chart) {
            alert('Test');

            // Useful for using chart methods such as chart.getSelection();
            console.log(chart.getSelection());
        }
    </script>
```

Sadly the alert won't appear. What is the correct way to do that?

Thank you very much for your help!

**Comment by kevinkhill** [comment]
I just ran a test with your code and you're right, it didn't work because you need to define in your script tag, what type of script it is.

try this:
```
<script type="text/javascript">
        function test (event, chart) {
            alert('Test');
        }
</script>
```

**Comment by TheTechnoMan** [comment]
Sadly still nothing is happening. Where do I need to put the LavachartsFacade::Ready('test');? Maybe it is at the wrong spot?

Thanks

**Comment by kevinkhill** [comment]
It needs to be attached to the chart, with the 'events' option/method. In your case, it would look something like this:

```
LavachartsFacade::LineChart('ChartTitle')
                             ->events([
                                 'ready' => LavachartsFacade::Ready('test')
                              ]);
```
or

```
LavachartsFacade::LineChart('ChartTitle')
                             ->setOptions([
                                 'events' => [
                                     'ready' => LavachartsFacade::Ready('test')
                                 ]
                             ]);
```

**Comment by TheTechnoMan** [comment]
Oh, okay. Did that wrong. Works fine. Really awesome package you got there, saved me a hell lot of trouble. Thank you very much for providing something like that for free!

**Comment by kevinkhill** [comment]
It has been fun to develop, because I like finding solutions to problems and writing code, so it doesn't feel like work. I'm glad you have found use in it, because that is all that I hope for.

I wrote it for myself at first, but once I realized that it could be pretty useful to others, I put it up here on Github.

Don't hesitate to ask any more questions if they arise, I'm happy to help :)

**Comment by TheTechnoMan** [comment]
Thats always the best "stategy" to write awesome products as it takes away a lot of pressure.

Cause you are offering, indeed 2 more (small) questions came up:

1) Is there a way to check if the requested chart is available, to avoid an exception when trying to display a non existing chart?

2) Is there a way to load/reload an chart over AJAX? For example when the user presses a button?

Thank you!

**Comment by kevinkhill** [comment]
hmmm, both are great questions, to which I don't have answers. If you could create another issue, I'll tag it as a feature request for v2.5

A new problem to solve!

**Comment by TheTechnoMan** [comment]
Alright, I will create that right now. :) THanks!
