### ISSUE TITLE
focusTarget option not available

### ISSUE THREAD

**Issue by TheTechnoMan** [kevinkhill/lavacharts#38]
Hey,

it looks like that the focusTarget option is only available for the BarChart, even though the other charts would support it as well. I would need it for Line and Area Charts to show values that are beneath others.

Thanks

**Comment by kevinkhill** [comment]
Line and area were some of the first charts I made, it's possible Google added those options after I made the classes. I will add it in for you though.

**Comment by TheTechnoMan** [comment]
Thank you very much Kevin!

**Comment by TheTechnoMan** [comment]
Hey,

just saw that you pushed to the master, I use 2.5@dev tho (cause of L5) :(

**Comment by kevinkhill** [comment]
You should always be able to depend on master or the most recent minor version (2.4.* right now). I only keep the tested, working code in master. If you depend on 2.5@dev (or any branch, unless specified) you will be getting bleeding-edge updates, that may or may not be stable.

I added Laravel 5 compatibility a couple versions back actually :)

**Comment by TheTechnoMan** [comment]
Alright, works fine. Thank you :) I really hope that you implement the AJAX thing, that would be insane. :P Thanks again for all your work. 5AM here, time to go to bed :/
