### ISSUE TITLE
Carbon Version

### ISSUE THREAD

**Issue by tpham451** [kevinkhill/lavacharts#39]
khill/lavacharts 2.4.2 requires nesbot/carbon ~1.14

The app I want to use this with requires nesbot/carbon 1.8.

Can change your composer.json to allow for >= 1.14?

**Comment by kevinkhill** [comment]
Do you mean Carbon 1.18? If so, the "~" already specifies Carbon >= 1.14, < 2.0

**Comment by tpham451** [comment]
Oh,  sorry about this.  You found an error in our app.  It says 1.8 but that doesn't exist yet.  Thanks.
