### ISSUE TITLE
Pie Chart doesn´t render decimal values?

### ISSUE THREAD

**Issue by rdgutierrez** [kevinkhill/lavacharts#40]
Hi,

I use your fantastic package in a small app, but i have 2 problems:

1. I´m recording expenses, and the app must be capable to save amounts like this 12.50 but the pie chart doesn´t work when amounts have this format 12.50 just this format 12 or 125. 

2. The other problem is that the pie chart only work in my local wamp server when i deploy to hostgator  to a shared hosting (all other funtion work) but the pie chart doesn´t work.

This is the Pie chart in local

![image](https://cloud.githubusercontent.com/assets/1667030/7428514/ad64f340-efbb-11e4-939f-998a631584e5.png)

And this is the same app in hostgator

![image](https://cloud.githubusercontent.com/assets/1667030/7428521/c5049d7a-efbb-11e4-8992-7f052c1c4207.png)

I upload a simple example of Google Charts to the server and works

![image](https://cloud.githubusercontent.com/assets/1667030/7428530/e92725a6-efbb-11e4-981d-ccae7675026c.png)

What you think can be the cause of this?

**Comment by kevinkhill** [comment]
That is strange... I'll look into the decimals issue and for the  rendering, If you could put your chart code into a gist I will take a look and see if I can figure out why

**Comment by rdgutierrez** [comment]
Of course, thanks a lot for answer my question

**Comment by rdgutierrez** [comment]
I checked and the errors in production server, is that the values was send as strings check this

$this.data = new google.visualization.DataTable({
    "cols": [{
        "type": "string",
        "label": "Category"
    }, {
        "type": "number",
        "label": "Expensed"
    }],
    "rows": [{
        "c": [{
            "v": "School expenses"
        }, {
            "v": "5589"
        }]
    }, {
        "c": [{
            "v": "Social"
        }, {
            "v": "56"
        }]
    }, {
        "c": [{
            "v": "Food"
        }, {
            "v": 0
        }]
    }, {
        "c": [{
            "v": "Transportation"
        }, {
            "v": 0
        }]
    }, {
        "c": [{
            "v": "Housing"
        }, {
            "v": 0
        }]
    }, {
        "c": [{
            "v": "Other"
        }, {
            "v": 0
        }]
    }]
}, 0.6);

That was the error, all works fine now .

**Comment by kevinkhill** [comment]
I'm glad you figured it out :)
