### ISSUE TITLE
Barchart problem

### ISSUE THREAD

**Issue by thaifood** [kevinkhill/lavacharts#43]
should be Votes and not Food Poll
<?php echo Lava::render('BarChart', 'Votes', 'poll_div', true); ?>
                http://laravel.io/bin/1yYqb

Also, what is the blade equivalent of line 1 for line 4 please ?    http://laravel.io/bin/BLyn9

You might want to include  <?php instead of just <? which doesn't work on all systems and semicolon at end.  Thanks !

**Comment by kevinkhill** [comment]
Since you titled your BarChart 'Votes' ```Lava::BarChart('Votes')``` then you need to render 'Votes'

```<?php echo Lava::render('BarChart', 'Votes', 'poll_div'); ?>```

I'm not sure what you mean by this:
>Also, what is the blade equivalent of line 1 for line 4 please ? http://laravel.io/bin/BLyn9
>You might want to include <?php instead of just <? which doesn't work on all systems and semicolon at end. Thanks !

Could you elaborate please?

**Comment by kevinkhill** [comment]
If you still have problems, please open a new issue with more details.

**Comment by roshimon** [comment]
<div id="poll_div"></div>
        {!! $lava->render('BarChart', 'Votes', 'poll_div') !!} works fine :)
