### ISSUE TITLE
namespace 'Khill\Lavacharts\Javascript\JavascriptFactory' not found

### ISSUE THREAD

**Issue by parweb** [kevinkhill/lavacharts#45]
hi,

the namespace 'Khill\Lavacharts\Javascript\JavascriptFactory' isn't good.
the class is located in Khill\Lavacharts\

Fatal error: Class 'Khill\Lavacharts\Javascript\JavascriptFactory' not found in /home/jeuconcours/public_html/dev/vendor/khill/lavacharts/src/Charts/Chart.php on line 427

**Comment by kevinkhill** [comment]
What version are you using?

**Comment by parweb** [comment]
"khill/lavacharts": "2.5.*"

another question
do i need to executed some additionnals command to use the package after composer update ?
because  where i put lava.js in my app.blade.php and googlechart.js ?

**Comment by kevinkhill** [comment]
Sorry I deleted my other comment, I got ahead of myself. Thank you for catching this error.

You don't need to worry about including lava.js manually, if you look at the JavascriptFactory, it includes it as part of the rendering process.

```php
    public function getCoreJs()
    {
        $out  = $this->jsAPI;
        $out .= $this->jsO;
        $out .= file_get_contents(__DIR__.'/../javascript/lava.js');
        $out .= $this->jsC;

        return $out;
    }
```

**Comment by kevinkhill** [comment]
I just pushed 2.5.4 so if you ```composer update``` again, you should get the fix

**Comment by parweb** [comment]
but i need google chart separately ?

think for the update ;)

**Comment by kevinkhill** [comment]
The library will also add a script tag to pull in the jsapi from Google. My
goal is to make it as easy/automatic as possible to get charts on the page.

**Comment by parweb** [comment]
ok good goal :)
