### ISSUE TITLE
Error in Laravel 5.1

### ISSUE THREAD

**Issue by marcuoli** [kevinkhill/lavacharts#47]
Hi guys,

When trying to use Lavacharts with Laravel 5.1 we've got this error. Any help would be very appreciated.

[2015-05-26 15:25:16] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\View\Compilers\BladeCompiler::createMatcher()' in /opt/www/orclstat/vendor/khill/lavacharts/src/Laravel/BladeTemplateExtensions.php:23
Stack trace:
#0 {main}

**Comment by kevinkhill** [comment]
I would appear that in Laravel 5.1 they removed the ability to create custom matchers? Until I can dig into you should be able to comment out the line ```include __DIR__.'/BladeTemplateExtensions.php';``` in the ```LavachartsServiceProvider``` and use the render method instead of blade syntax

Example: ```{{ Lava::render('LineChart', 'MyChartsTitle', 'my_div_id') }}```

**Comment by kevinkhill** [comment]
Thanks to @tobias-kuendig, this bug has been fixed. I will push a new release to the 2.5 branch soon.

**Comment by marcuoli** [comment]
Hi Kevin, thanks a lot.

The workaround you provided me some days ago worked like a charm. I'll try this new corrected version removing the workaround.

Regards,

Marcus

**Comment by kevinkhill** [comment]
Just pushed 2.5.5, which will get you the fix provided by @tobias-kuendig.

```composer update```! :)
