### ISSUE TITLE
Extending Lavacharts

### ISSUE THREAD

**Issue by wickedRidge** [kevinkhill/lavacharts#48]
Hi, first of all I want say that you have created a wonder wrapper for the Google Charts API. My only issue is that I want to extend the Lavacharts class with some functionality that is particular to the Laravel 5 project I am working on but I cannot add methods to this child class because of the last method_exists condition within the __call method . Is there any reason for not allowing your package to be extensible?

**Comment by kevinkhill** [comment]
Honestly, I didn't realize that it would prevent it from being extended.

**Comment by kevinkhill** [comment]
Please feel free to make changes and submit pull requests if you have useful features that everyone could benefit from. I welcome collaboration and fresh ideas.

**Comment by kevinkhill** [comment]
I removed the ```method_exists()``` check from ```__call()``` so you should be able to extend however you like.

**Comment by wickedRidge** [comment]
Thanks, I appreciate it!
