### ISSUE TITLE
Omitted to specify that lava.js and google charts api is required on the client site

### ISSUE THREAD

**Issue by alexdevmotion** [kevinkhill/lavacharts#52]
Very nice project, I found it extremely useful.
I would like to report a small issue: you could specify that the user has to include the google charts api and the lava.js in the views, before the chart is rendered.
Took me a while to realize that.

**Comment by kevinkhill** [comment]
If you are using the blade extensions or the render method off the main lava object, it is automatically added before the chart rendering. The jsapi method was added if wanted to place it manually, like in the head instead of in the body
