### ISSUE TITLE
Uncaught TypeError when rendering two charts on the same page

### ISSUE THREAD

**Issue by WesThorburn** [kevinkhill/lavacharts#54]
I'm trying to render two separate charts on one page. One Area Chart and one Bar Chart, both with different titles. Individually, either chart will render just fine with no errors, however when I try to render them both at the same time, neither chart is displayed and Google Chrome's console shows the following error: 
"Uncaught TypeError: Cannot read property 'StockPrice' of undefined".
```var $this = lava.charts.AreaChart["StockPrice"];```

I'm using Laravel 5.1. This is the code that renders the charts in the view.
```
{!! $stockPriceChart->render('AreaChart', 'StockPrice', 'stocks-div', array('height'=>500, 'width'=>800)) !!}
{!! $stockVolumeChart->render('BarChart', 'StockVolume', 'stocks-volume-div', array('height'=>100, 'width'=>800)) !!}
```
Either line renders their respective charts just fine individually, just not together.

Any ideas?

**Comment by kevinkhill** [comment]
If you could make a gist, or paste the Javascript output, I'll try and figure out whats going on.

**Comment by WesThorburn** [comment]
Here is a gist with all of the Javascript output
https://gist.github.com/WesThorburn/c076e7ede58eefb27963

**Comment by kevinkhill** [comment]
It looks like you are you passing the charts to the view, and calling the render method off of them? I think you could have found a bug, that I thought might be a problem. I had first enabled the charts to be rendered from themselves, but found that with multiple charts, I couldn't track the output of the JS between each chart rendering.

Try:
Instead of doing this
```
{!! $stockPriceChart->render('AreaChart', 'StockPrice', 'stocks-div', array('height'=>500, 'width'=>800)) !!}
{!! $stockVolumeChart->render('BarChart', 'StockVolume', 'stocks-volume-div', array('height'=>100, 'width'=>800)) !!}
```
use the blade extensions to render each chart:
```
@areachart('StockPrice', 'stocks-div', array('height'=>500, 'width'=>800))
@barchart('StockVolume', 'stocks-volume-div', array('height'=>100, 'width'=>800))
```
or the Lava facade
```
{!! Lava::render('AreaChart', 'StockPrice', 'stocks-div', array('height'=>500, 'width'=>800)) !!}
{!! Lava::render('BarChart', 'StockVolume', 'stocks-volume-div', array('height'=>100, 'width'=>800)) !!}
```

**Comment by WesThorburn** [comment]
I already tried this approach. However, I'm getting the Error Exception "AreaChart('StockPrice') was not found." whenever I attempt to use either the blade extension or the Lava facade. 

Am I missing something here? Is it possible that I simply haven't installed Lavacharts correctly for Laravel 5.1?

**Comment by kevinkhill** [comment]
Well, it looks like I need to dig a little deeper. If you want, you can try
the 3.0 branch. It's not done yet, but it's mostly stable.

In the mean time, could you make another gist of your controllers building
your charts so I can try and recreate your bug on my end? I don't want to
reverse engineering your charts from the json. Don't worry if you are using
database values, you can omit addRow calls, I'll just fill in some random
data.

**Comment by WesThorburn** [comment]
Thanks for your time, I appreciate you trying to help me out, but I have switched to Chart.js. 

To recreate the errors I was getting, I recommend you get a fresh install of Laravel 5.1 and use the code you have in your examples.

At one point, I had replicated your code, line-for-line from the AreaChart example in the Lavacharts documentation and I was getting the errors I mentioned previously.

**Comment by kevinkhill** [comment]
Sorry it didn't work out for you, but thank you for pointing out the issue.
I will try an squash this bug, and in the mean time, happy coding :)
