### ISSUE TITLE
CategoryFilter does not pass $columnLabel

### ISSUE THREAD

**Issue by MicahKV** [kevinkhill/lavacharts#55]
CategoryFilter does not pass the required $columnLabel.  It works when I change /src/Filters/Category.php line 11 from:
> public function __construct()

to
> public function __construct($columnLabel)

**Comment by kevinkhill** [comment]
Whoops! If you could make a pull request, I'll merge it.

**Comment by kevinkhill** [comment]
Don't worry about the pull request, I found some down time :)
