### ISSUE TITLE
Chart binding label is hard coded in JavascriptFactory.php

### ISSUE THREAD

**Issue by MicahKV** [kevinkhill/lavacharts#56]
Currently the dashboard only works if you pass the binding label as 'MyPie' in the controller because that label is hard coded in JavascriptFactory.php around line 292:
> $boundChart = $dashboard->getBinding('MyPie')->getChartWrapper()->getChart();

I'm currently getting around this issue by calling getBindings() and pulling the label from the first result.  I'm sure there's a better way to do this but it works:
> $allBinding = $dashboard->getBindings();
> foreach ($allBinding as $thisBinding)
> {
>     $bindingLabel = $thisBinding->getLabel();
>     break;
> }
> $boundChart = $dashboard->getBinding($bindingLabel)->getChartWrapper()->getChart();

**Comment by kevinkhill** [comment]
Another bug! That was just for my testing and I forgot to make it assignable. I will definitely add a way for that to be set, instead of being hard coded. Thank you for helping me find these issues.

**Comment by kevinkhill** [comment]
It's been a while, but I'm starting to tackle the binding issues. I found in Googles docs about dashboards, that bindings don't have to be one to one. This made me realize that I don't even really need them to be labeled, so I will be refactoring how to bindings work to allow OneToOne, OneToMany, and ManyToOne between controls and charts

**Comment by MicahKV** [comment]
That sounds great, thanks for the update!

**Comment by kevinkhill** [comment]
I removed the hard coded labels, by removing labels entirely. The Javascript Factory hashes the bindings now to create a label.

The bind method only needs two arguments, one or an array of ControlWrappers and one or an array of ChartWrappers.

I got ManyToOne working by testing an age vs salary scatter chart. OneToMany and ManyToMany still needs work, but I can see the path for how to make it work.

**Comment by MicahKV** [comment]
I finally got a chance to sit down and give this a go, and now I can't Lava to work for some reason... it appears to be looking for JavascriptFactory in the wrong place.  I've updated via composer a couple of times over now, I keep getting this:

    FatalErrorException in Chart.php line 475: 
    Class 'Khill\Lavacharts\JavascriptFactory' not found

Any idea what I might be doing wrong?  I tried updating Chart.php to use Khill\Lavacharts\Javascript\JavascriptFactory and just get different errors:

    ErrorException in JavascriptFactory.php line 139: 
    Argument 2 passed to Khill\Lavacharts\Javascript\JavascriptFactory::getChartJs() must be an instance of Khill\Lavacharts\Values\ElementId, string given, called in /my/laravel/vendor/khill/lavacharts/src/Charts/Chart.php on line 477 and defined (View: /my/laravel/resources/views/lavachart.blade.php)

**Comment by kevinkhill** [comment]
I have been doing a lot of refactoring, in an effort to get the internals in a more logical state. I appreciate your diligence in helping me squash bugs and muddle through errors. I will take a look!

**Comment by kevinkhill** [comment]
Fixed the use statement... Just out of curiosity, are you passing the chart to the view and calling render() on the chart object?

I ask because that was the initial concept, sort of a legacy feature now. When rendering from the charts directly, I had no way to track if the jsapi or lava.js had been output. It works for single charts, but if you were trying to multiple charts on one page, then you would let the top level Lava object store and track the charts internally with the volcano class.

**Comment by MicahKV** [comment]
Yeah I was taking the old approach because Lava:: wasn't working for me... turned out it was because I was using the full path in the 'use' statement instead of just 'use Lava'.  Figured that out and everything is working now!

Is there any way to set height/width for the filters?  I added a ChartRangeFilter for the date range and it's working perfectly, but it's also tall as the chart itself and I'd like to shrink it to about 50px high if possible :)

**Comment by kevinkhill** [comment]
yes, the filters have many [options](https://developers.google.com/chart/interactive/docs/gallery/controls?hl=en#googlevisualizationdaterangefilter), I just haven't gotten to implementing them yet. I had just created the base classes to test dashboards, but now that they are working, I'll move up filter options on my todo list. I should be able to whip up the options classes soon. It looks like what you'll be wanting is "ui.cssClass" where you could apply a height to the control :)

**Comment by MicahKV** [comment]
That sounds great, looking forward to the options :) Thanks for being so responsive on this!

**Comment by kevinkhill** [comment]
I have most of the ui option classes done, and I think I found a cleaner way to integrate setting of options to charts, dashboards, and everything!

Now, everything is set by manually creating the classes for each option:
```
[ 
    'legend' => Lava::Legend([
        'whatever=>'config'
    ]),
    'annotation' => Lava::Annotation([
        'whatever'=>'config'
    ])
]
```
very wordy....
I did that so you couldn't set an option that didn't exist since each config class checks for what options can be set and types. What I realize now is that I can just let the config array pass through, and create the classes internally! All the checks will still happen, but then you don't have to type out so much. The new way would look cleaner, less typing out new class names, and I can eliminate some factory methods from the main Lavacharts class:

```
[ 
    'legend' => [
        'whatever=>'config'
    ],
    'annotation' => [
        'whatever'=>'config'
    ]
]
```

**Comment by kevinkhill** [comment]
I forgot to post what I initially came here for. All of the new UI options are part of the 3.0-unstable branch. The filter classes are simpler to create, no more pulling from the datatable a column label. Well, you can if you want, but the first argument can now be a column index, so instead of  
```$lava->NumberRangeFilter($datatable->getColumnLabel(1), [])```
its just  
```$lava->NumberRangeFilter(1, [])```

as for the config, you can help test for me, just pass in what options you would like as the second parameter:
```
 $filter = $lava->NumberRangeFilter(1, [
      'ui'=> [
          'label' => 'This is a label',
          'labelStacking' => 'vertical',
          'cssClass' => 'fancy-class'
      ]
  ]);
```

**Comment by MicahKV** [comment]
Hey, sorry for not responding sooner.  I finally got a chance to sit down and give this a shot, but I'm running into some issues. This works with the 3.0 branch (not unstable):
> $lineChart = Lava::LineChart($name, $lavaTable)
>                            ->title($title)
>                            ->legend(Lava::Legend(['position' => 'top']));

On the unstable branch it throws an "Undefined variable: lavaClass" error for the legend() line, which makes sense given the changes you explained above but when I try changing it to this:

> $lineChart = Lava::LineChart($name, $lavaTable)
>                            ->title($title)
>                            ->legend(['position' => 'top']);

I get this error: Argument 1 passed to Khill\Lavacharts\Charts\Chart::legend() must be an instance of Khill\Lavacharts\Configs\Legend, array given

I get the same error when trying to do this:

> $lineChart = Lava::LineChart($name, $lavaTable, [
>            'title' => $title,
>            'legend' => [
>                'position' => 'top'
>            ]
>        ]);

And also when using setOptions:

> $lineChart = Lava::LineChart($name, $lavaTable)->setOptions([
>            'title' => $title,
>            'legend' => [
>                'position' => 'top'
>            ]
>        ]);

Can you tell me what I'm doing wrong?

**Comment by kevinkhill** [comment]
That would be because I hadn't finished that work yet. I am trying to keep the 3.0 branch stable, so I'm doing all my refactoring and rewriting in the unstable branch.

**Comment by MicahKV** [comment]
Ah, okay.  Should have read your post closer, I missed the context and thought it was already done.

**Comment by kevinkhill** [comment]
The unstable branch has lots of work done, but some tests are still
failing. I don't have lots of time to work as of late

**Comment by MicahKV** [comment]
No worries, I'm in the same boat.  Also going to be traveling soon and won't be back until mid September so if I don't respond to updates over the next few weeks, that's why :)

**Comment by kevinkhill** [comment]
Well, I wish you safe travels :) so knows, maybe v3 will be done by then!

**Comment by kevinkhill** [comment]
I'm just going to drop this here, and close this as an issue. The new version is almost ready to release. Just a few more changes, tests and documentation

[Upgrading 2.5 -> 3.0] (https://github.com/kevinkhill/lavacharts/wiki/Upgrading-from-2.5-to-3.0)
