### ISSUE TITLE
lava.loadData NumberFormat

### ISSUE THREAD

**Issue by farr433** [kevinkhill/lavacharts#57]
I have a graph that has a store's sales by default but a button lets the user select labor or cost of goods. Then the graph sends a new request and reloads that table data into the graph using the lava.loadData function. I think the function contains an automatic redraw but is there anyway I could get it to apply my NumberFormat? I know I am using is correctly and functions fine on the initial draw but when I use the function "lava.loadData" the data loads and redraws beautifully just without my NumberFormat where I am specifying a prefix and pattern when I create the initial column server side.

I'm thinking while typing this up and maybe If I can echo out that Lava::NumberFormat object right before the lava.loadData function call or inside the function? I feel like the function should look for the NumberFormat object and apply it if specified or I could just be doing it wrong. Hopefully you understand what I am saying and I can provide code to clear up confusion if needed.

**Comment by kevinkhill** [comment]
If you could provide a gist for me, I'd be happy to take a look. I might have overlooked applying formats within the redraw method in lava.js

**Comment by farr433** [comment]
Okay check it out. I am focusing on the javascript function "drawSales()" which calls the "getAllStoresWeekSales()" function in the controller. The initial "getAllStoreSalesGraph()" function in the controller results in perfect formatting on the first draw.

https://gist.github.com/farr433/23a8b77febcf539976c9

**Comment by kevinkhill** [comment]
hmmmmm, so I am seeing that the format blocks are added only on the first draw. When the you call the toJson() method on the datatable, the formats are not even included! You have found a bug I never thought to try and test. I will start looking into how to pass the formats along with the data and options so the lava.loadData() method can add them to the redraw.

**Comment by farr433** [comment]
You are awesome man, thanks for all of your hard work. I couldn't imagine testing a public package with all of weird combinations users would try!





On Fri, Jun 26, 2015 at 7:16 PM -0700, "Kevin Hill" <notifications@github.com> wrote:












hmmmmm, so I am seeing that the format blocks are added only on the first draw. When the you call the toJson() method on the datatable, the formats are not even included! You have found a bug I never thought to try and test. I will start looking into how to pass the formats along with the data and options so the lava.loadData() method can add them to the redraw.

**Comment by kevinkhill** [comment]
So I got the formats to work on the ajax reload.... But broke the initial render in doing so. XD

I'm not guaranteeing a resolution tonight, or soon, as I am currently slammed at my real job.

**Comment by farr433** [comment]
Yeah no worries... I've got plenty of other things to work on in the meantime and wouldnt consider a "$" and "," formatting a high priority haha. Thanks again.





On Fri, Jun 26, 2015 at 8:15 PM -0700, "Kevin Hill" <notifications@github.com> wrote:












So I got the formats to work on the ajax reload.... But broke the initial render in doing so. XD



I'm not guaranteeing a resolution tonight, or soon, as I am currently slammed at my real job.

**Comment by kevinkhill** [comment]
Actually, I think I got it. I'm going to push up a branch I a little bit with my fixes so you can test it in your app.

**Comment by farr433** [comment]
Yeah i have trouble walking away from  a bug or unworking code too lol. Just let me know. I'll be up.





On Fri, Jun 26, 2015 at 8:32 PM -0700, "Kevin Hill" <notifications@github.com> wrote:












Actually, I think I got it. I'm going to push up a branch I a little bit with my fixes so you can test it in your app.

**Comment by kevinkhill** [comment]
Alrighty, if you want to switch your composer dep to dev-master and give it an update, it *should* be working

**Comment by kevinkhill** [comment]
I also noticed a couple of things that I'd like to point out:

When a chart is created, via Lava::ColumnChart or others, it is stored internally in the volcano class (get it?) so you don't have to return it. When using the blade extensions, it pulls the charts from the volcano, or when using the Lava::render() method. It doesn't hurt anything, but saves some typing.
```
/* No need to assign this var */ $column = Lava::ColumnChart();
/* No need to return */ return $column
```

Also, in your json returning ajax methods, you don't need to recreate the chart. You can just create the datatable, create the columns and rows, and return it with ```toJson()```.

(as I wrote that last senence, I just got the idea to add a method to clear the table. Then maybe you only have to define its structure once, and assign rows as need via different ajax methods.)

**Comment by farr433** [comment]
Ah yes, it applied the formatting very nicely now. I had to make one small modification to get it to work. I had to add a closing </script> tag after "@columnchart('weekSales', 'chart_div'). Yeah sometimes when my code isn't working as expected I get flustered and start spitting code out and then go back and clean things up once it all makes sense. Thanks for everything! 

![image](https://cloud.githubusercontent.com/assets/3854190/8390444/9566c2e4-1c63-11e5-9d59-581df14ce1e4.png)

**Comment by farr433** [comment]
* closing "</script>" tag

**Comment by farr433** [comment]
* closing script tag. The comments keep deleting it.

**Comment by kevinkhill** [comment]
did [this] (https://github.com/kevinkhill/lavacharts/commit/1c234af229205d75001f601e5471d5103e08bf43) commit not fix it?

**Comment by farr433** [comment]
I'll re-update real quick and check. I might of grabbed it a little early.

**Comment by farr433** [comment]
This is what I have currently though

![image](https://cloud.githubusercontent.com/assets/3854190/8390477/1ba6b0e8-1c65-11e5-8d53-5e8be7c0a7cd.png)

**Comment by farr433** [comment]
Ah, yup I'm good now. I grabbed in between you closing the post and the post about updating composer. Awesome man, I can't thank you enough!

**Comment by kevinkhill** [comment]
hahaha, no worries, I was quite puzzled. Happy to help! :)
