### ISSUE TITLE
Event callback is displaying error: "lava.event is not a function."

### ISSUE THREAD

**Issue by WesThorburn** [kevinkhill/lavacharts#58]
I have a Lavacharts Areachart displaying a stock price graph and it's working fine. I'd like to give users the ability to change the graph's time frame by clicking buttons. (see image below).
![lava event error](https://cloud.githubusercontent.com/assets/1518191/8536621/2ba9999e-2497-11e5-8273-820eed0fb7aa.jpg)

I'm using Laravel 5.1.
Here is some relevant code from my view:
```
<script type="text/javascript">
		function loadDataHandler(loadData, StockPrice){
			console.log(StockPrice.loadData());
		}

		function getGraphData(timeFrame){
			$.getJSON('/graph/'+ '{{ $stock->stock_code }}/' + timeFrame, function (dataTableJson) {
				console.log(dataTableJson);
				lava.loadData('StockPrice', dataTableJson, function (chart) {
					console.log(chart);
				});
			});
		}
</script>

<div class="btn-group btn-group-sm" role="group">
  <button class="btn btn-default active" onclick="getGraphData('last_month')">30 Days</button>
  <button class="btn btn-default" onclick="getGraphData('last_3_months')">3 Months</button>
  <button class="btn btn-default" onclick="getGraphData('last_6_months')">6 Months</button>
  <button class="btn btn-default" onclick="getGraphData('last_year')">12 Months</button>
  <button class="btn btn-default" onclick="getGraphData('last_2_years')">2 Years</button>
  <button class="btn btn-default" onclick="getGraphData('last_5_years')">5 Years</button>
  <button class="btn btn-default" onclick="getGraphData('last_10_years')">All</button>
<button class="btn btn-default" onclick="getGraphData('all_time')">10 Years</button>
</div>

@areachart('StockPrice', 'stock_price_div')
```

I have two functions in my controller, this one generates the initial graph shown in the screenshot above. 
```
    public function show($id){
        $graphData = $this->stock->getGraphData($id);
        $stockPriceLava = new Lavacharts;
        $prices = \Lava::DataTable();
        $prices->addStringColumn('Date')
            ->addNumberColumn('Price')
            ->addRows($graphData);

        $stockPriceLava = \Lava::AreaChart('StockPrice')
            ->dataTable($prices)
            ->setOptions([
                'width' => 550,
                'height' => 325,
                'title' => 'Price of '.strtoupper($id),
                'events' => ['ready' => \Lava::Ready('getGraphData')]
            ]);

        return view('pages.individualstock')->with([
            'stockPriceLava' => $stockPriceLava,
            'stock' => Stock::where('stock_code', $id)->first(),
            'metrics' => StockMetrics::where('stock_code', $id)->first()
        ]);
}
```
And this one returns the DataTable JSON based on the stock code and the timeframe.
```
public function graph($stockCode, $timeFrame){
        $graphData = $this->stock->getGraphData($stockCode, $timeFrame);
        $prices = \Lava::DataTable();
        $prices->addStringColumn('Date')
            ->addNumberColumn('Price')
            ->addRows($graphData);
        return $prices->toJson();
}
```
This is the route for the AJAX call.
```
Route::get('graph/{stockCode}/{timeFrame}', 'StockController@graph');
```
When I click each of the buttons, JSONs of the correct sizes are being returned according to the console log, however the graph doesn't update, and I have that red error in the corner telling me that, "lava.event is not a function". There are no errors or warnings in the console.

Searching for "lava.event" in the page's source code reveals this line:
```
google.visualization.events.addListener($this.chart, "ready", function (event) {return lava.event(event, $this.chart, getGraphData);});
```

Any ideas as to what I'm doing wrong here?

**Comment by kevinkhill** [comment]
Upon first glance... 
You don't need to add getGraphData as an event in php, unless you want that function to be called when the chart is ready (after it has been rendered)

It *should* work with just the lava.loadData call, as the chart won't have the lava.event attached with this ready event omitted

**Comment by WesThorburn** [comment]
Thanks for answering so quickly! That makes sense so far, I removed:
```
'events' => ['ready' => \Lava::Ready('getGraphData')]
```
and I also removed the loadDataHandler function
```
function loadDataHandler(loadData, StockPrice){
            console.log(StockPrice.loadData());
}
```
The red "lava.event is not a function," error is gone now, however the chart isn't updating when the buttons are clicked. Again the console is showing that objects of the correct sizes are being returned. 

This is the console output if I click the '3 Month' button.
```
Object {cols: Array[2], rows: Array[60]}
AAC:66 pZ {yh: false, Wz: undefined, ea: div#stock_price_div.pull-left, Iq: kw, cw: dla…}
```
Output for the '6 Month' button.
```
Object {cols: Array[2], rows: Array[124]}
AAC:66 pZ {yh: false, Wz: undefined, ea: div#stock_price_div.pull-left, Iq: kw, cw: dla…}
```

The graph isn't changing however. Is there another function that could be used to force the chart to redraw?

**Comment by kevinkhill** [comment]
The fast replies come from the fact that I use [IFTTT](https://ifttt.com) with a github -> android recipe that pushes me a notification whenever an issue is opened. I like to stay on top of things and I hate to leave people hanging.

That's beside the point though, I'm taking a look into what could be going wrong with the lava.loadData calls

**Comment by kevinkhill** [comment]
I'm guessing you have 2.5.6 installed, because I believe you have just found that I accidentally broke ajax loading! I just checked out 2.5.5 in my environment and ajax works.

... digging deeper ...

**Comment by kevinkhill** [comment]
I think I figured it out! If you could switch your composer dep to dev-master and test it, I would appreciate it :)

If all is well, then I will push a new bugfix release

**Comment by WesThorburn** [comment]
Yep, works perfectly now!

You're a legend, thanks Kevin!
