### ISSUE TITLE
LineChart not rendering through ajax

### ISSUE THREAD

**Issue by jamalnasir** [kevinkhill/lavacharts#59]
I am rendering a line chart which renders OK on page load but when I send request through ajax then the chart doesn't render. I get the following error:

`TypeError: lava.charts[parts[0]][parts[1]].chart is null`

What could be the problem?

**Comment by kevinkhill** [comment]
Are you using the lava.loadData javascript method to get the new data from the php script returning DataTable->toJson()?

**Comment by jamalnasir** [comment]
Here is the code:

``` php
$lava = new Lavacharts;
        $linechart = $lava->DataTable();

        $linechart->addDateColumn('Date')
            ->addNumberColumn('Responses');

        foreach($graph as $g){
            $rowData = [
                $g->created_at, $g->total
            ];

            $linechart->addRow($rowData);

        }
```
And in the view:
``` php
$line = Lava::LineChart('Temps')
                ->dataTable($line)
                ->title('Responses in Time');

<div id="temps_div"></div>
<?php echo Lava::render('LineChart', 'Temps', 'temps_div') ?>
```

**Comment by kevinkhill** [comment]
That looks good, but for ajax loading you need to have another controller method/route that returns a new datatable with the toJson() method. That new JSON representation of a datatable table is passed to the second parameter of lava.loadData()

If you were using jquery... 

(I'm on mobile, so forgive my formatting), but something like this... 
```
$.getJSON('http://my.site.com/newData', function (dataTableJson) {
lava.loadData('Temps', dataTableJson, function () {
  console.log('Data Loaded');
});
```

**Comment by kevinkhill** [comment]
Also, you shouldn't create the LineChart in the view, that should be in the controller. The render method pulls the chart from within the Lava class via the label (Temps in your example)

**Comment by kevinkhill** [comment]
I just saw you were getting a type error in your original post. It didn't show up on my phone at first. Do you get there error while trying to loadData method?

**Comment by jamalnasir** [comment]
No, actually I am not using loadData method. Its just a normal ajax call which renders a partial view and in that partial view I am rendering the graph.

**Comment by kevinkhill** [comment]
To get the chart to show via ajax, you have to use lava.loadData(). What you could do, is prepare the chart and give it your data table with no rows, then use the loadData method to populate it with a datatable that has the rows

**Comment by jamalnasir** [comment]
`lava.loadData` fixed the issue. 
Thanks a lot for the help. Really appreciated! stay blessed.

**Comment by kevinkhill** [comment]
No problem :) happy to help
