### ISSUE TITLE
About trendlines

### ISSUE THREAD

**Issue by ajacquelin** [kevinkhill/lavacharts#60]
Hello,
I would like to draw a trendlines, is-it possible with lavacharts ? I know it's possible with google charts:
https://google-developers.appspot.com/chart/interactive/docs/gallery/trendlines#fullhtml

But I would like to use lavacharts to do it :)

I'm not familiar with laravel so any help will be very much appreciated.
Cheers,

**Comment by kevinkhill** [comment]
I can say with 99% ceertainy, yes, it's possible. Not yet, but I will add it to my feature request list :)

**Comment by ajacquelin** [comment]
That sounds great, thanks!

**Comment by kevinkhill** [comment]
If you are interested, the 3.0-unstable branch now has trendline capability. Once I write some tests for it, it will be merged into the 3.0 branch and included in the release :)

**Comment by kevinkhill** [comment]
Trendlines can be assigned the same way as any other config
```
$lava->ScatterChart('Trees', $data, [
      'trendlines' => [
        0 => [
          'type' => 'line',
          'color' => 'red',
          'pointsVisible'=>true,
          'pointSize' => 1
        ]
      ]
    ]);
```

**Comment by ajacquelin** [comment]
Thanks you!

**Comment by szabizs** [comment]
> Trendlines can be assigned the same way as any other config
> 
> ```
> $lava->ScatterChart('Trees', $data, [
>       'trendlines' => [
>         0 => [
>           'type' => 'line',
>           'color' => 'red',
>           'pointsVisible'=>true,
>           'pointSize' => 1
>         ]
>       ]
>     ]);
> ```

Kevin, i cannot manage to use it, could you please guide me?

```
            Lava::$chartType('Chart', $chart, [
                'vAxis' => [
                    'minValue' => 0
                ],
                'trendlines' => [
                    0 => [
                        'type' => 'exponential',
                        'color' => 'green',
                        'pointsVisible' => true,
                        'pointSize' => 3,
                        'lineWidth' => 10
                    ]
                ],
            ]);
```

**Comment by kevinkhill** [comment]
Glad you solved it yourself :+1:
