### ISSUE TITLE
ErrorException in Lavacharts.php line 156: Undefined variable: lavaClass

### ISSUE THREAD

**Issue by TheTechnoMan** [kevinkhill/lavacharts#62]
Hey,

with the dev version, I always get:
ErrorException in Lavacharts.php line 156: Undefined variable: lavaClass

I already updated the code to the new constructor. Any idea what the cause for this might be? Can't post the code right now because I am not at the office but thought that you maybe have an answer anyways that could help.

Thank you!

**Comment by kevinkhill** [comment]
It's probably because I merged the new config behavior into the 3.0 branch (you're using 3.0 right?) and didn't update my wiki entry for how to use them, sorry!

https://github.com/kevinkhill/lavacharts/wiki/Upgrading-from-2.5-to-3.0

**Comment by kevinkhill** [comment]
I should probably put a *trigger_error* and have some sort of depreciation warning instead of crashing

**Comment by TheTechnoMan** [comment]
Thanks!
