### ISSUE TITLE
AJAX loading chart options

### ISSUE THREAD

**Issue by marcusirgens** [kevinkhill/lavacharts#66]
Would it be possible to add a method to load chart options with AJAX (along with the data)?

**Comment by kevinkhill** [comment]
For the purpose of changing the look and feel of the chart on the fly? I suppose that would be possible, but I'm not making any promises. I am still working on getting v3 out, and I've locked down features for now. I will look into it as my next step of development, v3.1 most likely

**Comment by marcusirgens** [comment]
Yeah, that was what I hoped. As an example, pie charts have no style column, so if your data suddenly has more slices, the whole chart needs to be changed. But if you're planning ahead, being able to pass the entire chart over ajax would be amazing. 

Thanks for your reply. Loving this library.

**Comment by kevinkhill** [comment]
Hmmm, that's an interesting edge case you have found, I doubt I would have thought of that. I'm glad you brought it up.

Also, I'm glad you have found Lavacharts useful :)

**Comment by kevinkhill** [comment]
I have a working implementation of ```lava.loadOptions``` which acts the same as ```lava.loadData``` in the master branch. I will be adding it 3.1 and probably back-porting it to 3.0 as well.

**Comment by kevinkhill** [comment]
The master branch, which will soon become 3.1 should have support for this. Please re-open or start a new issue if needed.
