### ISSUE TITLE
Pie Chart Labeled Option

### ISSUE THREAD

**Issue by datune** [kevinkhill/lavacharts#67]
Is there a specific reason why you have not included the position value "labeled" for a legend object in a pie chart?

Also, I can't seem to figure out how to create a simple Top X Bar Chart, am I missing the obvious?

Good work btw ;-)

**Comment by kevinkhill** [comment]
It's entirely possible Google has expanded their api and I am jus not up to date with their changes. Me and another user were discussing this in another open issue, pop over and give me your two cents also?

As for your second concern, I don't follow... What are you trying to do?

**Comment by datune** [comment]
I'll pop over tomorrow, as for the second question, never mind, I figured it out. Thanks for the fast reply! I
