### ISSUE TITLE
Can the Chart Exported to JPG?

### ISSUE THREAD

**Issue by ketutjoko13** [kevinkhill/lavacharts#68]

**Comment by kevinkhill** [comment]
This isn't something that I plan on supporting right now, since Google already has the ability to get the chart as a png.

Here is a quick demo on how to [get the imageURI](https://github.com/kevinkhill/lavacharts/wiki/Getting-a-chart-as-an-image)

**Comment by ketutjoko13** [comment]
Thanks!

**Comment by kevinkhill** [comment]
No problem :)
