### ISSUE TITLE
InvalidDateTimeFormat Exception when $dateTimeFormat is NULL

### ISSUE THREAD

**Issue by SendDerek** [kevinkhill/lavacharts#69]
I have an InvalidDateTimeFormat error being thrown using Lavacharts 3.0.x-dev and the example code provided in the README.

    $stocksTable = Lava::DataTable();

    $stocksTable->addDateColumn('Day of Month')
        ->addNumberColumn('Projected')
        ->addNumberColumn('Official');

    // Random Data For Example
    for ($a = 1; $a < 30; $a++)
    {
        $rowData = [
            "2014-8-$a", rand(800,1000), rand(800,1000)
        ];

        $stocksTable->addRow($rowData);
    }

Error details:

    InvalidDateTimeFormat in DateCell.php line 60:
    NULL is invalid, must be a datetime format string which Carbon can use.

    1. in DateCell.php line 60
    2. at DateCell::parseString('2014-8-1', null) in RowFactory.php line 84
    3. at RowFactory->create(array('2014-8-1', '901', '931')) in DataTable.php line 558
    4. at DataTable->addRow(array('2014-8-1', '901', '931')) in IndexController.php line 38
    5. at IndexController->index()

Looking at line 60, we're defaulting to an empty string, but don't try to account for what happens when $dateTimeString is a null object:
https://github.com/kevinkhill/lavacharts/blob/3.0/src/DataTables/Cells/DateCell.php#L60

We're getting the null object in the first place from line 83 in RowFactory.php:
https://github.com/kevinkhill/lavacharts/blob/3.0/src/DataTables/Rows/RowFactory.php#L83

A quick fix is to do a quick check for $dateTimeFormat.  If it exists, then pass it along, otherwise, pass along an empty string.

      foreach ($valueArray as $index => $cell) {
           if ((bool) preg_match('/date|datetime|timeofday/', $columnTypes[$index]) === true) {
               if ($cell instanceof Carbon) {
                   $rowData[] = new DateCell($cell);
               } else {
    -               $rowData[] = DateCell::parseString($cell, $dateTimeFormat);
    +               $rowData[] = DateCell::parseString($cell, $dateTimeFormat ? $dateTimeFormat : '');
               }
           } else {
               $rowData[] = $cell;
           }
    -   }
    +  }

I wonder why PHP didn't complain/warn about an undeclared variable $dateTimeFormat in use?  Maybe this was by design?

Expected Behavior:  To execute sample code normally without any exceptions thrown.
Actual Behavior:  Exception thrown when example code is executed.
STRs:
1.) In Laravel, hijack or create a Controller
2.) Copy/paste code above
3.) Run controller by browsing to url that triggers controller method or by some other means.  Artisan tinker maybe?

**Comment by kevinkhill** [comment]
I can't check this at the moment, but I will look into it. I would happily accept a pull request if you want to submit one, since you seem quite knowledgeable.

I did not intend to break my own example, I probably just overlooked the null being passed.

**Comment by SendDerek** [comment]
Pull request generated.  I decided to err on the side of having more readable code and went with the following patch instead:

    diff --git a/src/DataTables/Rows/RowFactory.php b/src/DataTables/Rows/RowFactory.php
    index 94909cc..7a1d200 100644
    --- a/src/DataTables/Rows/RowFactory.php
    +++ b/src/DataTables/Rows/RowFactory.php
    @@ -80,7 +80,11 @@ class RowFactory
                     if ($cell instanceof Carbon) {
                         $rowData[] = new DateCell($cell);
                     } else {
    -                    $rowData[] = DateCell::parseString($cell, $dateTimeFormat);
    +                   if (isset($dateTimeFormat)) {
    +                        $rowData[] = DateCell::parseString($cell, $dateTimeFormat);
    +                    } else {
    +                        $rowData[] = DateCell::parseString($cell);
    +                    }
                     }
                 } else {
                     $rowData[] = $cell;

**Comment by kevinkhill** [comment]
Thank you for helping out, I appreciate your contribution. Your pull request has been merged
