### ISSUE TITLE
Usage Enhancement?  Why Specify ChartType in Controller and Template?

### ISSUE THREAD

**Issue by SendDerek** [kevinkhill/lavacharts#72]
I'm just curious about the design decision in v3.0 to require `$chartType` for both the code in the controller to create the chart and the code in the template where the charts are actually rendered?

In other words, why do we instantiate the chart as a 'LineChart' here with a chart label:

```
$chart = Lava::LineChart('PageViews', $pageViews, [
    'title' => 'Visitors and Page Views'
]);
```

And then require the caller to specify the chart type as 'LineChart' again when we've already specified this information?

```
<div id="perf_div"></div>
{!! \Lava::render('LineChart', 'PageViews', 'perf_div') !!}
```

It just seems redundant and makes things slightly more complicated and redundant.  Instead, I would recommend treating the chart label as a unique chart id.  Then, in `checkChart()`, we just look for the existance of the unique chart ID in the array:

```
@@ -68,15 +69,11 @@ class Volcano
      *
      * @return bool
      */
-    public function checkChart($type, $label)
+    public function checkChart($label)
     {
-        if (Utils::nonEmptyString($type) && Utils::nonEmptyString($label)) {
-            if (array_key_exists($type, $this->charts)) {
-                if (array_key_exists($label, $this->charts[$type])) {
-                    return true;
-                } else {
-                    return false;
-                }
+        if (Utils::nonEmptyString($label)) {
+            if (array_key_exists($label, $this->charts)) {
+                return true;
             } else {
                 return false;
             }
```

The rest would follow like so:
https://github.com/SendDerek/lavacharts/commit/9525c1f56255d9d2f154950df9bfd2b1c4b07b9e

Then, all that needs to happen to render is:

```
<div id="perf_div"></div>
{!! \Lava::render('PageViews', 'perf_div') !!}
```

The only thing I can't figure out is why the `Chart` attribute, `$datatable` is `null` with the above changes in place (even when specified in `Lava::LineChart()`).  Instead, I actualy need set it separately like so:

```
$chart = Lava::LineChart('PageViews', $pageViews, [
    'title' => 'Visitors and Page Views'
]);
$chart->datatable = $pageViews;
```

Any hints would be appreciated, but I just thought I'd send my thoughts along.  :-)

**Comment by kevinkhill** [comment]
Not at my laptop at the moment, but I think I was protecting against different chart types with the same name. I was probably thinking that someone might want two different representations of the same data set, so when rendering, you would need to specify type and title.

**Comment by kevinkhill** [comment]
Also, just to satisfy my curiosity, is there a reason why you use
``` Lava::render('LineChart', ... ) ```
Over the blade directives? 
``` @linechart( ... ) ```

**Comment by kevinkhill** [comment]
Thirdly, if the DataTable is getting nulled after the constructor, that was definitely an accident! I will look into it

**Comment by SendDerek** [comment]
That makes sense to have different chart types for the same datatable.  It helps my understanding of the design decision.  Personally, I would still be in favor of letting the user come up with a smartly created, unique chart label like [dataset] + [chart type], ie. "stocks-line-chart", "stocks-bar-chart".  If a chart is created with the same name, the key in the associative array would just be overwritten.  This is behavior I would expect from any PHP script dealing with arrays.  The unique label just makes things like dynamically rendering an array of diferent types of charts in a `foreach()` loop easier.

No good reason why I'm not using the blade directives other than personal preference.  For some reason, in my mind, it's easier to read/comprehend `Lava::render()`.  I might want to dynamically render an array of charts, i.e. `Lava::render($chartType, $chartLabel, ...)`.  Not sure if I could do this with `@$chartType(...)`.

The DataTable is null after my code modifications.  I wouldn't expect that to be your bug, but if you say so... ;-)  I see some comments about it in *Charts/Chart.php*, but I didn't find anything obvious after looking around the code for a while.

    /**
     * Assigns which Datatable will be used for this Chart.
     *
     * If a label is provided then the defined Datatable will be used.
     * If called with no argument, or the chart is attempted to be generated
     * without calling this function, the chart will search for a Datatable with
     * the same label as the Chart.
     *
     * @uses  Datatable
     * @param Datatable
     *
     * @return Chart
     */
    public function datatable(Datatable $d)
    {
        $this->datatable = $d;
    
        return $this;
    }

**Comment by SendDerek** [comment]
I took a fresh look at what I was trying to accomplish with being able to render an array of charts in a foreach loop with having to specify the chart type.  Thought I'd share...

    public function index()
    {
        $charts = array();

        $charts[] = Lava::LineChart('EngagedSessions', $this->get_engaged_sessions_data(), [
            'title' => "Engaged Sessions",
        ]);

        $charts[] = Lava::LineChart('PageViews', $this->get_visitors_and_page_views_data(), [
            'title' => "Visitors and Page Views",
            //'legend' =>  ["position" => "none"],
        ]);

        return view('index', compact('charts'));
    }

In the blade template view:

        @foreach($charts as $chart)
        
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-bar-chart-o fa-fw"></i> {{ $chart->title }}
                    </div>

                    
                    <div class="panel-body">
                        <div id="{{ (string)$chart->getLabel() }}"></div>
                        {!! \Lava::render($chart->getType(), (string)$chart->getLabel(), (string)$chart->getLabel()) !!}
                    </div>
                    
                </div>
                
            </div>
            
        </div>
        
        @endforeach

I'm not terribly worried about going the different direction with not requiring `$chartType` in the `render()` method.  The datatable being null issue isn't a problem when I use unmodified code.  I would say this could be closed unless you want to look into it a little more.

Thanks for this package by the way!  It's been very helpful and I'm excited to use it some more.

**Comment by kevinkhill** [comment]
I was thinking about if it would be easy to eliminate the need for declaring the type while rendering, and how to uniquely store the charts in the volcano, and I stumbled across this [SPL Object Hash](http://php.net/manual/en/function.spl-object-hash.php) which sounds like it might fit this use case perfectly. I will make a note of this for 3.1, since I can't seem to find time to finish the documentation for 3.0

**Comment by SendDerek** [comment]
Sounds good to me!  Thanks for taking a look and giving it some thought. :+1:

**Comment by SendDerek** [comment]
Oops... not sure if I should've closed this or not.  Reopening.

**Comment by kevinkhill** [comment]
no worries, you can leave it open

**Comment by kevinkhill** [comment]
I feel like I just had a revelation...

Why define type, or label, or element id at all in the view?!? Why have blade extensions, why require so much lavacharts related code in the view at all. My gears were turning, and I figured, wouldn't it be easier to assign the output div's element id to the chart, while in the controller. Then, since each chart is already stored in the volcano, with all needed info for output....

just call ```Lava::render()``` once, and be done with it.

The views will already have their divs, waiting to be filled in with the chart. The library would just loop through all the charts in the volcano, and voila!

I don't know why this didn't occur to me before, but I think this is what I am going to do for 3.1 (I have to lock features and officially release 3.0 *sometime*, haha)

**Comment by kevinkhill** [comment]
[Psssssssssssssst!](https://github.com/kevinkhill/lavacharts/commit/bbfc3381b4eca14dc139d8b983a64b867bac5d14)

**Comment by SendDerek** [comment]
Awesome!  Glad to see some progress already towards 3.1.  That was fast! :+1:

**Comment by kevinkhill** [comment]
If you look though the commits, you'll see mass deletions and removal of classes. Not trying to create classes for every single option, and methods for all sorts of type checking.... It makes it much, much easier on me.

The chart classes are just thin wrappers around the parent Chart class now and no more config objects to pass around internally.

**Comment by kevinkhill** [comment]
If you are feeling adventurous, the 3.1 branch has (mostly) working code for ```$lava->renderAll()``` as well as a new ```lava.ready()``` method for (hopefully) protecting against race conditions.

I put lots of notes in the [changelog](https://github.com/kevinkhill/lavacharts/blob/master/CHANGELOG.md) about the improvements if you feel like taking it for a spin.

**Comment by kevinkhill** [comment]
The master branch, which will soon become 3.1 should have support for this. Please re-open or start a new issue if needed.

**Comment by SendDerek** [comment]
Sounds good to me!  Thank you for your continued work on this project.
