### ISSUE TITLE
NumberColumn Format Pattern Not Being Applied

### ISSUE THREAD

**Issue by SendDerek** [kevinkhill/lavacharts#75]
Applies to Lavacharts v3.0.  I can't seem to get the number column to be formatted correctly.  It appears the javascript is generated sanely, but the result is that the text shown on the line is not formatted correctly?

![screen shot 2015-11-05 at 3 39 48 pm](https://cloud.githubusercontent.com/assets/469263/10984203/1c6f20fa-83d5-11e5-8d62-d20602dfa81b.png)

Here's the code I'm using:

        $currency = new NumberFormat();
        $currency->pattern('$###,###');
        $currency->negativeColor('red');
        $currency->negativeParens(true);
        
        $revenueDataTable = Lava::DataTable()
            ->addStringColumn('Month')
            ->addNumberColumn('Revenue', $currency);

        $revenueLineChart = Lava::LineChart('Revenue', $revenueDataTable, [
            'title' => "Revenue",
            'colors' => ['green'],
            'vAxis' => ['format' => '$###,###'],
        ]);

**Comment by kevinkhill** [comment]
Interesting.... I copy your code and see if I can figure out what's going on.

**Comment by kevinkhill** [comment]
Very strange.... I copied your code, required the 3.0 branch and carbon, put in a little random data and I get formatted currency.

[Imgur](http://i.imgur.com/859PqJ6.png)

[test.php](https://gist.github.com/kevinkhill/14988819480e08d030db)

**Comment by kevinkhill** [comment]
My JS output appears to be the same as yours too, hmm, this is weird. Do you have Firefox? could you try your code in it? (I used Firefox) I will install chromium and try it there too.

![screenshot from 2015-11-05 17 09 47](https://cloud.githubusercontent.com/assets/266076/10986639/bcaff0f2-83e0-11e5-9029-fa80dd2a4b93.png)

**Comment by SendDerek** [comment]
Thanks for taking the time to look at this.  Maybe the missing link here is the fact that I'm using AJAX to load the data.  Probably should've mentioned it beforehand.  I just tested on Firefox and I had the same result of no formatting.

**View**

    @foreach($charts as $chart)
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-bar-chart-o fa-fw"></i> {{ $chart->title }}
        </div>
        <div class="panel-body">
            {!! \Lava::render($chart->getType(), (string)$chart->getLabel(), (string)$chart->getLabel(), true) !!}
        </div>
    </div>
    @endforeach

    <script>
    $(document).ready(function() {
            function getData(url, id1) {
                console.log('Fetching data from ' + url);
                $.getJSON(url, function(data) {
                    console.log('Fetched ' + url);
                    lava.loadData(id1, data, function(chart) {
                        console.log(chart);
                    });
                });
            }

            @foreach($charts as $chart)
                getData('{{  $chart->dataUrl }}', '{{ (string)$chart->getLabel() }}');
            @endforeach
    });
    </script>

**Comment by kevinkhill** [comment]
Ahhh, yes, using ajax hits much more of the lava.js I wrote. I can easily say, Javascript is not my strong suit. I will give another look at what might be preventing the formats from loading. I'm guessing that they just need to be reapplied since the chart is redrawn

**Comment by SendDerek** [comment]
Thanks again.  I'm with ya... javascript isn't my strong suit either, but I'm sure you know more about it than I do through writing this API.  I will say that the vAxis format option does work, but that's probably because it's not being redrawn?

**Controller**

        $currency = new NumberFormat();
        $currency->pattern('$###,###');
        $currency->negativeColor('red');
        $currency->negativeParens(true);

        $revenueDataTable = Lava::DataTable()
            ->addStringColumn('Month')
            ->addNumberColumn('Revenue', $currency);

        $revenueLineChart = Lava::LineChart('Revenue', $revenueDataTable, [
            'title' => "Revenue",
            'colors' => ['green'],
            'vAxis' => ['format' => '$###,###'],
        ]);
        $revenueLineChart->dataUrl = 'data/revenue';

        $charts[] = $engagedSessionsLineChart;
        $charts[] = $revenueLineChart;

        return view('index', compact('charts'));

**Comment by kevinkhill** [comment]
I think I already see the problem...

Using lava.loadData calls setData on the chart then redraw. Inside the redraw function, the chart gets to new DataTable and options (hence the vAxis staying applied) but since the formats are separate, they weren't reapplied.

You've pulled out fridge and found a bug!

**Comment by SendDerek** [comment]
Hooray for bug finding!  Now, for bug squashing.  ;-)  Let me know if you need anything from my end.

**Comment by kevinkhill** [comment]
Between aggressive overtime at work and freelancing, it's hard to find time
for my hobby library. On the upside, I have vacation coming soon, so maybe
I can finally get version 3 properly released.

**Comment by SendDerek** [comment]
I can completely relate.  It's not a severe bug, so I can continue.  Thanks again.

**Comment by kevinkhill** [comment]
So I'm digging into the formatters not coming across with an ajax data call. It actually an interesting bug you have found.

So I have the formatters stored with the columns, in the datatable, and that's good, makes sense. When the chart is rendered, that is when the Format objects are turned into their javascript form
```
$this.formats["col1"] = new google.visualization.NumberFormat({"pattern":"$###,###","negativeColor":"red","negativeParens":true});
$this.formats["col1"].format($this.data, 1);
```
and applied upon the initial render. This is why you can see the tooltip formats with a direct rendered chart.

I was thinking it would be easy to just pull the formatters from the serialized DataTable and use them in the redraw method in the JS. I am realizing that when using ajax, the DataTable is serialized into just column definitions and rows and *no formatters even come out with a serialized DataTable.*  The JavascriptFactory is what turns the Formats into JS so the redraw method never even handles them.

Whoops

So now I need to decide one of these methods of formatting....
1. Should the user apply the format objects to initial DataTable columns, even if loading the chart via ajax and have them re-applied to the new data, even if the new DataTable doesn't have formats.
The downside being that the user could not apply different formats upon a new ajax call as the initial ones would always be used.  
2. The user can include formats with new json encoded DataTables and have the redraw method always apply formats, whether initially defined or not. The downside is figuring out how to get the formats to come out with the json of the datatable (I like the cleanliness of just the datatable getting serialized)  
3. Maybe create a new fluent method for outputting DataTable and Format json, specifically to cover this issue, like ```DataTable->withFormats()->toJson();```
4. Or a direct method ```DataTable->toJsonWithFormats();```  
5. Or automatically detect applied formats and send them out with ```->toJson()``` or part of the ```JsonSerialize()``` method of the DataTable

Care to give me your two cents?

**Comment by kevinkhill** [comment]
So I thought I posted that hours ago, only to come back to this tab, and seeing my comment just sitting here.

Anyways, I decided to go with route 5, automatically detecting if formats exist through the ```toJson()``` method of the DataTable. With some tweaks to lava.js it can detect if the json payload has formats and will apply them upon calling the ```loadData()``` method.

Upon my initial tests, it seems to working and I'm happy with the implementation :)

if you could test the 3.0-unstable branch and let me know, I would appreciate it.

Cheers!

**Comment by SendDerek** [comment]
Okay, tested with 3.0-unstable and received an error:  `Uncaught TypeError: Cannot read property 'draw' of null` on the line `$this.chart.draw($this.data, $this.options);`.

        lava.charts.AreaChart["EngagedSessions"].redraw = function () {
            var $this = lava.charts.AreaChart["EngagedSessions"];

            $this.chart.draw($this.data, $this.options);
        };

I'm not exactly sure what would be helpful debugging info for ya, but the same error applies to all charts, not just the one with formatting.  Here's a quick screengrab of what `lava.charts.AreaChart["EngagedSessions"]` looks like:

<img width="561" alt="screen shot 2015-11-07 at 10 00 02 am" src="https://cloud.githubusercontent.com/assets/469263/11016185/5acb6cc0-8536-11e5-8622-89659026f97c.png">

Let me know if you need any other context.

**Comment by kevinkhill** [comment]
So my test page, in Firefox, worked with no errors. Then I tried in Chrome and I got the same error you did. But upon refresh... The error vanished. So, I am not really sure what would be throwing the error in the first place, but not upon refresh?

**Comment by kevinkhill** [comment]
Now I can't get the error again! I don't understand

**Comment by SendDerek** [comment]
Would you be able to wrap your test code up into a git repo (or tarball) and share it?  Maybe I'm doing something wrong in my setup.  Perhaps a race condition?

Every once and a while, it will work successfully, but upon refresh, I get errors again even on unformatted charts.

    Uncaught TypeError: google.visualization.DataTable is not a function

Of course, it seems like it's in a different area now:

        lava.charts.AreaChart["EngagedSessions"].setData = function (data) {
            var $this = lava.charts.AreaChart["EngagedSessions"];

            $this.data = new google.visualization.DataTable(data, 0.6);  <------ ERROR
        };

        lava.charts.AreaChart["EngagedSessions"].redraw = function () {
            var $this = lava.charts.AreaChart["EngagedSessions"];

            $this.chart.draw($this.data, $this.options);
        };

        lava.registerChart("AreaChart", "EngagedSessions");

**Comment by kevinkhill** [comment]
I can definitely pass on my test code, I will when I get a chance. As for
getting the DataTable json, are you using the newly modified ```toJson()```
method? Or just ```json_encode()``` on the DataTable

**Comment by SendDerek** [comment]
To confirm, when I swich back to 3.0-dev, the errors above go away.  I am using the toJson() method, which I see you've now undeprecated (thanks!).

**Comment by kevinkhill** [comment]
ok, so here is the files I just used on my laptop to test the formats. 

[format-test.tar.gz](https://drive.google.com/file/d/0B3f4LHFBQajSMXJPaHJXc3V3WDg/view?usp=sharing)

You *should* be able to...
```
tar -xvf format-test.tar.gz
composer update
php -S localhost:8000
```
and then visit that page in your browser and get an initially formatted chart and formats after ajax loads

**Comment by SendDerek** [comment]
Sorry it's taken so long to get back to you on this one.  I had to get to a semi-stable state before I tried the code again.  I can confirm the bug is fixed when using the 3.0 unstable branch.  Thank you very much.

**Comment by kevinkhill** [comment]
Hooray! I'm happy that we could figure this out. I will merge the updates into the stable branch :)

**Comment by SendDerek** [comment]
Ya know, I hate to do this to ya, but I'm not convinced we're entirely out of the woods on this one yet.  I feel as if there is a race condition happening here.  Having some experience with race conditions in the past, this might be hard to narrow down to what code is at fault.

I suspect a race condition because of the six **memcached** charts I have on my dashboard, only two or three will render properly while the others will give errors like `Uncaught TypeError: Cannot read property 'draw' of null` or `Uncaught TypeError: google.visualization.DataTable is not a function`.  When I clear the cache (`php artisan cache:clear`) and reload, all the charts load.  It's as if the extra loading time to fetch the data from the remote DBs helps give the charts time to render.  This only happens with the 3.0-unstable branch, by the way.  The issue goes away after switching back to 3.0-dev (I havn't updated my local repo yet).

Of course, in order to really help you track this down and fix it, I'd need to come up with a minimal test case that reproduces the issue.  Right now, I have too many variables at play...

**Comment by kevinkhill** [comment]
Hmm, yes, it sounds like when the charts are cached, they are beating out the loading of Google's jsapi. So when you clear out the cache, the extra time gets the jsapi to load.

I bet the best thing to do would be to check for the loading of the jsapi before processing my lava.js module and trying to render the charts.

**Comment by SendDerek** [comment]
Thanks for reopening.  Yes, I'd agree that a simple check before attempting to process lava.js would be a great solution.  Currently, a `sleep(1)` in the PHP controller fixes it for me, but of course, that's a terrible solution! haha

**Comment by kevinkhill** [comment]
Finally, a use for the sleep function!

**Comment by kevinkhill** [comment]
So... Here is my initial stab at protecting the charts from rendering without the jsapi available. I found a tiny event library and added it to my lava.js module. Then I wrapped the chart rending in a listener, waiting for ```jsapi:ready``` to fire. Then I have the lava.js dynamically create the script tag for fetching the jsapi, and once loaded, fire of the ```jsapi:ready``` event, triggering the rendering. If you want to test against the [jsapi](https://github.com/kevinkhill/lavacharts/tree/jsapi) branch I just pushed and report back, we can see if this is a viable solution for the race condition.

**Comment by SendDerek** [comment]
No go, I'm afraid.  Got an error in my view right away: `Undefined variable: coreJs`.  Is it possible you've forgotten to `git add` a dependancy file?  Happens to me all the time...

**Comment by kevinkhill** [comment]
whoops, I'll double check

**Comment by kevinkhill** [comment]
can you see in the inspector where this is happeneing?

**Comment by kevinkhill** [comment]
I found one small error, trying to concat onto a variable that didn't exist yet, but otherwise, I'm not sure whats up

**Comment by SendDerek** [comment]
Didn't mean to leave ya hanging.  $coreJs is a variable name in `/src/Javascript/JavascriptFactory.php`.  Looking at the diff of the latest commit, here are the changes made:

    /vendor/khill/lavacharts$ git diff 7aacbf86b79d52eea9cc12c119366cfd6a98b696 HEAD^ | grep coreJs

    diff --git a/src/Javascript/JavascriptFactory.php b/src/Javascript/JavascriptFactory.php
    index 2d9152d..059acea 100644
    --- a/src/Javascript/JavascriptFactory.php
    +++ b/src/Javascript/JavascriptFactory.php
    @@ -101,7 +101,7 @@ class JavascriptFactory
    */
    public function getCoreJs()
    {
    -        //$coreJs  = self::JSAPI;
    +        $coreJs  = self::JSAPI;
    $coreJs .= self::JS_OPEN;
    $coreJs .= file_get_contents(__DIR__.'/../../javascript/lava.js');
    $coreJs .= self::JS_CLOSE;

Unfortunately, I don't have much debug information.  I'm simply lead to a standard `Whoops, looks like something went wrong.` page.  Here's the backtrace:

    in JavascriptFactory.php line 105
    at CompilerEngine->handleViewException(object(ErrorException), '1') in PhpEngine.php line 44
    at PhpEngine->evaluatePath('/home/vagrant/Code/analytics.embeddedarm.com/storage/framework/views/feac73107d66668363fb8da80c73c959', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'charts' => array(object(ComboChart), object(ComboChart), object(AreaChart), object(AreaChart), object(AreaChart)), 'annotations' => object(Collection), 'cards' => array(object(QuickCard), object(QuickCard), object(QuickCard)))) in CompilerEngine.php line 58
    at CompilerEngine->get('/home/vagrant/Code/analytics.embeddedarm.com/resources/views/index.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'charts' => array(object(ComboChart), object(ComboChart), object(AreaChart), object(AreaChart), object(AreaChart)), 'annotations' => object(Collection), 'cards' => array(object(QuickCard), object(QuickCard), object(QuickCard)))) in View.php line 135
    at View->getContents() in View.php line 106
    at View->renderContents() in View.php line 80
    at View->render() in Response.php line 51
    at Response->setContent(object(View)) in Response.php line 198
    at Response->__construct(object(View)) in Router.php line 1225
    at Router->prepareResponse(object(Request), object(View)) in ControllerDispatcher.php line 113

Hopefully this helps out a little more?

**Comment by kevinkhill** [comment]
Did you grab the latest commit? I just pushed a fix for ```$coreJs .= self::JS_OPEN;``` fixed to ```$coreJs = self::JS_OPEN;```

**Comment by SendDerek** [comment]
Let's give it a whirl...

**Comment by SendDerek** [comment]
Congrats!  Zero issues. :+1:  Want to do the honors of closing this one out? Haha

**Comment by kevinkhill** [comment]
Boosh!
