### ISSUE TITLE
Unable to get property 'DataTable' of undefined or null reference

### ISSUE THREAD

**Issue by kyranb** [kevinkhill/lavacharts#76]
I'm getting this for a very small amount of users. Not able to replicate it or deduce what's going on. I'm thinking that it might be due to an extension blocking the libraries from loading?

Anyway, just wondering if anyone else has run across this. I'll try and get in contact with the end users that are seeing this and ask what extensions they have installed.

``` TypeError Unable to get property 'DataTable' of undefined or null reference 
    https://site.com/:795:13 lava.charts.DonutChart.chartName.render
    https://site.com/:824:13 Anonymous function ```

**Comment by kevinkhill** [comment]
It sounds like you have this on a live site, so I'm guessing you are using the 2.5 branch? Also, could you possibly tell me what you chart names are? It's possible they are breaking the array syntax of the Javascript? (my first guess)

**Comment by kevinkhill** [comment]
This might be the same race condition error we're running into in #78

**Comment by kevinkhill** [comment]
It's possible this has been fixed with my latest commits to the 3.0-unstable branch. If you want to test and report back, I would love to know if your issues have been resolved. So for now, I'll leave this issue open for now

**Comment by kyranb** [comment]
Sorry for leaving you hanging Kevin. I've been on Holidays and haven't been active on GitHub.

Yes, it's on a live site. I've looked into the error logs and the error `TypeError/admin/analytics
Unable to get property 'DataTable' of undefined or null reference` is coming from users with IE 11

For what it's worth, I'm also seeing: `TypeError: null is not an object (evaluating '$this.chart.draw')` from users with Safari 11 (Mac)

What naming convention do you recommend using? Right now the chart names are:

- locations_chart
- dailydownloads_chart
- useragents_chart
- popularepisodes_chart
- recentepisodes_chart
- referrers_chart

I've just updated it to the latest version on the 3.0 branch - I'll see how things go :) Thanks for all of your work on this package again Kevin :+1:

**Comment by kevinkhill** [comment]
Those are good names, so that's not the problem. It looks like I will have to spin up some VMs or try WINE for IE and Safari since testing on my Ubuntu laptop just isn't cutting it. It might be the race condition I've been discussing in other issues, but I'm not sure.

**Comment by kevinkhill** [comment]
Version 3.0 is here! Hopefully all these lingering issues are resolved. Fingers crossed. As always, feel free to open new issues if they arise :+1:
