### ISSUE TITLE
ComboChart Call to Undefined Method Setting 'seriesType'

### ISSUE THREAD

**Issue by SendDerek** [kevinkhill/lavacharts#78]
Okay, I have another one for you.  Back in the v3.0 branch (specifically, still using unstable).  I'm attempting to create a ComboChart, but receiving the following error message:

    Call to undefined method Khill\Lavacharts\Charts\ComboChart::addOption()

The line responsible is 126 in */khill/lavacharts-3.0-unstable/src/JsonConfig.php:126}() in JsonConfig.php*.  Looks like we're attempting to use reflection here and `$this->seriesType($option)`, which is what `call_user_func()` turns out to be, is not available as a method.

            call_user_func([$this, $option], $value);

Here's the full code block:

    public function setOptions($config)
    {
        if (is_array($config) === false) {
            throw new InvalidConfigValue(
                static::TYPE . '->' . __FUNCTION__,
                'array'
            );
        }

        foreach ($config as $option => $value) {
            if ($this->options->hasOption($option) === false) {
                throw new InvalidConfigProperty(
                    static::TYPE,
                    __FUNCTION__,
                    $option,
                    $this->options->getDefaults()
                );
            }

            call_user_func([$this, $option], $value);
        }
    }

And, here's what I'm attempting to use:

       $shoppingCartConversionsColumnChart = Lava::ComboChart('ShoppingCartConversions', Lava::DataTable(), [
            'title' => "Shopping Cart Conversions by New, Upgrading, and Guests",
            'seriesType' => 'bars',
            'series' => [3 => ['type' => 'line']],
            'isStacked' => true,
        ]);

I've instrumented the `setOptions()` code around the `call_user_func()`, and this is what I see right before it bails out:

    ...
    >> Option: hAxis
    >> Value: Array
    (
    [format] => MMM-yy
    )
    
    >> Option: format
    >> Value: MMM-yy
    >> Executed call_user_func() Okay
    
    >> Executed call_user_func() Okay
    
    >> Option: type
    >> Value: line
    >> Executed call_user_func() Okay
    
    >> Option: title
    >> Value: Shopping Cart Conversions by New, Upgrading, and Guests
    >> Executed call_user_func() Okay
    
    >> Option: seriesType
    >> Value: bars
    <error>

You can see it's chugging along okay for the other options, but it freaks out on `seriesType`.  Once again, I'm hoping you can help me out with this one.  I used http://lavacharts.com/#example-combo as an example and then used https://github.com/kevinkhill/lavacharts/wiki/Upgrading-from-2.5-to-3.0 to make sure I had the new 3.x syntax correct.

**Comment by SendDerek** [comment]
Okay, I was able to work through it.  It wasn't obvious at first, but after taking a look at some other resources ([here](http://stackoverflow.com/questions/11852711/google-visualization-api-format-secondary-y-axis-different-from-primary-y-axis) and [here](http://www.marinamele.com/2014/04/google-charts-double-axes.html)), I figured it out.  Here's the code that got it to work.

        $shoppingCartConversionsColumnChart = Lava::ComboChart('ShoppingCartConversions', Lava::DataTable(), [
            'title' => "Shopping Cart Conversions by New, Upgrading, and Guests",
            'isStacked' => true,
            'legend' => ['position' => 'bottom'],
            'hAxis' => ["format" => 'MMM-yy'],
            'series' => [
                0 => ['type' => 'bars'],
                1 => ['type' => 'bars'],
                2 => ['type' => 'bars'],
                3 => ['type' => 'line']
            ]
        ]);

**Comment by kevinkhill** [comment]
I'm glad you were able to get it working. Regardless, what you were trying to do should have worked, I took it straight from [Google's reference](https://developers.google.com/chart/interactive/docs/gallery/combochart?hl=en)

I will take a look next chance I'm in the code to see what's up

**Comment by kevinkhill** [comment]
Turns out I just missed converting the ```seriesType``` method to the 3.0 format. You should be able to set the default for ComboCharts now :)

**Comment by SendDerek** [comment]
Sweet!  Good job. :+1:
