### ISSUE TITLE
Uncaught TypeError: lava.event is not a function

### ISSUE THREAD

**Issue by Rokasl** [kevinkhill/lavacharts#82]
Hi, I get an error "Uncaught TypeError: lava.event is not a function" when I click on a country in the geo chart. Is this a bug or I'm doing something wrong? 
Using select type event listener.
Laravel 5.1

CONTROLLER:

		$data = array_count_values(SurveyData::where('survey_id', $id)->whereNotNull('country')->lists('country')->all());

		$popularity = \Lava::DataTable();

		$popularity->addStringColumn('Country')
		           ->addNumberColumn('Popularity');

		foreach ($data as $k => $v) {
			$popularity->addRow(array($k, $v));
		}

		$geochart = \Lava::GeoChart('Popularity')
			->setOptions(array(
				'datatable' => $popularity,
				'events' 	=> ['select' => \Lava::Select('selectHandler')]
			));

		return view( 'dashboard.visitors.index', [
			'geochart' => $geochart,
		] );

VIEW:
 <div id="pop-div"></div>

    <script>
        function selectHandler (event, chart) {
            console.log(chart.getSelection());
        }
    </script>

        <?= \Lava::render('GeoChart', 'Popularity', 'pop-div'); ?>

**Comment by kevinkhill** [comment]
Upon first glance, everything looks right. You might have found a bug. I will look into this for you.

**Comment by kevinkhill** [comment]
I just pushed a new branch up with a fix, try the new branch with ```"dev-issue-82 as 2.5.8"``` instead of the version you are using now. If it works, I will go ahead and merge it into the 2.5 branch and tag a new version.

**Comment by sakalauskas** [comment]
+1. I can confirm that bug is resolved on the new branch, thanks.

**Comment by kevinkhill** [comment]
Version 3.0 should have the same fixes as the 2.5 branch. If you are using PHP 5.4+ I would recommend upgrading to the latest version :)
