### ISSUE TITLE
AreaChart isStacked Does Not Support Valid Non-Bool Options

### ISSUE THREAD

**Issue by SendDerek** [kevinkhill/lavacharts#83]
I'm trying to use `isStacked: 'relative'` or `isStacked: 'percent'` options as described in [Google Charts API Documentation](https://google-developers.appspot.com/chart/interactive/docs/gallery/areachart#stacking-areas) but getting error 

    The value for AreaChart->isStacked must be of type (bool).

    1. in JsonConfig.php line 259
    2. at JsonConfig->setBoolOption('isStacked', 'percent') in IsStackedTrait.php line 17
    3. at AreaChart->isStacked('percent')
    4. at call_user_func(array(object(AreaChart), 'isStacked'), 'percent') in JsonConfig.php line 125
    5. at JsonConfig->setOptions(array('height' => '250', 'title' => 'Session Channels', 'legend' => array('position' => 'bottom'), 'isStacked' => 'percent', 'hAxis' => array('format' => 'MMM-yy'), 'vAxis' => array('minValue' => '0'), 'animation' => array('startup' => true, 'duration' => '1000', 'easing' => 'out'))) in JsonConfig.php line 52

My code:

       $sessionChannelsAreaChart = Lava::AreaChart('SessionChannels', $dummyTable, [
            'height' => 250,
            'title' => "Session Channels",
            'legend' =>  ['position' => 'bottom'],
            'isStacked' => 'percent', // <== Should be able to use this option value, not just true/false
            'hAxis' => ["format" => 'MMM-yy'],
            'vAxis' => ['minValue' => 0],
            'animation' => ['startup' => true, 'duration' => 1000, 'easing' => 'out'],
        ]);

Looks like the `isStacked` trait only expects to ever set a bool option:

    public function isStacked($isStacked)
    {
        return $this->setBoolOption(__FUNCTION__, $isStacked);
    }

I would expect to be able to set either Bool or String options.  I'm not sure if this aligns with your code design, but it seems to fix the issue...

1.) Add isBoolOrString to Utils.php

    /**
     * Tests input for valid boolean or percent
     *
     * Valid boolean = true or false
     * Valid string = 'relative' or 'percent'
     *
     * @param mixed Boolean or string.
     * @return bool Returns true if valid boolean or string, otherwise false.
     */
    public static function isBoolOrString($val)
    {
        if (is_bool($val) === true || is_string($val) === true) {
            return true;
        } else {
            return false;
        }
    }

2.) Add setBoolOrStringOption to JsonConfig.php

    /**
     * Sets the value of a string or boolean option.
     *
     * @param  string $option Option to set.
     * @param  int    $value Value of the option.
     * @return \Khill\Lavacharts\JsonConfig
     * @throws \Khill\Lavacharts\Exceptions\InvalidConfigValue
     * @throws \Khill\Lavacharts\Exceptions\InvalidOption
     */
    protected function setBoolOrStringOption($option, $value)
    {
        if (Utils::isBoolOrString($value) === false) {
            throw new InvalidConfigValue(
                static::TYPE . '->' . $option,
                'bool|string',
                'String only if using optional values like \'percent\' or \'relative\''
            );
        }

        $this->options->set($option, $value);

        return $this;
    }

3.) Change setBoolOption() to setBoolOrStringOption() in IsStackedTrait.php

    /**
     * If set to true, series elements are stacked.
     *
     * @param  bool $isStacked
     * @throws \Khill\Lavacharts\Exceptions\InvalidConfigValue
     * @return \Khill\Lavacharts\Charts\Chart
     */
    public function isStacked($isStacked)
    {
        return $this->setBoolOrStringOption(__FUNCTION__, $isStacked);
    }

It's probably also necessary to add a new config type so that you can display an error when somebody tries to use an option other than 'relative', 'percent', or 'absolute', but this is a start.

**Comment by kevinkhill** [comment]
You've found another instance of #64, where I haven't kept up with Google's API changes. I will snag your code bits and incorporate them, so you can use this option.

**Comment by SendDerek** [comment]
Sounds good. :+1:

**Comment by kevinkhill** [comment]
I modified what you gave me a little, but I think this should work for you? Let me know if you can test against the 3.0-unstable branch, and if it works, I'll pull it into 3.0

**Comment by SendDerek** [comment]
That looks good to me!  Thanks for doing that.  I trust it'll work. :-)

**Comment by kevinkhill** [comment]
I'll close this for now, since we have it sorted out.
