### ISSUE TITLE
addRow() is generating wrong output when taking DataCell as input for any cell

### ISSUE THREAD

**Issue by antoniotajuelo** [kevinkhill/lavacharts#84]
Hello,

addRow() is working in an unexpected way. If you use addRow() and pass a DataCell as input for any cell, it generates wrong input.

Example:
$chart->addRow(array(2015, new DataCell(0.8,'80%')));

Fix:
In file lavacharts/src/Configs/DataTable.php, line 378 should be replaced with:
                          if(is_object($optCellArray[$index])) {
                            $rowVals[] = array('v' => $optCellArray[$index]->v,'f' => $optCellArray[$index]->f,'p' => $optCellArray[$index]->p);
                          } else {
                            $rowVals[] = array('v' => $optCellArray[$index]);
                          }

**Comment by kevinkhill** [comment]
You don't need to be creating DataCells manually, the addRow function takes arrays of data.

**Comment by antoniotajuelo** [comment]
Thanks for the quick reply.

So could you provide me a simple example of how to use addRow() for generating a row where some cells contains both normal value (v) and formatted value (f) versions of data?

--
Sonríe a la vida

**Comment by kevinkhill** [comment]
I guess the docs aren't very clear, but you format the column, so all the values appear formatted. 

First you create a [format object](http://lavacharts.com/#datatable-formats) then you pass in the format object to the [column](http://lavacharts.com/#datatable-columns) when creating the datatable

**Comment by antoniotajuelo** [comment]
Thank you for the clarification.

However, how about cell-level formatting using "v" and "f" parameters? Sometimes, this needs to be done on a cell by cell basis and on my understanding cannot take advantage of the column formatting feature.

Sample output for two cells, the second with a formatted value.
['Hermione', {v: new Date(1999,0,1),f: 'January First, Nineteen ninety-nine'}]

**Comment by kevinkhill** [comment]
Ah, yes, I see. You're right, I don't think I currently support that capability. I am in the middle of getting v3 out the door, so I will add this to my list of todos once it is released. I have quit working on the codebase for now so I can finish the docs. Although, if you want to whip up a pull request with that functionality, I'd happily merge it in.

**Comment by antoniotajuelo** [comment]
Sure, here it is: https://github.com/kevinkhill/lavacharts/pull/85
