### ISSUE TITLE
Is the MagnifyingGlass config option available for all charts, or just the GeoChart?

### ISSUE THREAD

**Issue by WesThorburn** [kevinkhill/lavacharts#88]
Hi Kevin,

Happy new year!

I've got a couple of line charts that I'd like to be able to let users zoom in on. Just wondering if I can adjust the zoomFactor for line graphs? Or is it only available for the GeoCharts?

**Comment by kevinkhill** [comment]
Happy new year to you too, thanks :)

As far as I know, the magnifying glass option is only for geocharts per Google and not me. I think I remember seeing an "explorer" option that seemed like it would implement the functionality of desire.

I've been trying to finish the 3.0 docs in my free time, and they are close to being done. I want to get back into the library and move forward, writing docs is boring.

**Comment by WesThorburn** [comment]
As always, thanks for your quick reply! 

Thanks for the suggestion, I'll check out the explorer option. 

I look forward to seeing 3.0 when it's ready!

**Comment by kevinkhill** [comment]
I edited my post, because I should have mentioned I haven't implemented the Explorer option yet. I just saw it on Google's docs for charts, sorry!

**Comment by kevinkhill** [comment]
If you are using the 2.5 branch, check out what I just posted in issue #64

**Comment by kevinkhill** [comment]
[Version 2.5.9](https://github.com/kevinkhill/lavacharts/releases/tag/2.5.9)

**Comment by WesThorburn** [comment]
Thanks so much Kevin, it's working perfectly!
