### ISSUE TITLE
Mimicing a Timeline chart

### ISSUE THREAD

**Issue by Rewarewa** [kevinkhill/lavacharts#89]
Hi, I am interesting in displaying a Timeline Chart that is shown on the Google Charts site. I can not see that it is a chart type supported in lavacharts. I thought I could get the same effect using a stacked barchart and making the first bar transparent. This does kind of work but the start date is always 1970. Is there a way to get the axis to recognize a different start date?

**Comment by kevinkhill** [comment]
Are you using any of the date related columns? Date, DateTime, TimeOfDay?

**Comment by Rewarewa** [comment]
I am using 'addDateColumn' currently. The code I have used in shown below. One thing I have tried is  *'hAxis' => \Lava::HorizontalAxis(array('baseline' => '2005-01-01'))*. However, this comes up with an error message of *The value for HorizontalAxis::baseline must be of type 'int | jsDate' int if column is "number", jsDate if column is "date"*. I can not see any reference to jsDate in the lavacharts documentation? 



$firstdate = '2009-02-01';
$seconddate = '2011-04-01';
$votes  = \Lava::DataTable();

$votes->addStringColumn('Food Poll')
      ->addDateColumn('Start') 
      ->addDateColumn('Votes')
      ->addDateColumn('Toads')	  
      ->addRow(array('Tacos', $firstdate, $seconddate, '2014-10-01'))
      ->addRow(array('Salad', $firstdate, $seconddate, '2014-10-01'))
      ->addRow(array('Pizza', $firstdate, $seconddate, '2014-10-01'))
      ->addRow(array('Apples', $firstdate, $seconddate, '2014-10-01'))
      ->addRow(array('Fish', $firstdate, $seconddate, '2014-10-01'));

\Lava::BarChart('Votes')
     ->setOptions(array(
         'datatable' => $votes,
		 'isStacked' => true,
		'colors' => array('transparent','green','blue')
));		 
echo \Lava::render('BarChart', 'Votes', 'poll_div', true);

**Comment by kevinkhill** [comment]
How embarrassing, I left @TODO marks and never actually finished the functionality of ```baseline()```!

**Comment by kevinkhill** [comment]
If you feel like playing with development builds, dev-3.1 has timeline charts :)

**Comment by Rewarewa** [comment]
Awesome - thanks

**Comment by kevinkhill** [comment]
This is soon to be in the 3.0 branch. It is working in ```dev-master``` and will be included in the next tag of the 3.0 branch. Closing this for now.
