### ISSUE TITLE
Getting a Base64 string

### ISSUE THREAD

**Issue by happyaaz** [kevinkhill/lavacharts#90]
I am trying to display a base64 string on the page. I was following the LineChart example on the documentation, but can't get my head around how to get that base64 string ._.
I tried declaring a new Lava variable, I tried using the Echo function (which is my preferred option since I plan on using that string later in other scripts)- nothing.

And nothing is shown in the console either. The code is below in case you want to look at it.

Btw, if I use your new beta version of the project, the code below won't work at all (ormaybe it is me whow screwed up somewhere).

And thank you for your awesome work!

include('C:/Path/Carbon-master/src/Carbon/Carbon.php');
include('C:/Path/lavacharts-2.5/src/Lavacharts.php');

use \Khill\Lavacharts\Lavacharts;
$lava = new Lavacharts; // See note below for Laravel

$temperatures = $lava->DataTable();

$temperatures->addDateColumn('Date')
             ->addNumberColumn('Max Temp')
             ->addNumberColumn('Mean Temp')
             ->addNumberColumn('Min Temp')
             ->addRow(array('2014-10-1', 67, 65, 62))
             ->addRow(array('2014-10-2', 68, 65, 61))
             ->addRow(array('2014-10-3', 68, 62, 55))
             ->addRow(array('2014-10-4', 72, 62, 52))
             ->addRow(array('2014-10-5', 61, 54, 47))
             ->addRow(array('2014-10-6', 70, 58, 45))
             ->addRow(array('2014-10-7', 74, 70, 65))
             ->addRow(array('2014-10-8', 75, 69, 62))
             ->addRow(array('2014-10-9', 69, 63, 56))
             ->addRow(array('2014-10-10', 64, 58, 52))
             ->addRow(array('2014-10-11', 59, 55, 50))
             ->addRow(array('2014-10-12', 65, 56, 46))
             ->addRow(array('2014-10-13', 66, 56, 46))
             ->addRow(array('2014-10-14', 75, 70, 64))
             ->addRow(array('2014-10-15', 76, 72, 68))
             ->addRow(array('2014-10-16', 71, 66, 60))
             ->addRow(array('2014-10-17', 72, 66, 60))
             ->addRow(array('2014-10-18', 63, 62, 62));

$linechart = $lava->LineChart('Temps')
                  ->dataTable($temperatures)
                  ->title('Weather in October');

				  
				  

echo $lava->render('LineChart', 'Temps', 'temps_div');

$lava = new Khill\Lavacharts\Lavacharts;
$lava->LineChart('Temps')
     ->datatable($temperatures)
     ->setOptions([
         'events' => [
             $lava->Ready('getImageCallback')
         ]
     ]);

//  below is the JS function and html code with the div block.

    function getImage (event, chart) {
        document.write(chart.getImageURI());
        // This will return in the form of "data:image/png;base64,iVBORw0KGgoAAAAUA..."
    }

<div id="temps_div"></div>

**Comment by happyaaz** [comment]
I seem to have figured out everything. It was my bad.
Lesson learnt - I should not learn how to use a new package after you have been working with a completely different language for 10 hours straight =D

**Comment by happyaaz** [comment]
But then I have a question - is it possible to display the Base64 string with the Echo function?
Or return the string as a parameter that I can get access to?

**Comment by kevinkhill** [comment]
Haha, no problem. I'm glad you were able to figure it out.
