### ISSUE TITLE
series on linechart

### ISSUE THREAD

**Issue by AlexECP** [kevinkhill/lavacharts#92]
Hi,

Im having trouble configuring a line chart so the two lines have different lineWidths... is this possible?  I keep getting ```"series" is not a valid property for LineChart->setOptions``` 

thanks

**Comment by kevinkhill** [comment]
Are you using the 2.5 branch or the 3.0?

**Comment by AlexECP** [comment]
2.5, but willing to switch to 3...

**Comment by kevinkhill** [comment]
Well, I will be publishing 3.0 very soon, but, it looks like it doesn't
have the series trait either.

So, for now in 2.5, you can use the customize() method to add any option
you want. Just pass in nested, associative arrays for the options you want.
This bypasses the checking for valid options.

I plan on incorporating that functionality directly into the chart
constructor for 3.0, so you won't have to call an extra method.

2.5, but willing to switch to 3...

—
Reply to this email directly or view it on GitHub
<https://github.com/kevinkhill/lavacharts/issues/92#issuecomment-173444548>.

**Comment by AlexECP** [comment]
that worked thanks!!  This is a great system, thank you.  

BTW, on laravel, how does the data get passed to the view?  It seems sort of miraculous...

**Comment by kevinkhill** [comment]
The service provider creates an instant of Lavacharts and stores it in the
app. All charts are stored within the Lavacharts class, so every time the
Facade is used, it grabs the same instance with all your charts
