### ISSUE TITLE
Scatter plot data point labels

### ISSUE THREAD

**Issue by edfearon** [kevinkhill/lavacharts#94]
Hello.  I've been getting to grips with this and it's been brilliant for a project that I'm working on.  Is there a way to add labels to scatter plot data points?  I tried adding a third (string) column, but it wasn't happy.  I'm graphing one type of test score against another, and I want to click on points and see the name of the person who scored the result.  Many thanks,  Ed.

**Comment by kevinkhill** [comment]
For this you will want to use a ```RoleColumn``` which can be added as the third column.
To get the functionality you want, use ```->addRoleColumn('string', 'tooltip')```
then each row's array of data can have a third item, the text you want displayed on hover.

```
$votes = $lava->DataTable();
    $votes->addNumberColumn('Thing1')
          ->addNumberColumn('Thing2')
          ->addRoleColumn('string', 'tooltip')
          ->addRow([rand(0,100), rand(0,100), 'Tacos!'])
          ->addRow([rand(0,100), rand(0,100)])
          ->addRow([rand(0,100), rand(0,100)])
          ->addRow([rand(0,100), rand(0,100)]);

    $lava->ScatterChart('Grades', $votes, [
      'width'=>300,
      'legend' => ['position'=>'none']
    ]);
```

![](http://i.imgur.com/kyF0xYv.png)

**Comment by kevinkhill** [comment]
Here's a link to [Google's Docs](https://developers.google.com/chart/interactive/docs/roles) on column roles

**Comment by edfearon** [comment]
That's fantastic.  Thanks a lot.  Ed.
