### ISSUE TITLE
How to position the column legends of 'line-chart' below the chart? 

### ISSUE THREAD

**Issue by arafatx** [kevinkhill/lavacharts#96]
Screenshot:
http://s27.postimg.org/96ui8kss3/position.png

You can see when the 2 legends on the right: 'Retailer Price' and 'Consumer Price' are not display properly. I dig into the documentation and found the axisTitlesPosition() function which accepts 'in', 'out' and 'none' argument. I tried all parameters but still I cannot make the 2 legends display below the charts. Any idea?

**Comment by kevinkhill** [comment]
What you have circled is the Legend, not the Axis Titles, so those are the config options you want to set.

**Comment by kevinkhill** [comment]
The axis titles would be underneath the horizontal axis and to the left of the vertical axis

**Comment by arafatx** [comment]
Sorry for the confusing, yeah those are legends not title. I want to position the 2 legends at the bottom of the chart because the texts are not fully displayed there This is what I have:

   $product = Product::findOrFail($id);

        $prices = \Lava::DataTable();

        $prices->addDateColumn('Date')
            ->addNumberColumn('Retailer Price')
            ->addNumberColumn('Consumer Price')
            ->addRow(array('2014-10-1', 67, 65))
            ->addRow(array('2014-10-2', 68, 65))
            ->addRow(array('2014-10-3', 68, 62))
            ->addRow(array('2014-10-4', 72, 62))
            ->addRow(array('2014-10-5', 61, 54))
            ->addRow(array('2014-10-6', 70, 58))
            ->addRow(array('2014-10-7', 74, 70))
            ->addRow(array('2014-10-8', 75, 69))
            ->addRow(array('2014-10-9', 69, 63))
            ->addRow(array('2014-10-10', 64, 58))
            ->addRow(array('2014-10-11', 59, 55))
            ->addRow(array('2014-10-12', 65, 56))
            ->addRow(array('2014-10-13', 66, 56))
            ->addRow(array('2014-10-14', 75, 70))
            ->addRow(array('2014-10-15', 76, 72))
            ->addRow(array('2014-10-16', 71, 66))
            ->addRow(array('2014-10-17', 72, 66))
            ->addRow(array('2014-10-18', 63, 62));

        $linechart = \Lava::LineChart('Price_History')
            ->dataTable($prices)
            ->title('Price history for: '.$product->name)
        ->legend('in'); //?

**Comment by kevinkhill** [comment]
you need to pass in a [```Legend```](http://lavacharts.com/#config-legend) object. Create one, with the options you want as an array for the constructor.

```php
$linechart = \Lava::LineChart('Price_History')
    ->datatable($prices)
    ->title('Price history for: '.$product->name)
    ->legend(\Lava::Legend(array('position' => 'in'));
```

**Comment by arafatx** [comment]
Actually, I followed exactly what you did before from the example of area chart http://lavacharts.com/#example-area and it did not work because I forgot the '\'. -_-

 It works now. Thank you!

**Comment by kevinkhill** [comment]
Happy to help :)
