### ISSUE TITLE
Chart doesn't render properly inside a hidden tab (like inside a second tab).

### ISSUE THREAD

**Issue by arafatx** [kevinkhill/lavacharts#97]
This is my controller:

```
        $prices->addDateColumn('Month')
        ->addNumberColumn('Retailer Price')
        ->addNumberColumn('Consumer Price')
        ->addRow(array('2014-10-1', 67, 65))
        ->addRow(array('2014-10-2', 68, 65))
        ->addRow(array('2014-10-3', 68, 62))
        ->addRow(array('2014-10-4', 72, 62))
        ->addRow(array('2014-10-5', 61, 54))
        ->addRow(array('2014-10-6', 70, 58))
        ->addRow(array('2014-10-7', 74, 70))
        ->addRow(array('2014-10-8', 75, 69))
        ->addRow(array('2014-10-9', 69, 63))
        ->addRow(array('2014-10-10', 64, 58))
        ->addRow(array('2014-10-11', 59, 55))
        ->addRow(array('2014-10-12', 65, 56))
        ->addRow(array('2014-10-13', 66, 56))
        ->addRow(array('2014-10-14', 75, 70))
        ->addRow(array('2014-10-15', 76, 72))
        ->addRow(array('2014-10-16', 71, 66))
        ->addRow(array('2014-10-17', 72, 66))
        ->addRow(array('2014-10-18', 63, 62))
        ->addRow(array('2014-10-19', 63, 55))
        ->addRow(array('2014-10-20', 63, 56))
        ->addRow(array('2014-10-21', 63, 55))
        ->addRow(array('2014-10-24', 63, 33))
        ->addRow(array('2014-10-29', 63, 64))
        ->addRow(array('2014-10-30', 63, 63));

    $linechart = \Lava::LineChart('Price_History')
        ->dataTable($prices)
        ->title('Price history for: product_name')
        ->legend(\Lava::Legend(array('position' => 'in')));
```

http://postimg.org/image/o9gsju91f/
Screenshot 1-on first tab loaded / clicked: (display correctly)

http://postimg.org/image/k18bhfsnd/
Screenshot 2-on second tab clicked: (display incorrectly; the chart becomes smaller.)

I have 3 tabs in a page. The first tab (from the screenshot) called Product Details, the Second One is Price Details. The last one is not important to demonstrate. So, if I put my chart rendering in the second tab in the blade like below:

```
  <div id="price_history_chart"></div>
  {!! \Lava::render('LineChart', 'Price_History','price_history_chart') !!}
```

and when i click on the second tab, it wont display properly. But if I put it in the first tab, it displayed properly like in the screenshot. 

Is there a way to set a fixed size of the chart so, it won't automatically resize? I'm not sure if the fixed size option will solve this problem.

I found out a similar issue but on the different chart package: http://stackoverflow.com/questions/30302711/drawing-flot-chart-inside-bootstrap-tab-issue

Tried to set the div hidden and shown when active still doesn't work.

**Comment by arafatx** [comment]
Found the solution. When the chart is resize, it will automatically redraw itself. So my solution is to call $(window).trigger('resize'); everytime when the second tab is clicked: 

 $('#tab2').on('click',function(){

        $(window).trigger('resize');
 });

**Comment by arafatx** [comment]
I accidentally closed this issue without debugging my solution. The solution that I posted doesn't work. I posted the issue on github too: http://stackoverflow.com/questions/34972183/lavacharts-doesnt-display-chart-size-properly-using-tab-first-tab-is-ok-seco

**Comment by kevinkhill** [comment]
This is what I wrote on SO:

> So the charts should already be responsive, and resize on window resize. This was an issue that
> was brought up before and as far as I know, it is working. As for being resized when brought into
> view in the tab, I'm not certain how to handle that. I suppose adding an endpoint to the lava.js
> module for manually resizing, so the user could use the bootstrap event of the tab showing to 
> activate the resize.

**Comment by sankety** [comment]
I have answered my solution here
http://stackoverflow.com/a/36063175/1933690

**Comment by kevinkhill** [comment]
I'm glad you have found a solution for this! 

One small note, you should edit the example 3.0 code to have the datatable as the second parameter, and the options as the third.

**Comment by sankety** [comment]
Yes I have updated the code :+1:

**Comment by kevinkhill** [comment]
:smile:

**Comment by kevinkhill** [comment]
I'm going to go ahead and close this as an issue, since we've seemed to resolve it.

**Comment by vietmh** [comment]
Hi @kevinkhill ,
I got the same problem with @arafatx, and @sankety 's solution is to set a fixed size for charts.
But I cannot set a fixed size, since I need to support multiple screen sizes.
Could you please suggest any other solutions ?
Thanks.

**Comment by kevinkhill** [comment]
Can you try attaching an event handler, triggered by what makes the tab visible?

Have it run something like this?
```lava.getChart('my-chart-title', function (chart) { chart.redraw(); });```

**Comment by vietmh** [comment]
Hi @kevinkhill ,

Thank you very for your reply, your solution works great. I have charts on many tabs, here is how I apply your solution to solve my problem.

`$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                        if (e.target.id === "chartA") // newly activated tab
                            lava.getChart('chartA-title', function (chart) {
                                chart.redraw();
                            });
                        if (e.target.id === "chartB") // newly activated tab
                            lava.getChart('chartB-title', function (chart) {
                                chart.redraw();
                            });
                    });`

**Comment by kevinkhill** [comment]
👍 Happy to be of assistance!
