### ISSUE TITLE
Show a blue dot on graph line without having to hover the mouse on the graph line

### ISSUE THREAD

**Issue by arafatx** [kevinkhill/lavacharts#98]
http://postimg.org/image/79x4ydrnl/ - Screenshot of blue dot graph:

In the screenshot I posted above, If I hover my mouse over the line of the graph, it will show up a blue dot. How do I make all dots appear without having to hover using mouse.

I have this from the example:

$lava = new Lavacharts;

$population = $lava->DataTable();

$population->addDateColumn('Year')
           ->addNumberColumn('Number of People')
           ->addRow(array('2006', 623452))
           ->addRow(array('2007', 685034))
           ->addRow(array('2008', 716845))
           ->addRow(array('2009', 757254))
           ->addRow(array('2010', 778034))
           ->addRow(array('2011', 792353))
           ->addRow(array('2012', 839657))
           ->addRow(array('2013', 842367))
           ->addRow(array('2014', 873490));

$areachart = $lava->AreaChart('Population')
                  ->setOptions(array(
                    'datatable' => $population,
                    'title' => 'Population Growth',
                    'legend' => $lava->Legend(array(
                      'position' => 'in'
                    ))
                  ));

**Comment by kevinkhill** [comment]
Just use the ```pointSize``` option.
For example, adding
```php
"pointSize" => 5,
```
will give you this:
![example](https://cloud.githubusercontent.com/assets/266076/12558353/ef6e668e-c343-11e5-9621-32a0fbe2eb45.png)

Also check out [Google's Docs](https://developers.google.com/chart/interactive/docs/points) on point customization.
