### ISSUE TITLE
Not all charts load

### ISSUE THREAD

**Issue by scalen121** [kevinkhill/lavacharts#99]
I am making a page with laravel and lavacharts 3.0.0 for displaying survey results using columnCharts.

In my controller I make an array of data tables: 

```
                $aTables = array();
                foreach ($a_questions as $a_question)
                {
                        $aTable = Lava::DataTable();
                        $aTable->addStringColumn('Answer');
                        $aTable->addNumberColumn('Responses');
                        foreach ($a_question->answers as $key=>$a)
                        {       
                                        $aTable->addRow([$a, Quiz_Results::where($a_question->results_column, 'LIKE', "%$key%")->count()]);
                        }
                        Lava::ColumnChart('a'.$a_question->results_column, $aTable, [ 'legend'=> ['position'=> 'none'] ]);
                        array_push($aTables, 'a'.$a_question->results_column);
               }
```

Then to render them:

```
                               @foreach ($aTables as $key=>$table)
                                        <h3>{{$a_questions[$key]->question}}</h3>
                                        <div class="chart">
                                                {!! \Lava::render('ColumnChart', $table, $table.'-div', true) !!}
                                        </div>
                                        <br><br>
                                @endforeach
```

I do this for two quizzes on the same page with the same code to make the charts. The 2 sets of charts are in different divs and there is a toggle to hide one and see the other. In total there are about 40 charts.

The problem is, when the page loads the first charts load but then if I click on the page or scroll or anything, some of the charts at the bottom don't load. If I load the page and wait 10-20 seconds before doing anything, then all the charts load and the page works as expected. 
I added a spinner to make the user wait extra time before they try to click, and it generally works for a timer of 10 seconds or so, but obviously not optimal and even then sometimes they don't all load.

Any ideas what might be wrong? I've dug through the other bugs and gone through the documentation, but I can't figure why only some of them wouldn't load.

**Comment by kevinkhill** [comment]
If all of the Javascript is output correctly onto the page, then it could be an issue with they way I have the charts rendering through my lava.js module. There could be something causing the delay, but I haven't yet tried to render that many charts on one page. I will have to look into this more.

**Comment by kevinkhill** [comment]
Do I tried a test render of 40 charts on one page and they all loaded almost instantly, then 100 charts and it took a couple seconds, but they all popped up. It must be something with hiding them in a div, I will keep investigating.

**Comment by scalen121** [comment]
Thanks for investigating! I'll dig around a bit and see if I can figure anything else out

**Comment by quickshiftin** [comment]
I encountered this same problem and it looks to me like the the method used to wait for the DOM ready state is not working on my browser (_Chrome 55.0.2883.95 (64-bit)_)? By adding this snippet around `lava.events.emit('jsapi:ready', window.google);`, all charts load as expected.
```javascript
document.addEventListener("DOMContentLoaded", function(event) {
    lava.events.emit('jsapi:ready', window.google);
});
```
I found this approach on a [Stackoverflow thread](http://stackoverflow.com/a/800010/680920).

**Comment by kevinkhill** [comment]
Yeah, it's been quite a while since I have even been in the code. I'm not surprised that you're finding bugs. My day job responsibilities have doubled so I don't really ever have time to work on this, sadly :(

I'm glad you found a work around though. I will just add this to my ever growing todo list, if I ever get back into this.

**Comment by quickshiftin** [comment]
All good, I just thought I would at least put it in the thread here as others may find it of use. You've saved me some time in a personal project and I thank you for that Kevin!

**Comment by Denn1992** [comment]
>  encountered this same problem and it looks to me like the the method used to wait for the DOM ready state is not working on my browser (Chrome 55.0.2883.95 (64-bit))? By adding this snippet around lava.events.emit('jsapi:ready', window.google);, all charts load as expected.

This worked also for me, thank you for the solution.

**Comment by kevinkhill** [comment]
Has anyone update to the new version? Is this issue resolved with the update?

**Comment by yasserito** [comment]
I had the same problem, i'm with Laravel 5.2 and lavachart 3.0 , the solution given by quickshiftin works perfectly for me. I've been struggling with it for weeks hhh, thanks :+1:

**Comment by kevinkhill** [comment]
> I've been struggling with it for weeks

You should have come here sooner! I have my github issues setup to alert me on my phone and I try to at least give guidance if I can't hop on and give an immediate fix.

**Comment by scalen121** [comment]
Thanks all for the help! I saw these responses but have moved to a much busier job and found it hard to get back to this codebase. Thanks quickshiftin for the solution, it works great! :) Sorry for the late response!

**Comment by quickshiftin** [comment]
@kevinkhill Should I create a pull request for this?

**Comment by kevinkhill** [comment]
What exactly would you be making a pull for?

To add this?
> `lava.events.emit('jsapi:ready', window.google);`
